# Existing nodes in Neo4j as of batch_004
EXISTING_NODES = {
    "agricultural_product", "airport_equipment", "aluminum_panel", "animal_feed",
    "architectural_design_service", "automotive_aluminum", "automotive_brake_system",
    "automotive_chip", "automotive_electronics", "automotive_engine_accessory",
    "automotive_environment_system", "automotive_inspection_service", "automotive_maintenance_service",
    "automotive_sales_service", "automotive_steel", "automotive_steering_system",
    "automotive_transmission_system", "bicycle", "big_data_service", "bms_component",
    "bond_investment_service", "bonded_warehousing_service", "building_curtain_wall",
    "bulk_cargo", "cement", "chain_retail_service", "chassis_system", "chemical_fertilizer",
    "city_gas_supply", "cloud_service_resource", "cloud_solution", "coal", "coal_power_generation",
    "color_tv", "commercial_property", "communication_device", "construction_service",
    "consumer_battery_pack", "container", "container_handling_service", "crude_oil",
    "display_module", "dram_chip", "ecological_restoration_service", "electric_bicycle",
    "electricity_distribution", "electricity_power", "electricity_transmission",
    "electronic_glass", "electronics_market_service", "emergency_security_service",
    "energy_chemical_equipment", "energy_storage_battery", "energy_storage_technology",
    "engineering_glass", "financial_bond", "float_glass", "food_condiment", "food_ingredient",
    "gardening_material", "gas_power_generation", "gold_jewelry", "grain_oil",
    "grain_processing", "grain_storage_service", "greening_construction_service",
    "hard_disk_drive", "hard_disk_platter", "heating_supply", "high_tech_industrial_engineering",
    "hotel_operation_service", "housing_rental_service", "hydro_power_generation",
    "industrial_property", "information_system_integration", "injection_molding_part",
    "interbank_lending_service", "it_distribution_service", "it_hardware", "jewelry_retail_service",
    "land", "landscape_design_service", "laptop_computer", "lcd_monitor", "lcd_panel",
    "lcd_polarizer", "led_display_screen", "lithium_battery_anode", "lithium_battery_cathode",
    "lithium_ion_cell", "lithium_salt", "live_pig", "loan_service", "logistics_service",
    "magnetic_head", "medical_device", "memory_dimm", "memory_module", "memory_wafer",
    "mobile_app_security_service", "mobile_phone", "module_power_supply", "municipal_waste_treatment",
    "nand_flash_chip", "natural_gas", "natural_graphite", "needle_coke", "network_equipment",
    "nursery_stock", "office_equipment", "offshore_engineering_equipment", "oled_polarizer",
    "operating_system", "packaging_material", "packaging_substrate", "pcb_board", "pcb_substrate",
    "petrochemical_product", "pharmaceutical_distribution", "pharmaceutical_product",
    "pharmaceutical_raw_material", "pharmaceutical_retail", "photovoltaic_module",
    "plastic_resin", "platform_screen_door", "poultry", "power_supply_system", "precious_metal",
    "property_management_service", "public_deposit", "pv_glass", "pva_film", "quartz_sand",
    "rail_maintenance_service", "rail_vehicle", "refining_service", "refrigerator",
    "residential_property", "road_transport_vehicle", "security_database", "semiconductor_device",
    "server_hardware", "shipping_service", "signaling_system", "silicon_material", "sludge_treatment",
    "smart_meter", "soda_ash", "software_license", "soil", "solar_power_generation",
    "stainless_steel", "steel_rebar", "steel_sheet", "storage_equipment", "suspension_system",
    "tac_film", "tea", "thermal_management_system", "urban_sanitation_service",
    "usb_flash_drive", "washing_machine", "waste_incineration_equipment", "waste_to_energy",
    "waste_water_treatment", "watch", "watch_component", "watch_movement", "watch_retail_service",
    "wind_power_generation",
}
