#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generator for batch 128 submission scripts."""
import json, os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def ev(source_title, quote="根据企业公开信息"):
    return [{"source_title": source_title, "source_url": None, "quote": quote}]

def write_batch(batch_num, nodes, edges, companies, exposures):
    graph = {
        "batch_id": f"batch_{batch_num}_nodes",
        "task_description": f"Batch {batch_num} industrial nodes and edges",
        "nodes_to_upsert": nodes,
        "edges_to_upsert": edges
    }
    path_g = os.path.join(BASE_DIR, "tmp_script", f"batch_{batch_num}_nodes.json")
    with open(path_g, "w", encoding="utf-8") as f:
        json.dump(graph, f, ensure_ascii=False, indent=2)

    business = {
        "batch_id": f"batch_{batch_num}_business",
        "task_description": f"Batch {batch_num} business registration",
        "companies_to_upsert": companies,
        "company_node_exposures_to_upsert": exposures,
        "industries_to_upsert": [],
        "industry_node_mappings_to_upsert": []
    }
    path_b = os.path.join(BASE_DIR, "tmp_script", f"batch_{batch_num}_business.json")
    with open(path_b, "w", encoding="utf-8") as f:
        json.dump(business, f, ensure_ascii=False, indent=2)
    print(f"Batch {batch_num}: {len(nodes)} nodes, {len(edges)} edges, {len(companies)} companies, {len(exposures)} exposures")

NODES_128 = [
    {"node_id": "hotel_accommodation", "canonical_name_zh": "住宿服务", "canonical_name_en": "hotel accommodation", "entity_type": "service", "aliases": [], "definition": "酒店提供的住宿服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("金陵饭店主营业务")},
    {"node_id": "conference_service", "canonical_name_zh": "会议服务", "canonical_name_en": "conference service", "entity_type": "service", "aliases": [], "definition": "酒店及会展场所提供的会议接待与服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("金陵饭店经营范围")},
    {"node_id": "electrolytic_manganese_dioxide", "canonical_name_zh": "电解二氧化锰", "canonical_name_en": "electrolytic manganese dioxide", "entity_type": "material", "aliases": [], "definition": "通过电解工艺生产的二氧化锰，用于电池等领域", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("湘潭电化主营业务")},
    {"node_id": "electrolytic_metal_manganese", "canonical_name_zh": "电解金属锰", "canonical_name_en": "electrolytic metal manganese", "entity_type": "material", "aliases": [], "definition": "通过电解工艺生产的金属锰", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("湘潭电化经营范围")},
    {"node_id": "clinical_laboratory_test", "canonical_name_zh": "临床检验检测", "canonical_name_en": "clinical laboratory test", "entity_type": "service", "aliases": [], "definition": "为临床诊断提供的医学检验检测服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("博晖创新主营业务")},
    {"node_id": "trace_element_detection_system", "canonical_name_zh": "微量元素检测系统", "canonical_name_en": "trace element detection system", "entity_type": "device", "aliases": [], "definition": "用于检测人体微量元素的仪器系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("博晖创新主营业务")},
    {"node_id": "trace_element_detection_reagent", "canonical_name_zh": "微量元素检测试剂", "canonical_name_en": "trace element detection reagent", "entity_type": "material", "aliases": [], "definition": "用于微量元素检测的配套试剂", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("博晖创新经营范围")},
    {"node_id": "general_bearing", "canonical_name_zh": "通用轴承", "canonical_name_en": "general bearing", "entity_type": "component", "aliases": [], "definition": "广泛应用于各类机械设备的通用型轴承", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("ST汇洲主营业务")},
    {"node_id": "railway_bearing", "canonical_name_zh": "铁路轴承", "canonical_name_en": "railway bearing", "entity_type": "component", "aliases": [], "definition": "专门用于铁路车辆及设备的轴承", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("ST汇洲经营范围")},
    {"node_id": "enterprise_cloud_service", "canonical_name_zh": "企业云服务", "canonical_name_en": "enterprise cloud service", "entity_type": "service", "aliases": [], "definition": "面向企业提供云计算及云存储服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("ST汇洲经营范围")},
    {"node_id": "big_data_service", "canonical_name_zh": "大数据服务", "canonical_name_en": "big data service", "entity_type": "service", "aliases": [], "definition": "面向企业提供大数据分析及应用服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("ST汇洲经营范围")},
    {"node_id": "new_energy_vehicle_thermal_management", "canonical_name_zh": "新能源汽车热管理", "canonical_name_en": "new energy vehicle thermal management", "entity_type": "service", "aliases": [], "definition": "新能源汽车整车热管理系统解决方案", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("银轮股份主营业务")},
    {"node_id": "high_low_temperature_water_tank", "canonical_name_zh": "高低温水箱", "canonical_name_en": "high low temperature water tank", "entity_type": "component", "aliases": [], "definition": "用于汽车热管理系统的高低温水箱", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("银轮股份主营业务")},
    {"node_id": "battery_cooling_plate", "canonical_name_zh": "电池冷却板", "canonical_name_en": "battery cooling plate", "entity_type": "component", "aliases": [], "definition": "用于动力电池散热的冷却板", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("银轮股份经营范围")},
    {"node_id": "motor_cooler", "canonical_name_zh": "电机冷却器", "canonical_name_en": "motor cooler", "entity_type": "component", "aliases": [], "definition": "用于驱动电机散热的冷却器", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("银轮股份经营范围")},
    {"node_id": "ptc_heater", "canonical_name_zh": "PTC加热器", "canonical_name_en": "PTC heater", "entity_type": "component", "aliases": [], "definition": "采用正温度系数材料的电加热器", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("银轮股份经营范围")},
    {"node_id": "heat_exchanger", "canonical_name_zh": "热交换器", "canonical_name_en": "heat exchanger", "entity_type": "component", "aliases": [], "definition": "用于热量传递交换的装置", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("银轮股份经营范围")},
    {"node_id": "exhaust_aftertreatment", "canonical_name_zh": "尾气后处理", "canonical_name_en": "exhaust aftertreatment", "entity_type": "component", "aliases": [], "definition": "用于处理汽车尾气排放的装置系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("银轮股份经营范围")},
    {"node_id": "port_cargo_handling", "canonical_name_zh": "港口货物装卸", "canonical_name_en": "port cargo handling", "entity_type": "service", "aliases": [], "definition": "港口提供的货物装卸作业服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("连云港主营业务")},
    {"node_id": "warehousing_service", "canonical_name_zh": "仓储服务", "canonical_name_en": "warehousing service", "entity_type": "service", "aliases": [], "definition": "提供货物存储及保管的服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("连云港经营范围")},
    {"node_id": "heat_shrink_material", "canonical_name_zh": "热缩材料", "canonical_name_en": "heat shrink material", "entity_type": "material", "aliases": [], "definition": "受热后收缩的高分子材料，用于绝缘保护", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("沃尔核材主营业务")},
    {"node_id": "cold_shrink_material", "canonical_name_zh": "冷缩材料", "canonical_name_en": "cold shrink material", "entity_type": "material", "aliases": [], "definition": "无需加热即可收缩的弹性材料，用于电缆附件", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("沃尔核材经营范围")},
    {"node_id": "flame_retardant_material", "canonical_name_zh": "阻燃材料", "canonical_name_en": "flame retardant material", "entity_type": "material", "aliases": [], "definition": "具有阻燃特性的功能性材料", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("沃尔核材经营范围")},
    {"node_id": "insulating_material", "canonical_name_zh": "绝缘材料", "canonical_name_en": "insulating material", "entity_type": "material", "aliases": [], "definition": "用于电气绝缘保护的材料", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("沃尔核材经营范围")},
    {"node_id": "high_temp_corrosion_resistant_material", "canonical_name_zh": "耐高温耐腐蚀新型材料", "canonical_name_en": "high temperature corrosion resistant material", "entity_type": "material", "aliases": [], "definition": "具有耐高温和耐腐蚀特性的新型功能材料", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("沃尔核材经营范围")},
    {"node_id": "cable_accessory", "canonical_name_zh": "电缆附件", "canonical_name_en": "cable accessory", "entity_type": "component", "aliases": [], "definition": "用于电缆连接、终端处理的配套器件", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("沃尔核材经营范围")},
    {"node_id": "solar_silicon_material", "canonical_name_zh": "太阳能硅材料", "canonical_name_en": "solar silicon material", "entity_type": "material", "aliases": [], "definition": "用于太阳能光伏电池的硅材料", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("TCL中环主营业务")},
    {"node_id": "semiconductor_silicon_material", "canonical_name_zh": "半导体硅材料", "canonical_name_en": "semiconductor silicon material", "entity_type": "material", "aliases": [], "definition": "用于半导体器件制造的硅材料", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("TCL中环经营范围")},
    {"node_id": "power_chip", "canonical_name_zh": "功率芯片", "canonical_name_en": "power chip", "entity_type": "component", "aliases": [], "definition": "用于电力电子领域的功率半导体芯片", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("TCL中环经营范围")},
    {"node_id": "polished_wafer", "canonical_name_zh": "抛光片", "canonical_name_en": "polished wafer", "entity_type": "material", "aliases": [], "definition": "经过抛光处理的硅晶圆片", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("TCL中环经营范围")},
    {"node_id": "brand_integrated_service", "canonical_name_zh": "品牌综合服务", "canonical_name_en": "brand integrated service", "entity_type": "service", "aliases": [], "definition": "为品牌方提供的综合运营服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("南极电商主营业务")},
    {"node_id": "social_e_commerce", "canonical_name_zh": "社交电商", "canonical_name_en": "social e-commerce", "entity_type": "service", "aliases": [], "definition": "基于社交网络的电子商务模式", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("南极电商经营范围")},
    {"node_id": "short_video", "canonical_name_zh": "短视频", "canonical_name_en": "short video", "entity_type": "service", "aliases": [], "definition": "短时长的视频内容及平台服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("利欧股份经营范围")},
    {"node_id": "creative_content", "canonical_name_zh": "创意内容", "canonical_name_en": "creative content", "entity_type": "service", "aliases": [], "definition": "广告及营销领域的创意内容制作", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("利欧股份经营范围")},
    {"node_id": "battery_material", "canonical_name_zh": "电池材料", "canonical_name_en": "battery material", "entity_type": "material", "aliases": [], "definition": "用于电池制造的材料", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("湘潭电化经营范围")},
    {"node_id": "park_platform_service", "canonical_name_zh": "园区平台服务", "canonical_name_en": "park platform service", "entity_type": "service", "aliases": [], "definition": "面向产业园区提供的平台运营服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("南极电商经营范围")},
    {"node_id": "dealer_brand_authorization", "canonical_name_zh": "经销商品牌授权", "canonical_name_en": "dealer brand authorization", "entity_type": "service", "aliases": [], "definition": "面向经销商授予品牌使用权", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("南极电商经营范围")},
    {"node_id": "business_consulting", "canonical_name_zh": "商业咨询", "canonical_name_en": "business consulting", "entity_type": "service", "aliases": [], "definition": "面向企业提供商业策略及运营咨询服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("利欧股份经营范围")},
]

EDGES_128 = [
    {"edge_id": "hotel_accommodation_hotel_operation", "from_node": "hotel_accommodation", "to_node": "hotel_operation", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "住宿服务是酒店经营的核心业务", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "conference_service_hotel_operation", "from_node": "conference_service", "to_node": "hotel_operation", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "会议服务是酒店经营的配套服务", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "electrolytic_manganese_dioxide_chemical_product", "from_node": "electrolytic_manganese_dioxide", "to_node": "chemical_product", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "电解二氧化锰是化工产品的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "electrolytic_metal_manganese_metal_product", "from_node": "electrolytic_metal_manganese", "to_node": "metal_product", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "电解金属锰是金属产品的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "clinical_laboratory_test_medical_device", "from_node": "clinical_laboratory_test", "to_node": "medical_device", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "临床检验检测依托医疗器械开展", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "trace_element_detection_system_medical_device", "from_node": "trace_element_detection_system", "to_node": "medical_device", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "微量元素检测系统属于医疗器械", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "trace_element_detection_reagent_pharmaceutical", "from_node": "trace_element_detection_reagent", "to_node": "pharmaceutical", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "微量元素检测试剂属于医药制品", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "general_bearing_bearing", "from_node": "general_bearing", "to_node": "bearing", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "通用轴承是轴承的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "railway_bearing_bearing", "from_node": "railway_bearing", "to_node": "bearing", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "铁路轴承是轴承的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "enterprise_cloud_service_software_development_service", "from_node": "enterprise_cloud_service", "to_node": "software_development_service", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "企业云服务是软件开发服务的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "big_data_service_software_development_service", "from_node": "big_data_service", "to_node": "software_development_service", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "大数据服务是软件开发服务的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "new_energy_vehicle_thermal_management_automotive", "from_node": "new_energy_vehicle_thermal_management", "to_node": "automotive", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "新能源汽车热管理是汽车配套服务", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "high_low_temperature_water_tank_automotive", "from_node": "high_low_temperature_water_tank", "to_node": "automotive", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "高低温水箱是汽车零部件", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "battery_cooling_plate_automotive", "from_node": "battery_cooling_plate", "to_node": "automotive", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "电池冷却板是新能源汽车零部件", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "motor_cooler_automotive", "from_node": "motor_cooler", "to_node": "automotive", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "电机冷却器是汽车零部件", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "ptc_heater_automotive", "from_node": "ptc_heater", "to_node": "automotive", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "PTC加热器是汽车零部件", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "heat_exchanger_machinery", "from_node": "heat_exchanger", "to_node": "machinery", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "热交换器是机械设备的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "exhaust_aftertreatment_automotive", "from_node": "exhaust_aftertreatment", "to_node": "automotive", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "尾气后处理是汽车零部件", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "port_cargo_handling_port", "from_node": "port_cargo_handling", "to_node": "port", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "港口货物装卸是港口的核心服务", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "warehousing_service_logistics", "from_node": "warehousing_service", "to_node": "logistics", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "仓储服务是物流服务的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "heat_shrink_material_new_material", "from_node": "heat_shrink_material", "to_node": "new_material", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "热缩材料是新材料的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "cold_shrink_material_new_material", "from_node": "cold_shrink_material", "to_node": "new_material", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "冷缩材料是新材料的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "flame_retardant_material_chemical_product", "from_node": "flame_retardant_material", "to_node": "chemical_product", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "阻燃材料是化工产品的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "insulating_material_electronic_component", "from_node": "insulating_material", "to_node": "electronic_component", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "绝缘材料用于电子元器件领域", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "high_temp_corrosion_resistant_material_new_material", "from_node": "high_temp_corrosion_resistant_material", "to_node": "new_material", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "耐高温耐腐蚀新型材料属于新材料", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "cable_accessory_electronic_component", "from_node": "cable_accessory", "to_node": "electronic_component", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "电缆附件属于电子元器件配套产品", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "solar_silicon_material_solar_power_generation", "from_node": "solar_silicon_material", "to_node": "solar_power_generation", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "太阳能硅材料用于太阳能发电", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "semiconductor_silicon_material_semiconductor", "from_node": "semiconductor_silicon_material", "to_node": "semiconductor", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "半导体硅材料用于半导体制造", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "power_chip_integrated_circuit", "from_node": "power_chip", "to_node": "integrated_circuit", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "功率芯片是集成电路的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "polished_wafer_semiconductor", "from_node": "polished_wafer", "to_node": "semiconductor", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "抛光片是半导体材料的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "brand_integrated_service_e_commerce", "from_node": "brand_integrated_service", "to_node": "e_commerce", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "品牌综合服务是电商服务的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "social_e_commerce_e_commerce", "from_node": "social_e_commerce", "to_node": "e_commerce", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "社交电商是电子商务的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "short_video_digital_media", "from_node": "short_video", "to_node": "digital_media", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "短视频是数字媒体的一种形式", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "creative_content_digital_media", "from_node": "creative_content", "to_node": "digital_media", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "创意内容是数字媒体服务的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "battery_material_chemical_product", "from_node": "battery_material", "to_node": "chemical_product", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "电池材料是化工产品的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "park_platform_service_e_commerce", "from_node": "park_platform_service", "to_node": "e_commerce", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "园区平台服务是电商服务的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "dealer_brand_authorization_e_commerce", "from_node": "dealer_brand_authorization", "to_node": "e_commerce", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "经销商品牌授权是电商服务的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "business_consulting_technical_service", "from_node": "business_consulting", "to_node": "technical_service", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "商业咨询是技术服务的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
]

COMPANIES_128 = [
    {"company_id": "sh_601007", "name_zh": "金陵饭店", "name_en": "Jinling Hotel Corporation, Ltd.", "country": "CN", "province": "江苏", "city": "南京市", "stock_codes": ["601007.SH"], "description": "酒店经营、住宿、餐饮、会议", "founded_year": 2002, "employee_count": 2800},
    {"company_id": "sz_002125", "name_zh": "湘潭电化", "name_en": "Xiangtan Electrochemical Scientific Co., Ltd.", "country": "CN", "province": "湖南", "city": "湘潭市", "stock_codes": ["002125.SZ"], "description": "电解二氧化锰、电解金属锰", "founded_year": 1994, "employee_count": 2100},
    {"company_id": "sz_300318", "name_zh": "博晖创新", "name_en": "Bioevopeak Co., Ltd.", "country": "CN", "province": "北京", "city": "北京市", "stock_codes": ["300318.SZ"], "description": "临床检验快速检测、微量元素检测", "founded_year": 2001, "employee_count": 1200},
    {"company_id": "sz_002122", "name_zh": "ST汇洲", "name_en": "Tianma Bearing Group Co., Ltd.", "country": "CN", "province": "浙江", "city": "杭州市", "stock_codes": ["002122.SZ"], "description": "通用轴承、铁路轴承、企业云服务、大数据", "founded_year": 2002, "employee_count": 3200},
    {"company_id": "sz_002126", "name_zh": "银轮股份", "name_en": "Zhejiang Yinlun Machinery Co., Ltd.", "country": "CN", "province": "浙江", "city": "台州市", "stock_codes": ["002126.SZ"], "description": "新能源汽车热管理、热交换器、尾气后处理", "founded_year": 1999, "employee_count": 8200},
    {"company_id": "sh_601008", "name_zh": "连云港", "name_en": "Lianyungang Port Co., Ltd.", "country": "CN", "province": "江苏", "city": "连云港市", "stock_codes": ["601008.SH"], "description": "港口货物装卸、仓储服务", "founded_year": 2001, "employee_count": 4800},
    {"company_id": "sz_002130", "name_zh": "沃尔核材", "name_en": "Shenzhen Woer Heat-Shrinkable Material Co., Ltd.", "country": "CN", "province": "广东", "city": "深圳市", "stock_codes": ["002130.SZ"], "description": "热缩材料、冷缩材料、阻燃材料、绝缘材料、电缆附件", "founded_year": 1998, "employee_count": 5800},
    {"company_id": "sz_002129", "name_zh": "TCL中环", "name_en": "TCL Zhonghuan Renewable Energy Technology Co., Ltd.", "country": "CN", "province": "天津", "city": "天津市", "stock_codes": ["002129.SZ"], "description": "太阳能硅材料、半导体硅材料、功率芯片、抛光片", "founded_year": 1999, "employee_count": 12000},
    {"company_id": "sz_002127", "name_zh": "南极电商", "name_en": "Nanjids E-Commerce Co., Ltd.", "country": "CN", "province": "江苏", "city": "苏州市", "stock_codes": ["002127.SZ"], "description": "品牌综合服务、货品销售、社交电商", "founded_year": 1999, "employee_count": 600},
    {"company_id": "sz_002131", "name_zh": "利欧股份", "name_en": "Leo Group Co., Ltd.", "country": "CN", "province": "浙江", "city": "台州市", "stock_codes": ["002131.SZ"], "description": "商业咨询、数据与流量、创意内容、短视频、社交电商", "founded_year": 2001, "employee_count": 6200},
]

EXPOSURES_128 = [
    {"exposure_id": "sh_601007_provide_service_hotel_accommodation", "company_id": "sh_601007", "node_id": "hotel_accommodation", "activity_type": "provide_service", "weight": 0.35, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:住宿")},
    {"exposure_id": "sh_601007_provide_service_catering_service", "company_id": "sh_601007", "node_id": "catering_service", "activity_type": "provide_service", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:餐饮")},
    {"exposure_id": "sh_601007_provide_service_conference_service", "company_id": "sh_601007", "node_id": "conference_service", "activity_type": "provide_service", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:会议")},
    {"exposure_id": "sh_601007_provide_service_hotel_operation", "company_id": "sh_601007", "node_id": "hotel_operation", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:酒店经营")},
    {"exposure_id": "sh_601007_provide_service_technical_service", "company_id": "sh_601007", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术服务")},
    {"exposure_id": "sz_002125_produce_electrolytic_manganese_dioxide", "company_id": "sz_002125", "node_id": "electrolytic_manganese_dioxide", "activity_type": "produce", "weight": 0.40, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:电解二氧化锰")},
    {"exposure_id": "sz_002125_produce_electrolytic_metal_manganese", "company_id": "sz_002125", "node_id": "electrolytic_metal_manganese", "activity_type": "produce", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:电解金属锰")},
    {"exposure_id": "sz_002125_produce_chemical_product", "company_id": "sz_002125", "node_id": "chemical_product", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:化工产品")},
    {"exposure_id": "sz_002125_produce_battery_material", "company_id": "sz_002125", "node_id": "battery_material", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:电池材料")},
    {"exposure_id": "sz_002125_provide_service_technical_service", "company_id": "sz_002125", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术服务")},
    {"exposure_id": "sz_300318_produce_trace_element_detection_system", "company_id": "sz_300318", "node_id": "trace_element_detection_system", "activity_type": "produce", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:微量元素检测系统")},
    {"exposure_id": "sz_300318_produce_trace_element_detection_reagent", "company_id": "sz_300318", "node_id": "trace_element_detection_reagent", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:检测试剂")},
    {"exposure_id": "sz_300318_provide_service_clinical_laboratory_test", "company_id": "sz_300318", "node_id": "clinical_laboratory_test", "activity_type": "provide_service", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:临床检验")},
    {"exposure_id": "sz_300318_produce_medical_device", "company_id": "sz_300318", "node_id": "medical_device", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:医疗器械")},
    {"exposure_id": "sz_300318_provide_service_technical_service", "company_id": "sz_300318", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术服务")},
    {"exposure_id": "sz_002122_produce_general_bearing", "company_id": "sz_002122", "node_id": "general_bearing", "activity_type": "produce", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:通用轴承")},
    {"exposure_id": "sz_002122_produce_railway_bearing", "company_id": "sz_002122", "node_id": "railway_bearing", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:铁路轴承")},
    {"exposure_id": "sz_002122_provide_service_enterprise_cloud_service", "company_id": "sz_002122", "node_id": "enterprise_cloud_service", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:企业云服务")},
    {"exposure_id": "sz_002122_provide_service_big_data_service", "company_id": "sz_002122", "node_id": "big_data_service", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:大数据")},
    {"exposure_id": "sz_002122_produce_bearing", "company_id": "sz_002122", "node_id": "bearing", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:轴承")},
    {"exposure_id": "sz_002122_provide_service_artificial_intelligence", "company_id": "sz_002122", "node_id": "artificial_intelligence", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:商业人工智能")},
    {"exposure_id": "sz_002126_produce_heat_exchanger", "company_id": "sz_002126", "node_id": "heat_exchanger", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:热交换器")},
    {"exposure_id": "sz_002126_provide_service_new_energy_vehicle_thermal_management", "company_id": "sz_002126", "node_id": "new_energy_vehicle_thermal_management", "activity_type": "provide_service", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:新能源汽车热管理")},
    {"exposure_id": "sz_002126_produce_battery_cooling_plate", "company_id": "sz_002126", "node_id": "battery_cooling_plate", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:电池冷却板")},
    {"exposure_id": "sz_002126_produce_motor_cooler", "company_id": "sz_002126", "node_id": "motor_cooler", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:电机冷却器")},
    {"exposure_id": "sz_002126_produce_ptc_heater", "company_id": "sz_002126", "node_id": "ptc_heater", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:PTC加热器")},
    {"exposure_id": "sz_002126_produce_exhaust_aftertreatment", "company_id": "sz_002126", "node_id": "exhaust_aftertreatment", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:尾气后处理")},
    {"exposure_id": "sz_002126_provide_service_technical_service", "company_id": "sz_002126", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术服务")},
    {"exposure_id": "sh_601008_provide_service_port_cargo_handling", "company_id": "sh_601008", "node_id": "port_cargo_handling", "activity_type": "provide_service", "weight": 0.40, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:港口货物装卸")},
    {"exposure_id": "sh_601008_provide_service_port", "company_id": "sh_601008", "node_id": "port", "activity_type": "provide_service", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:港口")},
    {"exposure_id": "sh_601008_provide_service_warehousing_service", "company_id": "sh_601008", "node_id": "warehousing_service", "activity_type": "provide_service", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:仓储")},
    {"exposure_id": "sh_601008_provide_service_logistics", "company_id": "sh_601008", "node_id": "logistics", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:物流")},
    {"exposure_id": "sh_601008_provide_service_shipping", "company_id": "sh_601008", "node_id": "shipping", "activity_type": "provide_service", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:航运")},
    {"exposure_id": "sz_002130_produce_heat_shrink_material", "company_id": "sz_002130", "node_id": "heat_shrink_material", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:热缩材料")},
    {"exposure_id": "sz_002130_produce_cold_shrink_material", "company_id": "sz_002130", "node_id": "cold_shrink_material", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:冷缩材料")},
    {"exposure_id": "sz_002130_produce_flame_retardant_material", "company_id": "sz_002130", "node_id": "flame_retardant_material", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:阻燃材料")},
    {"exposure_id": "sz_002130_produce_insulating_material", "company_id": "sz_002130", "node_id": "insulating_material", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:绝缘材料")},
    {"exposure_id": "sz_002130_produce_high_temp_corrosion_resistant_material", "company_id": "sz_002130", "node_id": "high_temp_corrosion_resistant_material", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:耐高温耐腐蚀新型材料")},
    {"exposure_id": "sz_002130_produce_cable_accessory", "company_id": "sz_002130", "node_id": "cable_accessory", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:电缆附件")},
    {"exposure_id": "sz_002130_provide_service_technical_service", "company_id": "sz_002130", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术服务")},
    {"exposure_id": "sz_002129_produce_solar_silicon_material", "company_id": "sz_002129", "node_id": "solar_silicon_material", "activity_type": "produce", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:太阳能硅材料")},
    {"exposure_id": "sz_002129_produce_semiconductor_silicon_material", "company_id": "sz_002129", "node_id": "semiconductor_silicon_material", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:半导体硅材料")},
    {"exposure_id": "sz_002129_produce_power_chip", "company_id": "sz_002129", "node_id": "power_chip", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:功率芯片")},
    {"exposure_id": "sz_002129_produce_polished_wafer", "company_id": "sz_002129", "node_id": "polished_wafer", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:抛光片")},
    {"exposure_id": "sz_002129_produce_semiconductor", "company_id": "sz_002129", "node_id": "semiconductor", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:半导体")},
    {"exposure_id": "sz_002129_provide_service_technical_service", "company_id": "sz_002129", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术服务")},
    {"exposure_id": "sz_002127_provide_service_brand_integrated_service", "company_id": "sz_002127", "node_id": "brand_integrated_service", "activity_type": "provide_service", "weight": 0.35, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:品牌综合服务")},
    {"exposure_id": "sz_002127_provide_service_e_commerce", "company_id": "sz_002127", "node_id": "e_commerce", "activity_type": "provide_service", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:货品销售")},
    {"exposure_id": "sz_002127_provide_service_social_e_commerce", "company_id": "sz_002127", "node_id": "social_e_commerce", "activity_type": "provide_service", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:社交电商")},
    {"exposure_id": "sz_002127_provide_service_park_platform_service", "company_id": "sz_002127", "node_id": "park_platform_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:园区平台服务")},
    {"exposure_id": "sz_002127_provide_service_dealer_brand_authorization", "company_id": "sz_002127", "node_id": "dealer_brand_authorization", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:经销商品牌授权")},
    {"exposure_id": "sz_002131_provide_service_business_consulting", "company_id": "sz_002131", "node_id": "business_consulting", "activity_type": "provide_service", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:商业咨询")},
    {"exposure_id": "sz_002131_provide_service_internet_advertising", "company_id": "sz_002131", "node_id": "internet_advertising", "activity_type": "provide_service", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:数据与流量")},
    {"exposure_id": "sz_002131_provide_service_creative_content", "company_id": "sz_002131", "node_id": "creative_content", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:创意内容")},
    {"exposure_id": "sz_002131_provide_service_short_video", "company_id": "sz_002131", "node_id": "short_video", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:短视频")},
    {"exposure_id": "sz_002131_provide_service_digital_media", "company_id": "sz_002131", "node_id": "digital_media", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:媒体策划")},
    {"exposure_id": "sz_002131_provide_service_technical_service", "company_id": "sz_002131", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术服务")},
]

write_batch(128, NODES_128, EDGES_128, COMPANIES_128, EXPOSURES_128)
print("Batch 128 generated.")
