#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generator for batch 121-125 submission scripts."""

import json, os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def ev(source_title, quote="根据企业公开信息"):
    return [{"source_title": source_title, "source_url": None, "quote": quote}]

# Helper to write per-batch files
def write_batch(batch_num, nodes, edges, companies, exposures):
    # Graph batch JSON
    graph = {
        "batch_id": f"batch_{batch_num}_nodes",
        "task_description": f"Batch {batch_num} industrial nodes and edges",
        "nodes_to_upsert": nodes,
        "edges_to_upsert": edges
    }
    path_g = os.path.join(BASE_DIR, "tmp_script", f"batch_{batch_num}_nodes.json")
    with open(path_g, "w", encoding="utf-8") as f:
        json.dump(graph, f, ensure_ascii=False, indent=2)

    # Business batch JSON
    business = {
        "batch_id": f"batch_{batch_num}_business",
        "task_description": f"Batch {batch_num} business registration",
        "companies_to_upsert": companies,
        "company_node_exposures_to_upsert": exposures,
        "industries_to_upsert": [],
        "industry_node_mappings_to_upsert": []
    }
    path_b = os.path.join(BASE_DIR, "tmp_script", f"batch_{batch_num}_business.json")
    with open(path_b, "w", encoding="utf-8") as f:
        json.dump(business, f, ensure_ascii=False, indent=2)

    print(f"Batch {batch_num}: {len(nodes)} nodes, {len(edges)} edges, {len(companies)} companies, {len(exposures)} exposures -> written")

# ============================================================
# BATCH 121
# ============================================================
NODES_121 = [
    {"node_id": "air_transport", "canonical_name_zh": "航空运输", "canonical_name_en": "air transport", "entity_type": "service", "aliases": [], "definition": "利用航空器从事旅客、货物、邮件运输的服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("中国国航主营业务")},
    {"node_id": "aircraft_maintenance", "canonical_name_zh": "航空器维修", "canonical_name_en": "aircraft maintenance", "entity_type": "service", "aliases": [], "definition": "对民用航空器及其部件进行检测、修理、翻修和改装的维修活动", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("中国国航经营范围")},
    {"node_id": "ground_service", "canonical_name_zh": "航空地面服务", "canonical_name_en": "aviation ground service", "entity_type": "service", "aliases": [], "definition": "为航空器在地面运行期间提供的各类服务，包括客货装卸、飞机引导、加油等", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("中国国航经营范围")},
    {"node_id": "duty_free", "canonical_name_zh": "免税品", "canonical_name_en": "duty-free goods", "entity_type": "material", "aliases": [], "definition": "在免税商店销售的免除进口关税、增值税等税费的商品", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("中国国航经营范围")},
    {"node_id": "air_cargo", "canonical_name_zh": "航空货运", "canonical_name_en": "air cargo", "entity_type": "service", "aliases": [], "definition": "利用航空器运输货物的服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("中国国航主营业务")},
    {"node_id": "kraft_linerboard", "canonical_name_zh": "牛皮箱纸板", "canonical_name_en": "kraft linerboard", "entity_type": "material", "aliases": [], "definition": "以硫酸盐木浆为主要原料制成的强度高、耐折度好的包装纸板", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("景兴纸业主营业务")},
    {"node_id": "white_top_kraft_linerboard", "canonical_name_zh": "白面牛皮卡纸", "canonical_name_en": "white top kraft linerboard", "entity_type": "material", "aliases": [], "definition": "表面为白色、底层为牛皮浆的复合包装纸板", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("景兴纸业主营业务")},
    {"node_id": "corrugated_medium_paper", "canonical_name_zh": "瓦楞原纸", "canonical_name_en": "corrugated medium paper", "entity_type": "material", "aliases": [], "definition": "用于制造瓦楞纸板芯层的包装用纸", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("景兴纸业主营业务")},
    {"node_id": "corrugated_carton", "canonical_name_zh": "瓦楞纸箱", "canonical_name_en": "corrugated carton", "entity_type": "material", "aliases": [], "definition": "由瓦楞纸板制成的包装容器", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("景兴纸业主营业务")},
    {"node_id": "recycled_paper", "canonical_name_zh": "再生纸", "canonical_name_en": "recycled paper", "entity_type": "material", "aliases": [], "definition": "利用废纸为原料生产的纸制品", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("景兴纸业经营范围")},
    {"node_id": "carbon_black", "canonical_name_zh": "炭黑", "canonical_name_en": "carbon black", "entity_type": "material", "aliases": [], "definition": "由烃类化合物不完全燃烧或热裂解生成的黑色无定形碳粉末，主要用于橡胶补强", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("黑猫股份主要产品")},
    {"node_id": "white_carbon_black", "canonical_name_zh": "白炭黑", "canonical_name_en": "white carbon black", "entity_type": "material", "aliases": ["silica"], "definition": "白色无定形二氧化硅粉末，用作橡胶补强剂和涂料消光剂", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("黑猫股份经营范围")},
    {"node_id": "coal_tar", "canonical_name_zh": "煤焦油", "canonical_name_en": "coal tar", "entity_type": "material", "aliases": [], "definition": "煤干馏过程中产生的黑色或黑褐色粘稠液体，用于提取化工原料", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("黑猫股份经营范围")},
    {"node_id": "industrial_naphthalene", "canonical_name_zh": "工业萘", "canonical_name_en": "industrial naphthalene", "entity_type": "material", "aliases": [], "definition": "从煤焦油中提取的双环芳烃化合物，用于生产染料、农药等", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("黑猫股份经营范围")},
    {"node_id": "pitch", "canonical_name_zh": "沥青", "canonical_name_en": "pitch", "entity_type": "material", "aliases": [], "definition": "煤焦油蒸馏后的残渣，用于电极、防水材料等", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("黑猫股份经营范围")},
    {"node_id": "contrast_agent", "canonical_name_zh": "对比剂", "canonical_name_en": "contrast agent", "entity_type": "material", "aliases": [], "definition": "用于医学影像检查中增强组织对比度的药物", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("北陆药业主营业务")},
    {"node_id": "psychiatric_drug", "canonical_name_zh": "精神类药品", "canonical_name_en": "psychiatric drug", "entity_type": "material", "aliases": [], "definition": "用于治疗精神疾病的药物", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("北陆药业主营业务")},
    {"node_id": "hypoglycemic_drug", "canonical_name_zh": "降糖药", "canonical_name_en": "hypoglycemic drug", "entity_type": "material", "aliases": [], "definition": "用于降低血糖水平的药物", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("北陆药业主营业务")},
    {"node_id": "e_government_software", "canonical_name_zh": "电子政务软件", "canonical_name_en": "e-government software", "entity_type": "material", "aliases": [], "definition": "用于政府机构信息化管理的软件系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("华宇软件主营业务")},
    {"node_id": "judicial_informatization", "canonical_name_zh": "司法信息化", "canonical_name_en": "judicial informatization", "entity_type": "service", "aliases": [], "definition": "为法院、检察院等司法机关提供的信息化解决方案和服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("华宇软件主营业务")},
    {"node_id": "information_security_service", "canonical_name_zh": "信息安全服务", "canonical_name_en": "information security service", "entity_type": "service", "aliases": [], "definition": "为保护信息系统安全提供的咨询、测评、运维等服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("华宇软件经营范围")},
    {"node_id": "coalbed_methane", "canonical_name_zh": "煤层气", "canonical_name_en": "coalbed methane", "entity_type": "material", "aliases": [], "definition": "储存在煤层中的以甲烷为主要成分的天然气", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("潞安环能经营范围")},
    {"node_id": "marine_aquaculture", "canonical_name_zh": "海水养殖", "canonical_name_en": "marine aquaculture", "entity_type": "service", "aliases": [], "definition": "在海水环境中进行的动植物养殖活动", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("獐子岛主营业务")},
    {"node_id": "marine_fishery", "canonical_name_zh": "海洋渔业", "canonical_name_en": "marine fishery", "entity_type": "service", "aliases": [], "definition": "在海洋中进行的捕捞和养殖活动", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("獐子岛经营范围")},
    {"node_id": "aquatic_product", "canonical_name_zh": "水产品", "canonical_name_en": "aquatic product", "entity_type": "material", "aliases": [], "definition": "通过捕捞或养殖获得的水生动物和植物产品", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("獐子岛经营范围")},
    {"node_id": "management_software", "canonical_name_zh": "管理软件", "canonical_name_en": "management software", "entity_type": "material", "aliases": [], "definition": "用于企业和组织管理的软件系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("久其软件主营业务")},
    {"node_id": "digital_media", "canonical_name_zh": "数字传播", "canonical_name_en": "digital media", "entity_type": "service", "aliases": [], "definition": "通过数字化手段进行内容制作和传播的服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("久其软件主营业务")},
    {"node_id": "internet_bandwidth_optimization", "canonical_name_zh": "互联网带宽优化", "canonical_name_en": "internet bandwidth optimization", "entity_type": "service", "aliases": [], "definition": "通过技术手段优化互联网出口带宽使用效率的服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("凯瑞德主营业务")},
    {"node_id": "supply_chain_management", "canonical_name_zh": "供应链管理", "canonical_name_en": "supply chain management", "entity_type": "service", "aliases": [], "definition": "对供应链各环节进行计划、协调、控制和优化的管理活动", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("凯瑞德经营范围")},
    {"node_id": "internet_application_acceleration", "canonical_name_zh": "互联网应用加速", "canonical_name_en": "internet application acceleration", "entity_type": "service", "aliases": [], "definition": "通过技术手段提升互联网应用访问速度的服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("凯瑞德主营业务")},
    {"node_id": "hotel_operation", "canonical_name_zh": "酒店经营", "canonical_name_en": "hotel operation", "entity_type": "service", "aliases": [], "definition": "提供住宿、餐饮、会议等服务的酒店经营管理活动", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("北辰实业主营业务")},
    {"node_id": "exhibition_service", "canonical_name_zh": "会展服务", "canonical_name_en": "exhibition service", "entity_type": "service", "aliases": [], "definition": "为会议和展览活动提供场地、策划、组织等服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("北辰实业经营范围")},
]

EDGES_121 = [
    {"edge_id": "air_transport_aircraft_maintenance", "from_node": "air_transport", "to_node": "aircraft_maintenance", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "航空运输依赖航空器维修服务", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "air_transport_ground_service", "from_node": "air_transport", "to_node": "ground_service", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "航空运输需要地面服务支持", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "air_cargo_air_transport", "from_node": "air_cargo", "to_node": "air_transport", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "航空货运是航空运输的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "duty_free_air_transport", "from_node": "duty_free", "to_node": "air_transport", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "免税品销售依托航空运输场景", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "kraft_linerboard_corrugated_carton", "from_node": "kraft_linerboard", "to_node": "corrugated_carton", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "牛皮箱纸板是瓦楞纸箱的面纸材料", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "corrugated_medium_paper_corrugated_carton", "from_node": "corrugated_medium_paper", "to_node": "corrugated_carton", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "瓦楞原纸是瓦楞纸箱的芯纸材料", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "recycled_paper_kraft_linerboard", "from_node": "recycled_paper", "to_node": "kraft_linerboard", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "再生纸可用于生产牛皮箱纸板", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "carbon_black_rubber_product", "from_node": "carbon_black", "to_node": "rubber_product", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "炭黑是橡胶制品的重要补强剂", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "white_carbon_black_rubber_product", "from_node": "white_carbon_black", "to_node": "rubber_product", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "白炭黑用于橡胶和硅橡胶补强", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "coal_tar_pitch", "from_node": "coal_tar", "to_node": "pitch", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "煤焦油蒸馏残渣为沥青", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "industrial_naphthalene_coal_tar", "from_node": "industrial_naphthalene", "to_node": "coal_tar", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "工业萘从煤焦油中提取", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "contrast_agent_pharmaceutical", "from_node": "contrast_agent", "to_node": "pharmaceutical", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "对比剂是药品的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "psychiatric_drug_pharmaceutical", "from_node": "psychiatric_drug", "to_node": "pharmaceutical", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "精神类药品是药品的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "hypoglycemic_drug_pharmaceutical", "from_node": "hypoglycemic_drug", "to_node": "pharmaceutical", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "降糖药是药品的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "e_government_software_software_development_service", "from_node": "e_government_software", "to_node": "software_development_service", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "电子政务软件是软件开发服务的产品", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "judicial_informatization_e_government_software", "from_node": "judicial_informatization", "to_node": "e_government_software", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "司法信息化是电子政务软件的应用领域", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "information_security_service_software_development_service", "from_node": "information_security_service", "to_node": "software_development_service", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "信息安全服务支持软件开发", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "coalbed_methane_natural_gas", "from_node": "coalbed_methane", "to_node": "natural_gas", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "煤层气是天然气的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "marine_aquaculture_marine_fishery", "from_node": "marine_aquaculture", "to_node": "marine_fishery", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "海水养殖是海洋渔业的组成部分", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "aquatic_product_marine_fishery", "from_node": "aquatic_product", "to_node": "marine_fishery", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "水产品来自海洋渔业", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "management_software_software_development_service", "from_node": "management_software", "to_node": "software_development_service", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "管理软件是软件开发服务的产品", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "digital_media_management_software", "from_node": "digital_media", "to_node": "management_software", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "数字传播服务依托管理软件平台", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "internet_bandwidth_optimization_supply_chain_management", "from_node": "internet_bandwidth_optimization", "to_node": "supply_chain_management", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "带宽优化服务支持供应链管理", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "internet_application_acceleration_internet_bandwidth_optimization", "from_node": "internet_application_acceleration", "to_node": "internet_bandwidth_optimization", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "应用加速是带宽优化的延伸服务", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "hotel_operation_real_estate_development", "from_node": "hotel_operation", "to_node": "real_estate_development", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "酒店经营是房地产开发后续服务", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "exhibition_service_real_estate_development", "from_node": "exhibition_service", "to_node": "real_estate_development", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "会展服务依托商业地产开展", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
]

COMPANIES_121 = [
    {"company_id": "sh_601111", "name_zh": "中国国航", "name_en": "Air China Limited", "country": "CN", "province": "北京", "city": "北京市", "stock_codes": ["601111.SH"], "description": "国际、国内航空客货邮和行李运输业务", "founded_year": 2006, "employee_count": 107795},
    {"company_id": "sz_002067", "name_zh": "景兴纸业", "name_en": "Zhejiang Jingxing Paper Co., Ltd.", "country": "CN", "province": "浙江", "city": "嘉兴市", "stock_codes": ["002067.SZ"], "description": "牛皮箱纸板、白面牛皮卡纸、瓦楞原纸和瓦楞纸箱的生产销售", "founded_year": 1996, "employee_count": 2180},
    {"company_id": "sz_002068", "name_zh": "黑猫股份", "name_en": "Jiangxi Black Cat Carbon Black Co., Ltd.", "country": "CN", "province": "江西", "city": "景德镇市", "stock_codes": ["002068.SZ"], "description": "炭黑、白炭黑及相关化工产品的生产销售", "founded_year": 2001, "employee_count": 4259},
    {"company_id": "sz_300016", "name_zh": "北陆药业", "name_en": "Beijing Beilu Pharmaceutical Co., Ltd.", "country": "CN", "province": "北京", "city": "北京市", "stock_codes": ["300016.SZ"], "description": "对比剂系列、精神类药品和降糖类药品的研发、生产与销售", "founded_year": 1992, "employee_count": 1173},
    {"company_id": "sz_300271", "name_zh": "华宇软件", "name_en": "Beijing Thunisoft Co., Ltd.", "country": "CN", "province": "北京", "city": "北京市", "stock_codes": ["300271.SZ"], "description": "电子政务系统的产品开发与服务", "founded_year": 2001, "employee_count": 4140},
    {"company_id": "sh_601699", "name_zh": "潞安环能", "name_en": "Shanxi Lu'an Environmental Energy Development Co., Ltd.", "country": "CN", "province": "山西", "city": "长治市", "stock_codes": ["601699.SH"], "description": "原煤开采、煤炭洗选、煤焦冶炼", "founded_year": 2001, "employee_count": 34954},
    {"company_id": "sz_002069", "name_zh": "獐子岛", "name_en": "Zhangzidao Group Co., Ltd.", "country": "CN", "province": "辽宁", "city": "大连市", "stock_codes": ["002069.SZ"], "description": "海洋水产业", "founded_year": 1992, "employee_count": 1554},
    {"company_id": "sz_002279", "name_zh": "久其软件", "name_en": "Beijing Join-Cheer Software Co., Ltd.", "country": "CN", "province": "北京", "city": "北京市", "stock_codes": ["002279.SZ"], "description": "管理软件和数字传播", "founded_year": 1999, "employee_count": 3253},
    {"company_id": "sz_002072", "name_zh": "凯瑞德", "name_en": "Kairuide Holding Co., Ltd.", "country": "CN", "province": "湖北", "city": "荆门市", "stock_codes": ["002072.SZ"], "description": "互联网出口带宽优化服务和互联网应用加速服务", "founded_year": 2000, "employee_count": 43},
    {"company_id": "sh_601588", "name_zh": "北辰实业", "name_en": "Beijing North Star Co., Ltd.", "country": "CN", "province": "北京", "city": "北京市", "stock_codes": ["601588.SH"], "description": "发展物业、投资物业及商业物业", "founded_year": 1998, "employee_count": 4729},
]

EXPOSURES_121 = [
    {"exposure_id": "sh_601111_provide_service_air_transport", "company_id": "sh_601111", "node_id": "air_transport", "activity_type": "provide_service", "weight": 0.40, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:航空客货运输")},
    {"exposure_id": "sh_601111_provide_service_air_cargo", "company_id": "sh_601111", "node_id": "air_cargo", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:航空货运")},
    {"exposure_id": "sh_601111_provide_service_aircraft_maintenance", "company_id": "sh_601111", "node_id": "aircraft_maintenance", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:航空器维修")},
    {"exposure_id": "sh_601111_provide_service_ground_service", "company_id": "sh_601111", "node_id": "ground_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:地面服务")},
    {"exposure_id": "sh_601111_produce_duty_free", "company_id": "sh_601111", "node_id": "duty_free", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:机上免税品")},
    {"exposure_id": "sh_601111_provide_service_catering_service", "company_id": "sh_601111", "node_id": "catering_service", "activity_type": "provide_service", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:餐饮服务")},
    {"exposure_id": "sh_601111_provide_service_hotel_operation", "company_id": "sh_601111", "node_id": "hotel_operation", "activity_type": "provide_service", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:酒店管理")},
    {"exposure_id": "sh_601111_provide_service_technical_service", "company_id": "sh_601111", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术培训")},
    {"exposure_id": "sz_002067_produce_kraft_linerboard", "company_id": "sz_002067", "node_id": "kraft_linerboard", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:牛皮箱纸板")},
    {"exposure_id": "sz_002067_produce_white_top_kraft_linerboard", "company_id": "sz_002067", "node_id": "white_top_kraft_linerboard", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:白面牛皮卡纸")},
    {"exposure_id": "sz_002067_produce_corrugated_medium_paper", "company_id": "sz_002067", "node_id": "corrugated_medium_paper", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:瓦楞原纸")},
    {"exposure_id": "sz_002067_produce_corrugated_carton", "company_id": "sz_002067", "node_id": "corrugated_carton", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:瓦楞纸箱")},
    {"exposure_id": "sz_002067_produce_recycled_paper", "company_id": "sz_002067", "node_id": "recycled_paper", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:绿色环保再生纸")},
    {"exposure_id": "sz_002067_provide_service_technical_service", "company_id": "sz_002067", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术服务")},
    {"exposure_id": "sz_002068_produce_carbon_black", "company_id": "sz_002068", "node_id": "carbon_black", "activity_type": "produce", "weight": 0.35, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:炭黑")},
    {"exposure_id": "sz_002068_produce_white_carbon_black", "company_id": "sz_002068", "node_id": "white_carbon_black", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:白炭黑")},
    {"exposure_id": "sz_002068_produce_coal_tar", "company_id": "sz_002068", "node_id": "coal_tar", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:焦油")},
    {"exposure_id": "sz_002068_produce_pitch", "company_id": "sz_002068", "node_id": "pitch", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:沥青")},
    {"exposure_id": "sz_002068_produce_industrial_naphthalene", "company_id": "sz_002068", "node_id": "industrial_naphthalene", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:工业萘")},
    {"exposure_id": "sz_002068_provide_service_steam", "company_id": "sz_002068", "node_id": "steam", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:蒸汽")},
    {"exposure_id": "sz_002068_operate_power_generation", "company_id": "sz_002068", "node_id": "power_generation", "activity_type": "operate", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:发电")},
    {"exposure_id": "sz_300016_produce_contrast_agent", "company_id": "sz_300016", "node_id": "contrast_agent", "activity_type": "produce", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:对比剂系列")},
    {"exposure_id": "sz_300016_produce_psychiatric_drug", "company_id": "sz_300016", "node_id": "psychiatric_drug", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:精神类药品")},
    {"exposure_id": "sz_300016_produce_hypoglycemic_drug", "company_id": "sz_300016", "node_id": "hypoglycemic_drug", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:降糖类药品")},
    {"exposure_id": "sz_300016_produce_pharmaceutical_api", "company_id": "sz_300016", "node_id": "pharmaceutical_api", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:原料药")},
    {"exposure_id": "sz_300016_produce_chemical_drug", "company_id": "sz_300016", "node_id": "chemical_drug", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:生产销售注射剂片剂")},
    {"exposure_id": "sz_300271_produce_e_government_software", "company_id": "sz_300271", "node_id": "e_government_software", "activity_type": "produce", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:电子政务系统")},
    {"exposure_id": "sz_300271_provide_service_judicial_informatization", "company_id": "sz_300271", "node_id": "judicial_informatization", "activity_type": "provide_service", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:法院检察院信息化")},
    {"exposure_id": "sz_300271_produce_software_development_service", "company_id": "sz_300271", "node_id": "software_development_service", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:软件开发")},
    {"exposure_id": "sz_300271_provide_service_system_integration", "company_id": "sz_300271", "node_id": "system_integration", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:信息系统集成服务")},
    {"exposure_id": "sz_300271_provide_service_information_security_service", "company_id": "sz_300271", "node_id": "information_security_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:网络与信息安全软件开发")},
    {"exposure_id": "sz_300271_provide_service_artificial_intelligence", "company_id": "sz_300271", "node_id": "artificial_intelligence", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:人工智能应用软件开发")},
    {"exposure_id": "sh_601699_operate_coal_mining", "company_id": "sh_601699", "node_id": "coal_mining", "activity_type": "operate", "weight": 0.35, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:原煤开采")},
    {"exposure_id": "sh_601699_operate_coal_washing", "company_id": "sh_601699", "node_id": "coal_washing", "activity_type": "operate", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:煤炭洗选")},
    {"exposure_id": "sh_601699_produce_coal", "company_id": "sh_601699", "node_id": "coal", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:煤炭销售")},
    {"exposure_id": "sh_601699_operate_coking", "company_id": "sh_601699", "node_id": "coking", "activity_type": "operate", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:煤焦冶炼")},
    {"exposure_id": "sh_601699_produce_coalbed_methane", "company_id": "sh_601699", "node_id": "coalbed_methane", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:煤层气开发")},
    {"exposure_id": "sh_601699_provide_service_technical_service", "company_id": "sh_601699", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术服务")},
    {"exposure_id": "sz_002069_operate_marine_aquaculture", "company_id": "sz_002069", "node_id": "marine_aquaculture", "activity_type": "operate", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:海洋水产")},
    {"exposure_id": "sz_002069_operate_marine_fishery", "company_id": "sz_002069", "node_id": "marine_fishery", "activity_type": "operate", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:渔业捕捞")},
    {"exposure_id": "sz_002069_produce_aquatic_product", "company_id": "sz_002069", "node_id": "aquatic_product", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:水产养殖")},
    {"exposure_id": "sz_002069_provide_service_food_processing", "company_id": "sz_002069", "node_id": "food_processing", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:食品加工")},
    {"exposure_id": "sz_002069_provide_service_technical_service", "company_id": "sz_002069", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术服务")},
    {"exposure_id": "sz_002279_produce_management_software", "company_id": "sz_002279", "node_id": "management_software", "activity_type": "produce", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:管理软件")},
    {"exposure_id": "sz_002279_provide_service_digital_media", "company_id": "sz_002279", "node_id": "digital_media", "activity_type": "provide_service", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:数字传播")},
    {"exposure_id": "sz_002279_produce_software_development_service", "company_id": "sz_002279", "node_id": "software_development_service", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:软件开发")},
    {"exposure_id": "sz_002279_provide_service_e_government_software", "company_id": "sz_002279", "node_id": "e_government_software", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:电子政务")},
    {"exposure_id": "sz_002279_provide_service_system_integration", "company_id": "sz_002279", "node_id": "system_integration", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:信息系统集成服务")},
    {"exposure_id": "sz_002072_provide_service_internet_bandwidth_optimization", "company_id": "sz_002072", "node_id": "internet_bandwidth_optimization", "activity_type": "provide_service", "weight": 0.35, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:互联网出口带宽优化服务")},
    {"exposure_id": "sz_002072_provide_service_internet_application_acceleration", "company_id": "sz_002072", "node_id": "internet_application_acceleration", "activity_type": "provide_service", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:互联网应用加速服务")},
    {"exposure_id": "sz_002072_provide_service_supply_chain_management", "company_id": "sz_002072", "node_id": "supply_chain_management", "activity_type": "provide_service", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:供应链管理")},
    {"exposure_id": "sz_002072_produce_metal_ore", "company_id": "sz_002072", "node_id": "metal_ore", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:金属矿石加工销售")},
    {"exposure_id": "sz_002072_provide_service_technical_service", "company_id": "sz_002072", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术服务")},
    {"exposure_id": "sh_601588_provide_service_real_estate_development", "company_id": "sh_601588", "node_id": "real_estate_development", "activity_type": "provide_service", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:发展物业")},
    {"exposure_id": "sh_601588_provide_service_property_management", "company_id": "sh_601588", "node_id": "property_management", "activity_type": "provide_service", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:物业管理")},
    {"exposure_id": "sh_601588_provide_service_hotel_operation", "company_id": "sh_601588", "node_id": "hotel_operation", "activity_type": "provide_service", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:酒店")},
    {"exposure_id": "sh_601588_provide_service_exhibition_service", "company_id": "sh_601588", "node_id": "exhibition_service", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:承办展览展示")},
    {"exposure_id": "sh_601588_provide_service_construction_service", "company_id": "sh_601588", "node_id": "construction_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:房地产开发建设")},
    {"exposure_id": "sh_601588_provide_service_catering_service", "company_id": "sh_601588", "node_id": "catering_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:餐饮服务")},
]

write_batch(121, NODES_121, EDGES_121, COMPANIES_121, EXPOSURES_121)

# ============================================================
# BATCH 122
# ============================================================
NODES_122 = [
    {"node_id": "tire_manufacturing_equipment", "canonical_name_zh": "轮胎制造设备", "canonical_name_en": "tire manufacturing equipment", "entity_type": "device", "aliases": [], "definition": "用于轮胎生产过程中各工序的专用机械设备", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("软控股份主营业务")},
    {"node_id": "rubber_mixing_equipment", "canonical_name_zh": "橡胶混炼设备", "canonical_name_en": "rubber mixing equipment", "entity_type": "device", "aliases": [], "definition": "用于橡胶配方混炼的机械设备", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("软控股份主营业务")},
    {"node_id": "tire_curing_equipment", "canonical_name_zh": "轮胎硫化设备", "canonical_name_en": "tire curing equipment", "entity_type": "device", "aliases": [], "definition": "用于轮胎硫化成型的机械设备", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("软控股份主营业务")},
    {"node_id": "tire_forming_equipment", "canonical_name_zh": "轮胎成型设备", "canonical_name_en": "tire forming equipment", "entity_type": "device", "aliases": [], "definition": "用于轮胎胎坯成型的机械设备", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("软控股份主营业务")},
    {"node_id": "bulk_cargo_handling", "canonical_name_zh": "散杂货装卸", "canonical_name_en": "bulk cargo handling", "entity_type": "service", "aliases": [], "definition": "对散装货物和杂货进行装卸、堆存和中转的作业", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("日照港主营业务")},
    {"node_id": "power_battery", "canonical_name_zh": "动力电池", "canonical_name_en": "power battery", "entity_type": "component", "aliases": [], "definition": "为电动车辆、储能系统等提供动力的电池", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("国轩高科经营范围")},
    {"node_id": "energy_storage_system", "canonical_name_zh": "储能系统", "canonical_name_en": "energy storage system", "entity_type": "system", "aliases": [], "definition": "用于存储电能并在需要时释放的系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("国轩高科经营范围")},
    {"node_id": "charging_pile", "canonical_name_zh": "充电桩", "canonical_name_en": "charging pile", "entity_type": "device", "aliases": [], "definition": "为电动汽车提供电能补给的设备", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("国轩高科经营范围")},
    {"node_id": "switchgear", "canonical_name_zh": "开关柜", "canonical_name_en": "switchgear", "entity_type": "device", "aliases": [], "definition": "用于电力系统中接通、断开和保护电路的开关设备组合", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("国轩高科主营业务")},
    {"node_id": "gis_equipment", "canonical_name_zh": "气体绝缘开关设备", "canonical_name_en": "gas insulated switchgear", "entity_type": "device", "aliases": ["GIS"], "definition": "采用SF6等气体作为绝缘介质的金属封闭开关设备", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("国轩高科主营业务")},
    {"node_id": "special_steel", "canonical_name_zh": "特种钢", "canonical_name_en": "special steel", "entity_type": "material", "aliases": [], "definition": "具有特殊化学成分、组织性能或用途的合金钢", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("沙钢股份主营业务")},
    {"node_id": "automotive_steel", "canonical_name_zh": "汽车用钢", "canonical_name_en": "automotive steel", "entity_type": "material", "aliases": [], "definition": "用于汽车制造的各类特种钢材", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("沙钢股份主营业务")},
    {"node_id": "rail_steel", "canonical_name_zh": "轨道交通用钢", "canonical_name_en": "rail steel", "entity_type": "material", "aliases": [], "definition": "用于轨道交通车辆制造的特种钢材", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("沙钢股份主营业务")},
    {"node_id": "ship_steel", "canonical_name_zh": "船用钢", "canonical_name_en": "ship steel", "entity_type": "material", "aliases": [], "definition": "用于船舶制造的特种钢材", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("沙钢股份主营业务")},
    {"node_id": "energy_saving_lamp", "canonical_name_zh": "节能灯", "canonical_name_en": "energy saving lamp", "entity_type": "device", "aliases": [], "definition": "发光效率高于传统白炽灯的照明灯具", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("星光股份主营业务")},
    {"node_id": "hid_lamp", "canonical_name_zh": "氙气金卤灯", "canonical_name_en": "HID lamp", "entity_type": "device", "aliases": ["xenon metal halide lamp"], "definition": "利用高强度气体放电原理发光的照明灯具", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("星光股份主营业务")},
    {"node_id": "uv_lamp", "canonical_name_zh": "紫外线杀菌灯", "canonical_name_en": "UV lamp", "entity_type": "device", "aliases": [], "definition": "利用紫外线进行杀菌消毒的专用灯具", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("星光股份主营业务")},
    {"node_id": "electronic_ballast", "canonical_name_zh": "电子镇流器", "canonical_name_en": "electronic ballast", "entity_type": "component", "aliases": [], "definition": "用于气体放电灯的电子控制装置", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("星光股份主营业务")},
    {"node_id": "semiconductor_lighting", "canonical_name_zh": "半导体照明", "canonical_name_en": "semiconductor lighting", "entity_type": "device", "aliases": ["LED lighting"], "definition": "利用发光二极管作为光源的照明技术", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("星光股份经营范围")},
    {"node_id": "corporate_banking", "canonical_name_zh": "公司银行业务", "canonical_name_en": "corporate banking", "entity_type": "service", "aliases": [], "definition": "银行向企业客户提供的各类金融服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("工商银行主营业务")},
    {"node_id": "personal_banking", "canonical_name_zh": "个人银行业务", "canonical_name_en": "personal banking", "entity_type": "service", "aliases": [], "definition": "银行向个人客户提供的各类金融服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("工商银行主营业务")},
    {"node_id": "treasury_operations", "canonical_name_zh": "资金业务", "canonical_name_en": "treasury operations", "entity_type": "service", "aliases": [], "definition": "银行进行的资金运作和投资管理业务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("工商银行主营业务")},
    {"node_id": "diode", "canonical_name_zh": "二极管", "canonical_name_en": "diode", "entity_type": "component", "aliases": [], "definition": "具有单向导电性的半导体器件", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("苏州固锝主营业务")},
    {"node_id": "bridge_rectifier", "canonical_name_zh": "桥堆", "canonical_name_en": "bridge rectifier", "entity_type": "component", "aliases": [], "definition": "由四个二极管组成的桥式整流电路器件", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("苏州固锝主营业务")},
    {"node_id": "smd_device", "canonical_name_zh": "表面贴装器件", "canonical_name_en": "surface mount device", "entity_type": "component", "aliases": ["SMD"], "definition": "可直接贴装到印刷电路板表面的电子元器件", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("苏州固锝主营业务")},
    {"node_id": "integrated_circuit_packaging", "canonical_name_zh": "集成电路封装", "canonical_name_en": "integrated circuit packaging", "entity_type": "service", "aliases": [], "definition": "将集成电路芯片封装成可用器件的制造工艺", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("苏州固锝经营范围")},
    {"node_id": "mechanical_paper", "canonical_name_zh": "机制纸", "canonical_name_en": "mechanical paper", "entity_type": "material", "aliases": [], "definition": "通过造纸机生产的各类纸张", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("太阳纸业主营业务")},
    {"node_id": "coated_paperboard", "canonical_name_zh": "涂布纸板", "canonical_name_en": "coated paperboard", "entity_type": "material", "aliases": [], "definition": "表面涂有涂料层的包装纸板", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("太阳纸业主营业务")},
    {"node_id": "cultural_paper", "canonical_name_zh": "文化用纸", "canonical_name_en": "cultural paper", "entity_type": "material", "aliases": [], "definition": "用于书写、印刷等文化用途的纸张", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("太阳纸业主营业务")},
    {"node_id": "pulp", "canonical_name_zh": "纸浆", "canonical_name_en": "pulp", "entity_type": "material", "aliases": [], "definition": "造纸的原料，由植物纤维经化学或机械方法处理制成", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("太阳纸业经营范围")},
    {"node_id": "high_tech_park", "canonical_name_zh": "高科技园区", "canonical_name_en": "high tech park", "entity_type": "infrastructure", "aliases": [], "definition": "以高新技术产业为主导的产业园区", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("大港股份主营业务")},
    {"node_id": "park_service", "canonical_name_zh": "园区服务", "canonical_name_en": "park service", "entity_type": "service", "aliases": [], "definition": "为产业园区提供的物业管理、企业服务等综合性服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("大港股份主营业务")},
    {"node_id": "container_handling", "canonical_name_zh": "集装箱装卸", "canonical_name_en": "container handling", "entity_type": "service", "aliases": [], "definition": "对集装箱进行装卸、堆存和转运的作业", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("上港集团主营业务")},
    {"node_id": "port_logistics", "canonical_name_zh": "港口物流", "canonical_name_en": "port logistics", "entity_type": "service", "aliases": [], "definition": "依托港口开展的仓储、运输、配送等物流服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("上港集团主营业务")},
]

EDGES_122 = [
    {"edge_id": "rubber_mixing_equipment_tire_manufacturing_equipment", "from_node": "rubber_mixing_equipment", "to_node": "tire_manufacturing_equipment", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "橡胶混炼设备是轮胎制造设备的一部分", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "tire_curing_equipment_tire_manufacturing_equipment", "from_node": "tire_curing_equipment", "to_node": "tire_manufacturing_equipment", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "轮胎硫化设备是轮胎制造设备的一部分", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "tire_forming_equipment_tire_manufacturing_equipment", "from_node": "tire_forming_equipment", "to_node": "tire_manufacturing_equipment", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "轮胎成型设备是轮胎制造设备的一部分", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "bulk_cargo_handling_port", "from_node": "bulk_cargo_handling", "to_node": "port", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "散杂货装卸是港口的核心业务", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "power_battery_energy_storage_system", "from_node": "power_battery", "to_node": "energy_storage_system", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "动力电池是储能系统的组成部分", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "charging_pile_energy_storage_system", "from_node": "charging_pile", "to_node": "energy_storage_system", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "充电桩是储能系统的配套设备", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "switchgear_power_generation_equipment", "from_node": "switchgear", "to_node": "power_generation_equipment", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "开关柜是发电设备的配电组件", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "gis_equipment_switchgear", "from_node": "gis_equipment", "to_node": "switchgear", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "GIS是开关柜的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "automotive_steel_special_steel", "from_node": "automotive_steel", "to_node": "special_steel", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "汽车用钢是特种钢的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "rail_steel_special_steel", "from_node": "rail_steel", "to_node": "special_steel", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "轨道交通用钢是特种钢的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "ship_steel_special_steel", "from_node": "ship_steel", "to_node": "special_steel", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "船用钢是特种钢的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "energy_saving_lamp_lighting_equipment", "from_node": "energy_saving_lamp", "to_node": "lighting_equipment", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "节能灯是照明设备的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "hid_lamp_lighting_equipment", "from_node": "hid_lamp", "to_node": "lighting_equipment", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "氙气金卤灯是照明设备的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "uv_lamp_lighting_equipment", "from_node": "uv_lamp", "to_node": "lighting_equipment", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "紫外线杀菌灯是照明设备的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "electronic_ballast_lighting_equipment", "from_node": "electronic_ballast", "to_node": "lighting_equipment", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "电子镇流器是照明设备的配套组件", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "semiconductor_lighting_lighting_equipment", "from_node": "semiconductor_lighting", "to_node": "lighting_equipment", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "半导体照明是照明设备的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "corporate_banking_banking_service", "from_node": "corporate_banking", "to_node": "banking_service", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "公司银行业务是银行服务的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "personal_banking_banking_service", "from_node": "personal_banking", "to_node": "banking_service", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "个人银行业务是银行服务的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "treasury_operations_banking_service", "from_node": "treasury_operations", "to_node": "banking_service", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "资金业务是银行服务的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "diode_electronic_component", "from_node": "diode", "to_node": "electronic_component", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "二极管是电子元器件的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "bridge_rectifier_electronic_component", "from_node": "bridge_rectifier", "to_node": "electronic_component", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "桥堆是电子元器件的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "smd_device_electronic_component", "from_node": "smd_device", "to_node": "electronic_component", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "表面贴装器件是电子元器件的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "integrated_circuit_packaging_integrated_circuit", "from_node": "integrated_circuit_packaging", "to_node": "integrated_circuit", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "集成电路封装服务于集成电路生产", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "pulp_mechanical_paper", "from_node": "pulp", "to_node": "mechanical_paper", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "纸浆是机制纸的原料", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "coated_paperboard_pulp", "from_node": "coated_paperboard", "to_node": "pulp", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "涂布纸板以纸浆为原料", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "cultural_paper_pulp", "from_node": "cultural_paper", "to_node": "pulp", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "文化用纸以纸浆为原料", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "park_service_high_tech_park", "from_node": "park_service", "to_node": "high_tech_park", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "园区服务依托高科技园区开展", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "container_handling_port", "from_node": "container_handling", "to_node": "port", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "集装箱装卸是港口的核心业务", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "port_logistics_port", "from_node": "port_logistics", "to_node": "port", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "港口物流依托港口开展", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
]

COMPANIES_122 = [
    {"company_id": "sz_002073", "name_zh": "软控股份", "name_en": "MESNAC Co., Ltd.", "country": "CN", "province": "山东", "city": "青岛市", "stock_codes": ["002073.SZ"], "description": "轮胎橡胶生产中关键设备的系统集成", "founded_year": 2000, "employee_count": 4901},
    {"company_id": "sh_600017", "name_zh": "日照港", "name_en": "Rizhao Port Co., Ltd.", "country": "CN", "province": "山东", "city": "日照市", "stock_codes": ["600017.SH"], "description": "煤炭、矿石、水泥等散杂货的装卸、堆存中转服务", "founded_year": 2002, "employee_count": 5855},
    {"company_id": "sz_002074", "name_zh": "国轩高科", "name_en": "Gotion High-tech Co., Ltd.", "country": "CN", "province": "安徽", "city": "合肥市", "stock_codes": ["002074.SZ"], "description": "动力电池、储能、充电桩及输配电设备", "founded_year": 1995, "employee_count": 25575},
    {"company_id": "sz_002075", "name_zh": "沙钢股份", "name_en": "Jiangsu Shagang Co., Ltd.", "country": "CN", "province": "江苏", "city": "苏州市", "stock_codes": ["002075.SZ"], "description": "汽车用钢、机械工程用钢、轨道交通用钢等特种钢", "founded_year": 1999, "employee_count": 4836},
    {"company_id": "sz_002076", "name_zh": "星光股份", "name_en": "Guangdong Starlight Development Co., Ltd.", "country": "CN", "province": "广东", "city": "佛山市", "stock_codes": ["002076.SZ"], "description": "节能灯、氙气金卤灯、紫外线杀菌灯及电子镇流器", "founded_year": 1992, "employee_count": 470},
    {"company_id": "sh_601398", "name_zh": "工商银行", "name_en": "Industrial and Commercial Bank of China Limited", "country": "CN", "province": "北京", "city": "北京市", "stock_codes": ["601398.SH"], "description": "公司银行业务、个人银行业务、资金业务", "founded_year": 1985, "employee_count": 409758},
    {"company_id": "sz_002079", "name_zh": "苏州固锝", "name_en": "Suzhou Good-Ark Electronics Co., Ltd.", "country": "CN", "province": "江苏", "city": "苏州市", "stock_codes": ["002079.SZ"], "description": "二极管、桥堆、表面贴装器件及集成电路封装", "founded_year": 1990, "employee_count": 2185},
    {"company_id": "sz_002078", "name_zh": "太阳纸业", "name_en": "Shandong Sun Paper Co., Ltd.", "country": "CN", "province": "山东", "city": "济宁市", "stock_codes": ["002078.SZ"], "description": "机制纸、纸板的生产和销售", "founded_year": 2000, "employee_count": 16619},
    {"company_id": "sz_002077", "name_zh": "大港股份", "name_en": "Jiangsu Dagang Co., Ltd.", "country": "CN", "province": "江苏", "city": "镇江市", "stock_codes": ["002077.SZ"], "description": "房地产、高科技、园区服务", "founded_year": 2000, "employee_count": 432},
    {"company_id": "sh_600018", "name_zh": "上港集团", "name_en": "Shanghai International Port (Group) Co., Ltd.", "country": "CN", "province": "上海", "city": "上海市", "stock_codes": ["600018.SH"], "description": "集装箱、散杂货、港口服务和港口物流", "founded_year": 1988, "employee_count": 13046},
]

EXPOSURES_122 = [
    {"exposure_id": "sz_002073_produce_tire_manufacturing_equipment", "company_id": "sz_002073", "node_id": "tire_manufacturing_equipment", "activity_type": "produce", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:轮胎橡胶生产设备")},
    {"exposure_id": "sz_002073_produce_rubber_mixing_equipment", "company_id": "sz_002073", "node_id": "rubber_mixing_equipment", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:炼胶设备")},
    {"exposure_id": "sz_002073_produce_tire_curing_equipment", "company_id": "sz_002073", "node_id": "tire_curing_equipment", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:硫化设备")},
    {"exposure_id": "sz_002073_produce_tire_forming_equipment", "company_id": "sz_002073", "node_id": "tire_forming_equipment", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:成型设备")},
    {"exposure_id": "sz_002073_provide_service_technical_service", "company_id": "sz_002073", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术服务")},
    {"exposure_id": "sh_600017_operate_bulk_cargo_handling", "company_id": "sh_600017", "node_id": "bulk_cargo_handling", "activity_type": "operate", "weight": 0.40, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:散杂货装卸")},
    {"exposure_id": "sh_600017_operate_port", "company_id": "sh_600017", "node_id": "port", "activity_type": "operate", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:港口经营")},
    {"exposure_id": "sh_600017_provide_service_technical_service", "company_id": "sh_600017", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:信息系统运行维护")},
    {"exposure_id": "sh_600017_provide_service_construction_engineering", "company_id": "sh_600017", "node_id": "construction_engineering", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:各类工程建设")},
    {"exposure_id": "sz_002074_produce_power_battery", "company_id": "sz_002074", "node_id": "power_battery", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:电池制造")},
    {"exposure_id": "sz_002074_produce_energy_storage_system", "company_id": "sz_002074", "node_id": "energy_storage_system", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:储能技术服务")},
    {"exposure_id": "sz_002074_produce_charging_pile", "company_id": "sz_002074", "node_id": "charging_pile", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:充电桩销售")},
    {"exposure_id": "sz_002074_produce_switchgear", "company_id": "sz_002074", "node_id": "switchgear", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:开关柜")},
    {"exposure_id": "sz_002074_produce_gis_equipment", "company_id": "sz_002074", "node_id": "gis_equipment", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:GIS组合电器")},
    {"exposure_id": "sz_002074_provide_service_technical_service", "company_id": "sz_002074", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术服务")},
    {"exposure_id": "sz_002074_produce_photovoltaic_equipment", "company_id": "sz_002074", "node_id": "photovoltaic_equipment", "activity_type": "produce", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:光伏设备")},
    {"exposure_id": "sz_002075_produce_special_steel", "company_id": "sz_002075", "node_id": "special_steel", "activity_type": "produce", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:特种钢")},
    {"exposure_id": "sz_002075_produce_automotive_steel", "company_id": "sz_002075", "node_id": "automotive_steel", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:汽车用钢")},
    {"exposure_id": "sz_002075_produce_rail_steel", "company_id": "sz_002075", "node_id": "rail_steel", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:轨道交通用钢")},
    {"exposure_id": "sz_002075_produce_ship_steel", "company_id": "sz_002075", "node_id": "ship_steel", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:船用锚链钢")},
    {"exposure_id": "sz_002075_produce_steel_bar", "company_id": "sz_002075", "node_id": "steel_bar", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:钢材生产销售")},
    {"exposure_id": "sz_002075_provide_service_technical_service", "company_id": "sz_002075", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术服务")},
    {"exposure_id": "sz_002076_produce_energy_saving_lamp", "company_id": "sz_002076", "node_id": "energy_saving_lamp", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:节能灯")},
    {"exposure_id": "sz_002076_produce_hid_lamp", "company_id": "sz_002076", "node_id": "hid_lamp", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:氙气金卤灯")},
    {"exposure_id": "sz_002076_produce_uv_lamp", "company_id": "sz_002076", "node_id": "uv_lamp", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:紫外线杀菌灯")},
    {"exposure_id": "sz_002076_produce_electronic_ballast", "company_id": "sz_002076", "node_id": "electronic_ballast", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:电子镇流器")},
    {"exposure_id": "sz_002076_produce_semiconductor_lighting", "company_id": "sz_002076", "node_id": "semiconductor_lighting", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:半导体照明器件")},
    {"exposure_id": "sz_002076_produce_led_display", "company_id": "sz_002076", "node_id": "led_display", "activity_type": "produce", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:LED")},
    {"exposure_id": "sh_601398_provide_service_corporate_banking", "company_id": "sh_601398", "node_id": "corporate_banking", "activity_type": "provide_service", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:公司银行业务")},
    {"exposure_id": "sh_601398_provide_service_personal_banking", "company_id": "sh_601398", "node_id": "personal_banking", "activity_type": "provide_service", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:个人银行业务")},
    {"exposure_id": "sh_601398_provide_service_treasury_operations", "company_id": "sh_601398", "node_id": "treasury_operations", "activity_type": "provide_service", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:资金业务")},
    {"exposure_id": "sh_601398_provide_service_banking_service", "company_id": "sh_601398", "node_id": "banking_service", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:存贷款结算")},
    {"exposure_id": "sh_601398_produce_financial_bond", "company_id": "sh_601398", "node_id": "financial_bond", "activity_type": "produce", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:发行金融债券")},
    {"exposure_id": "sh_601398_provide_service_foreign_exchange", "company_id": "sh_601398", "node_id": "foreign_exchange", "activity_type": "provide_service", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:外汇业务")},
    {"exposure_id": "sz_002079_produce_diode", "company_id": "sz_002079", "node_id": "diode", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:二极管")},
    {"exposure_id": "sz_002079_produce_bridge_rectifier", "company_id": "sz_002079", "node_id": "bridge_rectifier", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:桥堆")},
    {"exposure_id": "sz_002079_produce_smd_device", "company_id": "sz_002079", "node_id": "smd_device", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:表面贴装器件")},
    {"exposure_id": "sz_002079_provide_service_integrated_circuit_packaging", "company_id": "sz_002079", "node_id": "integrated_circuit_packaging", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:集成电路封装")},
    {"exposure_id": "sz_002079_produce_electronic_component", "company_id": "sz_002079", "node_id": "electronic_component", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:电子元器件")},
    {"exposure_id": "sz_002079_provide_service_technical_service", "company_id": "sz_002079", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术服务")},
    {"exposure_id": "sz_002078_produce_mechanical_paper", "company_id": "sz_002078", "node_id": "mechanical_paper", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:机制纸")},
    {"exposure_id": "sz_002078_produce_coated_paperboard", "company_id": "sz_002078", "node_id": "coated_paperboard", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:涂布纸板")},
    {"exposure_id": "sz_002078_produce_cultural_paper", "company_id": "sz_002078", "node_id": "cultural_paper", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:文化用纸")},
    {"exposure_id": "sz_002078_produce_pulp", "company_id": "sz_002078", "node_id": "pulp", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:纸浆制造")},
    {"exposure_id": "sz_002078_provide_service_technical_service", "company_id": "sz_002078", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术服务")},
    {"exposure_id": "sz_002078_produce_new_material", "company_id": "sz_002078", "node_id": "new_material", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:新材料技术研发")},
    {"exposure_id": "sz_002077_provide_service_real_estate_development", "company_id": "sz_002077", "node_id": "real_estate_development", "activity_type": "provide_service", "weight": 0.35, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:房地产")},
    {"exposure_id": "sz_002077_provide_service_high_tech_park", "company_id": "sz_002077", "node_id": "high_tech_park", "activity_type": "provide_service", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:高科技")},
    {"exposure_id": "sz_002077_provide_service_park_service", "company_id": "sz_002077", "node_id": "park_service", "activity_type": "provide_service", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:园区服务")},
    {"exposure_id": "sz_002077_provide_service_property_management", "company_id": "sz_002077", "node_id": "property_management", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:物业管理")},
    {"exposure_id": "sh_600018_operate_container_handling", "company_id": "sh_600018", "node_id": "container_handling", "activity_type": "operate", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:集装箱业务")},
    {"exposure_id": "sh_600018_operate_bulk_cargo_handling", "company_id": "sh_600018", "node_id": "bulk_cargo_handling", "activity_type": "operate", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:散杂货业务")},
    {"exposure_id": "sh_600018_provide_service_port_logistics", "company_id": "sh_600018", "node_id": "port_logistics", "activity_type": "provide_service", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:港口物流")},
    {"exposure_id": "sh_600018_provide_service_port", "company_id": "sh_600018", "node_id": "port", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:港口经营")},
    {"exposure_id": "sh_600018_provide_service_technical_service", "company_id": "sh_600018", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:港口技术服务")},
]

write_batch(122, NODES_122, EDGES_122, COMPANIES_122, EXPOSURES_122)
print("Batch 121-122 generated.")
