#!/usr/bin/env python3
"""Batch 027 Submission Script (000758-000778)"""
import json, requests
BASE_URL = "http://localhost:8000/api/v1"
submit_graph = lambda b: requests.post(f"{BASE_URL}/batches", json=b)
submit_business = lambda b: requests.post(f"{BASE_URL}/business-batches", json=b)

nodes = [
    {"node_id":"non_ferrous_metal_engineering","canonical_name_zh":"有色金属工程","canonical_name_en":"Non-ferrous Metal Engineering","aliases":["有色工程设计","金属工程承包"],"definition":"围绕有色金属矿产资源开展的勘察设计、工程咨询、施工总承包及项目管理服务，涵盖采矿、选矿、冶炼及深加工全产业链。","entity_type":"service","evidence":[{"source_title":"中色股份 主营业务","quote":"主营业务为有色金属资源开发和国际有色工程的设计咨询和总承包"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"automotive_surface_plate","canonical_name_zh":"汽车表面板","canonical_name_en":"Automotive Surface Plate","aliases":["汽车板","汽车用钢"],"definition":"专用于汽车车身外板及结构件的高品质冷轧钢板，要求具备优良的表面质量、成型性能和焊接性能，是汽车轻量化的关键材料。","entity_type":"material","evidence":[{"source_title":"本钢板材 主营业务","quote":"主要产品:汽车表面板,家电板,石油管线钢,集装箱板,船板等钢材"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"home_appliance_steel","canonical_name_zh":"家电板","canonical_name_en":"Home Appliance Steel","aliases":["家电用钢","白色家电钢板"],"definition":"用于制造冰箱、洗衣机、空调等家电外壳及内胆的冷轧钢板或覆膜钢板，要求表面光洁、耐腐蚀、易成型。","entity_type":"material","evidence":[{"source_title":"本钢板材 主营业务","quote":"主要产品:汽车表面板,家电板...等钢材"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"chromium_iron_alloy","canonical_name_zh":"铬铁合金","canonical_name_en":"Ferrochrome","aliases":["铬铁","高碳铬铁"],"definition":"以铬和铁为主要成分的合金，是冶炼不锈钢的重要合金添加剂，也是生产铬系特种钢的原料，由高碳铬铁、中碳铬铁和低碳铬铁组成。","entity_type":"material","evidence":[{"source_title":"西藏矿业 主营业务","quote":"主要产品:铬铁合金,铬铁矿"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"chromite","canonical_name_zh":"铬铁矿","canonical_name_en":"Chromite","aliases":["铬矿","铬矿石"],"definition":"以铬尖晶石为主要矿物的铁矿石，是生产铬铁合金和金属铬的唯一矿物原料，主要用于不锈钢冶炼和耐火材料制造。","entity_type":"material","evidence":[{"source_title":"西藏矿业 主营业务","quote":"主要产品:铬铁合金,铬铁矿"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"chinese_patent_medicine","canonical_name_zh":"中成药制剂","canonical_name_en":"Chinese Patent Medicine","aliases":["中成药","中药制剂"],"definition":"以中药材为原料，在中医药理论指导下，按规定的处方和工艺加工成一定剂型的现成药品，包括丸、散、膏、丹、片、胶囊等剂型。","entity_type":"material","evidence":[{"source_title":"通化金马 主营业务","quote":"主要产品:治糜灵栓,壮骨伸筋胶囊,清热通淋胶囊,脑心舒口服液"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"aluminum_profile","canonical_name_zh":"铝合金型材","canonical_name_en":"Aluminum Alloy Profile","aliases":["铝型材","工业铝型材"],"definition":"将铝锭或铝合金棒材通过挤压、拉伸等工艺制成的具有特定截面形状的条状材料，广泛应用于航空航天、建筑幕墙、轨道交通、汽车零部件等领域。","entity_type":"material","evidence":[{"source_title":"中航西飞 主营业务","quote":"主要产品:航空零部件,铝合金型材"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"ductile_iron_pipe","canonical_name_zh":"球墨铸铁管","canonical_name_en":"Ductile Iron Pipe","aliases":["球铁管","离心球墨管"],"definition":"以球墨铸铁为材质，采用离心铸造工艺制成的管材，兼具铸铁的耐腐蚀性和钢的强度韧性，广泛用于城市供水、排水、燃气输送管网。","entity_type":"component","evidence":[{"source_title":"新兴铸管 主营业务","quote":"主营业务:离心球墨铸铁管及配套管件...等"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"casting_product","canonical_name_zh":"铸造制品","canonical_name_en":"Casting Product","aliases":["铸件","铸造件"],"definition":"将熔融金属浇注入铸型中凝固成型的金属制品，包括砂型铸件、精密铸件、压铸件等，是机械制造的基础毛坯件。","entity_type":"component","evidence":[{"source_title":"新兴铸管 主营业务","quote":"主营业务:...铸造制品...等"}],"confidence":"HIGH","status":"ACTIVE"}
]

edges = [
    {"edge_id":"flow_chromite_to_chromium_alloy","from_node":"chromite","to_node":"chromium_iron_alloy","description":"铬铁矿经高炉或电炉冶炼制成铬铁合金。","edge_namespace":"industrial_flow","edge_type":"material_flow","evidence":[{"source_title":"西藏矿业 主营业务","quote":"主要产品:铬铁合金,铬铁矿"}],"confidence":"HIGH"},
    {"edge_id":"flow_chromium_alloy_to_stainless","from_node":"chromium_iron_alloy","to_node":"stainless_steel","description":"铬铁合金作为合金添加剂用于不锈钢冶炼。","edge_namespace":"industrial_flow","edge_type":"material_flow","evidence":[{"source_title":"西藏矿业 经营范围","quote":"金属矿石销售"}],"confidence":"HIGH"},
    {"edge_id":"flow_automotive_plate_to_car","from_node":"automotive_surface_plate","to_node":"passenger_car","description":"汽车表面板作为车身外板及结构件材料用于汽车制造。","edge_namespace":"industrial_flow","edge_type":"composition","evidence":[{"source_title":"本钢板材 主营业务","quote":"主要产品:汽车表面板...等钢材"}],"confidence":"HIGH"},
    {"edge_id":"flow_home_appliance_steel_to_appliance","from_node":"home_appliance_steel","to_node":"kitchen_appliance","description":"家电板用于制造冰箱、洗衣机等家电外壳及内胆。","edge_namespace":"industrial_flow","edge_type":"composition","evidence":[{"source_title":"本钢板材 主营业务","quote":"主要产品:...家电板...等钢材"}],"confidence":"HIGH"},
    {"edge_id":"flow_aluminum_profile_to_aircraft","from_node":"aluminum_profile","to_node":"aircraft","description":"铝合金型材作为结构材料用于航空器机身及部件制造。","edge_namespace":"industrial_flow","edge_type":"composition","evidence":[{"source_title":"中航西飞 主营业务","quote":"主要产品:航空零部件,铝合金型材"}],"confidence":"HIGH"},
    {"edge_id":"flow_ductile_iron_to_water_supply","from_node":"ductile_iron_pipe","to_node":"tap_water_supply","description":"球墨铸铁管作为输水管材用于城市自来水供应系统。","edge_namespace":"industrial_flow","edge_type":"service_flow","evidence":[{"source_title":"新兴铸管 经营范围","quote":"离心球墨铸铁管,灰铁排水管,新型复合管材及配套管件"}],"confidence":"HIGH"}
]

companies = [
    {"company_id":"cnmc","name_zh":"中国有色金属建设股份有限公司","aliases":["中色股份"],"stock_codes":["000758.SZ"],"description":"主营业务为有色金属资源开发和国际有色工程的设计咨询和总承包。","country":"CN","province":"北京","city":"北京市","founded_year":1983,"employee_count":4911,"company_type":"public","status":"ACTIVE"},
    {"company_id":"zhongbai_group","name_zh":"中百控股集团股份有限公司","aliases":["中百集团"],"stock_codes":["000759.SZ"],"description":"主要业务为商品零售与批发业务，涵盖超市、百货、物流等业态。","country":"CN","province":"湖北","city":"武汉市","founded_year":1990,"employee_count":14045,"company_type":"public","status":"ACTIVE"},
    {"company_id":"benxi_steel","name_zh":"本钢板材股份有限公司","aliases":["本钢板材"],"stock_codes":["000761.SZ"],"description":"主要产品包括汽车表面板、家电板、石油管线钢、集装箱板、船板等钢材，业务涵盖钢铁冶炼、压延加工、发电、煤化工等。","country":"CN","province":"辽宁","city":"本溪市","founded_year":1997,"employee_count":12155,"company_type":"public","status":"ACTIVE"},
    {"company_id":"tibet_mining","name_zh":"西藏矿业发展股份有限公司","aliases":["西藏矿业"],"stock_codes":["000762.SZ"],"description":"主要产品为铬铁合金和铬铁矿，是西藏自治区重要的矿产资源开发企业。","country":"CN","province":"西藏","city":"拉萨市","founded_year":1997,"employee_count":412,"company_type":"public","status":"ACTIVE"},
    {"company_id":"tonghua_jinma","name_zh":"通化金马药业集团股份有限公司","aliases":["通化金马"],"stock_codes":["000766.SZ"],"description":"主要产品包括治糜灵栓、壮骨伸筋胶囊、清热通淋胶囊、脑心舒口服液等中成药。","country":"CN","province":"吉林","city":"通化市","founded_year":1993,"employee_count":1532,"company_type":"public","status":"ACTIVE"},
    {"company_id":"jinkong_power","name_zh":"晋能控股山西电力股份有限公司","aliases":["晋控电力"],"stock_codes":["000767.SZ"],"description":"主要业务为电力商品、热力商品生产和销售，以及燃料、材料、电力高新技术的开发销售。","country":"CN","province":"山西","city":"太原市","founded_year":1993,"employee_count":7064,"company_type":"public","status":"ACTIVE"},
    {"company_id":"avic_xifei","name_zh":"中航西安飞机工业集团股份有限公司","aliases":["中航西飞"],"stock_codes":["000768.SZ"],"description":"主要产品包括航空零部件和铝合金型材，是中国大中型军民用飞机研制生产的重要基地。","country":"CN","province":"陕西","city":"西安市","founded_year":1997,"employee_count":24751,"company_type":"public","status":"ACTIVE"},
    {"company_id":"gf_securities","name_zh":"广发证券股份有限公司","aliases":["广发证券"],"stock_codes":["000776.SZ"],"description":"主营业务为证券经纪、证券投资咨询、证券承销与保荐、证券自营、证券资产管理等综合金融服务。","country":"CN","province":"广东","city":"广州市","founded_year":1994,"employee_count":13640,"company_type":"public","status":"ACTIVE"},
    {"company_id":"cnncc_valve","name_zh":"中核苏阀科技实业股份有限公司","aliases":["中核科技"],"stock_codes":["000777.SZ"],"description":"主营业务范围为工业和项目建设用的各类阀门设计、制造、销售，主要产品包括工业阀门和水道阀门。","country":"CN","province":"江苏","city":"苏州市","founded_year":1997,"employee_count":1027,"company_type":"public","status":"ACTIVE"},
    {"company_id":"xinxing_ductile","name_zh":"新兴铸管股份有限公司","aliases":["新兴铸管"],"stock_codes":["000778.SZ"],"description":"主要产品包括离心球墨铸铁管、新兴钢材、新兴铸造、新兴钢塑管、新兴格板、新兴特种钢管等，业务涵盖铸造制品、钢铁冶炼及压延加工。","country":"CN","province":"河北","city":"邯郸市","founded_year":1997,"employee_count":14115,"company_type":"public","status":"ACTIVE"}
]

exposures = [
    {"exposure_id":"exp_cnmc_copper","company_id":"cnmc","node_id":"copper","activity_type":"produce","role":"铜资源开发商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"中色股份 主营业务","quote":"主营业务为有色金属资源开发"}],"status":"ACTIVE"},
    {"exposure_id":"exp_cnmc_lead_zinc","company_id":"cnmc","node_id":"lead_zinc_metal","activity_type":"produce","role":"铅锌资源开发商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"中色股份 主营业务","quote":"有色金属资源开发"}],"status":"ACTIVE"},
    {"exposure_id":"exp_cnmc_engineering","company_id":"cnmc","node_id":"non_ferrous_metal_engineering","activity_type":"operate","role":"国际有色工程承包商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"中色股份 主营业务","quote":"国际有色工程的设计咨询和总承包"}],"status":"ACTIVE"},
    {"exposure_id":"exp_zb_retail","company_id":"zhongbai_group","node_id":"chain_retail_service","activity_type":"operate","role":"连锁零售服务商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"中百集团 主营业务","quote":"主要业务:商品零售与批发业务"}],"status":"ACTIVE"},
    {"exposure_id":"exp_zb_trade","company_id":"zhongbai_group","node_id":"trade_service","activity_type":"operate","role":"商品批发商","weight":0.6,"confidence":"HIGH","evidence":[{"source_title":"中百集团 主营业务","quote":"商品零售与批发业务"}],"status":"ACTIVE"},
    {"exposure_id":"exp_bx_steel_plate","company_id":"benxi_steel","node_id":"steel_plate","activity_type":"produce","role":"板材生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"本钢板材 主营业务","quote":"主要产品:汽车表面板,家电板,石油管线钢,集装箱板,船板等钢材"}],"status":"ACTIVE"},
    {"exposure_id":"exp_bx_auto_plate","company_id":"benxi_steel","node_id":"automotive_surface_plate","activity_type":"produce","role":"汽车表面板生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"本钢板材 主营业务","quote":"主要产品:汽车表面板...等钢材"}],"status":"ACTIVE"},
    {"exposure_id":"exp_bx_home_appliance","company_id":"benxi_steel","node_id":"home_appliance_steel","activity_type":"produce","role":"家电板生产商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"本钢板材 主营业务","quote":"主要产品:...家电板...等钢材"}],"status":"ACTIVE"},
    {"exposure_id":"exp_bx_steel_sheet","company_id":"benxi_steel","node_id":"steel_sheet","activity_type":"produce","role":"冷轧钢板生产商","weight":0.6,"confidence":"HIGH","evidence":[{"source_title":"本钢板材 主营业务","quote":"主要业务:钢铁冶炼,压延加工"}],"status":"ACTIVE"},
    {"exposure_id":"exp_tm_chromium_alloy","company_id":"tibet_mining","node_id":"chromium_iron_alloy","activity_type":"produce","role":"铬铁合金生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"西藏矿业 主营业务","quote":"主要产品:铬铁合金,铬铁矿"}],"status":"ACTIVE"},
    {"exposure_id":"exp_tm_chromite","company_id":"tibet_mining","node_id":"chromite","activity_type":"produce","role":"铬铁矿生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"西藏矿业 主营业务","quote":"主要产品:铬铁合金,铬铁矿"}],"status":"ACTIVE"},
    {"exposure_id":"exp_thj_tcm","company_id":"tonghua_jinma","node_id":"traditional_chinese_medicine","activity_type":"manufacture","role":"中成药制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"通化金马 主营业务","quote":"主要产品:治糜灵栓,壮骨伸筋胶囊..."}],"status":"ACTIVE"},
    {"exposure_id":"exp_thj_patent_med","company_id":"tonghua_jinma","node_id":"chinese_patent_medicine","activity_type":"manufacture","role":"中成药制剂生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"通化金马 主营业务","quote":"主要产品:治糜灵栓,壮骨伸筋胶囊,清热通淋胶囊,脑心舒口服液"}],"status":"ACTIVE"},
    {"exposure_id":"exp_jkp_power","company_id":"jinkong_power","node_id":"electricity_power","activity_type":"produce","role":"电力生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"晋控电力 主营业务","quote":"主要业务:电力商品,热力商品生产和销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_jkp_heating","company_id":"jinkong_power","node_id":"heating_supply","activity_type":"produce","role":"热力供应商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"晋控电力 主营业务","quote":"热力商品生产和销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_jkp_coal_power","company_id":"jinkong_power","node_id":"coal_power_generation","activity_type":"operate","role":"燃煤发电运营商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"晋控电力 经营范围","quote":"发电业务,输电业务,供(配)电业务"}],"status":"ACTIVE"},
    {"exposure_id":"exp_avic_aero_part","company_id":"avic_xifei","node_id":"aerospace_precision_part","activity_type":"manufacture","role":"航空零部件制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"中航西飞 主营业务","quote":"主要产品:航空零部件"}],"status":"ACTIVE"},
    {"exposure_id":"exp_avic_al_profile","company_id":"avic_xifei","node_id":"aluminum_profile","activity_type":"manufacture","role":"铝合金型材制造商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"中航西飞 主营业务","quote":"主要产品:...铝合金型材"}],"status":"ACTIVE"},
    {"exposure_id":"exp_avic_aircraft","company_id":"avic_xifei","node_id":"aircraft","activity_type":"manufacture","role":"航空器制造商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"中航西飞 经营范围","quote":"飞机,飞行器零部件...的设计,试验,生产"}],"status":"ACTIVE"},
    {"exposure_id":"exp_gf_brokerage","company_id":"gf_securities","node_id":"securities_brokerage","activity_type":"operate","role":"证券经纪服务商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"广发证券 主营业务","quote":"主营业务:证券经纪"}],"status":"ACTIVE"},
    {"exposure_id":"exp_gf_underwriting","company_id":"gf_securities","node_id":"securities_underwriting","activity_type":"operate","role":"证券承销保荐服务商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"广发证券 经营范围","quote":"证券承销与保荐"}],"status":"ACTIVE"},
    {"exposure_id":"exp_gf_asset_mgmt","company_id":"gf_securities","node_id":"asset_management_service","activity_type":"operate","role":"资产管理服务商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"广发证券 经营范围","quote":"证券资产管理"}],"status":"ACTIVE"},
    {"exposure_id":"exp_cnncc_valve","company_id":"cnncc_valve","node_id":"valve","activity_type":"manufacture","role":"工业阀门制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"中核科技 主营业务","quote":"主要产品:工业阀门,水道阀门"}],"status":"ACTIVE"},
    {"exposure_id":"exp_xx_ductile_pipe","company_id":"xinxing_ductile","node_id":"ductile_iron_pipe","activity_type":"manufacture","role":"球墨铸铁管制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"新兴铸管 主营业务","quote":"主营业务:离心球墨铸铁管及配套管件...等"}],"status":"ACTIVE"},
    {"exposure_id":"exp_xx_casting","company_id":"xinxing_ductile","node_id":"casting_product","activity_type":"manufacture","role":"铸造制品制造商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"新兴铸管 主营业务","quote":"主营业务:...铸造制品...等"}],"status":"ACTIVE"},
    {"exposure_id":"exp_xx_steel","company_id":"xinxing_ductile","node_id":"steel_plate","activity_type":"produce","role":"钢材生产商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"新兴铸管 主营业务","quote":"主营业务:...钢铁冶炼及压延加工...等"}],"status":"ACTIVE"}
]

if __name__ == "__main__":
    gb = {"batch_id":"batch_027_graph","task_description":"Batch 027: Industrial nodes and edges for 10 companies (000758-000778). Focus on non-ferrous engineering, specialty steel, chromium alloy, TCM, power, aerospace, valves, ductile iron pipes.","nodes_to_upsert":nodes,"edges_to_upsert":edges,"rejected_or_pending":[]}
    bb = {"batch_id":"batch_027_business","task_description":"Batch 027: Company registrations and exposures for 10 companies (000758-000778).","industries_to_upsert":[],"industry_node_mappings_to_upsert":[],"companies_to_upsert":companies,"company_node_exposures_to_upsert":exposures}
    r1 = submit_graph(gb); print(f"Graph: {r1.status_code}", r1.json())
    r2 = submit_business(bb); print(f"Business: {r2.status_code}", r2.json())
