#!/usr/bin/env python3
"""Batch 032 Submission Script (000833-000859)"""
import requests
BASE_URL = "http://localhost:8000/api/v1"
submit_graph = lambda b: requests.post(f"{BASE_URL}/batches", json=b)
submit_business = lambda b: requests.post(f"{BASE_URL}/business-batches", json=b)

nodes = [
    {"node_id":"white_sugar","canonical_name_zh":"白砂糖","canonical_name_en":"White Sugar","aliases":["白糖","蔗糖"],"definition":"以甘蔗或甜菜为原料，经压榨、提汁、清净、蒸发、结晶、分蜜等工艺制成的精制食用糖，是食品工业和日常生活中最重要的甜味剂之一。","entity_type":"material","evidence":[{"source_title":"粤桂股份 主营业务","quote":"主要业务为:机制糖(白砂糖,赤砂糖)的生产和销售"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"bagasse_pulp","canonical_name_zh":"蔗渣纸浆","canonical_name_en":"Bagasse Pulp","aliases":["甘蔗渣浆"],"definition":"以甘蔗榨糖后的副产物蔗渣为原料，经蒸煮、漂白等制浆工艺制成的纸浆，是造纸工业重要的非木纤维原料，主要用于生产文化用纸和生活用纸。","entity_type":"material","evidence":[{"source_title":"粤桂股份 主营业务","quote":"主要业务为:...纸浆和机制纸(文化纸,生活用纸)的生产和销售"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"pyrite","canonical_name_zh":"硫铁矿","canonical_name_en":"Pyrite","aliases":["黄铁矿"],"definition":"主要成分为二硫化铁（FeS₂）的硫化物矿物，是生产硫酸的主要原料，也可用于提取硫和制造硫磺，在化工、冶金和农业领域有广泛应用。","entity_type":"material","evidence":[{"source_title":"粤桂股份 主营业务","quote":"主要业务为:...硫铁矿的开采,加工,销售及硫酸...的生产和销售"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"machine_tool","canonical_name_zh":"机床","canonical_name_en":"Machine Tool","aliases":["工作母机","机床设备"],"definition":"制造机器的机器，用于对金属或其他材料进行切削、成型、磨削等加工，是装备制造业的核心基础设备，包括车床、铣床、磨床、钻床、加工中心等类型。","entity_type":"device","evidence":[{"source_title":"秦川机床 主营业务","quote":"主要产品为机床,塑料机械等"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"plastic_machinery","canonical_name_zh":"塑料机械","canonical_name_en":"Plastic Machinery","aliases":["塑机","塑料加工设备"],"definition":"用于塑料原料加工和成型的机械设备，包括注塑机、挤出机、吹塑机、压延机等，广泛应用于塑料制品、包装、建材、汽车配件等行业。","entity_type":"device","evidence":[{"source_title":"秦川机床 主营业务","quote":"主要产品为机床,塑料机械等"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"cable_tv_network","canonical_name_zh":"有线电视网","canonical_name_en":"Cable TV Network","aliases":["有线电视","广电网络"],"definition":"利用同轴电缆或光纤作为传输介质，向用户提供广播电视信号接入和传输服务的有线通信网络，是传统广播电视传输的主要基础设施。","entity_type":"infrastructure","evidence":[{"source_title":"国安股份 主营业务","quote":"主要业务:信息网络基础设施业务中的有线电视网,卫星通信网的投资建设"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"satellite_communication","canonical_name_zh":"卫星通信","canonical_name_en":"Satellite Communication","aliases":["卫星通讯","卫通"],"definition":"利用人造地球卫星作为中继站转发无线电波，实现两个或多个地球站之间通信的无线通信方式，具有覆盖范围广、不受地理条件限制等优点，广泛用于广播电视传输、远程教育、应急通信等领域。","entity_type":"infrastructure","evidence":[{"source_title":"国安股份 主营业务","quote":"主要业务:...卫星通信网的投资建设"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"almond_beverage","canonical_name_zh":"杏仁露","canonical_name_en":"Almond Beverage","aliases":["杏仁饮料"],"definition":"以杏仁为主要原料，经研磨、调配、杀菌等工艺制成的植物蛋白饮料，具有独特的杏仁香味和营养价值，是植物蛋白饮料的代表性产品之一。","entity_type":"material","evidence":[{"source_title":"承德露露 主营业务","quote":"主营业务是饮料的生产和销售,属饮料食品行业,主要产品是植物蛋白饮料——杏仁露"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"oil_drilling_tool","canonical_name_zh":"石油钻具","canonical_name_en":"Oil Drilling Tool","aliases":["钻头钻具","井下工具"],"definition":"用于油气井钻探作业的各类工具和器具，包括钻头、钻杆、钻铤、螺杆钻具、提速工具、完井工具等，是石油钻采装备的核心组成部分。","entity_type":"component","evidence":[{"source_title":"石化机械 主营业务","quote":"产品包含钻头钻具及井下工具,陆上钻采装备,固井压裂装备...等多个领域的产品组合"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"fracturing_equipment","canonical_name_zh":"压裂装备","canonical_name_en":"Fracturing Equipment","aliases":["压裂设备","油气压裂装备"],"definition":"用于油气井压裂增产作业的专用设备系统，包括压裂泵车、混砂车、仪表车等，通过高压将压裂液注入地层形成裂缝，提高油气井产量，是页岩气等非常规油气开发的关键装备。","entity_type":"device","evidence":[{"source_title":"石化机械 主营业务","quote":"产品包含...固井压裂装备...等多个领域的产品组合"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"ceramic_product","canonical_name_zh":"日用陶瓷","canonical_name_en":"Ceramic Product","aliases":["陶瓷制品","日用瓷器"],"definition":"以黏土、长石、石英等为原料，经成型、干燥、高温烧制而成的日常生活用器皿，包括餐具、茶具、卫生陶瓷、艺术陶瓷等，是传统轻工业的重要产品类别。","entity_type":"material","evidence":[{"source_title":"冀东装备 主营业务","quote":"主要产品:日用陶瓷,耐火材料,卫生陶瓷"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"refractory_material","canonical_name_zh":"耐火材料","canonical_name_en":"Refractory Material","aliases":["耐火砖","高温材料"],"definition":"能在高温环境下保持物理化学稳定性的无机非金属材料，主要成分为氧化铝、氧化硅、氧化镁等，广泛用于钢铁冶炼、水泥生产、玻璃制造、石化等高温工业窑炉的内衬。","entity_type":"material","evidence":[{"source_title":"冀东装备 主营业务","quote":"主要产品:日用陶瓷,耐火材料,卫生陶瓷"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"plastic_film","canonical_name_zh":"塑料薄膜","canonical_name_en":"Plastic Film","aliases":["塑胶薄膜","功能薄膜"],"definition":"以聚乙烯、聚丙烯、聚酯等高分子材料为原料，经挤出、吹塑、流延等工艺制成的厚度通常在0.25mm以下的薄片材料，广泛用于包装、农业、电子、建筑等领域。","entity_type":"material","evidence":[{"source_title":"国风新材 主营业务","quote":"主要产品:塑料薄膜,化工原料,碳酸钙超细粉,工程塑料"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"capacitor_film","canonical_name_zh":"电容器薄膜","canonical_name_en":"Capacitor Film","aliases":["电容膜","BOPP电容膜"],"definition":"专门用于制造薄膜电容器的双向拉伸聚丙烯（BOPP）或聚酯薄膜，具有优异的介电性能、耐温性能和机械强度，是电子电力设备中电容器的关键介质材料。","entity_type":"material","evidence":[{"source_title":"国风新材 经营范围","quote":"电容器用薄膜...电子信息用膜材料"}],"confidence":"HIGH","status":"ACTIVE"}
]

edges = [
    {"edge_id":"flow_pyrite_to_sulfuric_acid","from_node":"pyrite","to_node":"sulfuric_acid","description":"硫铁矿经焙烧制酸工艺生产硫酸。","edge_namespace":"industrial_flow","edge_type":"material_flow","evidence":[{"source_title":"粤桂股份 产业链","quote":"硫铁矿→硫酸"}],"confidence":"HIGH"},
    {"edge_id":"flow_bagasse_pulp_to_paper","from_node":"bagasse_pulp","to_node":"paper_product","description":"蔗渣纸浆用于生产文化用纸和生活用纸。","edge_namespace":"industrial_flow","edge_type":"material_flow","evidence":[{"source_title":"粤桂股份 产业链","quote":"纸浆和机制纸的生产和销售"}],"confidence":"HIGH"},
    {"edge_id":"flow_sugar_cane_to_white_sugar","from_node":"sugar_cane","to_node":"white_sugar","description":"甘蔗经压榨提汁制成白砂糖。","edge_namespace":"industrial_flow","edge_type":"material_flow","evidence":[{"source_title":"粤桂股份 产业链","quote":"机制糖(白砂糖,赤砂糖)的生产和销售"}],"confidence":"HIGH"},
    {"edge_id":"flow_cable_to_broadcast","from_node":"cable_tv_network","to_node":"broadcasting_equipment","description":"有线电视网络承载广播电视信号传输。","edge_namespace":"industrial_flow","edge_type":"service_flow","evidence":[{"source_title":"国安股份 业务关联","quote":"有线电视网的投资建设"}],"confidence":"HIGH"},
    {"edge_id":"flow_drilling_tool_to_oilfield","from_node":"oil_drilling_tool","to_node":"oilfield_service","description":"石油钻具是油气田服务的关键工具装备。","edge_namespace":"industrial_flow","edge_type":"composition","evidence":[{"source_title":"石化机械 产业链","quote":"钻头钻具及井下工具→陆上钻采装备"}],"confidence":"HIGH"}
]

companies = [
    {"company_id":"yuegui","name_zh":"广西粤桂广业控股股份有限公司","aliases":["粤桂股份"],"stock_codes":["000833.SZ"],"description":"主要业务为机制糖（白砂糖、赤砂糖）的生产和销售，纸浆和机制纸的生产和销售，硫铁矿的开采、加工、销售及硫酸、铁矿粉和磷肥的生产和销售。","country":"CN","province":"广西","city":"贵港市","founded_year":1994,"employee_count":3152,"company_type":"public","status":"ACTIVE"},
    {"company_id":"qinchuan_machine_tool","name_zh":"秦川机床工具集团股份公司","aliases":["秦川机床"],"stock_codes":["000837.SZ"],"description":"主要产品为机床、塑料机械等，是国内重要的精密数控机床研发制造基地。","country":"CN","province":"陕西","city":"宝鸡市","founded_year":1998,"employee_count":9203,"company_type":"public","status":"ACTIVE"},
    {"company_id":"caixin_dev","name_zh":"财信地产发展集团股份有限公司","aliases":["*ST发展"],"stock_codes":["000838.SZ"],"description":"主营业务为房地产开发和环保。","country":"CN","province":"重庆","city":"重庆市","founded_year":1996,"employee_count":188,"company_type":"public","status":"ACTIVE"},
    {"company_id":"citic_guoan","name_zh":"中信国安信息产业股份有限公司","aliases":["国安股份"],"stock_codes":["000839.SZ"],"description":"主要业务包括有线电视网、卫星通信网的投资建设，增值电信服务，网络系统集成，应用软件开发，以及房地产开发及物业管理等。","country":"CN","province":"北京","city":"北京市","founded_year":1997,"employee_count":10195,"company_type":"public","status":"ACTIVE"},
    {"company_id":"chengde_lulu","name_zh":"承德露露股份公司","aliases":["承德露露"],"stock_codes":["000848.SZ"],"description":"主营业务是饮料的生产和销售，属饮料食品行业，主要产品是植物蛋白饮料——杏仁露。","country":"CN","province":"河北","city":"承德市","founded_year":1997,"employee_count":1292,"company_type":"public","status":"ACTIVE"},
    {"company_id":"huamao_textile","name_zh":"安徽华茂纺织股份有限公司","aliases":["华茂股份"],"stock_codes":["000850.SZ"],"description":"主营业务范围包括棉、毛、麻、丝和人造纤维的纯、混纺纱线及其织物、针织品、服装、印染加工等，主要产品包括纱线系列产品、坯布面料系列产品和色织面料系列产品等。","country":"CN","province":"安徽","city":"安庆市","founded_year":1998,"employee_count":3822,"company_type":"public","status":"ACTIVE"},
    {"company_id":"sinopec_machinery","name_zh":"中石化石油机械股份有限公司","aliases":["石化机械"],"stock_codes":["000852.SZ"],"description":"主营业务为油气勘探到开采、储运装备，产品包含钻头钻具及井下工具、陆上钻采装备、固井压裂装备、海洋石油装备和油气储运设备等多个领域的产品组合。","country":"CN","province":"湖北","city":"武汉市","founded_year":1998,"employee_count":4745,"company_type":"public","status":"ACTIVE"},
    {"company_id":"jidd_equipment","name_zh":"唐山冀东装备工程股份有限公司","aliases":["冀东装备"],"stock_codes":["000856.SZ"],"description":"主要产品包括日用陶瓷、耐火材料、卫生陶瓷，同时从事机械设备制造和工程服务等业务。","country":"CN","province":"河北","city":"唐山市","founded_year":1998,"employee_count":1686,"company_type":"public","status":"ACTIVE"},
    {"company_id":"wuliangye","name_zh":"宜宾五粮液股份有限公司","aliases":["五粮液"],"stock_codes":["000858.SZ"],"description":"主要产品为五粮液系列酒，是中国高端白酒的代表性品牌之一。","country":"CN","province":"四川","city":"宜宾市","founded_year":1998,"employee_count":25132,"company_type":"public","status":"ACTIVE"},
    {"company_id":"guofeng_new_material","name_zh":"安徽国风新材料股份有限公司","aliases":["国风新材"],"stock_codes":["000859.SZ"],"description":"主要产品包括塑料薄膜、化工原料、碳酸钙超细粉、工程塑料，是国内重要的塑料薄膜和新材料生产企业。","country":"CN","province":"安徽","city":"合肥市","founded_year":1998,"employee_count":1698,"company_type":"public","status":"ACTIVE"}
]

exposures = [
    {"exposure_id":"exp_yg_white_sugar","company_id":"yuegui","node_id":"white_sugar","activity_type":"produce","role":"白砂糖生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"粤桂股份 主营业务","quote":"主要业务为:机制糖(白砂糖,赤砂糖)的生产和销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_yg_bagasse","company_id":"yuegui","node_id":"bagasse_pulp","activity_type":"produce","role":"蔗渣纸浆生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"粤桂股份 主营业务","quote":"主要业务为:...纸浆和机制纸(文化纸,生活用纸)的生产和销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_yg_pyrite","company_id":"yuegui","node_id":"pyrite","activity_type":"produce","role":"硫铁矿生产商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"粤桂股份 主营业务","quote":"主要业务为:...硫铁矿的开采,加工,销售..."}],"status":"ACTIVE"},
    {"exposure_id":"exp_yg_sulfuric","company_id":"yuegui","node_id":"sulfuric_acid","activity_type":"produce","role":"硫酸生产商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"粤桂股份 主营业务","quote":"主要业务为:...硫酸...的生产和销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_qc_machine_tool","company_id":"qinchuan_machine_tool","node_id":"machine_tool","activity_type":"manufacture","role":"机床制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"秦川机床 主营业务","quote":"主要产品为机床,塑料机械等"}],"status":"ACTIVE"},
    {"exposure_id":"exp_qc_plastic_mach","company_id":"qinchuan_machine_tool","node_id":"plastic_machinery","activity_type":"manufacture","role":"塑料机械制造商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"秦川机床 主营业务","quote":"主要产品为机床,塑料机械等"}],"status":"ACTIVE"},
    {"exposure_id":"exp_cx_realestate","company_id":"caixin_dev","node_id":"real_estate_development","activity_type":"operate","role":"房地产开发商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"*ST发展 主营业务","quote":"主营业务:房地产开发和环保"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ga_cable","company_id":"citic_guoan","node_id":"cable_tv_network","activity_type":"operate","role":"有线电视网络运营商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"国安股份 主营业务","quote":"主要业务:信息网络基础设施业务中的有线电视网...的投资建设"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ga_satellite","company_id":"citic_guoan","node_id":"satellite_communication","activity_type":"operate","role":"卫星通信运营商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"国安股份 主营业务","quote":"主要业务:...卫星通信网的投资建设"}],"status":"ACTIVE"},
    {"exposure_id":"exp_cdl_almond","company_id":"chengde_lulu","node_id":"almond_beverage","activity_type":"produce","role":"杏仁露生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"承德露露 主营业务","quote":"主要产品是植物蛋白饮料——杏仁露"}],"status":"ACTIVE"},
    {"exposure_id":"exp_hm_yarn","company_id":"huamao_textile","node_id":"yarn","activity_type":"produce","role":"纱线生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"华茂股份 主营业务","quote":"主要产品包括:纱线系列产品,坯布面料系列产品和色织面料系列产品等"}],"status":"ACTIVE"},
    {"exposure_id":"exp_hm_textile","company_id":"huamao_textile","node_id":"textile_product","activity_type":"produce","role":"纺织品综合制造商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"华茂股份 主营业务","quote":"棉,毛,麻,丝和人造纤维的纯,混纺纱线及其织物,针织品,服装,印染加工"}],"status":"ACTIVE"},
    {"exposure_id":"exp_sm_drilling_tool","company_id":"sinopec_machinery","node_id":"oil_drilling_tool","activity_type":"manufacture","role":"石油钻具制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"石化机械 主营业务","quote":"产品包含钻头钻具及井下工具...等多个领域的产品组合"}],"status":"ACTIVE"},
    {"exposure_id":"exp_sm_fracturing","company_id":"sinopec_machinery","node_id":"fracturing_equipment","activity_type":"manufacture","role":"压裂装备制造商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"石化机械 主营业务","quote":"产品包含...固井压裂装备...等多个领域的产品组合"}],"status":"ACTIVE"},
    {"exposure_id":"exp_sm_oilfield","company_id":"sinopec_machinery","node_id":"oilfield_service","activity_type":"operate","role":"油气田服务商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"石化机械 主营业务","quote":"主营业务:油气勘探到开采,储运装备"}],"status":"ACTIVE"},
    {"exposure_id":"exp_jd_ceramic","company_id":"jidd_equipment","node_id":"ceramic_product","activity_type":"manufacture","role":"日用陶瓷制造商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"冀东装备 主营业务","quote":"主要产品:日用陶瓷,耐火材料,卫生陶瓷"}],"status":"ACTIVE"},
    {"exposure_id":"exp_jd_refractory","company_id":"jidd_equipment","node_id":"refractory_material","activity_type":"manufacture","role":"耐火材料制造商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"冀东装备 主营业务","quote":"主要产品:日用陶瓷,耐火材料,卫生陶瓷"}],"status":"ACTIVE"},
    {"exposure_id":"exp_wly_liquor","company_id":"wuliangye","node_id":"liquor","activity_type":"produce","role":"白酒生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"五粮液 主营业务","quote":"主要产品:五粮液系列酒"}],"status":"ACTIVE"},
    {"exposure_id":"exp_gf_plastic_film","company_id":"guofeng_new_material","node_id":"plastic_film","activity_type":"produce","role":"塑料薄膜生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"国风新材 主营业务","quote":"主要产品:塑料薄膜,化工原料,碳酸钙超细粉,工程塑料"}],"status":"ACTIVE"},
    {"exposure_id":"exp_gf_capacitor_film","company_id":"guofeng_new_material","node_id":"capacitor_film","activity_type":"produce","role":"电容器薄膜生产商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"国风新材 经营范围","quote":"电容器用薄膜...电子信息用膜材料"}],"status":"ACTIVE"}
]

if __name__ == "__main__":
    gb = {"batch_id":"batch_032_graph","task_description":"Batch 032: Industrial nodes and edges for 10 companies (000833-000859). Focus on sugar/pulp/pyrite, machine tools, real estate, cable/satellite, almond beverage, textiles, oil drilling equipment, ceramics, liquor, plastic film.","nodes_to_upsert":nodes,"edges_to_upsert":edges,"rejected_or_pending":[]}
    bb = {"batch_id":"batch_032_business","task_description":"Batch 032: Company registrations and exposures for 10 companies (000833-000859).","industries_to_upsert":[],"industry_node_mappings_to_upsert":[],"companies_to_upsert":companies,"company_node_exposures_to_upsert":exposures}
    r1 = submit_graph(gb); print(f"Graph: {r1.status_code}", r1.json())
    r2 = submit_business(bb); print(f"Business: {r2.status_code}", r2.json())
