#!/usr/bin/env python3
"""Batch 033 Submission Script (000860-000880)"""
import requests
BASE_URL = "http://localhost:8000/api/v1"
submit_graph = lambda b: requests.post(f"{BASE_URL}/batches", json=b)
submit_business = lambda b: requests.post(f"{BASE_URL}/business-batches", json=b)

nodes = [
    {"node_id":"meat_product","canonical_name_zh":"肉类产品","canonical_name_en":"Meat Product","aliases":["肉制品","冷鲜肉"],"definition":"以畜禽屠宰后的生鲜肉或加工后的肉制品为主要形态的食品类别，包括冷鲜肉、冷冻肉、高温肉制品、低温肉制品等，是食品工业和居民膳食的重要组成部分。","entity_type":"material","evidence":[{"source_title":"顺鑫农业 主营业务","quote":"主要业务:白酒的生产和销售;肉类产品的生产和销售"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"vegetable_fruit_beverage","canonical_name_zh":"果蔬饮料","canonical_name_en":"Vegetable and Fruit Beverage","aliases":["果汁饮料","果蔬汁"],"definition":"以新鲜水果或蔬菜为原料，经压榨、调配、杀菌等工艺制成的液态饮品，保留了原料中的维生素、矿物质和膳食纤维等营养成分，是软饮料行业的重要品类。","entity_type":"material","evidence":[{"source_title":"顺鑫农业 主营业务","quote":"主要业务:...果蔬饮料的生产和销售"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"bus","canonical_name_zh":"客车","canonical_name_en":"Bus","aliases":["大巴","公共交通车辆"],"definition":"设计用于载运多名乘客的道路机动车辆，包括公路客车、旅游客车、城市公交客车和校车等类型，是公共交通和长途客运的核心装备。","entity_type":"system","evidence":[{"source_title":"安凯客车 主营业务","quote":"主要产品:各类公路客车,旅游客车,团体客车,景观车,公交客车,新能源商用车等"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"new_energy_vehicle","canonical_name_zh":"新能源汽车","canonical_name_en":"New Energy Vehicle","aliases":["新能源车","NEV"],"definition":"采用新型动力系统，完全或主要依靠新型能源驱动的汽车，包括纯电动汽车（BEV）、插电式混合动力汽车（PHEV）和燃料电池汽车（FCEV）等，是汽车产业转型升级的主要方向。","entity_type":"system","evidence":[{"source_title":"安凯客车 主营业务","quote":"主要产品:...新能源商用车等"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"wine","canonical_name_zh":"葡萄酒","canonical_name_en":"Wine","aliases":["红酒","果酒"],"definition":"以新鲜葡萄或葡萄汁为原料，经全部或部分发酵酿制而成的酒精饮料，酒精度通常在8%~15%之间，按颜色分为红葡萄酒、白葡萄酒和桃红葡萄酒，是国际上消费量最大的发酵酒品类。","entity_type":"material","evidence":[{"source_title":"张裕A 主营业务","quote":"主要产品:葡萄酒,白兰地"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"brandy","canonical_name_zh":"白兰地","canonical_name_en":"Brandy","aliases":["蒸馏葡萄酒"],"definition":"以葡萄或其他水果为原料，经发酵、蒸馏、陈酿等工艺制成的烈性蒸馏酒，酒精度通常在40%左右，以法国干邑和雅文邑产区最为著名，是国际上重要的高档烈酒品类。","entity_type":"material","evidence":[{"source_title":"张裕A 主营业务","quote":"主要产品:葡萄酒,白兰地"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"marine_engine","canonical_name_zh":"船用发动机","canonical_name_en":"Marine Engine","aliases":["船舶柴油机","船机"],"definition":"安装在船舶上为船舶提供推进动力或发电动力的内燃机或涡轮机，包括船用主机、船用辅机和船用发电机组等，是船舶动力系统的核心设备。","entity_type":"component","evidence":[{"source_title":"潍柴重机 主营业务","quote":"主要产品:农用车,拖拉机,复合管"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"gearbox","canonical_name_zh":"齿轮箱","canonical_name_en":"Gearbox","aliases":["减速机","变速器"],"definition":"由齿轮、轴、轴承和箱体等组成的机械传动装置，用于传递动力、改变转速和扭矩方向，广泛应用于船舶推进、风力发电、工程机械、轨道交通和工业传动等领域。","entity_type":"component","evidence":[{"source_title":"潍柴重机 经营范围","quote":"齿轮及齿轮减,变速箱制造;齿轮及齿轮减,变速箱销售"}],"confidence":"HIGH","status":"ACTIVE"}
]

edges = [
    {"edge_id":"flow_live_pig_to_meat","from_node":"live_pig","to_node":"meat_product","description":"生猪屠宰加工制成肉类产品。","edge_namespace":"industrial_flow","edge_type":"material_flow","evidence":[{"source_title":"顺鑫农业 产业链","quote":"肉类产品的生产和销售"}],"confidence":"HIGH"},
    {"edge_id":"flow_bus_to_transport","from_node":"bus","to_node":"public_transportation","description":"客车作为公共交通工具用于旅客运输服务。","edge_namespace":"industrial_flow","edge_type":"service_flow","evidence":[{"source_title":"安凯客车 产业链","quote":"公交客车→公共交通"}],"confidence":"HIGH"},
    {"edge_id":"flow_wine_to_brandy","from_node":"wine","to_node":"brandy","description":"葡萄酒经蒸馏陈酿制成白兰地。","edge_namespace":"industrial_flow","edge_type":"material_flow","evidence":[{"source_title":"张裕A 产品关联","quote":"葡萄酒,白兰地"}],"confidence":"HIGH"},
    {"edge_id":"flow_marine_engine_to_ship","from_node":"marine_engine","to_node":"ship","description":"船用发动机作为动力核心装配于船舶。","edge_namespace":"industrial_flow","edge_type":"composition","evidence":[{"source_title":"潍柴重机 产品关联","quote":"船用配套设备制造"}],"confidence":"HIGH"}
]

companies = [
    {"company_id":"shunxin_agriculture","name_zh":"北京顺鑫农业股份有限公司","aliases":["顺鑫农业"],"stock_codes":["000860.SZ"],"description":"主要业务包括白酒的生产和销售、肉类产品的生产和销售、果蔬饮料的生产和销售、种畜产品、农作物种子、蔬菜种子的繁育和销售。","country":"CN","province":"北京","city":"北京市","founded_year":1998,"employee_count":3739,"company_type":"public","status":"ACTIVE"},
    {"company_id":"yinxing_energy","name_zh":"宁夏银星能源股份有限公司","aliases":["银星能源"],"stock_codes":["000862.SZ"],"description":"主营业务为风力发电、太阳能发电及其相关产业的建设与运营管理，以及新能源装备制造和检测检修服务。","country":"CN","province":"宁夏","city":"银川市","founded_year":1998,"employee_count":556,"company_type":"public","status":"ACTIVE"},
    {"company_id":"sanxiang_impression","name_zh":"三湘印象股份有限公司","aliases":["三湘印象"],"stock_codes":["000863.SZ"],"description":"主营业务包括投资兴办实业、国内贸易、房地产开发经营、资产管理和经济信息咨询，同时涉足文化演艺和数字内容制作领域。","country":"CN","province":"上海","city":"上海市","founded_year":1994,"employee_count":334,"company_type":"public","status":"ACTIVE"},
    {"company_id":"ankai_bus","name_zh":"安徽安凯汽车股份有限公司","aliases":["安凯客车"],"stock_codes":["000868.SZ"],"description":"主要产品包括各类公路客车、旅游客车、团体客车、景观车、公交客车、新能源商用车等，主要从事客车产品的研发、制造与销售。","country":"CN","province":"安徽","city":"合肥市","founded_year":1997,"employee_count":1881,"company_type":"public","status":"ACTIVE"},
    {"company_id":"changyu","name_zh":"烟台张裕葡萄酿酒股份有限公司","aliases":["张裕A"],"stock_codes":["000869.SZ"],"description":"主要产品为葡萄酒和白兰地，是中国历史最悠久、规模最大的葡萄酒生产企业之一。","country":"CN","province":"山东","city":"烟台市","founded_year":1997,"employee_count":2158,"company_type":"public","status":"ACTIVE"},
    {"company_id":"spic_green_energy","name_zh":"国电投绿色能源股份有限公司","aliases":["电投绿能"],"stock_codes":["000875.SZ"],"description":"主要业务包括发电（火电、水电、风电、太阳能、分布式能源、气电、生物质、核能）、供热（民用、工业）、清洁能源投资开发等，发电和供热是核心业务。","country":"CN","province":"吉林","city":"长春市","founded_year":1993,"employee_count":3731,"company_type":"public","status":"ACTIVE"},
    {"company_id":"new_hope","name_zh":"新希望六和股份有限公司","aliases":["新希望"],"stock_codes":["000876.SZ"],"description":"主要产品涉及饲料、养殖、肉制品加工及商贸等，是中国最大的农牧食品企业之一。","country":"CN","province":"四川","city":"绵阳市","founded_year":1998,"employee_count":41327,"company_type":"public","status":"ACTIVE"},
    {"company_id":"tianshan_cement","name_zh":"天山材料股份有限公司","aliases":["天山股份"],"stock_codes":["000877.SZ"],"description":"主要产品包括油井水泥、水工水泥、硫铝水泥、海工水泥、热工水泥、核工水泥、道路水泥、制品水泥等，是中国最大的水泥企业之一。","country":"CN","province":"新疆","city":"乌鲁木齐市","founded_year":1998,"employee_count":51423,"company_type":"public","status":"ACTIVE"},
    {"company_id":"yunnan_copper","name_zh":"云南铜业股份有限公司","aliases":["云南铜业"],"stock_codes":["000878.SZ"],"description":"主要产品包括高纯阴极铜、工业硫酸、黄金、白银，主要业务为铜精矿及其他有色金属矿产品的生产和销售。","country":"CN","province":"云南","city":"昆明市","founded_year":1998,"employee_count":9465,"company_type":"public","status":"ACTIVE"},
    {"company_id":"weichai_heavy_machinery","name_zh":"潍柴重机股份有限公司","aliases":["潍柴重机"],"stock_codes":["000880.SZ"],"description":"主要产品包括船用发动机、柴油发电机组、齿轮箱及船舶动力配套设备，业务涵盖通用设备制造、船用配套设备制造和海洋工程关键配套系统开发。","country":"CN","province":"山东","city":"潍坊市","founded_year":1993,"employee_count":2204,"company_type":"public","status":"ACTIVE"}
]

exposures = [
    {"exposure_id":"exp_sxa_liquor","company_id":"shunxin_agriculture","node_id":"liquor","activity_type":"produce","role":"白酒生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"顺鑫农业 主营业务","quote":"主要业务:白酒的生产和销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_sxa_meat","company_id":"shunxin_agriculture","node_id":"meat_product","activity_type":"produce","role":"肉类产品生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"顺鑫农业 主营业务","quote":"主要业务:...肉类产品的生产和销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_sxa_beverage","company_id":"shunxin_agriculture","node_id":"vegetable_fruit_beverage","activity_type":"produce","role":"果蔬饮料生产商","weight":0.6,"confidence":"HIGH","evidence":[{"source_title":"顺鑫农业 主营业务","quote":"主要业务:...果蔬饮料的生产和销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ye_wind","company_id":"yinxing_energy","node_id":"wind_power_generation","activity_type":"operate","role":"风力发电运营商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"银星能源 主营业务","quote":"主营业务:风力发电,太阳能发电及其相关产业的建设与运营管理"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ye_solar","company_id":"yinxing_energy","node_id":"solar_power_generation","activity_type":"operate","role":"太阳能发电运营商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"银星能源 主营业务","quote":"主营业务:风力发电,太阳能发电..."}],"status":"ACTIVE"},
    {"exposure_id":"exp_sxi_realestate","company_id":"sanxiang_impression","node_id":"real_estate_development","activity_type":"operate","role":"房地产开发商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"三湘印象 主营业务","quote":"主营业务:投资兴办实业;国内贸易;从事房地产开发经营"}],"status":"ACTIVE"},
    {"exposure_id":"exp_sxi_film","company_id":"sanxiang_impression","node_id":"film_television","activity_type":"operate","role":"影视文化运营商","weight":0.6,"confidence":"HIGH","evidence":[{"source_title":"三湘印象 经营范围","quote":"电影制片;组织文化艺术交流活动"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ak_bus","company_id":"ankai_bus","node_id":"bus","activity_type":"manufacture","role":"客车制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"安凯客车 主营业务","quote":"主要产品:各类公路客车,旅游客车,团体客车,景观车,公交客车...等"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ak_nev","company_id":"ankai_bus","node_id":"new_energy_vehicle","activity_type":"manufacture","role":"新能源汽车制造商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"安凯客车 主营业务","quote":"主要产品:...新能源商用车等"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ak_cv","company_id":"ankai_bus","node_id":"commercial_vehicle","activity_type":"manufacture","role":"商用车制造商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"安凯客车 主营业务","quote":"主要产品:各类公路客车,旅游客车..."}],"status":"ACTIVE"},
    {"exposure_id":"exp_zy_wine","company_id":"changyu","node_id":"wine","activity_type":"produce","role":"葡萄酒生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"张裕A 主营业务","quote":"主要产品:葡萄酒,白兰地"}],"status":"ACTIVE"},
    {"exposure_id":"exp_zy_brandy","company_id":"changyu","node_id":"brandy","activity_type":"produce","role":"白兰地生产商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"张裕A 主营业务","quote":"主要产品:葡萄酒,白兰地"}],"status":"ACTIVE"},
    {"exposure_id":"exp_spic_thermal","company_id":"spic_green_energy","node_id":"coal_power_generation","activity_type":"operate","role":"火电运营商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"电投绿能 主营业务","quote":"主要业务:发电(火电,水电,风电,太阳能...)"}],"status":"ACTIVE"},
    {"exposure_id":"exp_spic_hydro","company_id":"spic_green_energy","node_id":"hydro_power_generation","activity_type":"operate","role":"水电运营商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"电投绿能 主营业务","quote":"主要业务:发电(火电,水电...)"}],"status":"ACTIVE"},
    {"exposure_id":"exp_spic_wind","company_id":"spic_green_energy","node_id":"wind_power_generation","activity_type":"operate","role":"风电运营商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"电投绿能 主营业务","quote":"主要业务:发电(...风电,太阳能...)"}],"status":"ACTIVE"},
    {"exposure_id":"exp_spic_solar","company_id":"spic_green_energy","node_id":"solar_power_generation","activity_type":"operate","role":"光伏发电运营商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"电投绿能 主营业务","quote":"主要业务:发电(...太阳能...)"}],"status":"ACTIVE"},
    {"exposure_id":"exp_spic_heating","company_id":"spic_green_energy","node_id":"heating_supply","activity_type":"produce","role":"热力供应商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"电投绿能 主营业务","quote":"主要业务:...供热(民用,工业)..."}],"status":"ACTIVE"},
    {"exposure_id":"exp_nh_feed","company_id":"new_hope","node_id":"feed","activity_type":"produce","role":"饲料生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"新希望 主营业务","quote":"主要产品涉及饲料,养殖,肉制品加工及商贸等"}],"status":"ACTIVE"},
    {"exposure_id":"exp_nh_livestock","company_id":"new_hope","node_id":"livestock_breeding","activity_type":"operate","role":"养殖服务商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"新希望 经营范围","quote":"牲畜的饲养;猪的饲养;家禽的饲养"}],"status":"ACTIVE"},
    {"exposure_id":"exp_nh_meat","company_id":"new_hope","node_id":"meat_product","activity_type":"produce","role":"肉制品加工商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"新希望 主营业务","quote":"主要产品涉及...肉制品加工及商贸等"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ts_cement","company_id":"tianshan_cement","node_id":"cement","activity_type":"produce","role":"水泥生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"天山股份 主营业务","quote":"主要产品:油井水泥,水工水泥,硫铝水泥,海工水泥,热工水泥,核工水泥,道路水泥,制品水泥"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ync_copper","company_id":"yunnan_copper","node_id":"copper","activity_type":"produce","role":"阴极铜生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"云南铜业 主营业务","quote":"主要产品:高纯阴极铜,工业硫酸,黄金,白银"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ync_sulfuric","company_id":"yunnan_copper","node_id":"sulfuric_acid","activity_type":"produce","role":"硫酸生产商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"云南铜业 主营业务","quote":"主要产品:高纯阴极铜,工业硫酸..."}],"status":"ACTIVE"},
    {"exposure_id":"exp_ync_gold","company_id":"yunnan_copper","node_id":"gold","activity_type":"produce","role":"黄金生产商","weight":0.6,"confidence":"HIGH","evidence":[{"source_title":"云南铜业 主营业务","quote":"主要产品:...黄金,白银"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ync_silver","company_id":"yunnan_copper","node_id":"silver","activity_type":"produce","role":"白银生产商","weight":0.6,"confidence":"HIGH","evidence":[{"source_title":"云南铜业 主营业务","quote":"主要产品:...黄金,白银"}],"status":"ACTIVE"},
    {"exposure_id":"exp_wc_marine_engine","company_id":"weichai_heavy_machinery","node_id":"marine_engine","activity_type":"manufacture","role":"船用发动机制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"潍柴重机 经营范围","quote":"船用配套设备制造;船舶自动化,检测,监控系统制造"}],"status":"ACTIVE"},
    {"exposure_id":"exp_wc_generator","company_id":"weichai_heavy_machinery","node_id":"generator_set","activity_type":"manufacture","role":"发电机组制造商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"潍柴重机 经营范围","quote":"发电机及发电机组制造;发电机及发电机组销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_wc_gearbox","company_id":"weichai_heavy_machinery","node_id":"gearbox","activity_type":"manufacture","role":"齿轮箱制造商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"潍柴重机 经营范围","quote":"齿轮及齿轮减,变速箱制造;齿轮及齿轮减,变速箱销售"}],"status":"ACTIVE"}
]

if __name__ == "__main__":
    gb = {"batch_id":"batch_033_graph","task_description":"Batch 033: Industrial nodes and edges for 10 companies (000860-000880). Focus on meat/beverage/seed, new energy power, real estate/culture, bus/NEV, wine/brandy, diversified power, feed/livestock/meat, cement, copper, marine engine/generator/gearbox.","nodes_to_upsert":nodes,"edges_to_upsert":edges,"rejected_or_pending":[]}
    bb = {"batch_id":"batch_033_business","task_description":"Batch 033: Company registrations and exposures for 10 companies (000860-000880).","industries_to_upsert":[],"industry_node_mappings_to_upsert":[],"companies_to_upsert":companies,"company_node_exposures_to_upsert":exposures}
    r1 = submit_graph(gb); print(f"Graph: {r1.status_code}", r1.json())
    r2 = submit_business(bb); print(f"Business: {r2.status_code}", r2.json())
