#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Submit Batch 116: nodes + edges, then business batch."""

import json
import subprocess
import os
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLI_PATH = os.path.join(BASE_DIR, "cli", "arachne_cli.py")
PY = os.path.join(BASE_DIR, "backend", "venv", "Scripts", "python.exe")

# ============ NODES ============
NODES = [
    {"node_id": "gene_engineering_drug", "canonical_name_zh": "基因工程药物", "canonical_name_en": "gene engineering drug", "entity_type": "material", "aliases": ["genetic engineering drug", "recombinant protein drug"], "definition": "利用基因工程技术生产的蛋白质或多肽类药物，包括重组生长因子、细胞因子等", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "双鹭药业招股说明书", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "biochemical_drug", "canonical_name_zh": "生化药物", "canonical_name_en": "biochemical drug", "entity_type": "material", "aliases": ["biochemical pharmaceutical"], "definition": "从生物体中提取或通过生物化学方法制备的药物", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "双鹭药业主营业务", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "freeze_dried_powder_injection", "canonical_name_zh": "冻干粉针剂", "canonical_name_en": "freeze-dried powder injection", "entity_type": "component", "aliases": ["lyophilized powder injection"], "definition": "将药物溶液冷冻干燥后制成的注射用无菌粉末制剂", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "双鹭药业产品线", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "growth_factor", "canonical_name_zh": "生长因子", "canonical_name_en": "growth factor", "entity_type": "material", "aliases": ["cell growth factor"], "definition": "调节细胞生长、分化、增殖的生物活性蛋白质，如成纤维细胞生长因子、粒细胞刺激因子", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "双鹭药业产品目录", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "interleukin", "canonical_name_zh": "白介素", "canonical_name_en": "interleukin", "entity_type": "material", "aliases": ["IL-2", "IL-11"], "definition": "一类细胞因子，在免疫调节和炎症反应中起重要作用", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "双鹭药业产品目录", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "oxaliplatin", "canonical_name_zh": "奥沙利铂", "canonical_name_en": "oxaliplatin", "entity_type": "material", "aliases": [], "definition": "第三代铂类抗肿瘤化疗药物，用于结直肠癌等", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "双鹭药业原料药产品", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "steel_rolling", "canonical_name_zh": "钢压延加工", "canonical_name_en": "steel rolling", "entity_type": "service", "aliases": ["steel processing"], "definition": "将钢坯通过轧机轧制成各种型材、板材、管材等钢材产品的加工过程", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "山东钢铁经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "coking", "canonical_name_zh": "炼焦", "canonical_name_en": "coking", "entity_type": "service", "aliases": ["coke production"], "definition": "将炼焦煤在高温下干馏生产焦炭的过程，焦炭用于高炉炼铁", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "山东钢铁经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "mineral_processing", "canonical_name_zh": "矿物加工", "canonical_name_en": "mineral processing", "entity_type": "service", "aliases": ["ore dressing", "beneficiation"], "definition": "通过物理或化学方法将矿石中有用矿物与脉石分离，提高品位的过程", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "山东钢铁经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "modified_plastic", "canonical_name_zh": "改性塑料", "canonical_name_en": "modified plastic", "entity_type": "material", "aliases": ["engineered plastic"], "definition": "通过物理或化学方法改变塑料性能，使其具有特定功能的新材料", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "金发科技主营业务", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "engineering_plastic", "canonical_name_zh": "工程塑料", "canonical_name_en": "engineering plastic", "entity_type": "material", "aliases": ["high performance plastic"], "definition": "具有优良机械性能、耐热性、耐腐蚀性，可替代金属用于工程结构的塑料", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "金发科技经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "bio_based_material", "canonical_name_zh": "生物基材料", "canonical_name_en": "bio-based material", "entity_type": "material", "aliases": ["biomass material"], "definition": "利用可再生生物质为原料生产的材料，如生物基塑料、生物基化学品", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "金发科技经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "glass_fiber_reinforced_plastic", "canonical_name_zh": "玻璃纤维增强塑料", "canonical_name_en": "fiberglass reinforced plastic", "entity_type": "material", "aliases": ["FRP", "GRP"], "definition": "以玻璃纤维为增强材料、合成树脂为基体的复合材料", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "金发科技经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "rubber_product", "canonical_name_zh": "橡胶制品", "canonical_name_en": "rubber product", "entity_type": "material", "aliases": ["rubber goods"], "definition": "以天然橡胶或合成橡胶为原料制成的各类产品", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "金发科技经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "recycled_resource", "canonical_name_zh": "再生资源", "canonical_name_en": "recycled resource", "entity_type": "material", "aliases": ["recycled material"], "definition": "通过回收、加工可再次利用的废旧物资和材料", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "金发科技经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "plastic_product", "canonical_name_zh": "塑料制品", "canonical_name_en": "plastic product", "entity_type": "material", "aliases": ["plastic goods"], "definition": "以塑料为原料加工制成的各类产品", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "金发科技经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "gas_turbine_power", "canonical_name_zh": "燃气动力", "canonical_name_en": "gas turbine power", "entity_type": "service", "aliases": ["gas power"], "definition": "利用燃气轮机将天然气等燃料的化学能转化为机械能和电能的动力系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "中国动力经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "steam_turbine_power", "canonical_name_zh": "蒸汽动力", "canonical_name_en": "steam turbine power", "entity_type": "service", "aliases": ["steam power"], "definition": "利用蒸汽轮机将热能转化为机械能和电能的动力系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "中国动力经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "diesel_engine_power", "canonical_name_zh": "柴油机动力", "canonical_name_en": "diesel engine power", "entity_type": "service", "aliases": ["diesel power"], "definition": "利用柴油机将燃料化学能转化为机械能的动力系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "中国动力经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "marine_equipment", "canonical_name_zh": "海洋工程专用设备", "canonical_name_en": "marine engineering equipment", "entity_type": "system", "aliases": ["offshore equipment"], "definition": "用于海洋资源开发和海洋工程作业的专用设备和系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "中国动力经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "ship_support_equipment", "canonical_name_zh": "船用配套设备", "canonical_name_en": "ship supporting equipment", "entity_type": "system", "aliases": ["marine ancillary equipment"], "definition": "船舶运行所需的各类辅助设备和系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "中国动力经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "lead", "canonical_name_zh": "铅", "canonical_name_en": "lead", "entity_type": "material", "aliases": ["Pb"], "definition": "一种重金属元素，主要用于蓄电池、电缆护套、防辐射材料等", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "株冶集团主营业务", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "zinc", "canonical_name_zh": "锌", "canonical_name_en": "zinc", "entity_type": "material", "aliases": ["Zn"], "definition": "一种金属元素，主要用于镀锌、合金、电池等", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "株冶集团主营业务", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "lead_zinc_alloy", "canonical_name_zh": "铅锌合金", "canonical_name_en": "lead-zinc alloy", "entity_type": "material", "aliases": [], "definition": "铅和锌为主要成分的合金材料", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "株冶集团主营业务", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "industrial_sulfuric_acid", "canonical_name_zh": "工业硫酸", "canonical_name_en": "industrial sulfuric acid", "entity_type": "material", "aliases": [], "definition": "广泛用于冶金、化工、化肥等工业领域的硫酸产品", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "株冶集团主营业务", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "sulfur_dioxide", "canonical_name_zh": "二氧化硫", "canonical_name_en": "sulfur dioxide", "entity_type": "material", "aliases": ["SO2"], "definition": "一种无色有刺激性气味的气体，可用于制硫酸、漂白剂等", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "株冶集团主营业务", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "concentrated_apple_juice", "canonical_name_zh": "浓缩苹果清汁", "canonical_name_en": "concentrated apple juice", "entity_type": "material", "aliases": ["apple juice concentrate"], "definition": "将苹果汁浓缩后制成的产品，用于饮料调配和食品加工", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "国投中鲁主营业务", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "concentrated_fruit_vegetable_juice", "canonical_name_zh": "浓缩果蔬汁", "canonical_name_en": "concentrated fruit and vegetable juice", "entity_type": "material", "aliases": [], "definition": "将各种果蔬汁浓缩后制成的产品", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "国投中鲁经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "livestock_poultry_breeding", "canonical_name_zh": "畜禽养殖", "canonical_name_en": "livestock and poultry breeding", "entity_type": "service", "aliases": [], "definition": "牛、猪、鸡等畜禽的规模化养殖活动", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "福成五丰主营业务", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "slaughtering_processing", "canonical_name_zh": "屠宰加工", "canonical_name_en": "slaughtering and processing", "entity_type": "service", "aliases": [], "definition": "畜禽的屠宰及肉类初级加工活动", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "福成五丰主营业务", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "quick_frozen_food", "canonical_name_zh": "速冻食品", "canonical_name_en": "quick-frozen food", "entity_type": "material", "aliases": ["frozen food"], "definition": "经过快速冻结处理并在低温下储存流通的食品", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "福成五丰经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "coal_washing", "canonical_name_zh": "煤炭洗选", "canonical_name_en": "coal washing", "entity_type": "service", "aliases": ["coal preparation"], "definition": "通过物理或化学方法去除煤中杂质，提高煤质的过程", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "恒源煤电经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "cable_accessory", "canonical_name_zh": "电缆附件", "canonical_name_en": "cable accessory", "entity_type": "component", "aliases": ["cable fitting"], "definition": "电缆系统中用于连接、终端、接头等功能的配套器件", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "宝胜股份经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "superconducting_system", "canonical_name_zh": "超导系统", "canonical_name_en": "superconducting system", "entity_type": "system", "aliases": ["superconductor system"], "definition": "利用超导材料零电阻特性构建的电力传输或磁体系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "宝胜股份经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "optical_fiber", "canonical_name_zh": "光纤", "canonical_name_en": "optical fiber", "entity_type": "component", "aliases": ["fiber optic"], "definition": "利用光的全反射原理传输光信号的细丝状玻璃或塑料材料", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "宝胜股份经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "marine_engineering_equipment", "canonical_name_zh": "海洋工程装备", "canonical_name_en": "marine engineering equipment", "entity_type": "system", "aliases": [], "definition": "用于海洋资源勘探、开发、利用和保护的各类工程装备", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "宝胜股份经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "offshore_wind_power_equipment", "canonical_name_zh": "海上风电装备", "canonical_name_en": "offshore wind power equipment", "entity_type": "system", "aliases": [], "definition": "用于海上风力发电的专用设备和系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "宝胜股份经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "communication_equipment", "canonical_name_zh": "通信设备", "canonical_name_en": "communication equipment", "entity_type": "device", "aliases": ["telecom equipment"], "definition": "用于信息传输和通信网络的各类设备和器件", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "宝胜股份经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "navigation_instrument", "canonical_name_zh": "导航测绘气象及海洋专用仪器", "canonical_name_en": "navigation instrument", "entity_type": "device", "aliases": ["surveying instrument", "meteorological instrument"], "definition": "用于导航定位、地形测绘、气象观测和海洋监测的专用仪器设备", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "宝胜股份经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "non_ferrous_metal_smelting", "canonical_name_zh": "有色金属冶炼", "canonical_name_en": "non-ferrous metal smelting", "entity_type": "service", "aliases": [], "definition": "对有色金属矿石进行冶炼加工，提取金属的生产活动", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "株冶集团主营业务", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "engineering_design_service", "canonical_name_zh": "工程设计服务", "canonical_name_en": "engineering design service", "entity_type": "service", "aliases": [], "definition": "为各类工程项目提供方案设计、技术咨询和图纸编制服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "宝胜股份经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "technical_service", "canonical_name_zh": "技术服务", "canonical_name_en": "technical service", "entity_type": "service", "aliases": ["technology service"], "definition": "提供技术开发、技术咨询、技术转让和技术推广等服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "多家企业经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "electricity_supply", "canonical_name_zh": "电力供应", "canonical_name_en": "electricity supply", "entity_type": "service", "aliases": ["power supply"], "definition": "通过电网向终端用户提供电能的服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "广安爱众主营业务", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "new_material", "canonical_name_zh": "新材料", "canonical_name_en": "new material", "entity_type": "material", "aliases": ["advanced material"], "definition": "具有优异性能或特殊功能的新型材料，包括高性能结构材料、功能材料等", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "株冶集团经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
    {"node_id": "coal_and_products", "canonical_name_zh": "煤炭及制品", "canonical_name_en": "coal and products", "entity_type": "material", "aliases": [], "definition": "煤炭及其加工制品，包括原煤、洗精煤、焦炭、型煤等", "status": "ACTIVE", "confidence": "HIGH", "evidence": [{"source_title": "恒源煤电经营范围", "source_url": None, "timestamp": "2024-01-01T00:00:00Z", "quote": "根据企业公开信息"}]},
]

# ============ EDGES ============
EDGES = [
    {"edge_id": "gene_engineering_drug_biological_drug", "from_node": "gene_engineering_drug", "to_node": "biological_drug", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "基因工程药物是生物药物的一种", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "biochemical_drug_biological_drug", "from_node": "biochemical_drug", "to_node": "biological_drug", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "生化药物是生物药物的一种", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "freeze_dried_powder_injection_gene_engineering_drug", "from_node": "freeze_dried_powder_injection", "to_node": "gene_engineering_drug", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "冻干粉针剂是基因工程药物的一种制剂形式", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "growth_factor_gene_engineering_drug", "from_node": "growth_factor", "to_node": "gene_engineering_drug", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "生长因子是基因工程药物的重要品类", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "interleukin_gene_engineering_drug", "from_node": "interleukin", "to_node": "gene_engineering_drug", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "白介素是基因工程药物的重要品类", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "oxaliplatin_antitumor_drug", "from_node": "oxaliplatin", "to_node": "antitumor_drug", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "奥沙利铂是抗肿瘤药物的一种", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "steel_rolling_steel_bar", "from_node": "steel_rolling", "to_node": "steel_bar", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "钢压延加工服务产出棒材", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "coking_coal", "from_node": "coking", "to_node": "coal", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "炼焦以煤炭为原料", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "mineral_processing_iron_ore", "from_node": "mineral_processing", "to_node": "iron_ore", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "选矿以铁矿石为原料", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "modified_plastic_plastic_resin", "from_node": "modified_plastic", "to_node": "plastic_resin", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "改性塑料以塑料树脂为原料", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "engineering_plastic_synthetic_resin", "from_node": "engineering_plastic", "to_node": "synthetic_resin", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "工程塑料以合成树脂为原料", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "bio_based_material_plastic_resin", "from_node": "bio_based_material", "to_node": "plastic_resin", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "生物基材料可替代塑料树脂", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "glass_fiber_reinforced_plastic_plastic_resin", "from_node": "glass_fiber_reinforced_plastic", "to_node": "plastic_resin", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "玻璃纤维增强塑料以塑料树脂为基体", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "rubber_product_synthetic_resin", "from_node": "rubber_product", "to_node": "synthetic_resin", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "部分橡胶制品以合成树脂为原料", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "recycled_resource_steel_bar", "from_node": "recycled_resource", "to_node": "steel_bar", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "再生资源可回收加工成钢材", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "plastic_product_plastic_resin", "from_node": "plastic_product", "to_node": "plastic_resin", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "塑料制品以塑料树脂为原料", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "gas_turbine_power_power_generation_equipment", "from_node": "gas_turbine_power", "to_node": "power_generation_equipment", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "燃气动力是发电设备的动力形式之一", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "steam_turbine_power_power_generation_equipment", "from_node": "steam_turbine_power", "to_node": "power_generation_equipment", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "蒸汽动力是发电设备的动力形式之一", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "diesel_engine_power_power_generation_equipment", "from_node": "diesel_engine_power", "to_node": "power_generation_equipment", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "柴油机动力是发电设备的动力形式之一", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "marine_equipment_ship", "from_node": "marine_equipment", "to_node": "ship", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "海洋工程设备用于船舶和海洋平台", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "ship_support_equipment_ship", "from_node": "ship_support_equipment", "to_node": "ship", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "船用配套设备是船舶系统的组成部分", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "lead_lead_zinc_alloy", "from_node": "lead", "to_node": "lead_zinc_alloy", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "铅是铅锌合金的原料之一", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "zinc_lead_zinc_alloy", "from_node": "zinc", "to_node": "lead_zinc_alloy", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "锌是铅锌合金的原料之一", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "industrial_sulfuric_acid_sulfuric_acid", "from_node": "industrial_sulfuric_acid", "to_node": "sulfuric_acid", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "工业硫酸是硫酸的工业级产品", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "sulfur_dioxide_industrial_sulfuric_acid", "from_node": "sulfur_dioxide", "to_node": "industrial_sulfuric_acid", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "二氧化硫是生产工业硫酸的中间产物", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "concentrated_apple_juice_concentrated_fruit_vegetable_juice", "from_node": "concentrated_apple_juice", "to_node": "concentrated_fruit_vegetable_juice", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "浓缩苹果清汁是浓缩果蔬汁的一种", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "livestock_poultry_breeding_meat_product", "from_node": "livestock_poultry_breeding", "to_node": "meat_product", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "畜禽养殖为肉制品提供原料", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "slaughtering_processing_livestock_poultry_breeding", "from_node": "slaughtering_processing", "to_node": "livestock_poultry_breeding", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "屠宰加工承接畜禽养殖环节", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "quick_frozen_food_meat_product", "from_node": "quick_frozen_food", "to_node": "meat_product", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "速冻食品以肉制品等为原料", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "coal_washing_coal_mining", "from_node": "coal_washing", "to_node": "coal_mining", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "煤炭洗选是煤炭开采后的加工环节", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "cable_accessory_wire_cable", "from_node": "cable_accessory", "to_node": "wire_cable", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "电缆附件是电线电缆系统的配套组件", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "superconducting_system_power_generation_equipment", "from_node": "superconducting_system", "to_node": "power_generation_equipment", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "超导系统可用于发电和输电领域", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "optical_fiber_communication_equipment", "from_node": "optical_fiber", "to_node": "communication_equipment", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "光纤是通信设备的关键传输介质", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "marine_engineering_equipment_ocean_engineering", "from_node": "marine_engineering_equipment", "to_node": "ocean_engineering", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "海洋工程装备服务于海洋工程", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "offshore_wind_power_equipment_wind_power", "from_node": "offshore_wind_power_equipment", "to_node": "wind_power", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "海上风电装备是风电产业的组成部分", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "navigation_instrument_marine_equipment", "from_node": "navigation_instrument", "to_node": "marine_equipment", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "导航仪器是海洋工程设备的组成部分", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "non_ferrous_metal_smelting_lead", "from_node": "non_ferrous_metal_smelting", "to_node": "lead", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "有色金属冶炼产出铅等金属", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "non_ferrous_metal_smelting_zinc", "from_node": "non_ferrous_metal_smelting", "to_node": "zinc", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "有色金属冶炼产出锌等金属", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "engineering_design_service_construction_engineering", "from_node": "engineering_design_service", "to_node": "construction_engineering", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "工程设计服务服务于建筑工程", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "technical_service_engineering_design_service", "from_node": "technical_service", "to_node": "engineering_design_service", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "技术服务支持工程设计", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "electricity_supply_power_generation_equipment", "from_node": "electricity_supply", "to_node": "power_generation_equipment", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "电力供应依赖发电设备", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "new_material_engineering_plastic", "from_node": "new_material", "to_node": "engineering_plastic", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "工程塑料是新材料的重要品类", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
    {"edge_id": "coal_and_products_coal", "from_node": "coal_and_products", "to_node": "coal", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "煤炭及制品以煤炭为核心", "evidence": [{"source_title": "产业知识图谱", "source_url": None, "quote": "工业流程关系定义"}], "confidence": "HIGH"},
]

def submit_graph_batch():
    batch = {"batch_id": "batch_116_nodes", "task_description": "Batch 116 industrial nodes and edges for 10 A-share companies", "nodes_to_upsert": NODES, "edges_to_upsert": EDGES}
    path = os.path.join(BASE_DIR, "tmp_script", "batch_116_nodes.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(batch, f, ensure_ascii=False, indent=2)
    result = subprocess.run([PY, CLI_PATH, "submit", path], capture_output=True, text=True)
    print("[GRAPH BATCH] stdout:", result.stdout)
    print("[GRAPH BATCH] stderr:", result.stderr)
    return result.returncode

# ============ BUSINESS BATCH ============
BUSINESS = {
    "batch_id": "batch_116_business",
    "task_description": "Batch 116 business registration for 10 A-share companies",
    "companies_to_upsert": [
        {"company_id": "sz_002038", "name_zh": "双鹭药业", "name_en": "Beijing Sunway Pharmaceutical Co., Ltd.", "country": "CN", "province": "北京", "city": "北京市", "stock_codes": ["002038.SZ"], "description": "基因工程药物及生化、化学药物的研究开发、生产经营", "founded_year": 1994, "employee_count": 889},
        {"company_id": "sh_600022", "name_zh": "山东钢铁", "name_en": "Shandong Iron and Steel Co., Ltd.", "country": "CN", "province": "山东", "city": "济南市", "stock_codes": ["600022.SH"], "description": "型钢、棒材、钢筋、热轧卷板、冷轧薄板、宽厚板等钢铁产品生产", "founded_year": 2000, "employee_count": 16031},
        {"company_id": "sh_600143", "name_zh": "金发科技", "name_en": "Kingfa Sci. & Tech. Co., Ltd.", "country": "CN", "province": "广东", "city": "广州市", "stock_codes": ["600143.SH"], "description": "改性塑料的研制、生产和销售", "founded_year": 1993, "employee_count": 13083},
        {"company_id": "sh_600482", "name_zh": "中国动力", "name_en": "China Shipbuilding Industry Group Power Co., Ltd.", "country": "CN", "province": "河北", "city": "保定市", "stock_codes": ["600482.SH"], "description": "燃气动力、蒸汽动力、化学动力、全电动力、柴油机动力及热气机动力等领域的研发、设计、生产、销售", "founded_year": 2000, "employee_count": 24499},
        {"company_id": "sh_600961", "name_zh": "株冶集团", "name_en": "Zhuzhou Smelter Group Co., Ltd.", "country": "CN", "province": "湖南", "city": "株洲市", "stock_codes": ["600961.SH"], "description": "铅、锌及其合金产品的冶炼和销售", "founded_year": 1993, "employee_count": 4085},
        {"company_id": "sh_600962", "name_zh": "国投中鲁", "name_en": "SDIC Zhonglu Fruit Juice Co., Ltd.", "country": "CN", "province": "北京", "city": "北京市", "stock_codes": ["600962.SH"], "description": "浓缩苹果清汁及浓缩果蔬汁的生产销售", "founded_year": 1991, "employee_count": 1146},
        {"company_id": "sh_600965", "name_zh": "福成股份", "name_en": "Hebei Fucheng Wufeng Food Co., Ltd.", "country": "CN", "province": "河北", "city": "廊坊市", "stock_codes": ["600965.SH"], "description": "畜禽养殖、屠宰加工及食品加工、餐饮服务", "founded_year": 1998, "employee_count": 2089},
        {"company_id": "sh_600971", "name_zh": "恒源煤电", "name_en": "Anhui Hengyuan Coal and Electricity Co., Ltd.", "country": "CN", "province": "安徽", "city": "淮北市", "stock_codes": ["600971.SH"], "description": "煤炭开采、洗选加工和销售", "founded_year": 2000, "employee_count": 14223},
        {"company_id": "sh_600973", "name_zh": "宝胜股份", "name_en": "Baosheng Science and Technology Innovation Co., Ltd.", "country": "CN", "province": "江苏", "city": "扬州市", "stock_codes": ["600973.SH"], "description": "电线电缆及电缆附件开发、制造、销售及相关技术开发", "founded_year": 2000, "employee_count": 6346},
        {"company_id": "sh_600979", "name_zh": "广安爱众", "name_en": "Sichuan Guangan Aizhong Co., Ltd.", "country": "CN", "province": "四川", "city": "广安市", "stock_codes": ["600979.SH"], "description": "水力发电和电力供应、天然气供应、自来水生产和供应", "founded_year": 1999, "employee_count": 2352},
    ],
    "company_node_exposures_to_upsert": [
        # 双鹭药业
        {"exposure_id": "sz_002038_produce_gene_engineering_drug", "company_id": "sz_002038", "node_id": "gene_engineering_drug", "activity_type": "produce", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主营业务:基因工程药物", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sz_002038_produce_biochemical_drug", "company_id": "sz_002038", "node_id": "biochemical_drug", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主营业务:生化药物", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sz_002038_produce_chemical_drug", "company_id": "sz_002038", "node_id": "chemical_drug", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主营业务:化学药物", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sz_002038_produce_antitumor_drug", "company_id": "sz_002038", "node_id": "antitumor_drug", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "冻干粉针剂含抗肿瘤药", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sz_002038_produce_freeze_dried_powder_injection", "company_id": "sz_002038", "node_id": "freeze_dried_powder_injection", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主要产品:冻干粉针剂", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sz_002038_produce_growth_factor", "company_id": "sz_002038", "node_id": "growth_factor", "activity_type": "produce", "weight": 0.03, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "生物工程产品:重组人碱性成纤维细胞生长因子", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sz_002038_produce_interleukin", "company_id": "sz_002038", "node_id": "interleukin", "activity_type": "produce", "weight": 0.02, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "生物工程产品:重组人白介素-2/白介素-11", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        # 山东钢铁
        {"exposure_id": "sh_600022_produce_steel_section", "company_id": "sh_600022", "node_id": "steel_section", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主要产品:型钢", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600022_produce_steel_bar", "company_id": "sh_600022", "node_id": "steel_bar", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主要产品:棒材", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600022_produce_steel_rebar", "company_id": "sh_600022", "node_id": "steel_rebar", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主要产品:钢筋", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600022_produce_hot_rolled_coil", "company_id": "sh_600022", "node_id": "hot_rolled_coil", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主要产品:热轧卷板", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600022_produce_steel_plate", "company_id": "sh_600022", "node_id": "steel_plate", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主要产品:宽厚板/冷轧薄板", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600022_operate_steel_rolling", "company_id": "sh_600022", "node_id": "steel_rolling", "activity_type": "operate", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:钢压延加工", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600022_operate_coking", "company_id": "sh_600022", "node_id": "coking", "activity_type": "operate", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:炼焦", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600022_operate_mineral_processing", "company_id": "sh_600022", "node_id": "mineral_processing", "activity_type": "operate", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:选矿", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        # 金发科技
        {"exposure_id": "sh_600143_produce_modified_plastic", "company_id": "sh_600143", "node_id": "modified_plastic", "activity_type": "produce", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主营业务:改性塑料", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600143_produce_engineering_plastic", "company_id": "sh_600143", "node_id": "engineering_plastic", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:工程塑料", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600143_produce_bio_based_material", "company_id": "sh_600143", "node_id": "bio_based_material", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:生物基材料", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600143_produce_glass_fiber_reinforced_plastic", "company_id": "sh_600143", "node_id": "glass_fiber_reinforced_plastic", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:玻璃纤维增强塑料制品", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600143_produce_rubber_product", "company_id": "sh_600143", "node_id": "rubber_product", "activity_type": "produce", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:橡胶制品", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600143_produce_recycled_resource", "company_id": "sh_600143", "node_id": "recycled_resource", "activity_type": "produce", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:再生资源回收加工", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600143_produce_plastic_product", "company_id": "sh_600143", "node_id": "plastic_product", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:塑料制品", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600143_produce_synthetic_fiber", "company_id": "sh_600143", "node_id": "synthetic_fiber", "activity_type": "produce", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:合成纤维", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600143_produce_synthetic_resin", "company_id": "sh_600143", "node_id": "synthetic_resin", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:合成树脂", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        # 中国动力
        {"exposure_id": "sh_600482_produce_lead_acid_battery", "company_id": "sh_600482", "node_id": "lead_acid_battery", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主要产品:铅酸蓄电池", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600482_produce_marine_equipment", "company_id": "sh_600482", "node_id": "marine_equipment", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:海洋工程专用设备", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600482_produce_ship_support_equipment", "company_id": "sh_600482", "node_id": "ship_support_equipment", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:船用配套设备", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600482_produce_battery", "company_id": "sh_600482", "node_id": "battery", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:电池研发设计生产销售", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600482_provide_service_gas_turbine_power", "company_id": "sh_600482", "node_id": "gas_turbine_power", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:燃气动力研发设计生产销售", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600482_provide_service_steam_turbine_power", "company_id": "sh_600482", "node_id": "steam_turbine_power", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:蒸汽动力研发设计生产销售", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600482_provide_service_diesel_engine_power", "company_id": "sh_600482", "node_id": "diesel_engine_power", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:柴油机动力研发设计生产销售", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600482_provide_service_marine_engine", "company_id": "sh_600482", "node_id": "marine_engine", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:海洋工程专用设备研发设计生产销售", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        # 株冶集团
        {"exposure_id": "sh_600961_produce_lead", "company_id": "sh_600961", "node_id": "lead", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主要产品:铅", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600961_produce_zinc", "company_id": "sh_600961", "node_id": "zinc", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主要产品:锌", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600961_produce_lead_zinc_alloy", "company_id": "sh_600961", "node_id": "lead_zinc_alloy", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主要产品:铅锌合金", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600961_produce_industrial_sulfuric_acid", "company_id": "sh_600961", "node_id": "industrial_sulfuric_acid", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主营业务:工业硫酸", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600961_produce_sulfur_dioxide", "company_id": "sh_600961", "node_id": "sulfur_dioxide", "activity_type": "produce", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主营业务:二氧化硫烟气", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600961_produce_battery", "company_id": "sh_600961", "node_id": "battery", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:电池制造销售", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600961_operate_non_ferrous_metal_smelting", "company_id": "sh_600961", "node_id": "non_ferrous_metal_smelting", "activity_type": "operate", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主营业务:有色金属冶炼", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600961_produce_energy_storage_battery", "company_id": "sh_600961", "node_id": "energy_storage_battery", "activity_type": "produce", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:储能技术服务", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600961_produce_new_material", "company_id": "sh_600961", "node_id": "new_material", "activity_type": "produce", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:新材料技术研发", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        # 国投中鲁
        {"exposure_id": "sh_600962_produce_concentrated_apple_juice", "company_id": "sh_600962", "node_id": "concentrated_apple_juice", "activity_type": "produce", "weight": 0.60, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主营业务:浓缩苹果清汁", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600962_produce_concentrated_fruit_vegetable_juice", "company_id": "sh_600962", "node_id": "concentrated_fruit_vegetable_juice", "activity_type": "produce", "weight": 0.40, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:浓缩果蔬汁", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        # 福成股份
        {"exposure_id": "sh_600965_operate_livestock_poultry_breeding", "company_id": "sh_600965", "node_id": "livestock_poultry_breeding", "activity_type": "operate", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主营业务:畜禽养殖", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600965_operate_slaughtering_processing", "company_id": "sh_600965", "node_id": "slaughtering_processing", "activity_type": "operate", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主营业务:屠宰加工", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600965_produce_meat_product", "company_id": "sh_600965", "node_id": "meat_product", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:加工肉制品", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600965_produce_quick_frozen_food", "company_id": "sh_600965", "node_id": "quick_frozen_food", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:速冻食品", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600965_produce_dairy_product", "company_id": "sh_600965", "node_id": "dairy_product", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:乳制品", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600965_operate_catering_service", "company_id": "sh_600965", "node_id": "catering_service", "activity_type": "operate", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主营业务:餐饮服务", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600965_produce_organic_fertilizer", "company_id": "sh_600965", "node_id": "organic_fertilizer", "activity_type": "produce", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:有机肥料生产", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600965_produce_food_condiment", "company_id": "sh_600965", "node_id": "food_condiment", "activity_type": "produce", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:调味料", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        # 恒源煤电
        {"exposure_id": "sh_600971_operate_coal_mining", "company_id": "sh_600971", "node_id": "coal_mining", "activity_type": "operate", "weight": 0.40, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主营业务:煤炭开采", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600971_operate_coal_washing", "company_id": "sh_600971", "node_id": "coal_washing", "activity_type": "operate", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主营业务:煤炭洗选", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600971_produce_coal", "company_id": "sh_600971", "node_id": "coal", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:煤炭及制品销售", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600971_produce_coal_and_products", "company_id": "sh_600971", "node_id": "coal_and_products", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:煤炭及制品销售", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        # 宝胜股份
        {"exposure_id": "sh_600973_produce_wire_cable", "company_id": "sh_600973", "node_id": "wire_cable", "activity_type": "produce", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主营业务:电线电缆", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600973_produce_cable_accessory", "company_id": "sh_600973", "node_id": "cable_accessory", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:电线电缆及电缆附件", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600973_produce_superconducting_system", "company_id": "sh_600973", "node_id": "superconducting_system", "activity_type": "produce", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:超导系统开发与应用", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600973_produce_optical_fiber", "company_id": "sh_600973", "node_id": "optical_fiber", "activity_type": "produce", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:光纤技术开发", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600973_produce_optical_fiber_cable", "company_id": "sh_600973", "node_id": "optical_fiber_cable", "activity_type": "produce", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:光缆制造销售", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600973_produce_marine_engineering_equipment", "company_id": "sh_600973", "node_id": "marine_engineering_equipment", "activity_type": "produce", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:海洋工程装备制造", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600973_produce_offshore_wind_power_equipment", "company_id": "sh_600973", "node_id": "offshore_wind_power_equipment", "activity_type": "produce", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:海上风电相关装备", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600973_produce_communication_equipment", "company_id": "sh_600973", "node_id": "communication_equipment", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:通信设备制造", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600973_produce_navigation_instrument", "company_id": "sh_600973", "node_id": "navigation_instrument", "activity_type": "produce", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:导航测绘气象及海洋专用仪器", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600973_provide_service_engineering_design_service", "company_id": "sh_600973", "node_id": "engineering_design_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:建设工程设计施工", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600973_provide_service_technical_service", "company_id": "sh_600973", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "经营范围:技术服务技术开发", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        # 广安爱众
        {"exposure_id": "sh_600979_operate_hydro_power", "company_id": "sh_600979", "node_id": "hydro_power", "activity_type": "operate", "weight": 0.35, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主营业务:水力发电", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600979_provide_service_electricity_supply", "company_id": "sh_600979", "node_id": "electricity_supply", "activity_type": "provide_service", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主营业务:电力供应", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600979_provide_service_natural_gas_supply", "company_id": "sh_600979", "node_id": "natural_gas_supply", "activity_type": "provide_service", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主营业务:天然气供应", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
        {"exposure_id": "sh_600979_provide_service_water_supply", "company_id": "sh_600979", "node_id": "water_supply", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": [{"source_title": "主营业务:自来水供应", "timestamp": "2024-01-01T00:00:00Z", "source_url": None, "quote": "根据企业公开信息"}]},
    ],
    "industries_to_upsert": [],
    "industry_node_mappings_to_upsert": [],
}

def submit_business_batch():
    path = os.path.join(BASE_DIR, "tmp_script", "batch_116_business.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(BUSINESS, f, ensure_ascii=False, indent=2)
    result = subprocess.run([PY, CLI_PATH, "business-batch", path], capture_output=True, text=True)
    print("[BUSINESS BATCH] stdout:", result.stdout)
    print("[BUSINESS BATCH] stderr:", result.stderr)
    return result.returncode

if __name__ == "__main__":
    print("Submitting graph batch 116...")
    rc1 = submit_graph_batch()
    if rc1 != 0:
        print("Graph batch failed, aborting.")
        sys.exit(1)
    print("Submitting business batch 116...")
    rc2 = submit_business_batch()
    sys.exit(rc2)
