#!/usr/bin/env python3
"""Batch 030 Submission Script (000807-000819)"""
import json, requests
BASE_URL = "http://localhost:8000/api/v1"
submit_graph = lambda b: requests.post(f"{BASE_URL}/batches", json=b)
submit_business = lambda b: requests.post(f"{BASE_URL}/business-batches", json=b)

nodes = [
    {"node_id":"cigarette_packaging","canonical_name_zh":"烟标包装","canonical_name_en":"Cigarette Packaging","aliases":["烟标印刷","烟草包装"],"definition":"专为卷烟产品设计的包装印刷品，包括烟盒、烟条、烟箱等，兼具品牌展示和防伪功能，是烟草产业链中的重要配套环节。","entity_type":"material","evidence":[{"source_title":"陕西金叶 主营业务","quote":"主要业务:烟标印刷及包装材料的研发生产,新型烟草制品器具及原辅料的研发生产,教育产业"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"data_center_service","canonical_name_zh":"数据中心服务","canonical_name_en":"Data Center Service","aliases":["IDC服务","数据中心运营"],"definition":"提供数据中心基础设施租赁、服务器托管、云计算资源、网络带宽及运维管理等服务，是数字经济时代信息存储和计算的核心载体。","entity_type":"service","evidence":[{"source_title":"美利云 主营业务","quote":"主要业务:造纸,数据中心业务"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"special_chemical","canonical_name_zh":"特种化工产品","canonical_name_en":"Specialty Chemical","aliases":["精细化工","特种化学品"],"definition":"具有特定功能、高附加值、小批量生产的化工产品，区别于大宗化工品，包括电子化学品、特种涂料、功能性材料、医药中间体等。","entity_type":"material","evidence":[{"source_title":"航锦科技 主营业务","quote":"主要业务:化工业务,电子业务,其中化工业务主要产品为烧碱,环氧丙烷,聚醚"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"ic_design","canonical_name_zh":"集成电路设计","canonical_name_en":"Integrated Circuit Design","aliases":["芯片设计","IC设计"],"definition":"根据系统功能需求，通过电路设计、仿真验证、版图设计等流程，将逻辑功能转化为可制造的集成电路版图的技术活动，是半导体产业的核心环节。","entity_type":"technology_capability","evidence":[{"source_title":"航锦科技 主营业务","quote":"电子业务主要产品为特种芯片,FPGA芯片,总线接口芯片,微控制器等"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"methanol","canonical_name_zh":"甲醇","canonical_name_en":"Methanol","aliases":["木醇","CH3OH"],"definition":"结构最简单的饱和一元醇，是重要的基础有机化工原料和清洁燃料，广泛用于甲醛、醋酸、二甲醚、MTBE等化工产品的生产，也可作为车用燃料。","entity_type":"material","evidence":[{"source_title":"岳阳兴长 主营业务","quote":"主要业务:石油化工产品的生产,销售"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"lp_gas","canonical_name_zh":"液化石油气","canonical_name_en":"Liquefied Petroleum Gas","aliases":["LPG","液化气"],"definition":"由丙烷和丁烷组成的混合烃类气体，在常温常压下经压缩液化后储存运输，是重要的民用燃料和化工原料，广泛用于家庭 cooking、工业加热和汽车燃料。","entity_type":"material","evidence":[{"source_title":"岳阳兴长 主营业务","quote":"主要业务:石油化工产品的生产,销售"}],"confidence":"HIGH","status":"ACTIVE"}
]

edges = [
    {"edge_id":"flow_cigarette_packaging_to_tobacco","from_node":"cigarette_packaging","to_node":"cigarette","description":"烟标包装作为卷烟产品的外包装材料。","edge_namespace":"industrial_flow","edge_type":"composition","evidence":[{"source_title":"陕西金叶 产业链","quote":"烟标印刷→烟草包装"}],"confidence":"HIGH"},
    {"edge_id":"flow_aluminum_smelting_to_ingot","from_node":"aluminum_smelting","to_node":"aluminum_ingot","description":"铝冶炼过程产出铝锭。","edge_namespace":"industrial_flow","edge_type":"material_flow","evidence":[{"source_title":"云铝股份 产业链","quote":"铝冶炼→铝锭"}],"confidence":"HIGH"},
    {"edge_id":"flow_ingot_to_alloy","from_node":"aluminum_ingot","to_node":"aluminum_alloy","description":"铝锭经合金化后制成铝合金。","edge_namespace":"industrial_flow","edge_type":"material_flow","evidence":[{"source_title":"云铝股份 产业链","quote":"铝锭→铝合金"}],"confidence":"HIGH"},
    {"edge_id":"flow_methanol_to_fuel","from_node":"methanol","to_node":"refined_oil","description":"甲醇作为化工原料用于油品添加剂和清洁燃料生产。","edge_namespace":"industrial_flow","edge_type":"material_flow","evidence":[{"source_title":"岳阳兴长 产品关联","quote":"石油化工产品"}],"confidence":"HIGH"},
    {"edge_id":"flow_lp_gas_to_fuel","from_node":"lp_gas","to_node":"natural_gas","description":"液化石油气作为清洁燃料与天然气在民用燃气领域形成替代关系。","edge_namespace":"industrial_flow","edge_type":"service_flow","evidence":[{"source_title":"岳阳兴长 产品关联","quote":"石油化工产品"}],"confidence":"HIGH"}
]

companies = [
    {"company_id":"yunnan_aluminum","name_zh":"云南铝业股份有限公司","aliases":["云铝股份"],"stock_codes":["000807.SZ"],"description":"主要业务为铝锭、铝合金、铝加工产品的生产和销售，以及铝冶炼，是中国重要的铝工业基地。","country":"CN","province":"云南","city":"昆明市","founded_year":1998,"employee_count":10283,"company_type":"public","status":"ACTIVE"},
    {"company_id":"hezhan_energy","name_zh":"辽宁和展能源集团股份有限公司","aliases":["和展能源"],"stock_codes":["000809.SZ"],"description":"主要业务为风力发电，是清洁能源发电企业。","country":"CN","province":"辽宁","city":"铁岭市","founded_year":1993,"employee_count":67,"company_type":"public","status":"ACTIVE"},
    {"company_id":"skyworth_digital","name_zh":"创维数字股份有限公司","aliases":["创维数字"],"stock_codes":["000810.SZ"],"description":"主要业务为数字电视、宽带通信、智能家居等智能终端设备的研发、生产和销售，涵盖机顶盒、宽带连接设备、智能家庭网关等产品。","country":"CN","province":"四川","city":"遂宁市","founded_year":2002,"employee_count":3874,"company_type":"public","status":"ACTIVE"},
    {"company_id":"bingshan_env","name_zh":"冰轮环境技术股份有限公司","aliases":["冰轮环境"],"stock_codes":["000811.SZ"],"description":"主要业务为低温冷冻设备、中央空调设备、节能制热设备、能源化工装备、精密铸件、智慧服务、氢能装备等的研发生产，产品涵盖制冷压缩机、速冻设备、冷库设备等。","country":"CN","province":"山东","city":"烟台市","founded_year":1989,"employee_count":2718,"company_type":"public","status":"ACTIVE"},
    {"company_id":"shaanxi_jinye","name_zh":"陕西金叶科教集团股份有限公司","aliases":["陕西金叶"],"stock_codes":["000812.SZ"],"description":"主要业务为烟标印刷及包装材料的研发生产、新型烟草制品器具及原辅料的研发生产，同时布局教育产业。","country":"CN","province":"陕西","city":"西安市","founded_year":1994,"employee_count":1981,"company_type":"public","status":"ACTIVE"},
    {"company_id":"dezhan_health","name_zh":"德展大健康股份有限公司","aliases":["德展健康"],"stock_codes":["000813.SZ"],"description":"主要业务为化学药、原料药、生物制药、保健品的研发、生产和销售，产品涵盖心脑血管药物、抗感染药物等。","country":"CN","province":"新疆","city":"乌鲁木齐市","founded_year":1994,"employee_count":1240,"company_type":"public","status":"ACTIVE"},
    {"company_id":"meili_cloud","name_zh":"中冶美利云产业投资股份有限公司","aliases":["美利云"],"stock_codes":["000815.SZ"],"description":"主要业务为造纸和数据中心业务，产品包括文化用纸、包装用纸及数据中心托管服务。","country":"CN","province":"宁夏","city":"中卫市","founded_year":1998,"employee_count":1365,"company_type":"public","status":"ACTIVE"},
    {"company_id":"smart_agri","name_zh":"江苏农华智慧农业科技股份有限公司","aliases":["智慧农业"],"stock_codes":["000816.SZ"],"description":"主要业务为内燃机及终端产品的研发生产和销售，产品包括柴油发动机、汽油发动机、农业机械等。","country":"CN","province":"江苏","city":"盐城市","founded_year":1991,"employee_count":2149,"company_type":"public","status":"ACTIVE"},
    {"company_id":"hangjin_tech","name_zh":"航锦科技股份有限公司","aliases":["航锦科技"],"stock_codes":["000818.SZ"],"description":"主要业务涵盖化工业务和电子业务，化工业务主要产品为烧碱、环氧丙烷、聚醚，电子业务主要产品为特种芯片、FPGA芯片、总线接口芯片、微控制器等。","country":"CN","province":"辽宁","city":"葫芦岛市","founded_year":1997,"employee_count":1908,"company_type":"public","status":"ACTIVE"},
    {"company_id":"yueyang_xingchang","name_zh":"岳阳兴长石化股份有限公司","aliases":["岳阳兴长"],"stock_codes":["000819.SZ"],"description":"主要业务为石油化工产品的生产和销售，产品包括丙烯、液化石油气、MTBE、甲醇等，是石油化工产业链中的重要企业。","country":"CN","province":"湖南","city":"岳阳市","founded_year":1990,"employee_count":556,"company_type":"public","status":"ACTIVE"}
]

exposures = [
    {"exposure_id":"exp_ya_al_ingot","company_id":"yunnan_aluminum","node_id":"aluminum_ingot","activity_type":"produce","role":"铝锭生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"云铝股份 主营业务","quote":"主要业务:铝锭,铝合金,铝加工产品的生产和销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ya_al_alloy","company_id":"yunnan_aluminum","node_id":"aluminum_alloy","activity_type":"produce","role":"铝合金生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"云铝股份 主营业务","quote":"主要业务:铝锭,铝合金,铝加工产品的生产和销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ya_al_smelting","company_id":"yunnan_aluminum","node_id":"aluminum_smelting","activity_type":"operate","role":"铝冶炼运营商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"云铝股份 经营范围","quote":"铝冶炼"}],"status":"ACTIVE"},
    {"exposure_id":"exp_hz_wind","company_id":"hezhan_energy","node_id":"wind_power_generation","activity_type":"operate","role":"风力发电运营商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"和展能源 主营业务","quote":"主要业务:风力发电"}],"status":"ACTIVE"},
    {"exposure_id":"exp_hz_elec","company_id":"hezhan_energy","node_id":"electricity_power","activity_type":"produce","role":"电力生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"和展能源 经营范围","quote":"电力业务"}],"status":"ACTIVE"},
    {"exposure_id":"exp_sw_stb","company_id":"skyworth_digital","node_id":"set_top_box","activity_type":"manufacture","role":"机顶盒制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"创维数字 主营业务","quote":"数字电视,宽带通信,智能家居等智能终端设备"}],"status":"ACTIVE"},
    {"exposure_id":"exp_sw_broadcast","company_id":"skyworth_digital","node_id":"broadcasting_equipment","activity_type":"manufacture","role":"广播电视设备制造商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"创维数字 主营业务","quote":"数字电视...智能终端设备"}],"status":"ACTIVE"},
    {"exposure_id":"exp_bl_refrigeration","company_id":"bingshan_env","node_id":"refrigeration_equipment","activity_type":"manufacture","role":"制冷设备制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"冰轮环境 主营业务","quote":"主要业务:低温冷冻设备,中央空调设备,节能制热设备...等的研发生产"}],"status":"ACTIVE"},
    {"exposure_id":"exp_bl_compressor","company_id":"bingshan_env","node_id":"refrigeration_compressor","activity_type":"manufacture","role":"制冷压缩机制造商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"冰轮环境 主营业务","quote":"低温冷冻设备...制冷压缩机"}],"status":"ACTIVE"},
    {"exposure_id":"exp_sxj_cigarette","company_id":"shaanxi_jinye","node_id":"cigarette_packaging","activity_type":"manufacture","role":"烟标包装制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"陕西金叶 主营业务","quote":"主要业务:烟标印刷及包装材料的研发生产"}],"status":"ACTIVE"},
    {"exposure_id":"exp_dz_pharm","company_id":"dezhan_health","node_id":"pharmaceutical_product","activity_type":"manufacture","role":"药品制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"德展健康 主营业务","quote":"主要业务:化学药,原料药,生物制药,保健品的研发,生产和销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_mly_paper","company_id":"meili_cloud","node_id":"paper_product","activity_type":"produce","role":"造纸生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"美利云 主营业务","quote":"主要业务:造纸,数据中心业务"}],"status":"ACTIVE"},
    {"exposure_id":"exp_mly_dc","company_id":"meili_cloud","node_id":"data_center_service","activity_type":"operate","role":"数据中心服务商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"美利云 主营业务","quote":"主要业务:造纸,数据中心业务"}],"status":"ACTIVE"},
    {"exposure_id":"exp_zn_diesel","company_id":"smart_agri","node_id":"diesel_engine","activity_type":"manufacture","role":"柴油发动机制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"智慧农业 主营业务","quote":"主要业务:内燃机及终端产品的研发生产和销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_zn_agri_mach","company_id":"smart_agri","node_id":"agricultural_machinery","activity_type":"manufacture","role":"农业机械制造商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"智慧农业 主营业务","quote":"内燃机及终端产品的研发生产和销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_hjt_e_chem","company_id":"hangjin_tech","node_id":"electronic_chemical","activity_type":"produce","role":"电子化学品生产商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"航锦科技 主营业务","quote":"电子业务主要产品为特种芯片,FPGA芯片..."}],"status":"ACTIVE"},
    {"exposure_id":"exp_hjt_special_chem","company_id":"hangjin_tech","node_id":"special_chemical","activity_type":"produce","role":"特种化工产品生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"航锦科技 主营业务","quote":"化工业务主要产品为烧碱,环氧丙烷,聚醚"}],"status":"ACTIVE"},
    {"exposure_id":"exp_hjt_ic_design","company_id":"hangjin_tech","node_id":"ic_design","activity_type":"operate","role":"集成电路设计服务商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"航锦科技 主营业务","quote":"电子业务主要产品为特种芯片,FPGA芯片,总线接口芯片,微控制器等"}],"status":"ACTIVE"},
    {"exposure_id":"exp_yy_oil","company_id":"yueyang_xingchang","node_id":"refined_oil","activity_type":"produce","role":"石化产品生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"岳阳兴长 主营业务","quote":"主要业务:石油化工产品的生产,销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_yy_methanol","company_id":"yueyang_xingchang","node_id":"methanol","activity_type":"produce","role":"甲醇生产商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"岳阳兴长 主营业务","quote":"主要业务:石油化工产品的生产,销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_yy_lpg","company_id":"yueyang_xingchang","node_id":"lp_gas","activity_type":"produce","role":"液化石油气生产商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"岳阳兴长 主营业务","quote":"主要业务:石油化工产品的生产,销售"}],"status":"ACTIVE"}
]

if __name__ == "__main__":
    gb = {"batch_id":"batch_030_graph","task_description":"Batch 030: Industrial nodes and edges for 10 companies (000807-000819). Focus on aluminum smelting, wind power, digital TV/set-top box, refrigeration, cigarette packaging, pharmaceuticals, paper/data center, diesel engines/ farm machinery, specialty chemicals/IC design, petrochemicals.","nodes_to_upsert":nodes,"edges_to_upsert":edges,"rejected_or_pending":[]}
    bb = {"batch_id":"batch_030_business","task_description":"Batch 030: Company registrations and exposures for 10 companies (000807-000819).","industries_to_upsert":[],"industry_node_mappings_to_upsert":[],"companies_to_upsert":companies,"company_node_exposures_to_upsert":exposures}
    r1 = submit_graph(gb); print(f"Graph: {r1.status_code}", r1.json())
    r2 = submit_business(bb); print(f"Business: {r2.status_code}", r2.json())
