#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json, subprocess, os, sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLI_PATH = os.path.join(BASE_DIR, "cli", "arachne_cli.py")
PY = os.path.join(BASE_DIR, "backend", "venv", "Scripts", "python.exe")

def ev(source_title, quote="根据企业公开信息"):
    return [{"source_title": source_title, "source_url": None, "quote": quote}]

NODES = [
    {"node_id": "electromagnetic_flowmeter", "canonical_name_zh": "电磁流量计", "canonical_name_en": "electromagnetic flowmeter", "entity_type": "device", "aliases": [], "definition": "利用电磁感应原理测量导电液体体积流量的仪表", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("威尔泰主营业务")},
    {"node_id": "pressure_transmitter", "canonical_name_zh": "压力变送器", "canonical_name_en": "pressure transmitter", "entity_type": "device", "aliases": [], "definition": "将压力信号转换为标准电信号输出的测量仪表", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("威尔泰主营业务")},
    {"node_id": "automation_instrument", "canonical_name_zh": "自动化仪器仪表", "canonical_name_en": "automation instrument", "entity_type": "device", "aliases": [], "definition": "用于工业过程自动化测量、控制和显示的各类仪表设备", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("威尔泰主营业务")},
    {"node_id": "new_membrane_material", "canonical_name_zh": "新型膜材料", "canonical_name_en": "new membrane material", "entity_type": "material", "aliases": [], "definition": "具有分离、过滤等功能的新型高分子薄膜材料", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("威尔泰经营范围")},
    {"node_id": "scenic_spot", "canonical_name_zh": "景区景点", "canonical_name_en": "scenic spot", "entity_type": "infrastructure", "aliases": [], "definition": "具有观赏、文化或科学价值，可供游览的自然或人文景观区域", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("云南旅游主营业务")},
    {"node_id": "tourism_service", "canonical_name_zh": "旅游服务", "canonical_name_en": "tourism service", "entity_type": "service", "aliases": [], "definition": "为旅游者提供导游、交通、餐饮、住宿等配套服务的经营活动", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("云南旅游经营范围")},
    {"node_id": "wedding_service", "canonical_name_zh": "婚庆服务", "canonical_name_en": "wedding service", "entity_type": "service", "aliases": [], "definition": "为婚礼提供策划、场地、礼仪等服务的经营活动", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("云南旅游经营范围")},
    {"node_id": "convention_exhibition", "canonical_name_zh": "会展", "canonical_name_en": "convention and exhibition", "entity_type": "service", "aliases": [], "definition": "会议和展览活动的组织与服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("云南旅游经营范围")},
    {"node_id": "railway_transport", "canonical_name_zh": "铁路运输", "canonical_name_en": "railway transport", "entity_type": "service", "aliases": [], "definition": "利用铁路线路和机车车辆运送旅客和货物的运输方式", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("大秦铁路主营业务")},
    {"node_id": "coal_transportation", "canonical_name_zh": "煤炭运输", "canonical_name_en": "coal transportation", "entity_type": "service", "aliases": [], "definition": "利用铁路、公路、水路等方式将煤炭从产地运往消费地的运输活动", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("大秦铁路主营业务")},
    {"node_id": "water_conservancy_project", "canonical_name_zh": "水利水电工程", "canonical_name_en": "water conservancy and hydropower project", "entity_type": "service", "aliases": [], "definition": "以开发、利用、控制和调配水资源为目的的工程建设活动", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("广东建工主营业务")},
    {"node_id": "municipal_engineering", "canonical_name_zh": "市政工程", "canonical_name_en": "municipal engineering", "entity_type": "service", "aliases": [], "definition": "城市基础设施建设工程，包括道路、桥梁、给排水、燃气、供热等", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("广东建工主营业务")},
    {"node_id": "road_engineering", "canonical_name_zh": "公路工程", "canonical_name_en": "road engineering", "entity_type": "service", "aliases": [], "definition": "公路及其附属设施的新建、改建、扩建和养护工程", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("广东建工主营业务")},
    {"node_id": "electromechanical_installation", "canonical_name_zh": "机电安装工程", "canonical_name_en": "electromechanical installation", "entity_type": "service", "aliases": [], "definition": "机械设备、电气设备、自动化仪表等的安装调试工程", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("广东建工经营范围")},
    {"node_id": "wind_power_generation", "canonical_name_zh": "风力发电", "canonical_name_en": "wind power generation", "entity_type": "service", "aliases": [], "definition": "利用风力发电机组将风能转化为电能的发电方式", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("广东建工经营范围")},
    {"node_id": "solar_power", "canonical_name_zh": "太阳能发电", "canonical_name_en": "solar power", "entity_type": "service", "aliases": [], "definition": "利用光伏或光热技术将太阳能转化为电能的发电方式", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("广东建工经营范围")},
    {"node_id": "urban_rail_transit", "canonical_name_zh": "城市轨道交通", "canonical_name_en": "urban rail transit", "entity_type": "infrastructure", "aliases": [], "definition": "在城市范围内采用轨道结构进行运输的公共交通系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("浙江交科经营范围")},
    {"node_id": "harbor_waterway_engineering", "canonical_name_zh": "港航工程", "canonical_name_en": "harbor and waterway engineering", "entity_type": "service", "aliases": [], "definition": "港口、航道、码头等水运基础设施的建设工程", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("浙江交科经营范围")},
    {"node_id": "airport_engineering", "canonical_name_zh": "机场工程", "canonical_name_en": "airport engineering", "entity_type": "service", "aliases": [], "definition": "民用机场飞行区、航站区等基础设施的建设工程", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("浙江交科经营范围")},
    {"node_id": "dangerous_chemical", "canonical_name_zh": "危险化学品", "canonical_name_en": "dangerous chemical", "entity_type": "material", "aliases": [], "definition": "具有毒害、腐蚀、爆炸、燃烧、助燃等性质，对人体、设施、环境具有危害的化学品", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("浙江交科经营范围")},
    {"node_id": "foundation_engineering", "canonical_name_zh": "地基与基础工程", "canonical_name_en": "foundation engineering", "entity_type": "service", "aliases": [], "definition": "建筑物地基处理和基础施工的专业工程", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("宏润建设经营范围")},
    {"node_id": "steel_structure_engineering", "canonical_name_zh": "钢结构工程", "canonical_name_en": "steel structure engineering", "entity_type": "service", "aliases": [], "definition": "以钢材为主要材料建造建筑物或构筑物的工程", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("宏润建设经营范围")},
    {"node_id": "bridge_engineering", "canonical_name_zh": "桥梁工程", "canonical_name_en": "bridge engineering", "entity_type": "service", "aliases": [], "definition": "桥梁及其附属设施的新建、改建、扩建和养护工程", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("宏润建设经营范围")},
    {"node_id": "power_industry_software", "canonical_name_zh": "电力行业软件", "canonical_name_en": "power industry software", "entity_type": "material", "aliases": [], "definition": "专门为电力行业开发的管理、控制和信息系统软件", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("远光软件主营业务")},
    {"node_id": "financial_management_software", "canonical_name_zh": "财务管理软件", "canonical_name_en": "financial management software", "entity_type": "material", "aliases": [], "definition": "用于企业财务核算、预算、分析等管理活动的软件系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("远光软件主营业务")},
    {"node_id": "spandex", "canonical_name_zh": "氨纶", "canonical_name_en": "spandex", "entity_type": "material", "aliases": ["lycra", "elastane"], "definition": "聚氨酯类合成纤维，具有高弹性，广泛用于弹性织物", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("华峰化学主营业务")},
    {"node_id": "industry_application_software", "canonical_name_zh": "行业应用软件", "canonical_name_en": "industry application software", "entity_type": "material", "aliases": [], "definition": "针对特定行业需求开发的应用软件系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("东华软件主营业务")},
    {"node_id": "system_integration", "canonical_name_zh": "系统集成", "canonical_name_en": "system integration", "entity_type": "service", "aliases": [], "definition": "将计算机软件、硬件、网络通信等技术和产品集成为能够满足用户特定需求的信息系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("东华软件主营业务")},
    {"node_id": "artificial_intelligence", "canonical_name_zh": "人工智能", "canonical_name_en": "artificial intelligence", "entity_type": "technology_capability", "aliases": ["AI"], "definition": "研究、开发用于模拟、延伸和扩展人类智能的理论、方法、技术及应用系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("东华软件经营范围")},
    {"node_id": "refractory_material", "canonical_name_zh": "耐火材料", "canonical_name_en": "refractory material", "entity_type": "material", "aliases": [], "definition": "耐火度不低于1580℃的无机非金属材料，用于高温工业窑炉内衬", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("瑞泰科技主营业务")},
    {"node_id": "fused_cast_zirconia_corundum", "canonical_name_zh": "熔铸锆刚玉", "canonical_name_en": "fused cast zirconia corundum", "entity_type": "material", "aliases": [], "definition": "以氧化铝和氧化锆为主要原料经电熔铸造成型的耐火材料", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("瑞泰科技主营业务")},
    {"node_id": "fused_cast_alumina", "canonical_name_zh": "熔铸氧化铝", "canonical_name_en": "fused cast alumina", "entity_type": "material", "aliases": [], "definition": "以氧化铝为主要原料经电熔铸造成型的耐火材料", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("瑞泰科技主营业务")},
    {"node_id": "inorganic_non_metallic_material", "canonical_name_zh": "无机非金属材料", "canonical_name_en": "inorganic non-metallic material", "entity_type": "material", "aliases": [], "definition": "以某些元素的氧化物、碳化物、氮化物等为主要成分的材料，包括陶瓷、玻璃、耐火材料等", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("瑞泰科技经营范围")},
]

EDGES = [
    {"edge_id": "electromagnetic_flowmeter_automation_instrument", "from_node": "electromagnetic_flowmeter", "to_node": "automation_instrument", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "电磁流量计是自动化仪器仪表的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "pressure_transmitter_automation_instrument", "from_node": "pressure_transmitter", "to_node": "automation_instrument", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "压力变送器是自动化仪器仪表的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "new_membrane_material_new_material", "from_node": "new_membrane_material", "to_node": "new_material", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "新型膜材料属于新材料范畴", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "tourism_service_scenic_spot", "from_node": "tourism_service", "to_node": "scenic_spot", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "旅游服务依托景区景点开展", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "wedding_service_tourism_service", "from_node": "wedding_service", "to_node": "tourism_service", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "婚庆服务属于旅游服务的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "convention_exhibition_tourism_service", "from_node": "convention_exhibition", "to_node": "tourism_service", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "会展服务属于旅游服务的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "coal_transportation_railway_transport", "from_node": "coal_transportation", "to_node": "railway_transport", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "煤炭运输是铁路运输的重要业务", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "railway_transport_railway_project", "from_node": "railway_transport", "to_node": "railway_project", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "铁路运输依托铁路项目开展", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "water_conservancy_project_construction_engineering", "from_node": "water_conservancy_project", "to_node": "construction_engineering", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "水利水电工程属于建筑工程", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "municipal_engineering_construction_engineering", "from_node": "municipal_engineering", "to_node": "construction_engineering", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "市政工程属于建筑工程", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "road_engineering_construction_engineering", "from_node": "road_engineering", "to_node": "construction_engineering", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "公路工程属于建筑工程", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "electromechanical_installation_construction_engineering", "from_node": "electromechanical_installation", "to_node": "construction_engineering", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "机电安装工程属于建筑工程", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "wind_power_generation_renewable_energy_power_generation", "from_node": "wind_power_generation", "to_node": "renewable_energy_power_generation", "edge_namespace": "industrial_flow", "edge_type": "energy_flow", "description": "风力发电属于可再生能源发电", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "solar_power_renewable_energy_power_generation", "from_node": "solar_power", "to_node": "renewable_energy_power_generation", "edge_namespace": "industrial_flow", "edge_type": "energy_flow", "description": "太阳能发电属于可再生能源发电", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "urban_rail_transit_construction_engineering", "from_node": "urban_rail_transit", "to_node": "construction_engineering", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "城市轨道交通工程属于建筑工程", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "harbor_waterway_engineering_construction_engineering", "from_node": "harbor_waterway_engineering", "to_node": "construction_engineering", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "港航工程属于建筑工程", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "airport_engineering_construction_engineering", "from_node": "airport_engineering", "to_node": "construction_engineering", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "机场工程属于建筑工程", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "dangerous_chemical_chemical_product", "from_node": "dangerous_chemical", "to_node": "chemical_product", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "危险化学品是化工产品的一类", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "foundation_engineering_construction_engineering", "from_node": "foundation_engineering", "to_node": "construction_engineering", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "地基与基础工程属于建筑工程", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "steel_structure_engineering_construction_engineering", "from_node": "steel_structure_engineering", "to_node": "construction_engineering", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "钢结构工程属于建筑工程", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "bridge_engineering_construction_engineering", "from_node": "bridge_engineering", "to_node": "construction_engineering", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "桥梁工程属于建筑工程", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "power_industry_software_software_development_service", "from_node": "power_industry_software", "to_node": "software_development_service", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "电力行业软件是软件开发服务的产品", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "financial_management_software_software_development_service", "from_node": "financial_management_software", "to_node": "software_development_service", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "财务管理软件是软件开发服务的产品", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "spandex_synthetic_fiber", "from_node": "spandex", "to_node": "synthetic_fiber", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "氨纶是合成纤维的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "industry_application_software_software_development_service", "from_node": "industry_application_software", "to_node": "software_development_service", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "行业应用软件是软件开发服务的产品", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "system_integration_information_technology_service", "from_node": "system_integration", "to_node": "information_technology_service", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "系统集成属于信息技术服务", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "artificial_intelligence_information_technology_service", "from_node": "artificial_intelligence", "to_node": "information_technology_service", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "人工智能属于信息技术服务", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "fused_cast_zirconia_corundum_refractory_material", "from_node": "fused_cast_zirconia_corundum", "to_node": "refractory_material", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "熔铸锆刚玉是耐火材料的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "fused_cast_alumina_refractory_material", "from_node": "fused_cast_alumina", "to_node": "refractory_material", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "熔铸氧化铝是耐火材料的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "refractory_material_inorganic_non_metallic_material", "from_node": "refractory_material", "to_node": "inorganic_non_metallic_material", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "耐火材料是无机非金属材料的一类", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
]

BUSINESS = {
    "batch_id": "batch_120_business",
    "task_description": "Batch 120 business registration for 10 A-share companies",
    "companies_to_upsert": [
        {"company_id": "sz_002058", "name_zh": "威尔泰", "name_en": "Shanghai Welltech Automation Co., Ltd.", "country": "CN", "province": "上海", "city": "上海市", "stock_codes": ["002058.SZ"], "description": "自动化仪器仪表的研发、生产和销售", "founded_year": 1992, "employee_count": 315},
        {"company_id": "sz_002059", "name_zh": "云南旅游", "name_en": "Yunnan Tourism Co., Ltd.", "country": "CN", "province": "云南", "city": "昆明市", "stock_codes": ["002059.SZ"], "description": "景区景点的投资、经营及管理，旅游服务、餐饮、婚庆、会展", "founded_year": 2000, "employee_count": 894},
        {"company_id": "sh_601006", "name_zh": "大秦铁路", "name_en": "Daqin Railway Co., Ltd.", "country": "CN", "province": "山西", "city": "大同市", "stock_codes": ["601006.SH"], "description": "煤炭运输及铁路客货运输", "founded_year": 2004, "employee_count": 88072},
        {"company_id": "sz_002060", "name_zh": "广东建工", "name_en": "Guangdong Construction Engineering Group Co., Ltd.", "country": "CN", "province": "广东", "city": "广州市", "stock_codes": ["002060.SZ"], "description": "水利水电工程、市政工程、公路工程、机电安装工程等", "founded_year": 2001, "employee_count": 16529},
        {"company_id": "sz_002061", "name_zh": "浙江交科", "name_en": "Zhejiang Communications Technology Co., Ltd.", "country": "CN", "province": "浙江", "city": "衢州市", "stock_codes": ["002061.SZ"], "description": "公路工程、市政工程、城市轨道工程、铁路工程、港航工程、机场工程", "founded_year": 1998, "employee_count": 7955},
        {"company_id": "sz_002062", "name_zh": "宏润建设", "name_en": "Hongrun Construction Group Co., Ltd.", "country": "CN", "province": "浙江", "city": "宁波市", "stock_codes": ["002062.SZ"], "description": "市政公用工程、房屋建筑工程、地基与基础工程、钢结构工程、公路工程、桥梁工程", "founded_year": 1994, "employee_count": 2150},
        {"company_id": "sz_002063", "name_zh": "远光软件", "name_en": "YGSoft Co., Ltd.", "country": "CN", "province": "广东", "city": "珠海市", "stock_codes": ["002063.SZ"], "description": "电力行业财务和管理软件的开发与销售", "founded_year": 1998, "employee_count": 4136},
        {"company_id": "sz_002064", "name_zh": "华峰化学", "name_en": "Huafon Chemical Co., Ltd.", "country": "CN", "province": "浙江", "city": "温州市", "stock_codes": ["002064.SZ"], "description": "氨纶系列产品的生产", "founded_year": 1999, "employee_count": 8658},
        {"company_id": "sz_002065", "name_zh": "东华软件", "name_en": "DHC Software Co., Ltd.", "country": "CN", "province": "北京", "city": "北京市", "stock_codes": ["002065.SZ"], "description": "行业应用软件、计算机信息系统集成及相关服务", "founded_year": 2001, "employee_count": 10757},
        {"company_id": "sz_002066", "name_zh": "瑞泰科技", "name_en": "Ruitai Materials Technology Co., Ltd.", "country": "CN", "province": "北京", "city": "北京市", "stock_codes": ["002066.SZ"], "description": "熔铸耐火材料的研发、生产和销售", "founded_year": 2001, "employee_count": 2534},
    ],
    "company_node_exposures_to_upsert": [
        {"exposure_id": "sz_002058_produce_electromagnetic_flowmeter", "company_id": "sz_002058", "node_id": "electromagnetic_flowmeter", "activity_type": "produce", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:电磁流量计")},
        {"exposure_id": "sz_002058_produce_pressure_transmitter", "company_id": "sz_002058", "node_id": "pressure_transmitter", "activity_type": "produce", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:压力变送器")},
        {"exposure_id": "sz_002058_produce_automation_instrument", "company_id": "sz_002058", "node_id": "automation_instrument", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:自动化仪器仪表")},
        {"exposure_id": "sz_002058_produce_electronic_special_material", "company_id": "sz_002058", "node_id": "electronic_special_material", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:电子专用材料")},
        {"exposure_id": "sz_002058_produce_new_membrane_material", "company_id": "sz_002058", "node_id": "new_membrane_material", "activity_type": "produce", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:新型膜材料")},
        {"exposure_id": "sz_002059_operate_scenic_spot", "company_id": "sz_002059", "node_id": "scenic_spot", "activity_type": "operate", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:景区景点投资经营")},
        {"exposure_id": "sz_002059_provide_service_tourism_service", "company_id": "sz_002059", "node_id": "tourism_service", "activity_type": "provide_service", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:旅游服务")},
        {"exposure_id": "sz_002059_operate_catering_service", "company_id": "sz_002059", "node_id": "catering_service", "activity_type": "operate", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:餐饮服务")},
        {"exposure_id": "sz_002059_provide_service_wedding_service", "company_id": "sz_002059", "node_id": "wedding_service", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:婚庆服务")},
        {"exposure_id": "sz_002059_provide_service_convention_exhibition", "company_id": "sz_002059", "node_id": "convention_exhibition", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:会展")},
        {"exposure_id": "sz_002059_provide_service_technical_service", "company_id": "sz_002059", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术咨询")},
        {"exposure_id": "sh_601006_operate_railway_transport", "company_id": "sh_601006", "node_id": "railway_transport", "activity_type": "operate", "weight": 0.40, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:铁路运输")},
        {"exposure_id": "sh_601006_provide_service_coal_transportation", "company_id": "sh_601006", "node_id": "coal_transportation", "activity_type": "provide_service", "weight": 0.35, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:煤炭运输")},
        {"exposure_id": "sh_601006_provide_service_railway_project", "company_id": "sh_601006", "node_id": "railway_project", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:铁路设备设施制造安装维修")},
        {"exposure_id": "sh_601006_provide_service_logistics", "company_id": "sh_601006", "node_id": "logistics", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:物流服务")},
        {"exposure_id": "sz_002060_provide_service_water_conservancy_project", "company_id": "sz_002060", "node_id": "water_conservancy_project", "activity_type": "provide_service", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:水利水电工程")},
        {"exposure_id": "sz_002060_provide_service_municipal_engineering", "company_id": "sz_002060", "node_id": "municipal_engineering", "activity_type": "provide_service", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:市政工程")},
        {"exposure_id": "sz_002060_provide_service_road_engineering", "company_id": "sz_002060", "node_id": "road_engineering", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:公路工程")},
        {"exposure_id": "sz_002060_provide_service_electromechanical_installation", "company_id": "sz_002060", "node_id": "electromechanical_installation", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:机电安装工程")},
        {"exposure_id": "sz_002060_provide_service_construction_engineering", "company_id": "sz_002060", "node_id": "construction_engineering", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:建设工程施工")},
        {"exposure_id": "sz_002060_operate_wind_power_generation", "company_id": "sz_002060", "node_id": "wind_power_generation", "activity_type": "operate", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:风力发电技术服务")},
        {"exposure_id": "sz_002060_operate_solar_power", "company_id": "sz_002060", "node_id": "solar_power", "activity_type": "operate", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:太阳能发电技术服务")},
        {"exposure_id": "sz_002061_provide_service_road_engineering", "company_id": "sz_002061", "node_id": "road_engineering", "activity_type": "provide_service", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:公路工程")},
        {"exposure_id": "sz_002061_provide_service_municipal_engineering", "company_id": "sz_002061", "node_id": "municipal_engineering", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:市政工程")},
        {"exposure_id": "sz_002061_provide_service_urban_rail_transit", "company_id": "sz_002061", "node_id": "urban_rail_transit", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:城市轨道工程")},
        {"exposure_id": "sz_002061_provide_service_harbor_waterway_engineering", "company_id": "sz_002061", "node_id": "harbor_waterway_engineering", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:港航工程")},
        {"exposure_id": "sz_002061_provide_service_airport_engineering", "company_id": "sz_002061", "node_id": "airport_engineering", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:机场工程")},
        {"exposure_id": "sz_002061_produce_chemical_product", "company_id": "sz_002061", "node_id": "chemical_product", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:化工产品开发生产销售")},
        {"exposure_id": "sz_002061_produce_dangerous_chemical", "company_id": "sz_002061", "node_id": "dangerous_chemical", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:危险化学品生产")},
        {"exposure_id": "sz_002061_provide_service_construction_engineering", "company_id": "sz_002061", "node_id": "construction_engineering", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:建设工程施工")},
        {"exposure_id": "sz_002062_provide_service_construction_engineering", "company_id": "sz_002062", "node_id": "construction_engineering", "activity_type": "provide_service", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:市政公用工程房屋建筑工程")},
        {"exposure_id": "sz_002062_provide_service_foundation_engineering", "company_id": "sz_002062", "node_id": "foundation_engineering", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:地基与基础工程")},
        {"exposure_id": "sz_002062_provide_service_steel_structure_engineering", "company_id": "sz_002062", "node_id": "steel_structure_engineering", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:钢结构工程")},
        {"exposure_id": "sz_002062_provide_service_road_engineering", "company_id": "sz_002062", "node_id": "road_engineering", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:公路工程")},
        {"exposure_id": "sz_002062_provide_service_bridge_engineering", "company_id": "sz_002062", "node_id": "bridge_engineering", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:桥梁工程")},
        {"exposure_id": "sz_002062_provide_service_urban_rail_transit", "company_id": "sz_002062", "node_id": "urban_rail_transit", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:城市轨道交通工程")},
        {"exposure_id": "sz_002062_provide_service_real_estate_development", "company_id": "sz_002062", "node_id": "real_estate_development", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:房地产开发经营")},
        {"exposure_id": "sz_002063_produce_power_industry_software", "company_id": "sz_002063", "node_id": "power_industry_software", "activity_type": "produce", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:电力行业财务和管理软件")},
        {"exposure_id": "sz_002063_produce_financial_management_software", "company_id": "sz_002063", "node_id": "financial_management_software", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:财务管理软件")},
        {"exposure_id": "sz_002063_produce_software_development_service", "company_id": "sz_002063", "node_id": "software_development_service", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:软件开发")},
        {"exposure_id": "sz_002063_provide_service_system_integration", "company_id": "sz_002063", "node_id": "system_integration", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:信息系统集成服务")},
        {"exposure_id": "sz_002063_provide_service_technical_service", "company_id": "sz_002063", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术服务")},
        {"exposure_id": "sz_002064_produce_spandex", "company_id": "sz_002064", "node_id": "spandex", "activity_type": "produce", "weight": 0.50, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:氨纶系列产品")},
        {"exposure_id": "sz_002064_produce_synthetic_fiber", "company_id": "sz_002064", "node_id": "synthetic_fiber", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:合成纤维")},
        {"exposure_id": "sz_002064_produce_synthetic_resin", "company_id": "sz_002064", "node_id": "synthetic_resin", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:合成材料")},
        {"exposure_id": "sz_002064_produce_chemical_product", "company_id": "sz_002064", "node_id": "chemical_product", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:化工产品")},
        {"exposure_id": "sz_002065_produce_industry_application_software", "company_id": "sz_002065", "node_id": "industry_application_software", "activity_type": "produce", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:行业应用软件")},
        {"exposure_id": "sz_002065_provide_service_system_integration", "company_id": "sz_002065", "node_id": "system_integration", "activity_type": "provide_service", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:计算机信息系统集成")},
        {"exposure_id": "sz_002065_produce_software_development_service", "company_id": "sz_002065", "node_id": "software_development_service", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:软件开发")},
        {"exposure_id": "sz_002065_provide_service_artificial_intelligence", "company_id": "sz_002065", "node_id": "artificial_intelligence", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:人工智能应用软件开发")},
        {"exposure_id": "sz_002065_provide_service_technical_service", "company_id": "sz_002065", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术服务")},
        {"exposure_id": "sz_002066_produce_refractory_material", "company_id": "sz_002066", "node_id": "refractory_material", "activity_type": "produce", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:耐火材料")},
        {"exposure_id": "sz_002066_produce_fused_cast_zirconia_corundum", "company_id": "sz_002066", "node_id": "fused_cast_zirconia_corundum", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:熔铸锆刚玉")},
        {"exposure_id": "sz_002066_produce_fused_cast_alumina", "company_id": "sz_002066", "node_id": "fused_cast_alumina", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:熔铸氧化铝")},
        {"exposure_id": "sz_002066_produce_inorganic_non_metallic_material", "company_id": "sz_002066", "node_id": "inorganic_non_metallic_material", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:无机非金属材料")},
    ],
    "industries_to_upsert": [],
    "industry_node_mappings_to_upsert": [],
}

def submit():
    batch = {"batch_id": "batch_120_nodes", "task_description": "Batch 120 industrial nodes and edges", "nodes_to_upsert": NODES, "edges_to_upsert": EDGES}
    path = os.path.join(BASE_DIR, "tmp_script", "batch_120_nodes.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(batch, f, ensure_ascii=False, indent=2)
    r1 = subprocess.run([PY, CLI_PATH, "submit", path], capture_output=True, text=True)
    print("[GRAPH]", r1.stdout[:500], r1.stderr[:500])

    path2 = os.path.join(BASE_DIR, "tmp_script", "batch_120_business.json")
    with open(path2, "w", encoding="utf-8") as f:
        json.dump(BUSINESS, f, ensure_ascii=False, indent=2)
    r2 = subprocess.run([PY, CLI_PATH, "business-batch", path2], capture_output=True, text=True)
    print("[BUSINESS]", r2.stdout[:500], r2.stderr[:500])

if __name__ == "__main__":
    submit()
