#!/usr/bin/env python3
"""Batch 026 Submission Script (000737-000757)"""
import json, requests
BASE_URL = "http://localhost:8000/api/v1"
submit_graph = lambda b: requests.post(f"{BASE_URL}/batches", json=b)
submit_business = lambda b: requests.post(f"{BASE_URL}/business-batches", json=b)

nodes = [
    {"node_id":"sodium_sulfate","canonical_name_zh":"元明粉","canonical_name_en":"Sodium Sulfate","aliases":["无水硫酸钠","芒硝"],"definition":"化学式为Na₂SO₄的白色结晶粉末，是重要的基础化工原料，广泛用于洗涤剂填充剂、玻璃制造、造纸、印染及元明粉生产。","entity_type":"material","evidence":[{"source_title":"北方铜业 主营业务","quote":"主要产品:元明粉,硫化碱,硫酸钡和硫酸镁"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"sodium_sulfide","canonical_name_zh":"硫化碱","canonical_name_en":"Sodium Sulfide","aliases":["硫化钠","臭碱"],"definition":"化学式为Na₂S的无机化合物，呈强碱性，广泛用于染料中间体、皮革脱毛剂、造纸、矿物浮选及金属冶炼辅助剂。","entity_type":"material","evidence":[{"source_title":"北方铜业 主营业务","quote":"主要产品:元明粉,硫化碱,硫酸钡和硫酸镁"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"barium_sulfate","canonical_name_zh":"硫酸钡","canonical_name_en":"Barium Sulfate","aliases":["重晶石粉","钡白"],"definition":"化学式为BaSO₄的白色无定形粉末，不溶于水和酸，主要用作钻井泥浆加重剂、涂料填料、X光造影剂及橡胶塑料填充料。","entity_type":"material","evidence":[{"source_title":"北方铜业 主营业务","quote":"主要产品:元明粉,硫化碱,硫酸钡和硫酸镁"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"magnesium_sulfate","canonical_name_zh":"硫酸镁","canonical_name_en":"Magnesium Sulfate","aliases":["泻盐","苦盐"],"definition":"化学式为MgSO₄的无机盐，常以七水合物（泻盐）形式存在，用于医药泻剂、肥料、饲料添加剂、印染媒染剂及防火材料。","entity_type":"material","evidence":[{"source_title":"北方铜业 主营业务","quote":"主要产品:元明粉,硫化碱,硫酸钡和硫酸镁"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"engine_control_system","canonical_name_zh":"发动机控制系统","canonical_name_en":"Engine Control System","aliases":["ECU系统","发动机电控系统"],"definition":"用于控制航空发动机、汽车发动机等动力装置运行状态的机电子系统，包括燃油调节、状态监测、故障诊断、推力/功率管理等核心功能模块。","entity_type":"subsystem","evidence":[{"source_title":"航发控制 主营业务","quote":"主要产品:发动机控制系统及部件,国际合作和非航产品"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"aero_engine_part","canonical_name_zh":"航空发动机零部件","canonical_name_en":"Aero Engine Part","aliases":["航发零部件","发动机精密件"],"definition":"用于航空发动机内部的精密机械零件，包括涡轮叶片、燃烧室组件、燃油喷嘴、轴承座等，需在高温、高压、高转速极端工况下可靠工作。","entity_type":"component","evidence":[{"source_title":"航发控制 主营业务","quote":"主要产品:发动机控制系统及部件"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"benzene_refining_product","canonical_name_zh":"苯精制化工产品","canonical_name_en":"Benzene Refining Chemical Product","aliases":["苯系化工品","芳烃衍生物"],"definition":"以粗苯或煤焦油为原料，经蒸馏、萃取、加氢等精制工艺制得的苯类化工产品，包括纯苯、甲苯、二甲苯及下游衍生物，是染料、医药、农药和合成材料的重要原料。","entity_type":"material","evidence":[{"source_title":"山西高速 主营业务","quote":"主要产品:胶粘剂系列产品,苯精制系列化工产品"}],"confidence":"HIGH","status":"ACTIVE"}
]

edges = [
    {"edge_id":"flow_engine_ctrl_to_auto_engine","from_node":"engine_control_system","to_node":"automotive_engine","description":"发动机控制系统作为核心子系统嵌入汽车发动机，实现燃油喷射、点火正时与排放控制。","edge_namespace":"industrial_flow","edge_type":"composition","evidence":[{"source_title":"航发控制 主营业务","quote":"主要产品:发动机控制系统及部件"}],"confidence":"HIGH"},
    {"edge_id":"flow_aero_part_to_aircraft","from_node":"aero_engine_part","to_node":"aircraft","description":"航空发动机零部件装配于航空器动力系统，是飞机动力装置的核心构成件。","edge_namespace":"industrial_flow","edge_type":"composition","evidence":[{"source_title":"航发控制 主营业务","quote":"主要产品:发动机控制系统及部件,国际合作和非航产品"}],"confidence":"HIGH"}
]

companies = [
    {"company_id":"northern_copper","name_zh":"北方铜业股份有限公司","aliases":["北方铜业"],"stock_codes":["000737.SZ"],"description":"主要产品包括元明粉、硫化碱、硫酸钡、硫酸镁等化工产品，同时从事铜冶炼及有色金属压延加工。","country":"CN","province":"山西","city":"运城市","founded_year":1996,"employee_count":7324,"company_type":"public","status":"ACTIVE"},
    {"company_id":"aeroengine_control","name_zh":"中国航发动力控制股份有限公司","aliases":["航发控制"],"stock_codes":["000738.SZ"],"description":"主要产品为发动机控制系统及部件、国际合作和非航产品，服务于航空发动机及行走机械动力控制领域。","country":"CN","province":"江苏","city":"无锡市","founded_year":1997,"employee_count":7144,"company_type":"public","status":"ACTIVE"},
    {"company_id":"pulo_pharmaceutical","name_zh":"普洛药业股份有限公司","aliases":["普洛药业"],"stock_codes":["000739.SZ"],"description":"主要产品为原料药和制剂，从事医药行业的投资、研发、生产和销售。","country":"CN","province":"浙江","city":"金华市","founded_year":1997,"employee_count":6787,"company_type":"public","status":"ACTIVE"},
    {"company_id":"guohai_securities","name_zh":"国海证券股份有限公司","aliases":["国海证券"],"stock_codes":["000750.SZ"],"description":"主营业务为客户提供证券代理买卖、证券发行与承销、收购兼并、资产重组、财务顾问、资产管理、投资咨询等综合金融服务。","country":"CN","province":"广西","city":"桂林市","founded_year":1993,"employee_count":3364,"company_type":"public","status":"ACTIVE"},
    {"company_id":"zinc_industry","name_zh":"葫芦岛锌业股份有限公司","aliases":["锌业股份"],"stock_codes":["000751.SZ"],"description":"主要产品为锌、铅等有色金属冶炼及深加工产品，同时综合回收镉、铟、金、银、铋等副产品。","country":"CN","province":"辽宁","city":"葫芦岛市","founded_year":1992,"employee_count":5341,"company_type":"public","status":"ACTIVE"},
    {"company_id":"st_xifa","name_zh":"西藏发展股份有限公司","aliases":["*ST西发","西藏发展"],"stock_codes":["000752.SZ"],"description":"主要产品为啤酒，同时涉及饲料、养殖业、藏红花系列产品开发及高新技术产业投资。","country":"CN","province":"西藏","city":"拉萨市","founded_year":1997,"employee_count":256,"company_type":"public","status":"ACTIVE"},
    {"company_id":"zhangzhou_development","name_zh":"福建漳州发展股份有限公司","aliases":["漳州发展"],"stock_codes":["000753.SZ"],"description":"主要业务包括公路经营、自来水销售、废弃物处理等城市基础设施运营。","country":"CN","province":"福建","city":"漳州市","founded_year":1994,"employee_count":1654,"company_type":"public","status":"ACTIVE"},
    {"company_id":"shanxi_expressway","name_zh":"山西高速集团股份有限公司","aliases":["山西高速"],"stock_codes":["000755.SZ"],"description":"主要产品为胶粘剂系列产品、苯精制系列化工产品，同时从事高等级公路养护、收费及基础设施投资运营。","country":"CN","province":"山西","city":"临汾市","founded_year":1996,"employee_count":622,"company_type":"public","status":"ACTIVE"},
    {"company_id":"xinhua_pharmaceutical","name_zh":"山东新华制药股份有限公司","aliases":["新华制药"],"stock_codes":["000756.SZ"],"description":"主要产品包括原料药、制剂和化工产品，是中国重要的解热镇痛药生产和出口基地。","country":"CN","province":"山东","city":"淄博市","founded_year":1998,"employee_count":7240,"company_type":"public","status":"ACTIVE"},
    {"company_id":"haowu_share","name_zh":"四川浩物机电股份有限公司","aliases":["浩物股份"],"stock_codes":["000757.SZ"],"description":"主要业务为汽车发动机配件的生产和销售，同时涉及汽车销售、工程机械和机电产品贸易。","country":"CN","province":"四川","city":"内江市","founded_year":1997,"employee_count":1911,"company_type":"public","status":"ACTIVE"}
]

exposures = [
    {"exposure_id":"exp_nc_sodium_sulfate","company_id":"northern_copper","node_id":"sodium_sulfate","activity_type":"produce","role":"元明粉生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"北方铜业 主营业务","quote":"主要产品:元明粉,硫化碱,硫酸钡和硫酸镁"}],"status":"ACTIVE"},
    {"exposure_id":"exp_nc_sodium_sulfide","company_id":"northern_copper","node_id":"sodium_sulfide","activity_type":"produce","role":"硫化碱生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"北方铜业 主营业务","quote":"主要产品:元明粉,硫化碱,硫酸钡和硫酸镁"}],"status":"ACTIVE"},
    {"exposure_id":"exp_nc_barium_sulfate","company_id":"northern_copper","node_id":"barium_sulfate","activity_type":"produce","role":"硫酸钡生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"北方铜业 主营业务","quote":"主要产品:...硫酸钡和硫酸镁"}],"status":"ACTIVE"},
    {"exposure_id":"exp_nc_magnesium_sulfate","company_id":"northern_copper","node_id":"magnesium_sulfate","activity_type":"produce","role":"硫酸镁生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"北方铜业 主营业务","quote":"主要产品:...硫酸镁"}],"status":"ACTIVE"},
    {"exposure_id":"exp_nc_copper","company_id":"northern_copper","node_id":"copper","activity_type":"produce","role":"铜冶炼及生产商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"北方铜业 经营范围","quote":"常用有色金属冶炼;贵金属冶炼;有色金属压延加工"}],"status":"ACTIVE"},
    {"exposure_id":"exp_aec_engine_ctrl","company_id":"aeroengine_control","node_id":"engine_control_system","activity_type":"manufacture","role":"发动机控制系统制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"航发控制 主营业务","quote":"主要产品:发动机控制系统及部件"}],"status":"ACTIVE"},
    {"exposure_id":"exp_aec_aero_part","company_id":"aeroengine_control","node_id":"aero_engine_part","activity_type":"manufacture","role":"航空发动机零部件制造商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"航发控制 主营业务","quote":"主要产品:发动机控制系统及部件"}],"status":"ACTIVE"},
    {"exposure_id":"exp_pp_pharma_product","company_id":"pulo_pharmaceutical","node_id":"pharmaceutical_product","activity_type":"manufacture","role":"药品制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"普洛药业 主营业务","quote":"主要产品:原料药,制剂"}],"status":"ACTIVE"},
    {"exposure_id":"exp_pp_api","company_id":"pulo_pharmaceutical","node_id":"active_pharmaceutical_ingredient","activity_type":"manufacture","role":"原料药生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"普洛药业 主营业务","quote":"主要产品:原料药,制剂"}],"status":"ACTIVE"},
    {"exposure_id":"exp_gh_brokerage","company_id":"guohai_securities","node_id":"securities_brokerage","activity_type":"operate","role":"证券经纪服务商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"国海证券 主营业务","quote":"主营业务:为客户提供证券代理买卖...等综合金融服务"}],"status":"ACTIVE"},
    {"exposure_id":"exp_gh_underwriting","company_id":"guohai_securities","node_id":"securities_underwriting","activity_type":"operate","role":"证券承销与保荐服务商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"国海证券 主营业务","quote":"证券发行与承销"}],"status":"ACTIVE"},
    {"exposure_id":"exp_gh_asset_mgmt","company_id":"guohai_securities","node_id":"asset_management_service","activity_type":"operate","role":"资产管理服务商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"国海证券 主营业务","quote":"资产管理"}],"status":"ACTIVE"},
    {"exposure_id":"exp_zi_lead_zinc_ore","company_id":"zinc_industry","node_id":"lead_zinc_ore","activity_type":"produce","role":"铅锌矿石生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"锌业股份 主营业务","quote":"主要业务:有色金属锌,铅冶炼及深加工产品"}],"status":"ACTIVE"},
    {"exposure_id":"exp_zi_lead_zinc_metal","company_id":"zinc_industry","node_id":"lead_zinc_metal","activity_type":"produce","role":"铅锌金属生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"锌业股份 主营业务","quote":"主要产品:锌,铅"}],"status":"ACTIVE"},
    {"exposure_id":"exp_zi_sulfuric_acid","company_id":"zinc_industry","node_id":"sulfuric_acid","activity_type":"produce","role":"硫酸副产品生产商","weight":0.5,"confidence":"HIGH","evidence":[{"source_title":"锌业股份 主营业务","quote":"副产硫酸,硫酸锌等"}],"status":"ACTIVE"},
    {"exposure_id":"exp_xf_beer","company_id":"st_xifa","node_id":"beer","activity_type":"produce","role":"啤酒生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"*ST西发 主营业务","quote":"主要产品:啤酒"}],"status":"ACTIVE"},
    {"exposure_id":"exp_zd_highway","company_id":"zhangzhou_development","node_id":"highway","activity_type":"operate","role":"公路经营运营商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"漳州发展 主营业务","quote":"主要业务:公路经营"}],"status":"ACTIVE"},
    {"exposure_id":"exp_zd_tap_water","company_id":"zhangzhou_development","node_id":"tap_water_supply","activity_type":"operate","role":"自来水销售运营商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"漳州发展 主营业务","quote":"自来水销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_zd_waste","company_id":"zhangzhou_development","node_id":"municipal_waste_treatment","activity_type":"operate","role":"废弃物处理运营商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"漳州发展 主营业务","quote":"废弃物处理"}],"status":"ACTIVE"},
    {"exposure_id":"exp_se_highway","company_id":"shanxi_expressway","node_id":"highway","activity_type":"operate","role":"高速公路收费运营商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"山西高速 经营范围","quote":"高等级公路...养护,咨询服务及批准的收费"}],"status":"ACTIVE"},
    {"exposure_id":"exp_se_adhesive","company_id":"shanxi_expressway","node_id":"adhesive","activity_type":"produce","role":"胶粘剂生产商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"山西高速 主营业务","quote":"主要产品:胶粘剂系列产品"}],"status":"ACTIVE"},
    {"exposure_id":"exp_se_benzene","company_id":"shanxi_expressway","node_id":"benzene_refining_product","activity_type":"produce","role":"苯精制化工产品生产商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"山西高速 主营业务","quote":"主要产品:...苯精制系列化工产品"}],"status":"ACTIVE"},
    {"exposure_id":"exp_xhp_pharma","company_id":"xinhua_pharmaceutical","node_id":"pharmaceutical_product","activity_type":"manufacture","role":"药品制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"新华制药 主营业务","quote":"主要产品:原料药,制剂,化工产品及其他"}],"status":"ACTIVE"},
    {"exposure_id":"exp_xhp_api","company_id":"xinhua_pharmaceutical","node_id":"active_pharmaceutical_ingredient","activity_type":"manufacture","role":"原料药生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"新华制药 主营业务","quote":"主要产品:原料药,制剂"}],"status":"ACTIVE"},
    {"exposure_id":"exp_hw_engine_part","company_id":"haowu_share","node_id":"automotive_engine_accessory","activity_type":"manufacture","role":"汽车发动机配件制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"浩物股份 主营业务","quote":"主要业务:汽车发动机配件生产和销售"}],"status":"ACTIVE"}
]

if __name__ == "__main__":
    gb = {"batch_id":"batch_026_graph","task_description":"Batch 026: Industrial nodes and edges for 10 companies (000737-000757). Focus on chemical byproducts, engine controls, securities, non-ferrous metals, highways.","nodes_to_upsert":nodes,"edges_to_upsert":edges,"rejected_or_pending":[]}
    bb = {"batch_id":"batch_026_business","task_description":"Batch 026: Company registrations and exposures for 10 companies (000737-000757).","industries_to_upsert":[],"industry_node_mappings_to_upsert":[],"companies_to_upsert":companies,"company_node_exposures_to_upsert":exposures}
    r1 = submit_graph(gb); print(f"Graph: {r1.status_code}", r1.json())
    r2 = submit_business(bb); print(f"Business: {r2.status_code}", r2.json())
