#!/usr/bin/env python3
"""Batch 115 Submission Script"""
import httpx, json
BASE_URL = "http://localhost:8005/api/v1"
def submit_graph_batch(data):
    r = httpx.post(f"{BASE_URL}/batches", json=data, timeout=60)
    return r.status_code, r.json()
def submit_business_batch(data):
    r = httpx.post(f"{BASE_URL}/business-batches", json=data, timeout=60)
    return r.status_code, r.json()

graph_batch = {
    "batch_id": "batch_115_nodes",
    "task_description": "Batch 115:补充电力设备、服装、轮胎模具、炊具、旅游索道、垃圾发电、厨电、光学模组、民爆器材等缺失节点",
    "nodes_to_upsert": [
        {"node_id": "power_automation_protection", "canonical_name_zh": "电力自动化保护设备", "canonical_name_en": "power automation protection equipment", "aliases": ["继电保护设备"], "definition": "用于电力系统中对发电、输电、变电和配电设备进行监测、控制和保护的自动化装置系统，包括继电保护装置、自动重合闸、故障录波器、同期装置等，是保障电网安全稳定运行的关键设备。", "entity_type": "device", "evidence": [{"source_title": "思源电气主营业务", "quote": "主要产品为电力自动化保护设备,高压开关,高压互感器,电力电容器及电抗器,电力电子成套设备等"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "high_voltage_switch", "canonical_name_zh": "高压开关", "canonical_name_en": "high voltage switch", "aliases": ["高压断路器"], "definition": "用于额定电压3kV及以上电力系统中，能够关合、承载和开断正常回路电流，并能在规定时间内关合、承载和开断异常回路电流的开关设备，是变电站和电网的核心设备之一。", "entity_type": "device", "evidence": [{"source_title": "思源电气主营业务", "quote": "主要产品为电力自动化保护设备,高压开关,高压互感器,电力电容器及电抗器,电力电子成套设备等"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "mutual_inductor", "canonical_name_zh": "互感器", "canonical_name_en": "mutual inductor", "aliases": ["变压器式传感器", "CT/PT"], "definition": "利用电磁感应原理将高电压或大电流按比例变换成标准低电压或小电流的测量设备，包括电流互感器（CT）和电压互感器（PT），是电力系统测量、保护和监控的基础设备。", "entity_type": "device", "evidence": [{"source_title": "思源电气主营业务", "quote": "主要产品为电力自动化保护设备,高压开关,高压互感器,电力电容器及电抗器,电力电子成套设备等"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "power_capacitor", "canonical_name_zh": "电力电容器", "canonical_name_en": "power capacitor", "aliases": ["补偿电容器"], "definition": "用于电力系统中改善功率因数、滤波、储能和无功补偿的电容器设备，可提高电能质量、降低线路损耗、提高供电设备利用率。", "entity_type": "component", "evidence": [{"source_title": "思源电气主营业务", "quote": "主要产品为电力自动化保护设备,高压开关,高压互感器,电力电容器及电抗器,电力电子成套设备等"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "jacket", "canonical_name_zh": "茄克", "canonical_name_en": "jacket", "aliases": ["夹克"], "definition": "一种短款、前开襟、通常带有拉链或纽扣的上衣外套，款式多样，兼具实用性和时尚性，是男装和休闲服饰的经典品类。", "entity_type": "material", "evidence": [{"source_title": "七匹狼主营业务", "quote": "主要产品:茄克,T恤,休闲装,裤装,棉褛,衬衫,毛衫"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "t_shirt", "canonical_name_zh": "T恤", "canonical_name_en": "T-shirt", "aliases": ["短袖衫"], "definition": "一种采用针织面料制成的套头式短袖上衣，因展开后呈T字形而得名，款式简洁、穿着舒适，是日常休闲服装中最基础的品类之一。", "entity_type": "material", "evidence": [{"source_title": "七匹狼主营业务", "quote": "主要产品:茄克,T恤,休闲装,裤装,棉褛,衬衫,毛衫"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "trousers", "canonical_name_zh": "裤装", "canonical_name_en": "trousers", "aliases": ["裤子", "长裤"], "definition": "穿在腰部以下、分别包裹两条腿的下装服装，包括西裤、休闲裤、牛仔裤、运动裤等多种款式，是日常着装的基本组成部分。", "entity_type": "material", "evidence": [{"source_title": "七匹狼主营业务", "quote": "主要产品:茄克,T恤,休闲装,裤装,棉褛,衬衫,毛衫"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "cotton_padded_garment", "canonical_name_zh": "棉褛", "canonical_name_en": "cotton padded garment", "aliases": ["棉衣", "棉服"], "definition": "以棉花或人造棉为填充物，具有保暖功能的上衣外套，款式包括短款、中长款和长款，是寒冷季节的主要御寒服装品类。", "entity_type": "material", "evidence": [{"source_title": "七匹狼主营业务", "quote": "主要产品:茄克,T恤,休闲装,裤装,棉褛,衬衫,毛衫"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "sweater", "canonical_name_zh": "毛衫", "canonical_name_en": "sweater", "aliases": ["毛衣", "针织衫"], "definition": "以毛线或纱线为原料，通过针织工艺编织而成的上衣，材质包括羊毛、羊绒、棉纱、化纤等，具有良好的弹性和保暖性，适合春秋冬季节穿着。", "entity_type": "material", "evidence": [{"source_title": "七匹狼主营业务", "quote": "主要产品:茄克,T恤,休闲装,裤装,棉褛,衬衫,毛衫"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "tire_mold", "canonical_name_zh": "轮胎模具", "canonical_name_en": "tire mold", "aliases": ["子午线轮胎模具"], "definition": "用于硫化成型橡胶轮胎的精密模具，模具内表面刻有轮胎花纹和文字标识，决定了轮胎的花纹形状、排水性能和外观质量，是轮胎生产的关键工艺装备。", "entity_type": "device", "evidence": [{"source_title": "巨轮智能主营业务", "quote": "主要产品:子午线轮胎模具"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "cookware", "canonical_name_zh": "炊具", "canonical_name_en": "cookware", "aliases": ["厨房炊具", "锅具"], "definition": "用于烹饪食物的各种器具，包括炒锅、汤锅、蒸锅、压力锅、平底锅、电饭煲、电压力锅等，材质主要有铁、不锈钢、铝、陶瓷和不粘涂层等。", "entity_type": "device", "evidence": [{"source_title": "苏泊尔主营业务", "quote": "主要产品:电器产品,炊具产品"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "passenger_cableway", "canonical_name_zh": "客运索道", "canonical_name_en": "passenger cableway", "aliases": ["缆车", "索道"], "definition": "利用架设在空中的钢丝绳作为轨道，通过驱动装置带动吊厢或吊椅运送乘客的运输设施，广泛应用于山区旅游景区、滑雪场和城市交通等领域。", "entity_type": "infrastructure", "evidence": [{"source_title": "丽江股份主营业务", "quote": "主要业务:经营客运索道.《印象·丽江》雪山篇演出,酒店建设经营"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "performance", "canonical_name_zh": "演出服务", "canonical_name_en": "performance service", "aliases": ["演艺服务", "文艺演出"], "definition": "通过演员、舞台、灯光、音响等艺术手段，在特定场所为观众呈现戏剧、音乐、舞蹈、杂技等艺术表现形式的现场文化活动服务。", "entity_type": "service", "evidence": [{"source_title": "丽江股份主营业务", "quote": "主要业务:经营客运索道.《印象·丽江》雪山篇演出,酒店建设经营"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "waste_incineration_power_generation", "canonical_name_zh": "垃圾焚烧发电", "canonical_name_en": "waste incineration power generation", "aliases": ["垃圾发电"], "definition": "将城市生活垃圾在高温炉膛中燃烧，利用产生的热能加热水产生蒸汽驱动汽轮发电机组发电的能源回收技术，是实现垃圾减量化、无害化和资源化处理的重要方式。", "entity_type": "service", "evidence": [{"source_title": "旺能环境主营业务", "quote": "主要业务:垃圾焚烧发电主要产品:垃圾处理,发电,供热"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "waste_treatment", "canonical_name_zh": "垃圾处理", "canonical_name_en": "waste treatment", "aliases": ["固废处理", "废弃物处理"], "definition": "对城市生活垃圾、工业固体废物等进行收集、运输、分类、处理和资源化利用的全过程管理活动，处理方式包括填埋、焚烧、堆肥、回收利用等。", "entity_type": "service", "evidence": [{"source_title": "旺能环境主营业务", "quote": "主要业务:垃圾焚烧发电主要产品:垃圾处理,发电,供热"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "gas_stove", "canonical_name_zh": "燃气灶具", "canonical_name_en": "gas stove", "aliases": ["煤气灶", "燃气灶"], "definition": "以天然气、液化石油气或人工煤气为燃料，通过燃烧产生热量用于烹饪食物的厨房设备，包括台式灶和嵌入式灶两种主要类型。", "entity_type": "device", "evidence": [{"source_title": "华帝股份主营业务", "quote": "主要产品:燃气灶具,热水器,抽油烟机及消毒柜等厨房用具"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "water_heater", "canonical_name_zh": "热水器", "canonical_name_en": "water heater", "aliases": ["热水炉"], "definition": "通过电能、燃气或太阳能等能源将水加热至适宜温度的家用或商用设备，包括储水式电热水器、即热式电热水器、燃气热水器、太阳能热水器和空气能热水器等。", "entity_type": "device", "evidence": [{"source_title": "华帝股份主营业务", "quote": "主要产品:燃气灶具,热水器,抽油烟机及消毒柜等厨房用具"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "range_hood", "canonical_name_zh": "抽油烟机", "canonical_name_en": "range hood", "aliases": ["油烟机", "吸油烟机"], "definition": "安装在厨房炉灶上方，用于吸排烹饪过程中产生的油烟、蒸汽和异味的通风设备，通过风机产生负压将油烟吸入并经过滤或排出室外，保持厨房空气清新。", "entity_type": "device", "evidence": [{"source_title": "华帝股份主营业务", "quote": "主要产品:燃气灶具,热水器,抽油烟机及消毒柜等厨房用具"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "disinfection_cabinet", "canonical_name_zh": "消毒柜", "canonical_name_en": "disinfection cabinet", "aliases": ["消毒碗柜"], "definition": "通过紫外线、臭氧、高温蒸汽等方式对餐具、毛巾等物品进行消毒杀菌的家用电器，具有杀灭细菌、病毒和真菌的功能，广泛应用于家庭和餐饮场所。", "entity_type": "device", "evidence": [{"source_title": "华帝股份主营业务", "quote": "主要产品:燃气灶具,热水器,抽油烟机及消毒柜等厨房用具"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "camera_module", "canonical_name_zh": "摄像头模组", "canonical_name_en": "camera module", "aliases": ["摄像模组", "Camera模组"], "definition": "由光学镜头、图像传感器、滤光片、音圈马达、柔性电路板等组成的集成化摄像单元，是手机、安防监控、车载电子、物联网设备等产品的核心成像组件。", "entity_type": "component", "evidence": [{"source_title": "联创电子主营业务", "quote": "主营业务:研发,生产及销售光学镜头,镜片,摄像头模组及触控显示一体化等关键光学,光电子产品"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "touch_display_module", "canonical_name_zh": "触控显示模组", "canonical_name_en": "touch display module", "aliases": ["触显模组"], "definition": "将触摸屏和液晶显示屏集成于一体的模块化组件，同时具备图像显示和触摸感应输入功能，是智能手机、平板电脑、车载导航、工业控制设备等产品的核心人机交互部件。", "entity_type": "component", "evidence": [{"source_title": "联创电子主营业务", "quote": "主营业务:研发,生产及销售光学镜头,镜片,摄像头模组及触控显示一体化等关键光学,光电子产品"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "detonator", "canonical_name_zh": "雷管", "canonical_name_en": "detonator", "aliases": ["起爆器"], "definition": "一种装有少量高敏感炸药的爆破器材，能在较弱的外界刺激（如电火花、火焰、冲击波）作用下发生爆炸，用于引爆炸药装药实现工程爆破，包括电雷管、导爆管雷管、电子雷管等类型。", "entity_type": "material", "evidence": [{"source_title": "保利联合主营业务", "quote": "主要产品:雷管,索类,炸药等民用爆破器材产品"}], "confidence": "HIGH", "status": "ACTIVE"},
        {"node_id": "industrial_explosive", "canonical_name_zh": "工业炸药", "canonical_name_en": "industrial explosive", "aliases": ["民用炸药", "工程炸药"], "definition": "用于矿山开采、水利水电、交通建设、地质勘探等工程爆破作业的高能化学爆炸物质，包括铵油炸药、乳化炸药、水胶炸药、膨化硝铵炸药等，与军用炸药相比对感度和安定性要求不同。", "entity_type": "material", "evidence": [{"source_title": "保利联合主营业务", "quote": "主要产品:雷管,索类,炸药等民用爆破器材产品"}], "confidence": "HIGH", "status": "ACTIVE"}
    ],
    "edges_to_upsert": []
}

print("=" * 60)
print("STEP 1: Submitting missing nodes for Batch 115")
print("=" * 60)
code, result = submit_graph_batch(graph_batch)
print(f"Status: {code}")
print(json.dumps(result, ensure_ascii=False, indent=2))

business_batch = {
    "batch_id": "batch_115_business",
    "task_description": "Batch 115:注册10家公司及其产业节点暴露",
    "companies_to_upsert": [
        {"company_id": "sz_002028", "name_zh": "思源电气", "aliases": ["思源电气股份有限公司"], "stock_codes": ["002028.SZ"], "description": "主要产品为电力自动化保护设备,高压开关,高压互感器,电力电容器及电抗器,电力电子成套设备等", "country": "CN", "province": "上海", "city": "上海市", "employee_count": 9456, "company_type": "public", "status": "ACTIVE"},
        {"company_id": "sz_002029", "name_zh": "七匹狼", "aliases": ["福建七匹狼实业股份有限公司"], "stock_codes": ["002029.SZ"], "description": "主要产品:茄克,T恤,休闲装,裤装,棉褛,衬衫,毛衫", "country": "CN", "province": "福建", "city": "泉州市", "employee_count": 2032, "company_type": "public", "status": "ACTIVE"},
        {"company_id": "sz_002030", "name_zh": "达安基因", "aliases": ["广州达安基因股份有限公司"], "stock_codes": ["002030.SZ"], "description": "试剂,仪器,服务", "country": "CN", "province": "广东", "city": "广州市", "employee_count": 1730, "company_type": "public", "status": "ACTIVE"},
        {"company_id": "sz_002031", "name_zh": "巨轮智能", "aliases": ["巨轮智能装备股份有限公司"], "stock_codes": ["002031.SZ"], "description": "主要产品:子午线轮胎模具", "country": "CN", "province": "广东", "city": "揭阳市", "employee_count": 1845, "company_type": "public", "status": "ACTIVE"},
        {"company_id": "sz_002032", "name_zh": "苏泊尔", "aliases": ["浙江苏泊尔股份有限公司"], "stock_codes": ["002032.SZ"], "description": "主要产品:电器产品,炊具产品", "country": "CN", "province": "浙江", "city": "台州市", "employee_count": 10745, "company_type": "public", "status": "ACTIVE"},
        {"company_id": "sz_002033", "name_zh": "丽江股份", "aliases": ["丽江玉龙旅游股份有限公司"], "stock_codes": ["002033.SZ"], "description": "主要业务:经营客运索道.《印象·丽江》雪山篇演出,酒店建设经营", "country": "CN", "province": "云南", "city": "丽江市", "employee_count": 1658, "company_type": "public", "status": "ACTIVE"},
        {"company_id": "sz_002034", "name_zh": "旺能环境", "aliases": ["旺能环境股份有限公司"], "stock_codes": ["002034.SZ"], "description": "主要业务:垃圾焚烧发电主要产品:垃圾处理,发电,供热", "country": "CN", "province": "浙江", "city": "湖州市", "employee_count": 2655, "company_type": "public", "status": "ACTIVE"},
        {"company_id": "sz_002035", "name_zh": "华帝股份", "aliases": ["华帝股份有限公司"], "stock_codes": ["002035.SZ"], "description": "主要产品:燃气灶具,热水器,抽油烟机及消毒柜等厨房用具", "country": "CN", "province": "广东", "city": "中山市", "employee_count": 5205, "company_type": "public", "status": "ACTIVE"},
        {"company_id": "sz_002036", "name_zh": "联创电子", "aliases": ["联创电子科技股份有限公司"], "stock_codes": ["002036.SZ"], "description": "主营业务:研发,生产及销售光学镜头,镜片,摄像头模组及触控显示一体化等关键光学,光电子产品", "country": "CN", "province": "江西", "city": "南昌市", "employee_count": 13052, "company_type": "public", "status": "ACTIVE"},
        {"company_id": "sz_002037", "name_zh": "保利联合", "aliases": ["保利联合化工控股集团股份有限公司"], "stock_codes": ["002037.SZ"], "description": "主要产品:雷管,索类,炸药等民用爆破器材产品", "country": "CN", "province": "贵州", "city": "贵阳市", "employee_count": 7421, "company_type": "public", "status": "ACTIVE"}
    ],
    "company_node_exposures_to_upsert": [
        {"exposure_id": "sz_002028_produce_power_automation_protection", "company_id": "sz_002028", "node_id": "power_automation_protection", "activity_type": "produce", "role": "电力自动化保护设备生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "思源电气主营业务", "quote": "主要产品为电力自动化保护设备,高压开关,高压互感器,电力电容器及电抗器,电力电子成套设备等"}]},
        {"exposure_id": "sz_002028_produce_high_voltage_switch", "company_id": "sz_002028", "node_id": "high_voltage_switch", "activity_type": "produce", "role": "高压开关生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "思源电气主营业务", "quote": "主要产品为电力自动化保护设备,高压开关,高压互感器,电力电容器及电抗器,电力电子成套设备等"}]},
        {"exposure_id": "sz_002028_produce_mutual_inductor", "company_id": "sz_002028", "node_id": "mutual_inductor", "activity_type": "produce", "role": "互感器生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "思源电气主营业务", "quote": "主要产品为电力自动化保护设备,高压开关,高压互感器,电力电容器及电抗器,电力电子成套设备等"}]},
        {"exposure_id": "sz_002028_produce_power_capacitor", "company_id": "sz_002028", "node_id": "power_capacitor", "activity_type": "produce", "role": "电力电容器生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "思源电气主营业务", "quote": "主要产品为电力自动化保护设备,高压开关,高压互感器,电力电容器及电抗器,电力电子成套设备等"}]},
        {"exposure_id": "sz_002028_produce_reactor", "company_id": "sz_002028", "node_id": "reactor", "activity_type": "produce", "role": "电抗器生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "思源电气主营业务", "quote": "主要产品为电力自动化保护设备,高压开关,高压互感器,电力电容器及电抗器,电力电子成套设备等"}]},
        {"exposure_id": "sz_002029_produce_jacket", "company_id": "sz_002029", "node_id": "jacket", "activity_type": "produce", "role": "茄克生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "七匹狼主营业务", "quote": "主要产品:茄克,T恤,休闲装,裤装,棉褛,衬衫,毛衫"}]},
        {"exposure_id": "sz_002029_produce_t_shirt", "company_id": "sz_002029", "node_id": "t_shirt", "activity_type": "produce", "role": "T恤生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "七匹狼主营业务", "quote": "主要产品:茄克,T恤,休闲装,裤装,棉褛,衬衫,毛衫"}]},
        {"exposure_id": "sz_002029_produce_casual_wear", "company_id": "sz_002029", "node_id": "casual_wear", "activity_type": "produce", "role": "休闲装生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "七匹狼主营业务", "quote": "主要产品:茄克,T恤,休闲装,裤装,棉褛,衬衫,毛衫"}]},
        {"exposure_id": "sz_002029_produce_trousers", "company_id": "sz_002029", "node_id": "trousers", "activity_type": "produce", "role": "裤装生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "七匹狼主营业务", "quote": "主要产品:茄克,T恤,休闲装,裤装,棉褛,衬衫,毛衫"}]},
        {"exposure_id": "sz_002029_produce_cotton_padded_garment", "company_id": "sz_002029", "node_id": "cotton_padded_garment", "activity_type": "produce", "role": "棉褛生产商", "weight": 0.9, "confidence": "HIGH", "evidence": [{"source_title": "七匹狼主营业务", "quote": "主要产品:茄克,T恤,休闲装,裤装,棉褛,衬衫,毛衫"}]},
        {"exposure_id": "sz_002029_produce_shirt", "company_id": "sz_002029", "node_id": "shirt", "activity_type": "produce", "role": "衬衫生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "七匹狼主营业务", "quote": "主要产品:茄克,T恤,休闲装,裤装,棉褛,衬衫,毛衫"}]},
        {"exposure_id": "sz_002029_produce_sweater", "company_id": "sz_002029", "node_id": "sweater", "activity_type": "produce", "role": "毛衫生产商", "weight": 0.9, "confidence": "HIGH", "evidence": [{"source_title": "七匹狼主营业务", "quote": "主要产品:茄克,T恤,休闲装,裤装,棉褛,衬衫,毛衫"}]},
        {"exposure_id": "sz_002030_produce_diagnostic_reagent", "company_id": "sz_002030", "node_id": "in_vitro_diagnostic_reagent", "activity_type": "produce", "role": "诊断试剂生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "达安基因主营业务", "quote": "试剂,仪器,服务"}]},
        {"exposure_id": "sz_002030_produce_medical_instrument", "company_id": "sz_002030", "node_id": "medical_instrument", "activity_type": "produce", "role": "医疗仪器生产商", "weight": 0.9, "confidence": "HIGH", "evidence": [{"source_title": "达安基因主营业务", "quote": "试剂,仪器,服务"}]},
        {"exposure_id": "sz_002030_provide_genetic_testing_service", "company_id": "sz_002030", "node_id": "genetic_testing_service", "activity_type": "provide_service", "role": "基因检测服务商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "达安基因经营范围", "quote": "医学研究和试验发展;人体基因诊断与治疗技术开发"}]},
        {"exposure_id": "sz_002031_produce_tire_mold", "company_id": "sz_002031", "node_id": "tire_mold", "activity_type": "produce", "role": "轮胎模具生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "巨轮智能主营业务", "quote": "主要产品:子午线轮胎模具"}]},
        {"exposure_id": "sz_002032_produce_kitchen_appliance", "company_id": "sz_002032", "node_id": "kitchen_appliance", "activity_type": "produce", "role": "厨房电器生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "苏泊尔主营业务", "quote": "主要产品:电器产品,炊具产品"}]},
        {"exposure_id": "sz_002032_produce_cookware", "company_id": "sz_002032", "node_id": "cookware", "activity_type": "produce", "role": "炊具生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "苏泊尔主营业务", "quote": "主要产品:电器产品,炊具产品"}]},
        {"exposure_id": "sz_002033_operate_passenger_cableway", "company_id": "sz_002033", "node_id": "passenger_cableway", "activity_type": "operate", "role": "客运索道运营商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "丽江股份主营业务", "quote": "主要业务:经营客运索道.《印象·丽江》雪山篇演出,酒店建设经营"}]},
        {"exposure_id": "sz_002033_provide_performance", "company_id": "sz_002033", "node_id": "performance", "activity_type": "provide_service", "role": "演出服务商", "weight": 0.9, "confidence": "HIGH", "evidence": [{"source_title": "丽江股份主营业务", "quote": "主要业务:经营客运索道.《印象·丽江》雪山篇演出,酒店建设经营"}]},
        {"exposure_id": "sz_002033_operate_hotel", "company_id": "sz_002033", "node_id": "hotel", "activity_type": "operate", "role": "酒店运营商", "weight": 0.8, "confidence": "HIGH", "evidence": [{"source_title": "丽江股份主营业务", "quote": "主要业务:经营客运索道.《印象·丽江》雪山篇演出,酒店建设经营"}]},
        {"exposure_id": "sz_002034_operate_waste_incineration_power_generation", "company_id": "sz_002034", "node_id": "waste_incineration_power_generation", "activity_type": "operate", "role": "垃圾焚烧发电运营商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "旺能环境主营业务", "quote": "主要业务:垃圾焚烧发电主要产品:垃圾处理,发电,供热"}]},
        {"exposure_id": "sz_002034_provide_waste_treatment", "company_id": "sz_002034", "node_id": "waste_treatment", "activity_type": "provide_service", "role": "垃圾处理服务商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "旺能环境主营业务", "quote": "主要业务:垃圾焚烧发电主要产品:垃圾处理,发电,供热"}]},
        {"exposure_id": "sz_002034_provide_heat_supply", "company_id": "sz_002034", "node_id": "heat_supply", "activity_type": "provide_service", "role": "供热服务商", "weight": 0.7, "confidence": "HIGH", "evidence": [{"source_title": "旺能环境主营业务", "quote": "主要业务:垃圾焚烧发电主要产品:垃圾处理,发电,供热"}]},
        {"exposure_id": "sz_002035_produce_gas_stove", "company_id": "sz_002035", "node_id": "gas_stove", "activity_type": "produce", "role": "燃气灶具生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "华帝股份主营业务", "quote": "主要产品:燃气灶具,热水器,抽油烟机及消毒柜等厨房用具"}]},
        {"exposure_id": "sz_002035_produce_water_heater", "company_id": "sz_002035", "node_id": "water_heater", "activity_type": "produce", "role": "热水器生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "华帝股份主营业务", "quote": "主要产品:燃气灶具,热水器,抽油烟机及消毒柜等厨房用具"}]},
        {"exposure_id": "sz_002035_produce_range_hood", "company_id": "sz_002035", "node_id": "range_hood", "activity_type": "produce", "role": "抽油烟机生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "华帝股份主营业务", "quote": "主要产品:燃气灶具,热水器,抽油烟机及消毒柜等厨房用具"}]},
        {"exposure_id": "sz_002035_produce_disinfection_cabinet", "company_id": "sz_002035", "node_id": "disinfection_cabinet", "activity_type": "produce", "role": "消毒柜生产商", "weight": 0.9, "confidence": "HIGH", "evidence": [{"source_title": "华帝股份主营业务", "quote": "主要产品:燃气灶具,热水器,抽油烟机及消毒柜等厨房用具"}]},
        {"exposure_id": "sz_002036_produce_optical_lens", "company_id": "sz_002036", "node_id": "optical_lens", "activity_type": "produce", "role": "光学镜头生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "联创电子主营业务", "quote": "主营业务:研发,生产及销售光学镜头,镜片,摄像头模组及触控显示一体化等关键光学,光电子产品"}]},
        {"exposure_id": "sz_002036_produce_camera_module", "company_id": "sz_002036", "node_id": "camera_module", "activity_type": "produce", "role": "摄像头模组生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "联创电子主营业务", "quote": "主营业务:研发,生产及销售光学镜头,镜片,摄像头模组及触控显示一体化等关键光学,光电子产品"}]},
        {"exposure_id": "sz_002036_produce_touch_display_module", "company_id": "sz_002036", "node_id": "touch_display_module", "activity_type": "produce", "role": "触控显示模组生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "联创电子主营业务", "quote": "主营业务:研发,生产及销售光学镜头,镜片,摄像头模组及触控显示一体化等关键光学,光电子产品"}]},
        {"exposure_id": "sz_002037_produce_detonator", "company_id": "sz_002037", "node_id": "detonator", "activity_type": "produce", "role": "雷管生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "保利联合主营业务", "quote": "主要产品:雷管,索类,炸药等民用爆破器材产品"}]},
        {"exposure_id": "sz_002037_produce_industrial_explosive", "company_id": "sz_002037", "node_id": "industrial_explosive", "activity_type": "produce", "role": "工业炸药生产商", "weight": 1.0, "confidence": "HIGH", "evidence": [{"source_title": "保利联合主营业务", "quote": "主要产品:雷管,索类,炸药等民用爆破器材产品"}]}
    ]
}

print("\n" + "=" * 60)
print("STEP 2: Submitting companies and exposures for Batch 115")
print("=" * 60)
code, result = submit_business_batch(business_batch)
print(f"Status: {code}")
print(json.dumps(result, ensure_ascii=False, indent=2))
print("\nBatch 115 submission completed.")
