#!/usr/bin/env python3
"""Batch 029 Submission Script (000793-000803)"""
import json, requests
BASE_URL = "http://localhost:8000/api/v1"
submit_graph = lambda b: requests.post(f"{BASE_URL}/batches", json=b)
submit_business = lambda b: requests.post(f"{BASE_URL}/business-batches", json=b)

nodes = [
    {"node_id":"culture_tourism_service","canonical_name_zh":"文旅服务","canonical_name_en":"Culture and Tourism Service","aliases":["文化旅游","文旅产业"],"definition":"以文化资源为载体，以旅游活动为形式，提供文化体验、休闲娱乐、景区运营、演艺策划等综合性服务的产业形态，是文化产业与旅游产业的融合发展。","entity_type":"service","evidence":[{"source_title":"*ST华闻 主营业务","quote":"主要业务:文旅业务,主要产品:景区开发运营,旅游服务,文化传媒业务"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"micro_motor","canonical_name_zh":"微电机","canonical_name_en":"Micro Motor","aliases":["微型电机","微特电机"],"definition":"额定功率通常在750W以下的电动机，具有体积小、重量轻、控制精度高等特点，广泛用于家用电器、医疗器械、办公设备、汽车电子、工业自动化等领域。","entity_type":"component","evidence":[{"source_title":"英洛华 主营业务","quote":"主要业务:钕铁硼磁性材料和电机系列产品的研发,生产和销售"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"marine_fishery","canonical_name_zh":"海洋渔业","canonical_name_en":"Marine Fishery","aliases":["远洋渔业","捕捞渔业"],"definition":"在海洋环境中利用渔船和渔具捕捞鱼、虾、贝、藻等水生生物资源的产业活动，包括近海捕捞、远洋捕捞和海水养殖等业态。","entity_type":"service","evidence":[{"source_title":"中水渔业 主营业务","quote":"主营业务:远洋捕捞,水产品加工和销售"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"aquatic_product","canonical_name_zh":"水产品","canonical_name_en":"Aquatic Product","aliases":["水产","海鲜"],"definition":"从海洋、湖泊、河流等水域捕捞或养殖获得的鱼、虾、蟹、贝、藻等食用或工业用生物产品，经加工后形成冷冻水产品、鱼罐头、鱼粉等产品。","entity_type":"material","evidence":[{"source_title":"中水渔业 主营业务","quote":"水产品加工和销售"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"truck","canonical_name_zh":"重型卡车","canonical_name_en":"Heavy Truck","aliases":["重卡","载重汽车"],"definition":"总质量超过12吨的公路货运车辆，是物流运输和工程作业的主力装备，按用途分为牵引车、自卸车、载货车和专用车等类型。","entity_type":"system","evidence":[{"source_title":"一汽解放 主营业务","quote":"主要业务:商用车及零部件的研制,生产及销售"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"broadcasting_equipment","canonical_name_zh":"广播电视设备","canonical_name_en":"Broadcasting Equipment","aliases":["广电设备","播出设备"],"definition":"用于广播电视信号制作、传输、发射、接收和显示的各类电子设备和系统，包括摄录设备、演播室设备、发射机、机顶盒、监视器等。","entity_type":"device","evidence":[{"source_title":"四川九洲 主营业务","quote":"主要业务:智能终端,空管产品,微波射频的技术研发,产品制造,销售"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"set_top_box","canonical_name_zh":"机顶盒","canonical_name_en":"Set-Top Box","aliases":["STB","数字机顶盒"],"definition":"连接电视机与外部信号源的设备，将数字电视信号转换为模拟信号供电视机显示，同时具备视频点播、网络浏览、游戏等交互功能。","entity_type":"device","evidence":[{"source_title":"四川九洲 主营业务","quote":"主要业务:智能终端"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"film_television","canonical_name_zh":"影视制作","canonical_name_en":"Film and Television Production","aliases":["影视","电影电视"],"definition":"电影、电视剧、纪录片、综艺节目等视听内容的策划、拍摄、后期制作和发行的全过程，是文化娱乐产业的核心内容生产环节。","entity_type":"service","evidence":[{"source_title":"北京文化 主营业务","quote":"主要业务:影视文化业务,主要服务:电影,电视剧网剧,艺人经纪,综艺"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"cultural_entertainment","canonical_name_zh":"文化娱乐","canonical_name_en":"Cultural Entertainment","aliases":["文娱","文化演艺"],"definition":"以文化创意为核心，通过演出、展览、影视、游戏、动漫等形式满足公众精神文化消费需求的服务业态，是文化产业的重要组成部分。","entity_type":"service","evidence":[{"source_title":"北京文化 主营业务","quote":"主要业务:影视文化业务"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"organic_waste_treatment","canonical_name_zh":"有机废弃物处理","canonical_name_en":"Organic Waste Treatment","aliases":["餐厨垃圾处理","有机固废处理"],"definition":"对餐饮垃圾、厨余垃圾、畜禽粪便、农作物秸秆等有机废弃物进行收集、运输、资源化利用和无害化处置的过程，主要产品为沼气、有机肥和生物柴油等。","entity_type":"service","evidence":[{"source_title":"山高环能 主营业务","quote":"主营业务:有机固废领域的无害化处理与资源化利用及再生能源领域"}],"confidence":"HIGH","status":"ACTIVE"}
]

edges = [
    {"edge_id":"flow_ndfeb_to_micro_motor","from_node":"ndfeb_magnet","to_node":"micro_motor","description":"钕铁硼永磁材料用于制造微电机的永磁转子。","edge_namespace":"industrial_flow","edge_type":"composition","evidence":[{"source_title":"英洛华 产品关联","quote":"钕铁硼+电机"}],"confidence":"HIGH"},
    {"edge_id":"flow_fishery_to_aquatic","from_node":"marine_fishery","to_node":"aquatic_product","description":"海洋渔业捕捞获得水产品原料。","edge_namespace":"industrial_flow","edge_type":"material_flow","evidence":[{"source_title":"中水渔业 产业链","quote":"远洋捕捞→水产品加工"}],"confidence":"HIGH"},
    {"edge_id":"flow_diesel_engine_to_truck","from_node":"diesel_engine","to_node":"truck","description":"柴油发动机作为动力核心装配于重型卡车。","edge_namespace":"industrial_flow","edge_type":"composition","evidence":[{"source_title":"一汽解放 产品构成","quote":"商用车及零部件"}],"confidence":"HIGH"},
    {"edge_id":"flow_broadcast_to_stb","from_node":"broadcasting_equipment","to_node":"set_top_box","description":"广播电视设备系统包含机顶盒终端。","edge_namespace":"industrial_flow","edge_type":"composition","evidence":[{"source_title":"四川九洲 产品关联","quote":"智能终端"}],"confidence":"HIGH"},
    {"edge_id":"flow_film_to_entertainment","from_node":"film_television","to_node":"cultural_entertainment","description":"影视制作是文化娱乐产业的核心内容产出环节。","edge_namespace":"industrial_flow","edge_type":"service_flow","evidence":[{"source_title":"北京文化 业务关联","quote":"影视文化业务"}],"confidence":"HIGH"}
]

companies = [
    {"company_id":"st_huawen","name_zh":"华闻传媒投资集团股份有限公司","aliases":["*ST华闻"],"stock_codes":["000793.SZ"],"description":"主要业务为文旅业务和文化传媒业务，产品包括景区开发运营、旅游服务、媒体内容等。","country":"CN","province":"海南","city":"海口市","founded_year":1991,"employee_count":368,"company_type":"public","status":"ACTIVE"},
    {"company_id":"inovance","name_zh":"英洛华科技股份有限公司","aliases":["英洛华"],"stock_codes":["000795.SZ"],"description":"主要业务为钕铁硼磁性材料和电机系列产品的研发、生产和销售，产品广泛应用于新能源汽车、节能家电、智能制造等领域。","country":"CN","province":"浙江","city":"金华市","founded_year":1997,"employee_count":3781,"company_type":"public","status":"ACTIVE"},
    {"company_id":"caissa_tourism","name_zh":"凯撒同盛发展股份有限公司","aliases":["凯撒旅业"],"stock_codes":["000796.SZ"],"description":"主要业务为旅游服务，涵盖出境旅游、国内旅游、会奖旅游、邮轮旅游等业务。","country":"CN","province":"海南","city":"三亚市","founded_year":1996,"employee_count":1298,"company_type":"public","status":"ACTIVE"},
    {"company_id":"china_wuyi","name_zh":"中国武夷实业股份有限公司","aliases":["中国武夷"],"stock_codes":["000797.SZ"],"description":"主要业务为国内外建筑工程承包、房地产开发和物业管理，是国际工程承包领域的重要企业。","country":"CN","province":"福建","city":"福州市","founded_year":1988,"employee_count":2994,"company_type":"public","status":"ACTIVE"},
    {"company_id":"cnfic","name_zh":"中水集团远洋股份有限公司","aliases":["中水渔业"],"stock_codes":["000798.SZ"],"description":"主营业务为远洋捕捞、水产品加工和销售，拥有多个远洋捕捞船队和渔业基地。","country":"CN","province":"北京","city":"北京市","founded_year":1998,"employee_count":792,"company_type":"public","status":"ACTIVE"},
    {"company_id":"jiuguijiu","name_zh":"酒鬼酒股份有限公司","aliases":["酒鬼酒"],"stock_codes":["000799.SZ"],"description":"主要业务为白酒的生产和销售，主打馥郁香型白酒，是中国文化名酒的代表之一。","country":"CN","province":"湖南","city":"湘西土家族苗族自治州","founded_year":1997,"employee_count":2166,"company_type":"public","status":"ACTIVE"},
    {"company_id":"faw_jiefang","name_zh":"一汽解放集团股份有限公司","aliases":["一汽解放"],"stock_codes":["000800.SZ"],"description":"主要业务为商用车及零部件的研制、生产及销售，产品覆盖重型卡车、中型卡车、轻型卡车和客车等。","country":"CN","province":"吉林","city":"长春市","founded_year":1997,"employee_count":22264,"company_type":"public","status":"ACTIVE"},
    {"company_id":"sichuan_jiuzhou","name_zh":"四川九洲电器股份有限公司","aliases":["四川九洲"],"stock_codes":["000801.SZ"],"description":"主要业务为智能终端、空管产品、微波射频的技术研发、产品制造和销售，产品涵盖数字电视、机顶盒、空管系统等。","country":"CN","province":"四川","city":"绵阳市","founded_year":1991,"employee_count":2155,"company_type":"public","status":"ACTIVE"},
    {"company_id":"bj_culture","name_zh":"北京京西文化旅游股份有限公司","aliases":["北京文化"],"stock_codes":["000802.SZ"],"description":"主要业务为影视文化业务，提供电影、电视剧网剧、艺人经纪、综艺等文化娱乐内容。","country":"CN","province":"北京","city":"北京市","founded_year":1997,"employee_count":200,"company_type":"public","status":"ACTIVE"},
    {"company_id":"shandong_huanneng","name_zh":"山高环能集团股份有限公司","aliases":["山高环能"],"stock_codes":["000803.SZ"],"description":"主营业务为有机固废领域的无害化处理与资源化利用及再生能源领域，涵盖餐厨垃圾处理、废弃油脂资源化利用等。","country":"CN","province":"山东","city":"济南市","founded_year":1988,"employee_count":1143,"company_type":"public","status":"ACTIVE"}
]

exposures = [
    {"exposure_id":"exp_sthw_media","company_id":"st_huawen","node_id":"media","activity_type":"operate","role":"文化传媒运营商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"*ST华闻 主营业务","quote":"文化传媒业务"}],"status":"ACTIVE"},
    {"exposure_id":"exp_sthw_tourism","company_id":"st_huawen","node_id":"culture_tourism_service","activity_type":"operate","role":"文旅服务运营商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"*ST华闻 主营业务","quote":"主要业务:文旅业务,主要产品:景区开发运营,旅游服务"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ylh_ndfeb","company_id":"inovance","node_id":"ndfeb_magnet","activity_type":"produce","role":"钕铁硼磁材生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"英洛华 主营业务","quote":"主要业务:钕铁硼磁性材料...的研发,生产和销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ylh_motor","company_id":"inovance","node_id":"micro_motor","activity_type":"produce","role":"微电机生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"英洛华 主营业务","quote":"主要业务:...电机系列产品的研发,生产和销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ks_tourism","company_id":"caissa_tourism","node_id":"tourism_service","activity_type":"operate","role":"旅游服务运营商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"凯撒旅业 主营业务","quote":"主要业务:旅游服务"}],"status":"ACTIVE"},
    {"exposure_id":"exp_cw_construction","company_id":"china_wuyi","node_id":"construction_service","activity_type":"operate","role":"建筑工程承包商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"中国武夷 主营业务","quote":"主要业务:国内外建筑工程承包"}],"status":"ACTIVE"},
    {"exposure_id":"exp_cw_real_estate","company_id":"china_wuyi","node_id":"real_estate_development","activity_type":"operate","role":"房地产开发商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"中国武夷 主营业务","quote":"主要业务:...房地产开发"}],"status":"ACTIVE"},
    {"exposure_id":"exp_cnfic_fishery","company_id":"cnfic","node_id":"marine_fishery","activity_type":"operate","role":"远洋渔业运营商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"中水渔业 主营业务","quote":"主营业务:远洋捕捞"}],"status":"ACTIVE"},
    {"exposure_id":"exp_cnfic_aquatic","company_id":"cnfic","node_id":"aquatic_product","activity_type":"produce","role":"水产品生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"中水渔业 主营业务","quote":"水产品加工和销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_jgj_liquor","company_id":"jiuguijiu","node_id":"liquor","activity_type":"produce","role":"白酒生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"酒鬼酒 主营业务","quote":"主要业务:白酒的生产和销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_faw_truck","company_id":"faw_jiefang","node_id":"truck","activity_type":"manufacture","role":"重型卡车制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"一汽解放 主营业务","quote":"主要业务:商用车及零部件的研制,生产及销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_faw_cv","company_id":"faw_jiefang","node_id":"commercial_vehicle","activity_type":"manufacture","role":"商用车制造商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"一汽解放 主营业务","quote":"主要业务:商用车及零部件的研制,生产及销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_jz_broadcast","company_id":"sichuan_jiuzhou","node_id":"broadcasting_equipment","activity_type":"manufacture","role":"广播电视设备制造商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"四川九洲 主营业务","quote":"主要业务:智能终端,空管产品,微波射频的技术研发,产品制造,销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_jz_stb","company_id":"sichuan_jiuzhou","node_id":"set_top_box","activity_type":"manufacture","role":"机顶盒制造商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"四川九洲 主营业务","quote":"主要业务:智能终端"}],"status":"ACTIVE"},
    {"exposure_id":"exp_bj_film","company_id":"bj_culture","node_id":"film_television","activity_type":"operate","role":"影视制作运营商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"北京文化 主营业务","quote":"主要业务:影视文化业务,主要服务:电影,电视剧网剧,艺人经纪,综艺"}],"status":"ACTIVE"},
    {"exposure_id":"exp_bj_entertainment","company_id":"bj_culture","node_id":"cultural_entertainment","activity_type":"operate","role":"文化娱乐运营商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"北京文化 主营业务","quote":"影视文化业务"}],"status":"ACTIVE"},
    {"exposure_id":"exp_shw_waste_treatment","company_id":"shandong_huanneng","node_id":"municipal_waste_treatment","activity_type":"operate","role":"城市废弃物处理运营商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"山高环能 主营业务","quote":"主营业务:有机固废领域的无害化处理与资源化利用"}],"status":"ACTIVE"},
    {"exposure_id":"exp_shw_organic","company_id":"shandong_huanneng","node_id":"organic_waste_treatment","activity_type":"operate","role":"有机废弃物处理运营商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"山高环能 主营业务","quote":"主营业务:有机固废领域的无害化处理与资源化利用"}],"status":"ACTIVE"}
]

if __name__ == "__main__":
    gb = {"batch_id":"batch_029_graph","task_description":"Batch 029: Industrial nodes and edges for 10 companies (000793-000803). Focus on culture tourism, rare earth magnet, marine fishery, liquor, commercial vehicle, broadcasting equipment, film/entertainment, organic waste treatment.","nodes_to_upsert":nodes,"edges_to_upsert":edges,"rejected_or_pending":[]}
    bb = {"batch_id":"batch_029_business","task_description":"Batch 029: Company registrations and exposures for 10 companies (000793-000803).","industries_to_upsert":[],"industry_node_mappings_to_upsert":[],"companies_to_upsert":companies,"company_node_exposures_to_upsert":exposures}
    r1 = submit_graph(gb); print(f"Graph: {r1.status_code}", r1.json())
    r2 = submit_business(bb); print(f"Business: {r2.status_code}", r2.json())
