#!/usr/bin/env python3
"""Batch 034 Submission Script (000881-000903)"""
import requests
BASE_URL = "http://localhost:8000/api/v1"
submit_graph = lambda b: requests.post(f"{BASE_URL}/batches", json=b)
submit_business = lambda b: requests.post(f"{BASE_URL}/business-batches", json=b)

nodes = [
    {"node_id":"radiation_technology","canonical_name_zh":"核技术应用","canonical_name_en":"Radiation Technology Application","aliases":["核技术","辐照技术"],"definition":"利用放射性同位素和射线装置产生的电离辐射，在材料改性、医学诊疗、食品安全、工业检测和环境治理等领域的应用技术，包括辐照加工、核医学、工业探伤和辐射育种等方向。","entity_type":"technology_capability","evidence":[{"source_title":"中广核技 主营业务","quote":"主营业务:对外承包工程,承担国家经援项目,国际劳务技术合作"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"polymer_material","canonical_name_zh":"高分子材料","canonical_name_en":"Polymer Material","aliases":["聚合物材料","合成材料"],"definition":"由大量重复结构单元通过共价键连接形成的大分子化合物材料，包括塑料、橡胶、纤维、涂料和胶粘剂等，具有质轻、耐腐蚀、易加工等优点，是现代工业和日常生活中应用最广泛的材料类别之一。","entity_type":"material","evidence":[{"source_title":"中广核技 经营范围","quote":"化工材料的技术开发,技术转让,技术咨询,技术服务"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"rubber_seal","canonical_name_zh":"橡胶密封件","canonical_name_en":"Rubber Seal","aliases":["密封件","橡胶制品"],"definition":"利用橡胶材料的弹性和密封性能，用于防止流体或粉尘从机械结合面泄漏的功能性零部件，广泛应用于汽车、工程机械、航空航天、石油化工等领域的液压、气动和静态密封系统。","entity_type":"component","evidence":[{"source_title":"中鼎股份 主营业务","quote":"主营业务:密封件,特种橡胶制品的研发,生产,销售与服务"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"scenic_area","canonical_name_zh":"旅游景区","canonical_name_en":"Scenic Area","aliases":["风景名胜区","景点"],"definition":"以自然或人文景观为核心吸引物，具备游览、观光、休闲、度假等功能，经政府主管部门批准设立并实施统一管理的地理区域，是旅游产业的资源基础和空间载体。","entity_type":"service","evidence":[{"source_title":"峨眉山A 主营业务","quote":"主要业务:经营峨眉山风景区游山票,客运索道,旅游宾馆"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"ropeway","canonical_name_zh":"客运索道","canonical_name_en":"Passenger Ropeway","aliases":["索道","缆车"],"definition":"利用悬挂在支架之间的承载索和牵引索，通过驱动装置带动吊厢或吊椅运送乘客的特种运输设备，广泛应用于山区旅游景区、城市交通和滑雪场等场所，是解决复杂地形人员运输的高效方式。","entity_type":"infrastructure","evidence":[{"source_title":"峨眉山A 主营业务","quote":"主要业务:经营...客运索道"}],"confidence":"HIGH","status":"ACTIVE"}
]

edges = [
    {"edge_id":"flow_polymer_to_seal","from_node":"polymer_material","to_node":"rubber_seal","description":"高分子材料（橡胶）经加工制成橡胶密封件。","edge_namespace":"industrial_flow","edge_type":"material_flow","evidence":[{"source_title":"中鼎股份 产业链","quote":"橡胶→密封件"}],"confidence":"HIGH"}
]

companies = [
    {"company_id":"cgnn_tech","name_zh":"中广核核技术发展股份有限公司","aliases":["中广核技"],"stock_codes":["000881.SZ"],"description":"主营业务包括对外承包工程、承担国家经援项目、国际劳务技术合作等，同时布局核技术开发、高分子材料、进出口贸易等领域。","country":"CN","province":"辽宁","city":"大连市","founded_year":1993,"employee_count":4338,"company_type":"public","status":"ACTIVE"},
    {"company_id":"bhg_mall","name_zh":"北京华联商厦股份有限公司","aliases":["华联股份"],"stock_codes":["000882.SZ"],"description":"主要业务为百货零售，经营商业综合体管理、非居住房地产租赁等业务。","country":"CN","province":"北京","city":"北京市","founded_year":1998,"employee_count":1119,"company_type":"public","status":"ACTIVE"},
    {"company_id":"hubei_energy","name_zh":"湖北能源集团股份有限公司","aliases":["湖北能源"],"stock_codes":["000883.SZ"],"description":"主要业务为能源投资、开发与管理，从事或投资的主要业务包括水电、火电、核电、新能源发电、天然气输配、煤炭贸易和金融投资。","country":"CN","province":"湖北","city":"武汉市","founded_year":1993,"employee_count":4629,"company_type":"public","status":"ACTIVE"},
    {"company_id":"citydev_env","name_zh":"城发环境股份有限公司","aliases":["城发环境"],"stock_codes":["000885.SZ"],"description":"业务涉及生活垃圾、餐厨垃圾、城市污泥等各类低值废弃物的无害化处置和资源化利用；城镇供水、污水、清洁供暖项目的投资、建设及智慧化运营；高速公路等交通设施及配套产业的投资、建设、运营；工程设计咨询等专业化服务。","country":"CN","province":"河南","city":"郑州市","founded_year":1998,"employee_count":4573,"company_type":"public","status":"ACTIVE"},
    {"company_id":"hainan_expressway","name_zh":"海南高速公路股份有限公司","aliases":["海南高速"],"stock_codes":["000886.SZ"],"description":"主要业务包括高速公路的建设和养护管理、房地产的开发销售及物业管理、旅游服务业的综合开发、计算机工程和信息服务。","country":"CN","province":"海南","city":"海口市","founded_year":1993,"employee_count":1527,"company_type":"public","status":"ACTIVE"},
    {"company_id":"zhongding","name_zh":"安徽中鼎密封件股份有限公司","aliases":["中鼎股份"],"stock_codes":["000887.SZ"],"description":"主营业务为密封件、特种橡胶制品的研发、生产、销售与服务，是全球领先的汽车橡胶密封件供应商。","country":"CN","province":"安徽","city":"宣城市","founded_year":1998,"employee_count":22935,"company_type":"public","status":"ACTIVE"},
    {"company_id":"emei_shan","name_zh":"峨眉山旅游股份有限公司","aliases":["峨眉山A"],"stock_codes":["000888.SZ"],"description":"主要业务为经营峨眉山风景区游山票、客运索道、旅游宾馆，是四川省重要的旅游上市公司。","country":"CN","province":"四川","city":"乐山市","founded_year":1997,"employee_count":2034,"company_type":"public","status":"ACTIVE"},
    {"company_id":"zhongjiabochuang","name_zh":"中嘉博创信息技术股份有限公司","aliases":["中嘉博创"],"stock_codes":["000889.SZ"],"description":"主要业务为信息技术咨询服务、集成电路设计、信息系统集成服务、通信工程和计算机网络工程的设计等。","country":"CN","province":"河北","city":"秦皇岛市","founded_year":1997,"employee_count":2331,"company_type":"public","status":"ACTIVE"},
    {"company_id":"farsighted","name_zh":"江苏法尔胜股份有限公司","aliases":["法尔胜"],"stock_codes":["000890.SZ"],"description":"主要产品包括各类钢丝、钢丝绳产品，以及以应收账款融资为主要服务内容的商业保理服务。","country":"CN","province":"江苏","city":"无锡市","founded_year":1993,"employee_count":347,"company_type":"public","status":"ACTIVE"},
    {"company_id":"huanrui_century","name_zh":"欢瑞世纪联合股份有限公司","aliases":["欢瑞世纪"],"stock_codes":["000892.SZ"],"description":"主要业务为综合性、高品质文化娱乐内容供应，主要包括精品影视内容供应、艺人经纪及游戏等娱乐内容供应。","country":"CN","province":"重庆","city":"重庆市","founded_year":1997,"employee_count":141,"company_type":"public","status":"ACTIVE"},
    {"company_id":"asia_potash","name_zh":"亚钾国际投资(广州)股份有限公司","aliases":["亚钾国际"],"stock_codes":["000893.SZ"],"description":"主营业务为钾盐矿开采、加工、钾肥生产及销售，是海外钾肥资源开发的重要企业。","country":"CN","province":"广东","city":"广州市","founded_year":1998,"employee_count":5808,"company_type":"public","status":"ACTIVE"},
    {"company_id":"shuanghui","name_zh":"河南双汇投资发展股份有限公司","aliases":["双汇发展"],"stock_codes":["000895.SZ"],"description":"主要产品包括高温肉制品、低温肉制品、鲜冻猪产品，以及商业连锁服务，是中国最大的肉类加工企业。","country":"CN","province":"河南","city":"漯河市","founded_year":1998,"employee_count":46352,"company_type":"public","status":"ACTIVE"},
    {"company_id":"yuneeng_holdings","name_zh":"河南豫能控股股份有限公司","aliases":["豫能控股"],"stock_codes":["001896.SZ"],"description":"主要业务为火电项目的投资管理、能源销售、新能源项目投资建设、煤炭物流、环境保护和发电设备检修等。","country":"CN","province":"河南","city":"郑州市","founded_year":1997,"employee_count":3457,"company_type":"public","status":"ACTIVE"},
    {"company_id":"tianjin_jinbin","name_zh":"天津津滨发展股份有限公司","aliases":["津滨发展"],"stock_codes":["000897.SZ"],"description":"主要业务为商品销售、房屋租赁、房屋土地销售，是天津市重要的房地产开发企业。","country":"CN","province":"天津","city":"天津市","founded_year":1998,"employee_count":297,"company_type":"public","status":"ACTIVE"},
    {"company_id":"angang_steel","name_zh":"鞍钢股份有限公司","aliases":["鞍钢股份"],"stock_codes":["000898.SZ"],"description":"主要产品包括热轧板、冷轧板、镀锌板、彩涂板、中厚板、大型材、重轨、线材、无缝钢管、冷轧硅钢等，是中国最大的钢铁企业之一。","country":"CN","province":"辽宁","city":"鞍山市","founded_year":1998,"employee_count":23990,"company_type":"public","status":"ACTIVE"},
    {"company_id":"ganeng_power","name_zh":"江西赣能股份有限公司","aliases":["赣能股份"],"stock_codes":["000899.SZ"],"description":"主要业务为火力、水力发电，是江西省重要的电力生产企业。","country":"CN","province":"江西","city":"南昌市","founded_year":1997,"employee_count":1022,"company_type":"public","status":"ACTIVE"},
    {"company_id":"modern_investment","name_zh":"现代投资股份有限公司","aliases":["现代投资"],"stock_codes":["000900.SZ"],"description":"主要业务为经营高等级公路，同时涉及环保、清洁能源、资产管理等领域。","country":"CN","province":"湖南","city":"长沙市","founded_year":1993,"employee_count":2767,"company_type":"public","status":"ACTIVE"},
    {"company_id":"aerospace_tech","name_zh":"航天科技控股集团股份有限公司","aliases":["航天科技"],"stock_codes":["000901.SZ"],"description":"主要产品包括车联网及工业物联网、航天应用产品、汽车电子、电力设备，业务涵盖仪器仪表制造、智能车载设备、物联网应用服务等。","country":"CN","province":"黑龙江","city":"哈尔滨市","founded_year":1999,"employee_count":6043,"company_type":"public","status":"ACTIVE"},
    {"company_id":"xinyangfeng","name_zh":"新洋丰农业科技股份有限公司","aliases":["新洋丰"],"stock_codes":["000902.SZ"],"description":"主要业务为磷复肥、新型肥料的研发、生产和销售，以及现代农业产业解决方案提供业务，是中国磷复肥行业的龙头企业。","country":"CN","province":"湖北","city":"荆门市","founded_year":1986,"employee_count":8315,"company_type":"public","status":"ACTIVE"},
    {"company_id":"st_yundong","name_zh":"昆明云内动力股份有限公司","aliases":["ST云动"],"stock_codes":["000903.SZ"],"description":"主要产品包括100、102、90、95系列柴油机及柴油机配件，是国内重要的柴油发动机生产企业。","country":"CN","province":"云南","city":"昆明市","founded_year":1999,"employee_count":2594,"company_type":"public","status":"ACTIVE"}
]

exposures = [
    {"exposure_id":"exp_cgnn_radiation","company_id":"cgnn_tech","node_id":"radiation_technology","activity_type":"operate","role":"核技术应用服务商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"中广核技 经营范围","quote":"核技术开发,技术转让,技术咨询,技术服务"}],"status":"ACTIVE"},
    {"exposure_id":"exp_cgnn_polymer","company_id":"cgnn_tech","node_id":"polymer_material","activity_type":"produce","role":"高分子材料生产商","weight":0.6,"confidence":"HIGH","evidence":[{"source_title":"中广核技 经营范围","quote":"化工材料的技术开发,技术转让,技术咨询,技术服务"}],"status":"ACTIVE"},
    {"exposure_id":"exp_bhg_dept_store","company_id":"bhg_mall","node_id":"department_store","activity_type":"operate","role":"百货零售商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"华联股份 主营业务","quote":"主要业务:百货零售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_hbe_hydro","company_id":"hubei_energy","node_id":"hydro_power_generation","activity_type":"operate","role":"水电运营商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"湖北能源 主营业务","quote":"主要业务:能源投资,开发与管理,从事或投资的主要业务包括水电,火电..."}],"status":"ACTIVE"},
    {"exposure_id":"exp_hbe_thermal","company_id":"hubei_energy","node_id":"coal_power_generation","activity_type":"operate","role":"火电运营商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"湖北能源 主营业务","quote":"主要业务:...火电,核电,新能源发电..."}],"status":"ACTIVE"},
    {"exposure_id":"exp_hbe_gas","company_id":"hubei_energy","node_id":"natural_gas","activity_type":"produce","role":"天然气输配商","weight":0.6,"confidence":"HIGH","evidence":[{"source_title":"湖北能源 主营业务","quote":"主要业务:...天然气输配..."}],"status":"ACTIVE"},
    {"exposure_id":"exp_cde_waste","company_id":"citydev_env","node_id":"municipal_waste_treatment","activity_type":"operate","role":"城市废弃物处理运营商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"城发环境 主营业务","quote":"业务涉及生活垃圾,餐厨垃圾,城市污泥等各类低值废弃物的无害化处置和资源化利用"}],"status":"ACTIVE"},
    {"exposure_id":"exp_cde_highway","company_id":"citydev_env","node_id":"highway_operation_service","activity_type":"operate","role":"高速公路运营商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"城发环境 主营业务","quote":"高速公路等交通设施及配套产业的投资,建设,运营"}],"status":"ACTIVE"},
    {"exposure_id":"exp_hne_highway","company_id":"hainan_expressway","node_id":"highway_operation_service","activity_type":"operate","role":"高速公路运营商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"海南高速 主营业务","quote":"主要业务:高速公路的建设和养护管理"}],"status":"ACTIVE"},
    {"exposure_id":"exp_hne_realestate","company_id":"hainan_expressway","node_id":"real_estate_development","activity_type":"operate","role":"房地产开发商","weight":0.6,"confidence":"HIGH","evidence":[{"source_title":"海南高速 主营业务","quote":"主要业务:...房地产的开发,销售及物业管理"}],"status":"ACTIVE"},
    {"exposure_id":"exp_hne_tourism","company_id":"hainan_expressway","node_id":"tourism_service","activity_type":"operate","role":"旅游服务运营商","weight":0.6,"confidence":"HIGH","evidence":[{"source_title":"海南高速 主营业务","quote":"主要业务:...旅游服务业的综合开发"}],"status":"ACTIVE"},
    {"exposure_id":"exp_zd_rubber_seal","company_id":"zhongding","node_id":"rubber_seal","activity_type":"manufacture","role":"橡胶密封件制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"中鼎股份 主营业务","quote":"主营业务:密封件,特种橡胶制品的研发,生产,销售与服务"}],"status":"ACTIVE"},
    {"exposure_id":"exp_zd_auto_part","company_id":"zhongding","node_id":"automotive_part","activity_type":"manufacture","role":"汽车零部件制造商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"中鼎股份 经营范围","quote":"汽车零部件研发;汽车零部件及配件制造"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ems_scenic","company_id":"emei_shan","node_id":"scenic_area","activity_type":"operate","role":"旅游景区运营商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"峨眉山A 主营业务","quote":"主要业务:经营峨眉山风景区游山票..."}],"status":"ACTIVE"},
    {"exposure_id":"exp_ems_ropeway","company_id":"emei_shan","node_id":"ropeway","activity_type":"operate","role":"客运索道运营商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"峨眉山A 主营业务","quote":"主要业务:经营...客运索道..."}],"status":"ACTIVE"},
    {"exposure_id":"exp_zjbc_comm","company_id":"zhongjiabochuang","node_id":"communication_equipment","activity_type":"manufacture","role":"通信设备制造商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"中嘉博创 经营范围","quote":"信息技术咨询服务;集成电路设计;信息系统集成服务;通信工程..."}],"status":"ACTIVE"},
    {"exposure_id":"exp_fs_steel_wire","company_id":"farsighted","node_id":"steel_wire","activity_type":"produce","role":"钢丝生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"法尔胜 主营业务","quote":"主要产品:...钢丝产品主要有产品规格涵盖0.5mm-12mm的各类钢丝及其制品..."}],"status":"ACTIVE"},
    {"exposure_id":"exp_fs_steel_rope","company_id":"farsighted","node_id":"steel_rope","activity_type":"produce","role":"钢丝绳生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"法尔胜 主营业务","quote":"主要产品:主要用于航空,电脑,高档设备等的物资及动力传输的PU同步带用钢丝绳..."}],"status":"ACTIVE"},
    {"exposure_id":"exp_hr_film","company_id":"huanrui_century","node_id":"film_television","activity_type":"operate","role":"影视内容供应商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"欢瑞世纪 主营业务","quote":"主要业务:综合性,高品质文化娱乐内容供应...精品影视内容供应"}],"status":"ACTIVE"},
    {"exposure_id":"exp_hr_entertainment","company_id":"huanrui_century","node_id":"cultural_entertainment","activity_type":"operate","role":"文化娱乐运营商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"欢瑞世纪 主营业务","quote":"主要业务:综合性,高品质文化娱乐内容供应"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ak_potassium","company_id":"asia_potash","node_id":"potassium_chloride","activity_type":"produce","role":"钾肥生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"亚钾国际 主营业务","quote":"主营业务为钾盐矿开采,加工,钾肥生产及销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ak_fertilizer","company_id":"asia_potash","node_id":"chemical_fertilizer","activity_type":"produce","role":"化肥生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"亚钾国际 主营业务","quote":"主营业务为钾盐矿开采,加工,钾肥生产及销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_sh_meat","company_id":"shuanghui","node_id":"meat_product","activity_type":"produce","role":"肉类产品生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"双汇发展 主营业务","quote":"主要产品:高温肉制品,低温肉制品,鲜冻猪产品"}],"status":"ACTIVE"},
    {"exposure_id":"exp_sh_feed","company_id":"shuanghui","node_id":"feed","activity_type":"produce","role":"饲料生产商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"双汇发展 经营范围","quote":"畜牧渔业饲料销售;饲料原料销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_yn_thermal","company_id":"yuneeng_holdings","node_id":"coal_power_generation","activity_type":"operate","role":"火电运营商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"豫能控股 主营业务","quote":"主要业务:火电项目的投资管理..."}],"status":"ACTIVE"},
    {"exposure_id":"exp_yn_wind","company_id":"yuneeng_holdings","node_id":"wind_power_generation","activity_type":"operate","role":"风电运营商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"豫能控股 主营业务","quote":"主要业务:...新能源项目投资建设..."}],"status":"ACTIVE"},
    {"exposure_id":"exp_tj_realestate","company_id":"tianjin_jinbin","node_id":"real_estate_development","activity_type":"operate","role":"房地产开发商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"津滨发展 主营业务","quote":"主要业务:商品销售,房屋租赁,房屋土地销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ag_steel_plate","company_id":"angang_steel","node_id":"steel_plate","activity_type":"produce","role":"钢材综合生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"鞍钢股份 主营业务","quote":"主要产品:热轧板,冷轧板,镀锌板,彩涂板,中厚板,大型材,重轨,线材,无缝钢管,冷轧硅钢等"}],"status":"ACTIVE"},
    {"exposure_id":"exp_ag_hot_rolled","company_id":"angang_steel","node_id":"steel_bar","activity_type":"produce","role":"热轧钢材生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"鞍钢股份 主营业务","quote":"主要产品:热轧板...大型材,重轨,线材..."}],"status":"ACTIVE"},
    {"exposure_id":"exp_gn_thermal","company_id":"ganeng_power","node_id":"coal_power_generation","activity_type":"operate","role":"火电运营商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"赣能股份 主营业务","quote":"主要业务:火力,水力发电"}],"status":"ACTIVE"},
    {"exposure_id":"exp_gn_hydro","company_id":"ganeng_power","node_id":"hydro_power_generation","activity_type":"operate","role":"水电运营商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"赣能股份 主营业务","quote":"主要业务:火力,水力发电"}],"status":"ACTIVE"},
    {"exposure_id":"exp_gn_elec","company_id":"ganeng_power","node_id":"electricity_power","activity_type":"produce","role":"电力生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"赣能股份 经营范围","quote":"发电业务,输电业务,供(配)电业务,水力发电"}],"status":"ACTIVE"},
    {"exposure_id":"exp_mi_highway","company_id":"modern_investment","node_id":"highway_operation_service","activity_type":"operate","role":"高速公路运营商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"现代投资 主营业务","quote":"主要业务:经营高等级公路"}],"status":"ACTIVE"},
    {"exposure_id":"exp_at_iot","company_id":"aerospace_tech","node_id":"communication_equipment","activity_type":"manufacture","role":"汽车电子/物联网设备制造商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"航天科技 主营业务","quote":"主要产品:车联网及工业物联网,航天应用产品,汽车电子,电力设备"}],"status":"ACTIVE"},
    {"exposure_id":"exp_at_auto_elec","company_id":"aerospace_tech","node_id":"automotive_electronics","activity_type":"manufacture","role":"汽车电子制造商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"航天科技 主营业务","quote":"主要产品:...汽车电子..."}],"status":"ACTIVE"},
    {"exposure_id":"exp_xyf_fertilizer","company_id":"xinyangfeng","node_id":"compound_fertilizer","activity_type":"produce","role":"磷复肥生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"新洋丰 主营业务","quote":"主要业务:磷复肥,新型肥料的研发,生产和销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_xyf_chem_fert","company_id":"xinyangfeng","node_id":"chemical_fertilizer","activity_type":"produce","role":"化肥综合生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"新洋丰 经营范围","quote":"肥料生产;肥料销售;化肥销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_yd_diesel","company_id":"st_yundong","node_id":"diesel_engine","activity_type":"manufacture","role":"柴油发动机制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"ST云动 主营业务","quote":"主要产品:100,102,90,95系列柴油机,柴油机配件及其他轻卡,农用运输车"}],"status":"ACTIVE"},
    {"exposure_id":"exp_yd_auto_part","company_id":"st_yundong","node_id":"automotive_part","activity_type":"manufacture","role":"汽车配件制造商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"ST云动 主营业务","quote":"主要产品:...柴油机配件及其他轻卡,农用运输车"}],"status":"ACTIVE"}
]

if __name__ == "__main__":
    gb = {"batch_id":"batch_034_graph","task_description":"Batch 034: Industrial nodes and edges for 20 companies (000881-000903). Focus on radiation technology, polymer/seals, department store, energy, waste/environment, highway/tourism, scenic area/ropeway, telecom, steel wire/rope, film/entertainment, potash fertilizer, meat processing, thermal/wind power, real estate, steel, diesel engines, compound fertilizer.","nodes_to_upsert":nodes,"edges_to_upsert":edges,"rejected_or_pending":[]}
    bb = {"batch_id":"batch_034_business","task_description":"Batch 034: Company registrations and exposures for 20 companies (000881-000903).","industries_to_upsert":[],"industry_node_mappings_to_upsert":[],"companies_to_upsert":companies,"company_node_exposures_to_upsert":exposures}
    r1 = submit_graph(gb); print(f"Graph: {r1.status_code}", r1.json())
    r2 = submit_business(bb); print(f"Business: {r2.status_code}", r2.json())
