#!/usr/bin/env python3
"""Batch 028 Submission Script (000779-000792)"""
import json, requests
BASE_URL = "http://localhost:8000/api/v1"
submit_graph = lambda b: requests.post(f"{BASE_URL}/batches", json=b)
submit_business = lambda b: requests.post(f"{BASE_URL}/business-batches", json=b)

nodes = [
    {"node_id":"engineering_consulting_service","canonical_name_zh":"工程咨询服务","canonical_name_en":"Engineering Consulting Service","aliases":["工程咨询","技术咨询"],"definition":"为工程项目投资决策、设计优化、施工管理、竣工验收等全过程提供专业技术咨询和管理服务的智力密集型服务活动。","entity_type":"service","evidence":[{"source_title":"甘咨询 主营业务","quote":"经营范围:工程咨询服务"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"nylon_filament","canonical_name_zh":"锦纶长丝","canonical_name_en":"Nylon Filament Yarn","aliases":["尼龙长丝","PA长丝"],"definition":"以聚酰胺（锦纶）为原料，通过熔融纺丝工艺制成的高强度连续长丝，具有优异的耐磨性、弹性和抗皱性，广泛用于运动服装、户外用品、内衣和产业用纺织品。","entity_type":"material","evidence":[{"source_title":"恒申新材 主营业务","quote":"主要业务:锦纶纤维业务,主要产品:锦纶6切片,锦纶长丝,锦纶短纤"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"nylon_chip","canonical_name_zh":"锦纶切片","canonical_name_en":"Nylon Chip","aliases":["尼龙切片","PA6切片"],"definition":"聚酰胺（锦纶）的颗粒状半成品，是生产锦纶长丝、短纤和工程塑料的原料，通过己内酰胺聚合反应制得。","entity_type":"material","evidence":[{"source_title":"恒申新材 主营业务","quote":"主要产品:锦纶6切片,锦纶长丝,锦纶短纤"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"home_materials_retail","canonical_name_zh":"家居建材零售","canonical_name_en":"Home Materials Retail","aliases":["建材零售","家居零售"],"definition":"面向消费者或承包商销售家具、装饰材料、卫浴洁具、灯具、地板、门窗等家居及建筑装修材料的零售业态，通常以商场、建材超市或电商平台形式运营。","entity_type":"service","evidence":[{"source_title":"居然智家 主营业务","quote":"主要业务:大家居行业,从事的业务范围包括:连锁家居卖场业务,购物中心及现代百货业务,数字化智能家装业务,招商运营业务,本次变更后,公司的主营业务及发展方向没有发生重大变化"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"gypsum_board","canonical_name_zh":"石膏板","canonical_name_en":"Gypsum Board","aliases":["纸面石膏板","石膏墙板"],"definition":"以建筑石膏为主要原料，掺入适量添加剂和纤维，与护面纸牢固粘结而成的轻质建筑板材，广泛用于室内隔墙、吊顶和装饰装修。","entity_type":"material","evidence":[{"source_title":"北新建材 主营业务","quote":"主营业务:新型建材的生产和销售,主要产品:石膏板,龙骨,防水卷材,防水涂料等"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"light_steel_keel","canonical_name_zh":"轻钢龙骨","canonical_name_en":"Light Steel Keel","aliases":["龙骨","隔墙龙骨"],"definition":"以冷轧镀锌钢带为原料，经冲压成型的薄壁型钢构件，用于石膏板隔墙和吊顶系统的骨架支撑，具有自重轻、强度高、施工便捷等优点。","entity_type":"component","evidence":[{"source_title":"北新建材 主营业务","quote":"主要产品:石膏板,龙骨,防水卷材,防水涂料等"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"mineral_wool_board","canonical_name_zh":"矿棉板","canonical_name_en":"Mineral Wool Board","aliases":["矿棉天花板","岩棉板"],"definition":"以矿渣棉或岩棉为主要原料，加入适量粘结剂，经成型、干燥、固化等工艺制成的多孔轻质板材，主要用于室内吊顶，兼具吸声、隔热和防火功能。","entity_type":"material","evidence":[{"source_title":"北新建材 经营范围","quote":"一般项目:新材料技术研发;隔热和隔音材料制造;隔热和隔音材料销售"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"potassium_sulfate","canonical_name_zh":"硫酸钾","canonical_name_en":"Potassium Sulfate","aliases":["K2SO4"],"definition":"一种重要的无氯钾肥，含钾量约50%、硫约18%，适用于烟草、马铃薯、葡萄、柑橘等忌氯作物，也是制备其他钾盐和复合肥的原料。","entity_type":"material","evidence":[{"source_title":"盐湖股份 主营业务","quote":"主要业务:钾肥的生产和销售"}],"confidence":"HIGH","status":"ACTIVE"},
    {"node_id":"lithium_carbonate","canonical_name_zh":"碳酸锂","canonical_name_en":"Lithium Carbonate","aliases":["Li2CO3"],"definition":"锂的碳酸盐化合物，是制备锂离子电池正极材料、电解液和玻璃陶瓷工业的关键原料，也是锂产业链从盐湖卤水中提取锂的主要产品形式。","entity_type":"material","evidence":[{"source_title":"盐湖股份 经营范围","quote":"一般项目:碳酸锂生产"}],"confidence":"HIGH","status":"ACTIVE"}
]

edges = [
    {"edge_id":"flow_nylon_chip_to_filament","from_node":"nylon_chip","to_node":"nylon_filament","description":"锦纶切片熔融后纺丝制成锦纶长丝。","edge_namespace":"industrial_flow","edge_type":"material_flow","evidence":[{"source_title":"恒申新材 产业链","quote":"锦纶6切片→锦纶长丝"}],"confidence":"HIGH"},
    {"edge_id":"flow_gypsum_to_board","from_node":"gypsum","to_node":"gypsum_board","description":"石膏经加工制成石膏板。","edge_namespace":"industrial_flow","edge_type":"material_flow","evidence":[{"source_title":"北新建材 生产流程","quote":"石膏板生产"}],"confidence":"HIGH"},
    {"edge_id":"flow_keel_to_gypsum_board","from_node":"light_steel_keel","to_node":"gypsum_board","description":"轻钢龙骨作为石膏板隔墙的骨架支撑。","edge_namespace":"industrial_flow","edge_type":"composition","evidence":[{"source_title":"北新建材 产品应用","quote":"石膏板+龙骨系统"}],"confidence":"HIGH"},
    {"edge_id":"flow_potassium_chloride_to_fertilizer","from_node":"potassium_chloride","to_node":"chemical_fertilizer","description":"氯化钾作为原料用于生产化学肥料。","edge_namespace":"industrial_flow","edge_type":"material_flow","evidence":[{"source_title":"盐湖股份 产业链","quote":"氯化钾→钾肥"}],"confidence":"HIGH"},
    {"edge_id":"flow_lithium_carbonate_to_battery","from_node":"lithium_carbonate","to_node":"lithium_ion_battery","description":"碳酸锂用于生产锂离子电池正极材料和电解液。","edge_namespace":"industrial_flow","edge_type":"material_flow","evidence":[{"source_title":"盐湖股份 新能源布局","quote":"碳酸锂生产"}],"confidence":"HIGH"}
]

companies = [
    {"company_id":"gs_consulting","name_zh":"甘肃工程咨询集团股份有限公司","aliases":["甘咨询"],"stock_codes":["000779.SZ"],"description":"经营范围包括工程咨询服务和工程监理服务，是甘肃省重要的工程咨询企业。","country":"CN","province":"甘肃","city":"兰州市","founded_year":1998,"employee_count":687,"company_type":"public","status":"ACTIVE"},
    {"company_id":"henshen_new_material","name_zh":"恒申新材股份有限公司","aliases":["恒申新材"],"stock_codes":["000782.SZ"],"description":"主要业务为锦纶纤维业务，主要产品包括锦纶6切片、锦纶长丝、锦纶短纤等，是国内锦纶纤维行业的重要企业。","country":"CN","province":"福建","city":"福州市","founded_year":1994,"employee_count":4871,"company_type":"public","status":"ACTIVE"},
    {"company_id":"cj_securities","name_zh":"长江证券股份有限公司","aliases":["长江证券"],"stock_codes":["000783.SZ"],"description":"主要业务涵盖证券经纪、证券投资咨询、证券承销与保荐、证券自营、证券资产管理等综合金融服务。","country":"CN","province":"湖北","city":"武汉市","founded_year":1991,"employee_count":7203,"company_type":"public","status":"ACTIVE"},
    {"company_id":"juran_smart_home","name_zh":"居然智家新零售连锁集团有限公司","aliases":["居然智家","居然之家"],"stock_codes":["000785.SZ"],"description":"大家居行业企业，业务涵盖连锁家居卖场、购物中心及现代百货、数字化智能家装、招商运营等。","country":"CN","province":"北京","city":"北京市","founded_year":1999,"employee_count":7045,"company_type":"public","status":"ACTIVE"},
    {"company_id":"bnmc","name_zh":"北新集团建材股份有限公司","aliases":["北新建材"],"stock_codes":["000786.SZ"],"description":"主营业务为新型建材的生产和销售，主要产品包括石膏板、龙骨、防水卷材、防水涂料等，是全球最大的石膏板产业集团。","country":"CN","province":"北京","city":"北京市","founded_year":1997,"employee_count":28293,"company_type":"public","status":"ACTIVE"},
    {"company_id":"beida_pharm","name_zh":"北大医药股份有限公司","aliases":["北大医药"],"stock_codes":["000788.SZ"],"description":"主要业务为药品制造、销售及流通，产品涵盖化学原料药、化学药制剂、生物制品等。","country":"CN","province":"重庆","city":"重庆市","founded_year":1997,"employee_count":1199,"company_type":"public","status":"ACTIVE"},
    {"company_id":"wannianqing","name_zh":"江西万年青水泥股份有限公司","aliases":["万年青"],"stock_codes":["000789.SZ"],"description":"主要业务为水泥和混凝土的生产与销售，是江西省重要的水泥生产企业。","country":"CN","province":"江西","city":"南昌市","founded_year":1997,"employee_count":3092,"company_type":"public","status":"ACTIVE"},
    {"company_id":"huashen_tech","name_zh":"华神科技集团股份有限公司","aliases":["华神科技"],"stock_codes":["000790.SZ"],"description":"主要业务涵盖中成药制造、生物制品生产和医药流通，主要产品包括中西成药、生物制药等。","country":"CN","province":"四川","city":"成都市","founded_year":1988,"employee_count":596,"company_type":"public","status":"ACTIVE"},
    {"company_id":"gansu_energy","name_zh":"甘肃电投能源发展股份有限公司","aliases":["甘肃能源"],"stock_codes":["000791.SZ"],"description":"主要业务为水力发电和风力发电，是甘肃省重要的清洁能源发电企业。","country":"CN","province":"甘肃","city":"兰州市","founded_year":1997,"employee_count":1154,"company_type":"public","status":"ACTIVE"},
    {"company_id":"salt_lake","name_zh":"青海盐湖工业股份有限公司","aliases":["盐湖股份"],"stock_codes":["000792.SZ"],"description":"主要业务为钾肥的生产和销售，同时布局碳酸锂等新能源材料，是中国最大的钾肥生产基地。","country":"CN","province":"青海","city":"格尔木市","founded_year":1997,"employee_count":8463,"company_type":"public","status":"ACTIVE"}
]

exposures = [
    {"exposure_id":"exp_gs_consulting","company_id":"gs_consulting","node_id":"engineering_consulting_service","activity_type":"operate","role":"工程咨询服务提供商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"甘咨询 经营范围","quote":"经营范围:工程咨询服务"}],"status":"ACTIVE"},
    {"exposure_id":"exp_hs_nylon_filament","company_id":"henshen_new_material","node_id":"nylon_filament","activity_type":"produce","role":"锦纶长丝生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"恒申新材 主营业务","quote":"主要业务:锦纶纤维业务,主要产品:锦纶6切片,锦纶长丝,锦纶短纤"}],"status":"ACTIVE"},
    {"exposure_id":"exp_hs_nylon_chip","company_id":"henshen_new_material","node_id":"nylon_chip","activity_type":"produce","role":"锦纶切片生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"恒申新材 主营业务","quote":"主要产品:锦纶6切片"}],"status":"ACTIVE"},
    {"exposure_id":"exp_cj_brokerage","company_id":"cj_securities","node_id":"securities_brokerage","activity_type":"operate","role":"证券经纪服务商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"长江证券 主营业务","quote":"主要业务:证券经纪"}],"status":"ACTIVE"},
    {"exposure_id":"exp_cj_underwriting","company_id":"cj_securities","node_id":"securities_underwriting","activity_type":"operate","role":"证券承销保荐服务商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"长江证券 经营范围","quote":"证券承销与保荐"}],"status":"ACTIVE"},
    {"exposure_id":"exp_cj_asset_mgmt","company_id":"cj_securities","node_id":"asset_management_service","activity_type":"operate","role":"资产管理服务商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"长江证券 经营范围","quote":"证券资产管理"}],"status":"ACTIVE"},
    {"exposure_id":"exp_juran_retail","company_id":"juran_smart_home","node_id":"home_materials_retail","activity_type":"operate","role":"家居建材零售商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"居然智家 主营业务","quote":"主要业务:大家居行业,连锁家居卖场业务"}],"status":"ACTIVE"},
    {"exposure_id":"exp_juran_furniture","company_id":"juran_smart_home","node_id":"furniture","activity_type":"operate","role":"家具零售商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"居然智家 经营范围","quote":"家居用品销售;家具销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_bnmc_gypsum_board","company_id":"bnmc","node_id":"gypsum_board","activity_type":"produce","role":"石膏板生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"北新建材 主营业务","quote":"主要产品:石膏板,龙骨,防水卷材,防水涂料等"}],"status":"ACTIVE"},
    {"exposure_id":"exp_bnmc_keel","company_id":"bnmc","node_id":"light_steel_keel","activity_type":"produce","role":"轻钢龙骨生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"北新建材 主营业务","quote":"主要产品:石膏板,龙骨..."}],"status":"ACTIVE"},
    {"exposure_id":"exp_bnmc_mineral_wool","company_id":"bnmc","node_id":"mineral_wool_board","activity_type":"produce","role":"矿棉板生产商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"北新建材 经营范围","quote":"隔热和隔音材料制造;隔热和隔音材料销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_bd_pharm_product","company_id":"beida_pharm","node_id":"pharmaceutical_product","activity_type":"manufacture","role":"药品制造商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"北大医药 主营业务","quote":"主要业务:药品制造,销售及流通"}],"status":"ACTIVE"},
    {"exposure_id":"exp_wnq_cement","company_id":"wannianqing","node_id":"cement","activity_type":"produce","role":"水泥生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"万年青 主营业务","quote":"主要业务:水泥和混凝土的生产与销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_wnq_concrete","company_id":"wannianqing","node_id":"ready_mix_concrete","activity_type":"produce","role":"混凝土生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"万年青 主营业务","quote":"主要业务:水泥和混凝土的生产与销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_hshen_tcm","company_id":"huashen_tech","node_id":"traditional_chinese_medicine","activity_type":"manufacture","role":"中成药制造商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"华神科技 主营业务","quote":"主要业务涵盖中成药制造,生物制品生产"}],"status":"ACTIVE"},
    {"exposure_id":"exp_hshen_biological","company_id":"huashen_tech","node_id":"biological_product","activity_type":"manufacture","role":"生物制品制造商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"华神科技 主营业务","quote":"生物制品生产"}],"status":"ACTIVE"},
    {"exposure_id":"exp_gse_hydro","company_id":"gansu_energy","node_id":"hydro_power_generation","activity_type":"operate","role":"水电运营商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"甘肃能源 主营业务","quote":"主要业务:水力发电和风力发电"}],"status":"ACTIVE"},
    {"exposure_id":"exp_gse_wind","company_id":"gansu_energy","node_id":"wind_power_generation","activity_type":"operate","role":"风电运营商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"甘肃能源 主营业务","quote":"主要业务:水力发电和风力发电"}],"status":"ACTIVE"},
    {"exposure_id":"exp_gse_elec","company_id":"gansu_energy","node_id":"electricity_power","activity_type":"produce","role":"电力生产商","weight":0.8,"confidence":"HIGH","evidence":[{"source_title":"甘肃能源 经营范围","quote":"电力业务"}],"status":"ACTIVE"},
    {"exposure_id":"exp_sl_potassium_chloride","company_id":"salt_lake","node_id":"potassium_chloride","activity_type":"produce","role":"氯化钾生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"盐湖股份 主营业务","quote":"主要业务:钾肥的生产和销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_sl_fertilizer","company_id":"salt_lake","node_id":"chemical_fertilizer","activity_type":"produce","role":"钾肥生产商","weight":0.9,"confidence":"HIGH","evidence":[{"source_title":"盐湖股份 主营业务","quote":"主要业务:钾肥的生产和销售"}],"status":"ACTIVE"},
    {"exposure_id":"exp_sl_k2so4","company_id":"salt_lake","node_id":"potassium_sulfate","activity_type":"produce","role":"硫酸钾生产商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"盐湖股份 产品范围","quote":"钾肥产品"}],"status":"ACTIVE"},
    {"exposure_id":"exp_sl_lithium","company_id":"salt_lake","node_id":"lithium_carbonate","activity_type":"produce","role":"碳酸锂生产商","weight":0.7,"confidence":"HIGH","evidence":[{"source_title":"盐湖股份 经营范围","quote":"一般项目:碳酸锂生产"}],"status":"ACTIVE"}
]

if __name__ == "__main__":
    gb = {"batch_id":"batch_028_graph","task_description":"Batch 028: Industrial nodes and edges for 10 companies (000779-000792). Focus on engineering consulting, nylon fiber, home retail, gypsum board, pharmaceuticals, cement, clean energy, potash fertilizer.","nodes_to_upsert":nodes,"edges_to_upsert":edges,"rejected_or_pending":[]}
    bb = {"batch_id":"batch_028_business","task_description":"Batch 028: Company registrations and exposures for 10 companies (000779-000792).","industries_to_upsert":[],"industry_node_mappings_to_upsert":[],"companies_to_upsert":companies,"company_node_exposures_to_upsert":exposures}
    r1 = submit_graph(gb); print(f"Graph: {r1.status_code}", r1.json())
    r2 = submit_business(bb); print(f"Business: {r2.status_code}", r2.json())
