"""
Batch 003 产业图与公司视图构建脚本
为 data/stock_batches/batch_003.json 中的10家上市公司构建产业实体图和公司视图。
"""

import asyncio
import httpx
import json
from datetime import datetime

API_BASE = "http://localhost:8000/api/v1"

# ============================================================
# Evidence helper
# ============================================================

def ev(source_title: str, quote: str, source_url: str = ""):
    return {"source_title": source_title, "source_url": source_url or None, "quote": quote}


# ============================================================
# 新建产业节点 (IndustrialNode)
# ============================================================

NEW_NODES = [
    # ---- 医药链（国药一致）----
    {
        "node_id": "pharmaceutical_raw_material",
        "canonical_name_zh": "医药原料药",
        "canonical_name_en": "Pharmaceutical Raw Material",
        "aliases": ["原料药", "API", "活性药物成分"],
        "definition": "用于生产各类药品制剂的活性药物成分或化学原料，是制药工业的上游基础物料。",
        "entity_type": "material",
        "evidence": [ev(
            "国药一致2025年年度报告",
            "公司经营范围包括化学原料药、抗生素原料药的批发；药品是公司的核心产品，2025年药品收入639.87亿元。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "automotive_brake_system",
        "canonical_name_zh": "汽车制动系统",
        "canonical_name_en": "Automotive Brake System",
        "aliases": ["制动系统", "刹车系统"],
        "definition": "用于使行驶中的汽车减速或停止的成套装置，包括制动器、制动管路、制动助力器等核心部件。",
        "entity_type": "subsystem",
        "evidence": [ev(
            "富奥股份2024年年度报告",
            "公司主要产品包括底盘系统、环境系统、制动和传动系统、转向及安全系统、电子电器系统、发动机附件系统等六大系列。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "automotive_transmission_system",
        "canonical_name_zh": "汽车传动系统",
        "canonical_name_en": "Automotive Transmission System",
        "aliases": ["传动系统", "变速箱系统"],
        "definition": "将发动机输出的动力传递至驱动轮的成套装置，包括变速器、传动轴、差速器等部件。",
        "entity_type": "subsystem",
        "evidence": [ev(
            "富奥股份2024年年度报告",
            "公司主要产品包括底盘系统、环境系统、制动和传动系统、转向及安全系统、电子电器系统、发动机附件系统等六大系列。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "automotive_steering_system",
        "canonical_name_zh": "汽车转向系统",
        "canonical_name_en": "Automotive Steering System",
        "aliases": ["转向系统", "方向盘系统"],
        "definition": "控制汽车行驶方向的成套装置，包括转向机、转向柱、转向拉杆等核心部件。",
        "entity_type": "subsystem",
        "evidence": [ev(
            "富奥股份2024年年度报告",
            "公司主要产品包括底盘系统、环境系统、制动和传动系统、转向及安全系统、电子电器系统、发动机附件系统等六大系列。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "automotive_electronics",
        "canonical_name_zh": "汽车电子电器",
        "canonical_name_en": "Automotive Electronics",
        "aliases": ["汽车电子", "车载电子"],
        "definition": "安装在汽车上用于控制、监测和辅助驾驶功能的电子设备和电气系统，包括ECU、传感器、线束等。",
        "entity_type": "component",
        "evidence": [ev(
            "富奥股份2024年年度报告",
            "公司主要产品包括底盘系统、环境系统、制动和传动系统、转向及安全系统、电子电器系统、发动机附件系统等六大系列。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "automotive_engine_accessory",
        "canonical_name_zh": "汽车发动机附件",
        "canonical_name_en": "Automotive Engine Accessory",
        "aliases": ["发动机附件", "发动机周边部件"],
        "definition": "围绕汽车发动机工作的配套零部件，包括水泵、发电机、起动机、涡轮增压器等。",
        "entity_type": "component",
        "evidence": [ev(
            "富奥股份2024年年度报告",
            "公司主要产品包括底盘系统、环境系统、制动和传动系统、转向及安全系统、电子电器系统、发动机附件系统等六大系列。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "automotive_environment_system",
        "canonical_name_zh": "汽车环境系统",
        "canonical_name_en": "Automotive Environment System",
        "aliases": ["汽车空调系统", "热管理系统", "环境系统"],
        "definition": "用于调节汽车内部温度和空气质量的成套系统，包括空调压缩机、冷凝器、蒸发器、暖风芯体等。",
        "entity_type": "subsystem",
        "evidence": [ev(
            "富奥股份2024年年度报告",
            "公司主要产品包括底盘系统、环境系统、制动和传动系统、转向及安全系统、电子电器系统、发动机附件系统等六大系列。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    # ---- 地产链（大悦城）----
    {
        "node_id": "industrial_property",
        "canonical_name_zh": "工业物业",
        "canonical_name_en": "Industrial Property",
        "aliases": ["工业厂房", "产业园区", "工业地产"],
        "definition": "用于工业生产、仓储物流等用途的建筑物及附属设施，包括标准厂房、仓库、研发中心等。",
        "entity_type": "component",
        "evidence": [ev(
            "大悦城2025年年度报告",
            "公司主营业务为房地产开发、经营、销售、出租及管理住宅、商用物业，经营业态涵盖住宅、商业地产及部分产业地产。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "hotel_operation_service",
        "canonical_name_zh": "酒店经营服务",
        "canonical_name_en": "Hotel Operation Service",
        "aliases": ["酒店服务", "酒店运营"],
        "definition": "为旅客提供住宿、餐饮、会议等综合性服务的商业经营活动。",
        "entity_type": "service",
        "evidence": [ev(
            "大悦城2025年年度报告",
            "公司主要产品包括服务为住宅、商业物业、工业物业、酒店经营。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    # ---- 高科技/IT链（深桑达A、神州数码）----
    {
        "node_id": "high_tech_industrial_engineering",
        "canonical_name_zh": "高科技产业工程服务",
        "canonical_name_en": "High-Tech Industrial Engineering Service",
        "aliases": ["高科技工程", "产业工程服务", "洁净室工程"],
        "definition": "为半导体、新型显示、生物医药等高科技产业提供厂房建设、洁净室设计施工、设备安装调试等工程总承包服务。",
        "entity_type": "service",
        "evidence": [ev(
            "深桑达A2024年年度报告",
            "高科技产业工程服务收入629.69亿元，公司在半导体、新型显示器等优势行业稳固地位，并拓展海外市场。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "big_data_service",
        "canonical_name_zh": "大数据服务",
        "canonical_name_en": "Big Data Service",
        "aliases": ["数据服务", "数据治理服务"],
        "definition": "基于数据基础设施，为客户提供数据采集、存储、治理、分析、运营等全生命周期服务。",
        "entity_type": "service",
        "evidence": [ev(
            "深桑达A2024年年度报告",
            "公司作为中国电子在数据要素业务的排头兵，已形成中国电子云数据智能平台产品、数据港数据运营产品，并提供数据治理服务。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "information_system_integration",
        "canonical_name_zh": "信息系统集成服务",
        "canonical_name_en": "Information System Integration Service",
        "aliases": ["系统集成", "IT集成服务"],
        "definition": "将计算机软件、硬件、网络通信等技术和产品集成为能够满足用户特定需求的信息系统整体解决方案。",
        "entity_type": "service",
        "evidence": [ev(
            "深桑达A2024年年度报告",
            "公司面向国防、能源、金融、交通、卫健等关键行业提供数字化解决方案，致力于成为数字基础设施和数据资源体系的建设者和运营商。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "communication_device",
        "canonical_name_zh": "通信设备",
        "canonical_name_en": "Communication Device",
        "aliases": ["通信产品", "通讯设备"],
        "definition": "用于实现信息传输和通信功能的电子设备，包括基站设备、路由器、交换机、光通信设备等。",
        "entity_type": "device",
        "evidence": [ev(
            "深桑达A2024年年度报告",
            "公司研发、生产、销售通信设备、交通通讯设备、计算机及软件、办公自动化设备等。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "module_power_supply",
        "canonical_name_zh": "模块电源",
        "canonical_name_en": "Module Power Supply",
        "aliases": ["电源模块", "模块化电源"],
        "definition": "采用模块化设计、可即插即用的标准化电源转换装置，广泛应用于通信、工业控制、轨道交通等领域。",
        "entity_type": "component",
        "evidence": [ev(
            "深桑达A2024年年度报告",
            "公司主要产品包括彩电回扫变压器、手机、模块电源等。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "laptop_computer",
        "canonical_name_zh": "笔记本电脑",
        "canonical_name_en": "Laptop Computer",
        "aliases": ["笔记本", "便携电脑"],
        "definition": "集计算、显示、输入输出于一体的小型便携式个人计算机。",
        "entity_type": "device",
        "evidence": [ev(
            "神州数码2025年年度报告",
            "公司主营业务包括移动办公设备、笔记本电脑、显示设备、服务器、存储设备、网络设备、计算机配件。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "network_equipment",
        "canonical_name_zh": "网络设备",
        "canonical_name_en": "Network Equipment",
        "aliases": ["网络产品", "网络硬件"],
        "definition": "用于构建计算机网络、实现数据传输和交换的硬件设备，包括路由器、交换机、防火墙等。",
        "entity_type": "device",
        "evidence": [ev(
            "神州数码2025年年度报告",
            "公司主营业务包括移动办公设备、笔记本电脑、显示设备、服务器、存储设备、网络设备、计算机配件。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "storage_equipment",
        "canonical_name_zh": "存储设备",
        "canonical_name_en": "Storage Equipment",
        "aliases": ["存储产品", "数据存储设备"],
        "definition": "用于数据存储、备份和管理的硬件设备，包括磁盘阵列、NAS、SAN存储系统等。",
        "entity_type": "device",
        "evidence": [ev(
            "神州数码2025年年度报告",
            "公司主营业务包括移动办公设备、笔记本电脑、显示设备、服务器、存储设备、网络设备、计算机配件。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "office_equipment",
        "canonical_name_zh": "办公设备",
        "canonical_name_en": "Office Equipment",
        "aliases": ["办公自动化设备", "OA设备"],
        "definition": "用于办公场景的电子设备和器具，包括打印机、复印机、扫描仪、投影仪等。",
        "entity_type": "device",
        "evidence": [ev(
            "神州数码2025年年度报告",
            "公司主营业务包括移动办公设备、笔记本电脑、显示设备、服务器、存储设备、网络设备、计算机配件。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    # ---- 环保链（中国天楹）----
    {
        "node_id": "waste_incineration_equipment",
        "canonical_name_zh": "垃圾焚烧发电设备",
        "canonical_name_en": "Waste Incineration Power Generation Equipment",
        "aliases": ["焚烧炉", "垃圾焚烧设备"],
        "definition": "用于将城市生活垃圾通过高温焚烧转化为热能并驱动发电机组发电的成套设备系统。",
        "entity_type": "device",
        "evidence": [ev(
            "中国天楹2024年年度报告",
            "公司提供优质的垃圾焚烧发电整体解决方案及行业领先的新型核心装备，涉及生活垃圾焚烧发电等设备的设计、制造、安装、调试、运营及移交。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "municipal_waste_treatment",
        "canonical_name_zh": "城市生活垃圾处理服务",
        "canonical_name_en": "Municipal Waste Treatment Service",
        "aliases": ["垃圾处理服务", "生活垃圾处理"],
        "definition": "对城市居民产生的日常生活垃圾进行收集、运输、分类、处理和处置的综合服务。",
        "entity_type": "service",
        "evidence": [ev(
            "中国天楹2024年年度报告",
            "公司前端业务涵盖城乡环卫一体化服务、智慧垃圾分类系统、再生资源回收等基础环节；末端聚焦于垃圾焚烧发电、危废处理、餐厨垃圾资源化等可再生能源领域。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "urban_sanitation_service",
        "canonical_name_zh": "城乡环卫一体化服务",
        "canonical_name_en": "Urban Sanitation Service",
        "aliases": ["环卫服务", "城市清洁服务"],
        "definition": "为城市和乡村提供道路清扫、垃圾收集转运、公厕管理、绿化养护等环境卫生综合服务。",
        "entity_type": "service",
        "evidence": [ev(
            "中国天楹2024年年度报告",
            "公司前端业务涵盖城乡环卫一体化服务、智慧垃圾分类系统、再生资源回收等基础环节。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    # ---- 能源链（深南电A）----
    {
        "node_id": "heating_supply",
        "canonical_name_zh": "供热服务",
        "canonical_name_en": "Heating Supply Service",
        "aliases": ["供暖服务", "热力供应"],
        "definition": "通过热电联产或集中供热系统向工业和居民用户供应蒸汽和热水的服务。",
        "entity_type": "service",
        "evidence": [ev(
            "深南电A2025年年度报告",
            "公司主要业务为生产经营供电供热，从事发电厂的相关技术咨询和技术服务。启东项目等9个垃圾焚烧发电项目开展供汽供热业务。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "energy_storage_technology",
        "canonical_name_zh": "储能技术服务",
        "canonical_name_en": "Energy Storage Technology Service",
        "aliases": ["储能服务", "储能技术"],
        "definition": "为电力系统提供储能系统设计、集成、运维和优化调度的技术服务，包括电化学储能、重力储能等技术路线。",
        "entity_type": "service",
        "evidence": [ev(
            "深南电A2025年年度报告",
            "公司提供储能技术服务、合同能源管理、节能管理服务等技术服务。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    # ---- 运输装备链（中集集团）----
    {
        "node_id": "road_transport_vehicle",
        "canonical_name_zh": "道路运输车辆",
        "canonical_name_en": "Road Transport Vehicle",
        "aliases": ["半挂车", "罐式运输车", "货运车辆"],
        "definition": "在道路上行驶、用于货物运输的各类车辆，包括半挂车、罐式运输车、冷藏车等专用车辆。",
        "entity_type": "device",
        "evidence": [ev(
            "中集集团2024年年度报告",
            "中集车辆是全球排名第一的半挂车生产制造商。主要业务为现代化交通运输装备、能源、化工及液态食品装备、海洋工程装备、物流服务、空港装备的制造及服务业务。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "energy_chemical_equipment",
        "canonical_name_zh": "能源化工装备",
        "canonical_name_en": "Energy and Chemical Equipment",
        "aliases": ["能源装备", "化工装备", "LNG装备"],
        "definition": "用于能源、化工及液态食品行业的各类型运输、储存及加工装备，包括LNG储罐、罐式集装箱、化工储罐等。",
        "entity_type": "device",
        "evidence": [ev(
            "中集集团2024年年度报告",
            "能源、化工及液态食品装备业务板块主要从事广泛用于能源、化工及液态食品装备三个行业的各类型运输、储存及加工装备的设计、开发、制造、工程、销售及运作。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "offshore_engineering_equipment",
        "canonical_name_zh": "海洋工程装备",
        "canonical_name_en": "Offshore Engineering Equipment",
        "aliases": ["海工装备", "FPSO", "风电安装船"],
        "definition": "用于海洋资源开发和海上工程作业的成套装备，包括FPSO浮式生产储卸油装置、海上风电安装船、半潜式钻井平台等。",
        "entity_type": "device",
        "evidence": [ev(
            "中集集团2024年年度报告",
            "海洋工程业务集设计、采购、生产、建造、调试、运营一体化运作模式，提供批量化、产业化总包建造高端海洋工程装备。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "airport_equipment",
        "canonical_name_zh": "空港装备",
        "canonical_name_en": "Airport Equipment",
        "aliases": ["机场设备", "登机桥", "地面支持设备"],
        "definition": "用于机场运营的各类设备和系统，包括旅客登机桥、机场地面支持设备、行李处理系统、机场物流系统等。",
        "entity_type": "device",
        "evidence": [ev(
            "中集集团2024年年度报告",
            "中集天达为全球登机桥主要供货商之一。空港与物流装备业务主要包括旅客登机桥、机场地面支持设备、机场行李处理系统、物流处理系统及智能仓储系统。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
    {
        "node_id": "logistics_service",
        "canonical_name_zh": "物流服务",
        "canonical_name_en": "Logistics Service",
        "aliases": ["物流运输服务", "货运服务"],
        "definition": "为客户提供货物运输、仓储管理、供应链优化等综合性物流解决方案的服务。",
        "entity_type": "service",
        "evidence": [ev(
            "中集集团2024年年度报告",
            "本集团以物流服务业务为依托，提供物流专业领域的产品及服务。",
        )],
        "confidence": "HIGH",
        "status": "ACTIVE",
    },
]


# ============================================================
# 新建产业流边 (GraphEdge - industrial_flow)
# ============================================================

EDGES = [
    # 医药链
    {
        "edge_id": "flow_api_to_pharma",
        "from_node": "pharmaceutical_raw_material",
        "to_node": "pharmaceutical_product",
        "edge_namespace": "industrial_flow",
        "edge_type": "material_flow",
        "description": "医药原料药经过制剂加工成为药品，原料药是制药工业的上游基础物料。",
        "evidence": [ev("国药一致2025年年度报告", "公司经营范围包括化学原料药、抗生素原料药的批发；药品是公司的核心产品。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_device_to_pharma_dist",
        "from_node": "medical_device",
        "to_node": "pharmaceutical_distribution",
        "edge_namespace": "industrial_flow",
        "edge_type": "service_flow",
        "description": "医疗器械通过医药分销渠道流向医疗机构和终端用户。",
        "evidence": [ev("国药一致2025年年度报告", "公司2025年器械耗材收入76.93亿元，通过医药批发和零售渠道分销。")],
        "confidence": "HIGH",
    },
    # 汽车零部件链
    {
        "edge_id": "flow_steel_to_brake",
        "from_node": "automotive_steel",
        "to_node": "automotive_brake_system",
        "edge_namespace": "industrial_flow",
        "edge_type": "material_flow",
        "description": "汽车钢材作为原材料流入汽车制动系统的生产制造环节。",
        "evidence": [ev("富奥股份2024年年度报告", "公司主要产品包括制动和传动系统，为众多国内整车企业配套，钢材是核心原材料。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_steel_to_transmission",
        "from_node": "automotive_steel",
        "to_node": "automotive_transmission_system",
        "edge_namespace": "industrial_flow",
        "edge_type": "material_flow",
        "description": "汽车钢材作为原材料流入汽车传动系统的生产制造环节。",
        "evidence": [ev("富奥股份2024年年度报告", "公司主要产品包括制动和传动系统，为众多国内整车企业配套。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_steel_to_steering",
        "from_node": "automotive_steel",
        "to_node": "automotive_steering_system",
        "edge_namespace": "industrial_flow",
        "edge_type": "material_flow",
        "description": "汽车钢材作为原材料流入汽车转向系统的生产制造环节。",
        "evidence": [ev("富奥股份2024年年度报告", "公司主要产品包括转向及安全系统，为众多国内整车企业配套。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_steel_to_engine_acc",
        "from_node": "automotive_steel",
        "to_node": "automotive_engine_accessory",
        "edge_namespace": "industrial_flow",
        "edge_type": "material_flow",
        "description": "汽车钢材作为原材料流入汽车发动机附件的生产制造环节。",
        "evidence": [ev("富奥股份2024年年度报告", "公司主要产品包括发动机附件系统，为众多国内整车企业配套。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_steel_to_env",
        "from_node": "automotive_steel",
        "to_node": "automotive_environment_system",
        "edge_namespace": "industrial_flow",
        "edge_type": "material_flow",
        "description": "汽车钢材作为原材料流入汽车环境系统（空调/热管理）的生产制造环节。",
        "evidence": [ev("富奥股份2024年年度报告", "公司主要产品包括环境系统，为众多国内整车企业配套。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_alum_to_brake",
        "from_node": "automotive_aluminum",
        "to_node": "automotive_brake_system",
        "edge_namespace": "industrial_flow",
        "edge_type": "material_flow",
        "description": "汽车铝材作为轻量化材料用于汽车制动系统的部分零部件制造。",
        "evidence": [ev("富奥股份2024年年度报告", "公司主要产品包括制动和传动系统，铝材是核心轻量化原材料之一。")],
        "confidence": "MEDIUM",
    },
    # 地产链
    {
        "edge_id": "flow_construction_to_industrial",
        "from_node": "construction_service",
        "to_node": "industrial_property",
        "edge_namespace": "industrial_flow",
        "edge_type": "composition",
        "description": "建筑施工服务将各类建筑材料组装建造成为工业物业（厂房、仓库等）。",
        "evidence": [ev("大悦城2025年年度报告", "公司主营业务为房地产开发、经营、销售、出租及管理住宅、商用物业，经营业态涵盖住宅、商业地产及部分产业地产。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_industrial_to_mgmt",
        "from_node": "industrial_property",
        "to_node": "property_management_service",
        "edge_namespace": "industrial_flow",
        "edge_type": "service_flow",
        "description": "工业物业建成后需要物业管理服务进行日常运营和维护。",
        "evidence": [ev("大悦城2025年年度报告", "公司经营业态涵盖住宅、商业地产及部分产业地产，提供出租及管理住宅、商用物业服务。")],
        "confidence": "HIGH",
    },
    # 高科技/IT链
    {
        "edge_id": "flow_server_to_bigdata",
        "from_node": "server_hardware",
        "to_node": "big_data_service",
        "edge_namespace": "industrial_flow",
        "edge_type": "capability_supply",
        "description": "服务器硬件为大数据服务提供底层算力和存储支撑能力。",
        "evidence": [ev("深桑达A2024年年度报告", "公司基于中国电子云的高安全算力基础设施，主动开展数据基础设施建设探索和实践。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_server_to_integration",
        "from_node": "server_hardware",
        "to_node": "information_system_integration",
        "edge_namespace": "industrial_flow",
        "edge_type": "capability_supply",
        "description": "服务器硬件为信息系统集成服务提供底层基础设施能力支撑。",
        "evidence": [ev("深桑达A2024年年度报告", "公司面向国防、能源、金融、交通、卫健等关键行业提供数字化解决方案。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_semi_to_laptop",
        "from_node": "semiconductor_device",
        "to_node": "laptop_computer",
        "edge_namespace": "industrial_flow",
        "edge_type": "composition",
        "description": "半导体器件（CPU、内存控制器等）是笔记本电脑的核心组成部件。",
        "evidence": [ev("行业常识", "笔记本电脑的核心组件包括CPU、GPU、内存等半导体器件。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_display_to_laptop",
        "from_node": "display_module",
        "to_node": "laptop_computer",
        "edge_namespace": "industrial_flow",
        "edge_type": "composition",
        "description": "显示模组是笔记本电脑屏幕的核心组成部分。",
        "evidence": [ev("行业常识", "笔记本电脑的显示屏由液晶面板、背光模组、驱动电路等组成。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_semi_to_network",
        "from_node": "semiconductor_device",
        "to_node": "network_equipment",
        "edge_namespace": "industrial_flow",
        "edge_type": "composition",
        "description": "半导体器件（交换芯片、路由芯片等）是网络设备的核心组成部件。",
        "evidence": [ev("行业常识", "路由器、交换机的核心功能由专用半导体芯片实现。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_semi_to_storage",
        "from_node": "semiconductor_device",
        "to_node": "storage_equipment",
        "edge_namespace": "industrial_flow",
        "edge_type": "composition",
        "description": "半导体器件（存储控制器、SSD主控芯片等）是存储设备的核心组成部件。",
        "evidence": [ev("行业常识", "现代存储设备依赖半导体控制器和闪存芯片实现数据存储。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_hw_to_office",
        "from_node": "it_hardware",
        "to_node": "office_equipment",
        "edge_namespace": "industrial_flow",
        "edge_type": "composition",
        "description": "IT硬件组件组装构成办公设备（打印机、复印机等办公自动化设备）。",
        "evidence": [ev("行业常识", "办公自动化设备由各类电子硬件组件组装而成。")],
        "confidence": "MEDIUM",
    },
    # 环保链
    {
        "edge_id": "flow_equipment_to_wte",
        "from_node": "waste_incineration_equipment",
        "to_node": "waste_to_energy",
        "edge_namespace": "industrial_flow",
        "edge_type": "capability_supply",
        "description": "垃圾焚烧发电设备为垃圾焚烧发电服务提供核心技术和装备支撑能力。",
        "evidence": [ev("中国天楹2024年年度报告", "公司提供优质的垃圾焚烧发电整体解决方案及行业领先的新型核心装备。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_waste_to_wte",
        "from_node": "municipal_waste_treatment",
        "to_node": "waste_to_energy",
        "edge_namespace": "industrial_flow",
        "edge_type": "service_flow",
        "description": "城市生活垃圾处理服务将收集的垃圾转运至焚烧发电厂进行能源化利用。",
        "evidence": [ev("中国天楹2024年年度报告", "公司前端业务涵盖城乡环卫一体化服务；末端聚焦于垃圾焚烧发电。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_sanitation_to_waste",
        "from_node": "urban_sanitation_service",
        "to_node": "municipal_waste_treatment",
        "edge_namespace": "industrial_flow",
        "edge_type": "service_flow",
        "description": "城乡环卫一体化服务负责垃圾的收集和初级分类，为后续垃圾处理服务提供原料。",
        "evidence": [ev("中国天楹2024年年度报告", "公司前端业务涵盖城乡环卫一体化服务、智慧垃圾分类系统。")],
        "confidence": "HIGH",
    },
    # 能源链
    {
        "edge_id": "flow_coal_power_to_heat",
        "from_node": "coal_power_generation",
        "to_node": "heating_supply",
        "edge_namespace": "industrial_flow",
        "edge_type": "energy_flow",
        "description": "燃煤发电厂通过热电联产同时生产电力和蒸汽，向外供应热能。",
        "evidence": [ev("深南电A2025年年度报告", "公司主要业务为生产经营供电供热，从事发电厂的相关技术咨询和技术服务。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_gas_power_to_heat",
        "from_node": "gas_power_generation",
        "to_node": "heating_supply",
        "edge_namespace": "industrial_flow",
        "edge_type": "energy_flow",
        "description": "燃气发电厂通过热电联产同时生产电力和蒸汽，向外供应热能。",
        "evidence": [ev("深南电A2025年年度报告", "公司主要业务为生产经营供电供热。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_elec_to_storage",
        "from_node": "electricity_power",
        "to_node": "energy_storage_technology",
        "edge_namespace": "industrial_flow",
        "edge_type": "energy_flow",
        "description": "电力是储能技术服务的输入能源，储能系统将电能转化为其他形式储存并在需要时释放。",
        "evidence": [ev("深南电A2025年年度报告", "公司提供储能技术服务、合同能源管理、节能管理服务等技术服务。")],
        "confidence": "HIGH",
    },
    # 运输装备链
    {
        "edge_id": "flow_steel_to_road_vehicle",
        "from_node": "steel_sheet",
        "to_node": "road_transport_vehicle",
        "edge_namespace": "industrial_flow",
        "edge_type": "composition",
        "description": "冷轧钢板是制造半挂车、罐式运输车等道路运输车辆车身的主要材料。",
        "evidence": [ev("中集集团2024年年度报告", "中集车辆是全球排名第一的半挂车生产制造商，钢材是核心原材料。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_container_to_logistics",
        "from_node": "container",
        "to_node": "logistics_service",
        "edge_namespace": "industrial_flow",
        "edge_type": "service_flow",
        "description": "集装箱作为标准化运输单元，支撑现代物流服务的高效运作。",
        "evidence": [ev("中集集团2024年年度报告", "本集团以物流服务业务为依托，提供物流专业领域的产品及服务。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_road_vehicle_to_logistics",
        "from_node": "road_transport_vehicle",
        "to_node": "logistics_service",
        "edge_namespace": "industrial_flow",
        "edge_type": "service_flow",
        "description": "道路运输车辆是物流服务的关键运载工具。",
        "evidence": [ev("中集集团2024年年度报告", "本集团以物流服务业务为依托，提供物流专业领域的产品及服务。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_echem_to_logistics",
        "from_node": "energy_chemical_equipment",
        "to_node": "logistics_service",
        "edge_namespace": "industrial_flow",
        "edge_type": "service_flow",
        "description": "罐式集装箱等能源化工装备用于运输化学品和液态食品，是特种物流服务的重要组成部分。",
        "evidence": [ev("中集集团2024年年度报告", "能源、化工及液态食品装备业务板块主要从事各类型运输、储存及加工装备。")],
        "confidence": "HIGH",
    },
    {
        "edge_id": "flow_offshore_to_shipping",
        "from_node": "offshore_engineering_equipment",
        "to_node": "shipping_service",
        "edge_namespace": "industrial_flow",
        "edge_type": "service_flow",
        "description": "海洋工程装备（如FPSO、风电安装船）为海上油气开采和航运服务提供关键装备支撑。",
        "evidence": [ev("中集集团2024年年度报告", "海洋工程业务提供批量化、产业化总包建造高端海洋工程装备。")],
        "confidence": "HIGH",
    },
]


# ============================================================
# 公司档案 (Company)
# ============================================================

COMPANIES = [
    {
        "company_id": "sinopharm_unified",
        "name_zh": "国药集团一致药业股份有限公司",
        "name_en": "Sinopharm Group Unified Pharmaceutical Co., Ltd.",
        "aliases": ["国药一致"],
        "stock_codes": ["000028.SZ"],
        "description": "中国医药集团旗下医药商业平台，主要从事医药批发、医药零售及制药业务，2025年营收734.16亿元。",
        "country": "CN",
        "province": "广东",
        "city": "深圳市",
        "founded_year": 1986,
        "employee_count": 28336,
        "revenue_cny": 73415858423.13,
        "market_cap_cny": 13246248833.0,
        "net_profit_cny": 1135926834.84,
        "company_type": "public",
        "status": "ACTIVE",
    },
    {
        "company_id": "shenzhen_fang_a",
        "name_zh": "深圳经济特区房地产(集团)股份有限公司",
        "name_en": "Shenzhen Special Economic Zone Real Estate & Properties (Group) Co., Ltd.",
        "aliases": ["深深房A"],
        "stock_codes": ["000029.SZ"],
        "description": "深圳老牌房地产开发企业，主要从事房地产开发、物业租赁和物业管理业务，2025年营收14.83亿元。",
        "country": "CN",
        "province": "广东",
        "city": "深圳市",
        "founded_year": 1986,
        "employee_count": 210,
        "revenue_cny": 1482872299.36,
        "market_cap_cny": 25797330000.0,
        "net_profit_cny": 99956003.75,
        "company_type": "public",
        "status": "ACTIVE",
    },
    {
        "company_id": "fawer_parts",
        "name_zh": "富奥汽车零部件股份有限公司",
        "name_en": "FAWER Automotive Parts Limited Company",
        "aliases": ["富奥股份"],
        "stock_codes": ["000030.SZ"],
        "description": "中国知名汽车零部件制造企业，一汽集团旗下核心零部件平台，产品涵盖底盘系统、环境系统、制动传动、转向安全、电子电器、发动机附件六大系列，2025年营收174.10亿元。",
        "country": "CN",
        "province": "吉林",
        "city": "长春市",
        "founded_year": 1988,
        "employee_count": 8032,
        "revenue_cny": 17410397362.62,
        "market_cap_cny": 8100309080.0,
        "net_profit_cny": 702615804.9,
        "company_type": "public",
        "status": "ACTIVE",
    },
    {
        "company_id": "joy_city",
        "name_zh": "大悦城控股集团股份有限公司",
        "name_en": "Joy City Property Group Limited",
        "aliases": ["大悦城"],
        "stock_codes": ["000031.SZ"],
        "description": "中粮集团旗下房地产平台，主要从事住宅、商业地产、工业物业开发及酒店经营，2025年营收308.92亿元。",
        "country": "CN",
        "province": "广东",
        "city": "深圳市",
        "founded_year": 1993,
        "employee_count": 6189,
        "revenue_cny": 30892372928.84,
        "market_cap_cny": 11315867215.0,
        "net_profit_cny": -2350270677.56,
        "company_type": "public",
        "status": "ACTIVE",
    },
    {
        "company_id": "sunda_a",
        "name_zh": "深圳市桑达实业股份有限公司",
        "name_en": "Shenzhen Sunda Industrial Co., Ltd.",
        "aliases": ["深桑达A"],
        "stock_codes": ["000032.SZ"],
        "description": "中国电子旗下重要二级企业，聚焦高科技产业工程服务（半导体/新型显示洁净室工程）和数字与信息服务（中国电子云、数据创新），2025年营收491.70亿元。",
        "country": "CN",
        "province": "广东",
        "city": "深圳市",
        "founded_year": 1993,
        "employee_count": 20005,
        "revenue_cny": 49170356917.15,
        "market_cap_cny": 23319290978.0,
        "net_profit_cny": -127069431.4,
        "company_type": "public",
        "status": "ACTIVE",
    },
    {
        "company_id": "digital_china",
        "name_zh": "神州数码集团股份有限公司",
        "name_en": "Digital China Group Co., Ltd.",
        "aliases": ["神州数码"],
        "stock_codes": ["000034.SZ"],
        "description": "中国领先的IT分销和数字化服务企业，主营笔记本电脑、服务器、存储、网络设备等IT硬件分销及云服务，2025年营收1437.51亿元。",
        "country": "CN",
        "province": "广东",
        "city": "深圳市",
        "founded_year": 1982,
        "employee_count": 5548,
        "revenue_cny": 143751044503.13,
        "market_cap_cny": 29556622003.0,
        "net_profit_cny": 522943843.22,
        "company_type": "public",
        "status": "ACTIVE",
    },
    {
        "company_id": "china_tianying",
        "name_zh": "中国天楹股份有限公司",
        "name_en": "China Tianying Co., Ltd.",
        "aliases": ["中国天楹"],
        "stock_codes": ["000035.SZ"],
        "description": "环保+新能源双轮驱动企业，主营垃圾焚烧发电运营、环保装备制造、城乡环卫服务及风力发电，2025年营收52.83亿元。",
        "country": "CN",
        "province": "江苏",
        "city": "南通市",
        "founded_year": 1984,
        "employee_count": 19595,
        "revenue_cny": 5283464987.58,
        "market_cap_cny": 14304316286.0,
        "net_profit_cny": 283949932.62,
        "company_type": "public",
        "status": "ACTIVE",
    },
    {
        "company_id": "hualian_holding",
        "name_zh": "华联控股股份有限公司",
        "name_en": "Hualian Holdings Co., Ltd.",
        "aliases": ["华联控股"],
        "stock_codes": ["000036.SZ"],
        "description": "深圳房地产开发企业，主要从事房地产开发和自有物业租赁管理业务，2025年营收6.21亿元。",
        "country": "CN",
        "province": "广东",
        "city": "深圳市",
        "founded_year": 1989,
        "employee_count": 645,
        "revenue_cny": 621481960.92,
        "market_cap_cny": 7636773864.0,
        "net_profit_cny": 70145408.95,
        "company_type": "public",
        "status": "ACTIVE",
    },
    {
        "company_id": "shennan_electric",
        "name_zh": "深圳南山热电股份有限公司",
        "name_en": "Shenzhen Nanshan Thermal Power Co., Ltd.",
        "aliases": ["深南电A"],
        "stock_codes": ["000037.SZ"],
        "description": "深圳本地电力企业，主要从事燃煤/燃气发电、供电供热及储能技术服务，2025年营收4.02亿元。",
        "country": "CN",
        "province": "广东",
        "city": "深圳市",
        "founded_year": 1990,
        "employee_count": 292,
        "revenue_cny": 401681583.1,
        "market_cap_cny": 5961322074.0,
        "net_profit_cny": 161038200.4,
        "company_type": "public",
        "status": "ACTIVE",
    },
    {
        "company_id": "cimc_group",
        "name_zh": "中国国际海运集装箱(集团)股份有限公司",
        "name_en": "China International Marine Containers (Group) Co., Ltd.",
        "aliases": ["中集集团", "CIMC"],
        "stock_codes": ["000039.SZ"],
        "description": "全球领先的物流及能源行业装备与解决方案供应商，集装箱、半挂车、能源化工装备、海洋工程装备产量全球领先，2025年营收1566.11亿元。",
        "country": "CN",
        "province": "广东",
        "city": "深圳市",
        "founded_year": 1980,
        "employee_count": 51541,
        "revenue_cny": 156611446000.0,
        "market_cap_cny": 55704735577.0,
        "net_profit_cny": 220820000.0,
        "company_type": "public",
        "status": "ACTIVE",
    },
]


# ============================================================
# 公司节点暴露 (CompanyNodeExposure)
# ============================================================

EXPOSURES = [
    # ---- 国药一致 ----
    {
        "exposure_id": "sinopharm_unified_produce_pharma",
        "company_id": "sinopharm_unified",
        "node_id": "pharmaceutical_product",
        "activity_type": "produce",
        "role": "头孢类抗生素及中成药制造商",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("国药一致2025年年度报告", "公司主要产品包括药品，2025年药品收入639.87亿元，其中头孢类系列产品是核心制药产品。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "sinopharm_unified_provide_pharma_dist",
        "company_id": "sinopharm_unified",
        "node_id": "pharmaceutical_distribution",
        "activity_type": "provide_service",
        "role": "医药批发分销商",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("国药一致2025年年度报告", "公司医药批发收入511.73亿元，占营业收入的69.7%，是公司的核心业务。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "sinopharm_unified_provide_pharma_retail",
        "company_id": "sinopharm_unified",
        "node_id": "pharmaceutical_retail",
        "activity_type": "provide_service",
        "role": "医药零售连锁运营商",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("国药一致2025年年度报告", "公司医药零售收入218.62亿元，占营业收入的29.8%。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "sinopharm_unified_produce_medical_device",
        "company_id": "sinopharm_unified",
        "node_id": "medical_device",
        "activity_type": "procure",
        "role": "医疗器械分销商",
        "weight": 0.7,
        "confidence": "HIGH",
        "evidence": [ev("国药一致2025年年度报告", "公司2025年器械耗材收入76.93亿元，通过医药批发和零售渠道分销。")],
        "status": "ACTIVE",
    },
    # ---- 深深房A ----
    {
        "exposure_id": "shenzhen_fang_a_produce_residential",
        "company_id": "shenzhen_fang_a",
        "node_id": "residential_property",
        "activity_type": "produce",
        "role": "商品住宅开发商",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("深深房A2025年年度报告", "公司主要业务为房地产开发，主营产品为房地产-住宅。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "shenzhen_fang_a_provide_property_mgmt",
        "company_id": "shenzhen_fang_a",
        "node_id": "property_management_service",
        "activity_type": "provide_service",
        "role": "物业管理服务商",
        "weight": 0.8,
        "confidence": "HIGH",
        "evidence": [ev("深深房A2025年年度报告", "公司主要业务包括物业管理。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "shenzhen_fang_a_provide_housing_rental",
        "company_id": "shenzhen_fang_a",
        "node_id": "housing_rental_service",
        "activity_type": "provide_service",
        "role": "物业租赁运营商",
        "weight": 0.6,
        "confidence": "HIGH",
        "evidence": [ev("深深房A2025年年度报告", "公司主要业务包括房屋租赁。")],
        "status": "ACTIVE",
    },
    # ---- 富奥股份 ----
    {
        "exposure_id": "fawer_manufacture_chassis",
        "company_id": "fawer_parts",
        "node_id": "chassis_system",
        "activity_type": "manufacture",
        "role": "汽车底盘系统供应商",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("富奥股份2024年年度报告", "公司主要产品包括底盘系统，为一汽大众、比亚迪等整车企业配套。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "fawer_manufacture_brake",
        "company_id": "fawer_parts",
        "node_id": "automotive_brake_system",
        "activity_type": "manufacture",
        "role": "汽车制动系统供应商",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("富奥股份2024年年度报告", "公司主要产品包括制动和传动系统。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "fawer_manufacture_transmission",
        "company_id": "fawer_parts",
        "node_id": "automotive_transmission_system",
        "activity_type": "manufacture",
        "role": "汽车传动系统供应商",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("富奥股份2024年年度报告", "公司主要产品包括制动和传动系统。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "fawer_manufacture_steering",
        "company_id": "fawer_parts",
        "node_id": "automotive_steering_system",
        "activity_type": "manufacture",
        "role": "汽车转向系统供应商",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("富奥股份2024年年度报告", "公司主要产品包括转向及安全系统。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "fawer_manufacture_electronics",
        "company_id": "fawer_parts",
        "node_id": "automotive_electronics",
        "activity_type": "manufacture",
        "role": "汽车电子电器供应商",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("富奥股份2024年年度报告", "公司主要产品包括电子电器系统。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "fawer_manufacture_engine_accessory",
        "company_id": "fawer_parts",
        "node_id": "automotive_engine_accessory",
        "activity_type": "manufacture",
        "role": "汽车发动机附件供应商",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("富奥股份2024年年度报告", "公司主要产品包括发动机附件系统。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "fawer_manufacture_environment",
        "company_id": "fawer_parts",
        "node_id": "automotive_environment_system",
        "activity_type": "manufacture",
        "role": "汽车环境系统（空调/热管理）供应商",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("富奥股份2024年年度报告", "公司主要产品包括环境系统，产品涉及汽车空调、转向系统、悬架系统、涡轮增压等。")],
        "status": "ACTIVE",
    },
    # ---- 大悦城 ----
    {
        "exposure_id": "joy_city_produce_residential",
        "company_id": "joy_city",
        "node_id": "residential_property",
        "activity_type": "produce",
        "role": "住宅开发商",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("大悦城2025年年度报告", "公司主营业务为房地产开发、经营、销售、出租及管理住宅、商用物业。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "joy_city_produce_commercial",
        "company_id": "joy_city",
        "node_id": "commercial_property",
        "activity_type": "produce",
        "role": "商业地产开发商",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("大悦城2025年年度报告", "公司经营业态涵盖住宅、商业地产及部分产业地产。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "joy_city_produce_industrial",
        "company_id": "joy_city",
        "node_id": "industrial_property",
        "activity_type": "produce",
        "role": "工业物业开发商",
        "weight": 0.5,
        "confidence": "HIGH",
        "evidence": [ev("大悦城2025年年度报告", "公司经营业态涵盖住宅、商业地产及部分产业地产。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "joy_city_operate_hotel",
        "company_id": "joy_city",
        "node_id": "hotel_operation_service",
        "activity_type": "operate",
        "role": "酒店经营运营商",
        "weight": 0.6,
        "confidence": "HIGH",
        "evidence": [ev("大悦城2025年年度报告", "公司主要产品包括服务为住宅、商业物业、工业物业、酒店经营。")],
        "status": "ACTIVE",
    },
    # ---- 深桑达A ----
    {
        "exposure_id": "sunda_provide_high_tech_eng",
        "company_id": "sunda_a",
        "node_id": "high_tech_industrial_engineering",
        "activity_type": "provide_service",
        "role": "高科技产业工程服务商（半导体/新型显示洁净室工程）",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("深桑达A2024年年度报告", "高科技产业工程服务收入629.69亿元，占营业收入93.4%，在半导体、新型显示器等优势行业稳固地位。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "sunda_provide_bigdata",
        "company_id": "sunda_a",
        "node_id": "big_data_service",
        "activity_type": "provide_service",
        "role": "大数据服务提供商（中国电子云数据智能平台）",
        "weight": 0.8,
        "confidence": "HIGH",
        "evidence": [ev("深桑达A2024年年度报告", "公司作为中国电子在数据要素业务的排头兵，已形成数据智能平台产品、数据港数据运营产品。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "sunda_provide_isi",
        "company_id": "sunda_a",
        "node_id": "information_system_integration",
        "activity_type": "provide_service",
        "role": "信息系统集成服务商",
        "weight": 0.8,
        "confidence": "HIGH",
        "evidence": [ev("深桑达A2024年年度报告", "公司面向国防、能源、金融、交通、卫健等关键行业提供数字化解决方案。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "sunda_manufacture_comm_device",
        "company_id": "sunda_a",
        "node_id": "communication_device",
        "activity_type": "manufacture",
        "role": "通信设备制造商",
        "weight": 0.5,
        "confidence": "MEDIUM",
        "evidence": [ev("深桑达A2024年年度报告", "公司研发、生产、销售通信设备、交通通讯设备。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "sunda_manufacture_module_power",
        "company_id": "sunda_a",
        "node_id": "module_power_supply",
        "activity_type": "manufacture",
        "role": "模块电源制造商",
        "weight": 0.4,
        "confidence": "MEDIUM",
        "evidence": [ev("深桑达A2024年年度报告", "公司主要产品包括彩电回扫变压器、手机、模块电源等。")],
        "status": "ACTIVE",
    },
    # ---- 神州数码 ----
    {
        "exposure_id": "digital_china_provide_it_dist",
        "company_id": "digital_china",
        "node_id": "it_distribution_service",
        "activity_type": "provide_service",
        "role": "IT硬件产品分销商",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("神州数码2025年年度报告", "公司主营业务包括移动办公设备、笔记本电脑、显示设备、服务器、存储设备、网络设备、计算机配件的分销。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "digital_china_procure_server",
        "company_id": "digital_china",
        "node_id": "server_hardware",
        "activity_type": "procure",
        "role": "服务器产品分销商",
        "weight": 0.9,
        "confidence": "HIGH",
        "evidence": [ev("神州数码2025年年度报告", "公司主营业务包括服务器的分销。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "digital_china_procure_network",
        "company_id": "digital_china",
        "node_id": "network_equipment",
        "activity_type": "procure",
        "role": "网络设备产品分销商",
        "weight": 0.8,
        "confidence": "HIGH",
        "evidence": [ev("神州数码2025年年度报告", "公司主营业务包括网络设备的分销。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "digital_china_procure_storage",
        "company_id": "digital_china",
        "node_id": "storage_equipment",
        "activity_type": "procure",
        "role": "存储设备产品分销商",
        "weight": 0.8,
        "confidence": "HIGH",
        "evidence": [ev("神州数码2025年年度报告", "公司主营业务包括存储设备的分销。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "digital_china_procure_laptop",
        "company_id": "digital_china",
        "node_id": "laptop_computer",
        "activity_type": "procure",
        "role": "笔记本电脑产品分销商",
        "weight": 0.9,
        "confidence": "HIGH",
        "evidence": [ev("神州数码2025年年度报告", "公司主营业务包括笔记本电脑的分销。")],
        "status": "ACTIVE",
    },
    # ---- 中国天楹 ----
    {
        "exposure_id": "tianying_operate_wte",
        "company_id": "china_tianying",
        "node_id": "waste_to_energy",
        "activity_type": "operate",
        "role": "垃圾焚烧发电运营商",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("中国天楹2024年年度报告", "公司以垃圾焚烧发电为核心业务，在越南、新加坡、印尼等一带一路国家落地多个垃圾焚烧发电项目。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "tianying_manufacture_wte_equip",
        "company_id": "china_tianying",
        "node_id": "waste_incineration_equipment",
        "activity_type": "manufacture",
        "role": "垃圾焚烧发电设备制造商",
        "weight": 0.9,
        "confidence": "HIGH",
        "evidence": [ev("中国天楹2024年年度报告", "公司提供优质的垃圾焚烧发电整体解决方案及行业领先的新型核心装备的设计、制造。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "tianying_provide_sanitation",
        "company_id": "china_tianying",
        "node_id": "urban_sanitation_service",
        "activity_type": "provide_service",
        "role": "城乡环卫一体化服务商",
        "weight": 0.8,
        "confidence": "HIGH",
        "evidence": [ev("中国天楹2024年年度报告", "公司前端业务涵盖城乡环卫一体化服务、智慧垃圾分类系统。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "tianying_operate_wind",
        "company_id": "china_tianying",
        "node_id": "wind_power_generation",
        "activity_type": "operate",
        "role": "风力发电运营商",
        "weight": 0.6,
        "confidence": "HIGH",
        "evidence": [ev("中国天楹2024年年度报告", "公司新能源发电业务主要为风力发电，在吉林、黑龙江、内蒙古等风光富集地区落地风电项目。")],
        "status": "ACTIVE",
    },
    # ---- 华联控股 ----
    {
        "exposure_id": "hualian_produce_residential",
        "company_id": "hualian_holding",
        "node_id": "residential_property",
        "activity_type": "produce",
        "role": "住宅开发商",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("华联控股2025年年度报告", "公司主要业务为房地产开发和自有物业租赁管理业务。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "hualian_provide_property_mgmt",
        "company_id": "hualian_holding",
        "node_id": "property_management_service",
        "activity_type": "provide_service",
        "role": "物业管理及租赁服务商",
        "weight": 0.8,
        "confidence": "HIGH",
        "evidence": [ev("华联控股2025年年度报告", "公司主要业务包括自有物业管理及房地产经纪。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "hualian_provide_housing_rental",
        "company_id": "hualian_holding",
        "node_id": "housing_rental_service",
        "activity_type": "provide_service",
        "role": "物业租赁运营商",
        "weight": 0.7,
        "confidence": "HIGH",
        "evidence": [ev("华联控股2025年年度报告", "公司主要业务包括自有物业租赁管理。")],
        "status": "ACTIVE",
    },
    # ---- 深南电A ----
    {
        "exposure_id": "shennan_operate_coal_power",
        "company_id": "shennan_electric",
        "node_id": "coal_power_generation",
        "activity_type": "operate",
        "role": "燃煤发电运营商",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("深南电A2025年年度报告", "公司主要业务为生产经营供电供热，拥有燃煤发电机组。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "shennan_operate_gas_power",
        "company_id": "shennan_electric",
        "node_id": "gas_power_generation",
        "activity_type": "operate",
        "role": "燃气发电运营商",
        "weight": 0.9,
        "confidence": "HIGH",
        "evidence": [ev("深南电A2025年年度报告", "公司主要业务为生产经营供电供热，拥有燃气发电机组。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "shennan_provide_heating",
        "company_id": "shennan_electric",
        "node_id": "heating_supply",
        "activity_type": "provide_service",
        "role": "热电联产供热服务商",
        "weight": 0.8,
        "confidence": "HIGH",
        "evidence": [ev("深南电A2025年年度报告", "公司主要业务为生产经营供电供热，从事发电厂的相关技术咨询和技术服务。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "shennan_provide_storage_tech",
        "company_id": "shennan_electric",
        "node_id": "energy_storage_technology",
        "activity_type": "provide_service",
        "role": "储能技术服务提供商",
        "weight": 0.5,
        "confidence": "MEDIUM",
        "evidence": [ev("深南电A2025年年度报告", "公司提供储能技术服务、合同能源管理、节能管理服务等技术服务。")],
        "status": "ACTIVE",
    },
    # ---- 中集集团 ----
    {
        "exposure_id": "cimc_manufacture_container",
        "company_id": "cimc_group",
        "node_id": "container",
        "activity_type": "manufacture",
        "role": "集装箱制造商（全球产量第一）",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("中集集团2024年年度报告", "本集团的标准干货集装箱、冷藏箱、特种集装箱产量均保持全球第一。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "cimc_manufacture_road_vehicle",
        "company_id": "cimc_group",
        "node_id": "road_transport_vehicle",
        "activity_type": "manufacture",
        "role": "道路运输车辆（半挂车）制造商（全球排名第一）",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("中集集团2024年年度报告", "中集车辆是全球排名第一的半挂车生产制造商。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "cimc_manufacture_energy_chem",
        "company_id": "cimc_group",
        "node_id": "energy_chemical_equipment",
        "activity_type": "manufacture",
        "role": "能源化工装备制造商（LNG装备、罐式集装箱全球第一）",
        "weight": 1.0,
        "confidence": "HIGH",
        "evidence": [ev("中集集团2024年年度报告", "中集安瑞科罐式集装箱产量保持全球第一，LNG车用瓶销售收入同比增长31%。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "cimc_manufacture_offshore",
        "company_id": "cimc_group",
        "node_id": "offshore_engineering_equipment",
        "activity_type": "manufacture",
        "role": "海洋工程装备制造商（FPSO、风电安装船）",
        "weight": 0.9,
        "confidence": "HIGH",
        "evidence": [ev("中集集团2024年年度报告", "海洋工程业务营业收入165.56亿元，新签订单32.5亿美元，交付FPSO模块、风电安装船等。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "cimc_manufacture_airport",
        "company_id": "cimc_group",
        "node_id": "airport_equipment",
        "activity_type": "manufacture",
        "role": "空港装备制造商（登机桥全球主要供应商）",
        "weight": 0.8,
        "confidence": "HIGH",
        "evidence": [ev("中集集团2024年年度报告", "中集天达为全球登机桥主要供货商之一，空港装备业务包括旅客登机桥、机场地面支持设备等。")],
        "status": "ACTIVE",
    },
    {
        "exposure_id": "cimc_provide_logistics",
        "company_id": "cimc_group",
        "node_id": "logistics_service",
        "activity_type": "provide_service",
        "role": "物流服务提供商",
        "weight": 0.7,
        "confidence": "HIGH",
        "evidence": [ev("中集集团2024年年度报告", "本集团以物流服务业务为依托，提供物流专业领域的产品及服务。")],
        "status": "ACTIVE",
    },
]


# ============================================================
# 提交逻辑
# ============================================================

async def submit_graph_batch():
    """提交产业图批次（节点+边）"""
    batch = {
        "batch_id": "batch_003_industrial_graph",
        "task_description": "Batch 003: 为10家上市公司构建产业实体图，涵盖医药、汽车零部件、房地产、高科技工程、IT分销、环保、火力发电、运输装备等产业链。",
        "nodes_to_upsert": NEW_NODES,
        "edges_to_upsert": EDGES,
        "rejected_or_pending": []
    }
    
    async with httpx.AsyncClient() as client:
        resp = await client.post(f"{API_BASE}/batches", json=batch, timeout=120.0)
        print(f"Graph batch status: {resp.status_code}")
        result = resp.json()
        print(json.dumps(result, indent=2, ensure_ascii=False))
        return result


async def submit_business_batch():
    """提交商业批次（公司+暴露关系）"""
    batch = {
        "batch_id": "batch_003_company_views",
        "task_description": "Batch 003: 为10家上市公司构建公司视图，包括公司信息和产业节点暴露关系。",
        "industries_to_upsert": [],
        "industry_node_mappings_to_upsert": [],
        "companies_to_upsert": COMPANIES,
        "company_node_exposures_to_upsert": EXPOSURES
    }
    
    async with httpx.AsyncClient() as client:
        resp = await client.post(f"{API_BASE}/business-batches", json=batch, timeout=120.0)
        print(f"Business batch status: {resp.status_code}")
        result = resp.json()
        print(json.dumps(result, indent=2, ensure_ascii=False))
        return result


async def main():
    print("=" * 70)
    print("Batch 003 产业图与公司视图构建")
    print("=" * 70)
    print(f"新建节点: {len(NEW_NODES)}")
    print(f"新建边: {len(EDGES)}")
    print(f"新建公司: {len(COMPANIES)}")
    print(f"新建暴露关系: {len(EXPOSURES)}")
    print()
    
    print("=" * 70)
    print("Step 1: Submitting GraphRegistrationBatch (nodes + edges)")
    print("=" * 70)
    graph_result = await submit_graph_batch()
    
    print("\n" + "=" * 70)
    print("Step 2: Submitting BusinessRegistrationBatch (companies + exposures)")
    print("=" * 70)
    biz_result = await submit_business_batch()
    
    print("\n" + "=" * 70)
    print("SUMMARY")
    print("=" * 70)
    print(f"Graph batch: nodes_created={graph_result.get('nodes_created')}, nodes_updated={graph_result.get('nodes_updated')}, edges_created={graph_result.get('edges_created')}, edges_updated={graph_result.get('edges_updated')}, errors={len(graph_result.get('errors', []))}")
    if graph_result.get('errors'):
        for e in graph_result['errors']:
            print(f"  ERROR: {e}")
    print(f"Business batch: companies_created={biz_result.get('companies_created')}, companies_updated={biz_result.get('companies_updated')}, exposures_created={biz_result.get('exposures_created')}, exposures_updated={biz_result.get('exposures_updated')}, errors={len(biz_result.get('errors', []))}")
    if biz_result.get('errors'):
        for e in biz_result['errors']:
            print(f"  ERROR: {e}")


if __name__ == "__main__":
    asyncio.run(main())
