#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json, subprocess, os, sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLI_PATH = os.path.join(BASE_DIR, "cli", "arachne_cli.py")
PY = os.path.join(BASE_DIR, "backend", "venv", "Scripts", "python.exe")

def ev(source_title, quote="根据企业公开信息"):
    return [{"source_title": source_title, "source_url": None, "quote": quote}]

NODES = [
    {"node_id": "cotton_yarn", "canonical_name_zh": "纯棉纱线", "canonical_name_en": "cotton yarn", "entity_type": "material", "aliases": [], "definition": "以棉花为原料纺制而成的纱线", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("华孚时尚主营业务")},
    {"node_id": "blended_yarn", "canonical_name_zh": "混纺纱线", "canonical_name_en": "blended yarn", "entity_type": "material", "aliases": [], "definition": "由两种或两种以上纤维混合纺制而成的纱线", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("华孚时尚主营业务")},
    {"node_id": "cotton_grey_cloth", "canonical_name_zh": "纯棉坯布", "canonical_name_en": "cotton grey cloth", "entity_type": "material", "aliases": [], "definition": "以纯棉纱线织成未经染整加工的织物", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("华孚时尚主营业务")},
    {"node_id": "blended_grey_cloth", "canonical_name_zh": "混纺坯布", "canonical_name_en": "blended grey cloth", "entity_type": "material", "aliases": [], "definition": "以混纺纱线织成未经染整加工的织物", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("华孚时尚主营业务")},
    {"node_id": "decorative_veneer", "canonical_name_zh": "装饰贴面板", "canonical_name_en": "decorative veneer", "entity_type": "material", "aliases": [], "definition": "表面贴有装饰性木皮或浸渍纸的人造板材", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("兔宝宝主营业务")},
    {"node_id": "plywood", "canonical_name_zh": "胶合板", "canonical_name_en": "plywood", "entity_type": "material", "aliases": [], "definition": "由木段旋切成单板或由木方刨切成薄木，再用胶粘剂胶合而成的三层或多层板状材料", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("兔宝宝主营业务")},
    {"node_id": "wooden_floor", "canonical_name_zh": "木地板", "canonical_name_en": "wooden floor", "entity_type": "material", "aliases": [], "definition": "以木材为主要材料制成的地板", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("兔宝宝经营范围")},
    {"node_id": "wood_processing", "canonical_name_zh": "木材加工", "canonical_name_en": "wood processing", "entity_type": "service", "aliases": [], "definition": "将原木加工成板材、木制品等产品的生产活动", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("兔宝宝经营范围")},
    {"node_id": "health_examination", "canonical_name_zh": "健康体检", "canonical_name_en": "health examination", "entity_type": "service", "aliases": [], "definition": "通过医学检查手段对受检者进行身体状况评估的专业服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("美年健康主营业务")},
    {"node_id": "health_management", "canonical_name_zh": "健康管理", "canonical_name_en": "health management", "entity_type": "service", "aliases": [], "definition": "对个体或群体的健康危险因素进行全面监测、分析、评估和干预的服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("美年健康主营业务")},
    {"node_id": "audio_system", "canonical_name_zh": "音响系统", "canonical_name_en": "audio system", "entity_type": "system", "aliases": [], "definition": "由扬声器、功放、信号源等组成的音频重放系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("国光电器主营业务")},
    {"node_id": "loudspeaker_unit", "canonical_name_zh": "扬声器单元", "canonical_name_en": "loudspeaker unit", "entity_type": "component", "aliases": ["speaker unit"], "definition": "将电信号转换为声音信号的电声器件", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("国光电器主营业务")},
    {"node_id": "electronic_connector", "canonical_name_zh": "电子连接器", "canonical_name_en": "electronic connector", "entity_type": "component", "aliases": [], "definition": "用于实现电路之间电气连接的电子元器件", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("国光电器经营范围")},
    {"node_id": "spindle", "canonical_name_zh": "电主轴", "canonical_name_en": "motorized spindle", "entity_type": "component", "aliases": [], "definition": "将电机与主轴集成于一体的高精度旋转部件", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("国机精工主营业务")},
    {"node_id": "non_metallic_mineral_product", "canonical_name_zh": "非金属矿物制品", "canonical_name_en": "non-metallic mineral product", "entity_type": "material", "aliases": [], "definition": "以非金属矿物为原料加工制成的各类产品", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("国机精工经营范围")},
    {"node_id": "non_ferrous_metal_alloy", "canonical_name_zh": "有色金属合金", "canonical_name_en": "non-ferrous metal alloy", "entity_type": "material", "aliases": [], "definition": "以一种有色金属为基体，加入一种或几种其他元素所构成的合金材料", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("国机精工经营范围")},
    {"node_id": "analytical_instrument", "canonical_name_zh": "实验分析仪器", "canonical_name_en": "analytical instrument", "entity_type": "device", "aliases": [], "definition": "用于实验室分析和检测的各类仪器设备", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("国机精工经营范围")},
    {"node_id": "photovoltaic_equipment", "canonical_name_zh": "光伏设备", "canonical_name_en": "photovoltaic equipment", "entity_type": "device", "aliases": ["PV equipment"], "definition": "用于太阳能光伏发电系统的各类设备和器件", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("国机精工经营范围")},
    {"node_id": "building_decoration", "canonical_name_zh": "建筑装饰", "canonical_name_en": "building decoration", "entity_type": "service", "aliases": [], "definition": "对建筑物内外表面进行装饰装修的专业工程服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("宝鹰股份主营业务")},
    {"node_id": "intelligent_building_system", "canonical_name_zh": "智能建筑系统", "canonical_name_en": "intelligent building system", "entity_type": "system", "aliases": [], "definition": "利用自动化、信息化技术实现建筑设备管理和环境控制的集成系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("宝鹰股份经营范围")},
    {"node_id": "fire_protection_engineering", "canonical_name_zh": "消防工程", "canonical_name_en": "fire protection engineering", "entity_type": "service", "aliases": [], "definition": "用于预防和控制火灾的工程设计、施工和安装服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("宝鹰股份经营范围")},
    {"node_id": "curtain_wall", "canonical_name_zh": "幕墙", "canonical_name_en": "curtain wall", "entity_type": "component", "aliases": [], "definition": "悬挂于建筑主体结构外侧的围护结构，不承担主体结构荷载", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("宝鹰股份经营范围")},
    {"node_id": "automotive_interior_exterior_trim", "canonical_name_zh": "汽车内外饰件", "canonical_name_en": "automotive interior and exterior trim", "entity_type": "component", "aliases": [], "definition": "汽车内部和外部的装饰件和功能件", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("宁波华翔主营业务")},
    {"node_id": "automotive_body_metal_part", "canonical_name_zh": "车身金属件", "canonical_name_en": "automotive body metal part", "entity_type": "component", "aliases": [], "definition": "构成汽车车身结构的金属零部件", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("宁波华翔主营业务")},
    {"node_id": "automotive_lightweight_material", "canonical_name_zh": "车身轻量化材料", "canonical_name_en": "automotive lightweight material", "entity_type": "material", "aliases": [], "definition": "用于减轻汽车车身重量的新型材料", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("宁波华翔主营业务")},
    {"node_id": "automotive_part", "canonical_name_zh": "汽车零部件", "canonical_name_en": "automotive part", "entity_type": "component", "aliases": [], "definition": "构成汽车整车的各类零部件和总成", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("宁波华翔经营范围")},
    {"node_id": "smart_chip", "canonical_name_zh": "智能芯片", "canonical_name_en": "smart chip", "entity_type": "component", "aliases": [], "definition": "具有信息处理、存储和通信功能的集成电路芯片", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("紫光国微主营业务")},
    {"node_id": "special_integrated_circuit", "canonical_name_zh": "特种集成电路", "canonical_name_en": "special integrated circuit", "entity_type": "component", "aliases": [], "definition": "用于特定应用领域（如军工、航天等）的高可靠性集成电路", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("紫光国微主营业务")},
    {"node_id": "memory_chip", "canonical_name_zh": "存储器芯片", "canonical_name_en": "memory chip", "entity_type": "component", "aliases": [], "definition": "用于数据存储的半导体集成电路芯片", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("紫光国微主营业务")},
    {"node_id": "globe_valve", "canonical_name_zh": "截止阀", "canonical_name_en": "globe valve", "entity_type": "component", "aliases": [], "definition": "通过阀瓣沿阀座中心线移动来启闭流体的阀门", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("三花智控主营业务")},
    {"node_id": "electronic_expansion_valve", "canonical_name_zh": "电子膨胀阀", "canonical_name_en": "electronic expansion valve", "entity_type": "component", "aliases": [], "definition": "利用电子信号控制制冷剂流量的节流装置", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("三花智控主营业务")},
    {"node_id": "solenoid_valve", "canonical_name_zh": "电磁阀", "canonical_name_en": "solenoid valve", "entity_type": "component", "aliases": [], "definition": "利用电磁力控制流体通断或流向的自动化基础元件", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("三花智控主营业务")},
    {"node_id": "refrigeration_air_conditioning_equipment", "canonical_name_zh": "制冷空调设备", "canonical_name_en": "refrigeration and air conditioning equipment", "entity_type": "device", "aliases": [], "definition": "用于制冷和空气调节的机械设备和系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("三花智控经营范围")},
    {"node_id": "railway_video_monitoring", "canonical_name_zh": "铁路综合视频监控系统", "canonical_name_en": "railway integrated video monitoring system", "entity_type": "system", "aliases": [], "definition": "用于铁路线路和车站综合视频监控的集成系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("世纪瑞尔主营业务")},
    {"node_id": "railway_disaster_prevention_system", "canonical_name_zh": "铁路防灾安全监控系统", "canonical_name_en": "railway disaster prevention system", "entity_type": "system", "aliases": [], "definition": "用于监测和预警铁路沿线自然灾害和安全风险的系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("世纪瑞尔主营业务")},
    {"node_id": "railway_communication_system", "canonical_name_zh": "铁路通信监控系统", "canonical_name_en": "railway communication monitoring system", "entity_type": "system", "aliases": [], "definition": "用于铁路通信设备运行状态监控的系统", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("世纪瑞尔主营业务")},
    {"node_id": "railway_operation_maintenance_service", "canonical_name_zh": "铁路综合运维服务", "canonical_name_en": "railway operation and maintenance service", "entity_type": "service", "aliases": [], "definition": "为铁路系统提供设备维护、运营支持等综合服务", "status": "ACTIVE", "confidence": "HIGH", "evidence": ev("世纪瑞尔主营业务")},
]

EDGES = [
    {"edge_id": "cotton_yarn_textile_weaving", "from_node": "cotton_yarn", "to_node": "textile_weaving", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "纯棉纱线用于纺织织造", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "blended_yarn_textile_weaving", "from_node": "blended_yarn", "to_node": "textile_weaving", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "混纺纱线用于纺织织造", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "cotton_grey_cloth_textile_garment", "from_node": "cotton_grey_cloth", "to_node": "textile_garment", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "纯棉坯布是纺织服装的原材料", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "decorative_veneer_plywood", "from_node": "decorative_veneer", "to_node": "plywood", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "装饰贴面板以胶合板为基材", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "plywood_wooden_floor", "from_node": "plywood", "to_node": "wooden_floor", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "胶合板可用于木地板生产", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "wood_processing_plywood", "from_node": "wood_processing", "to_node": "plywood", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "木材加工生产胶合板", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "health_examination_medical_service", "from_node": "health_examination", "to_node": "medical_service", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "健康体检属于医疗服务范畴", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "health_management_health_examination", "from_node": "health_management", "to_node": "health_examination", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "健康管理包含健康体检环节", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "audio_system_loudspeaker_unit", "from_node": "audio_system", "to_node": "loudspeaker_unit", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "扬声器单元是音响系统的核心组件", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "loudspeaker_unit_electronic_connector", "from_node": "loudspeaker_unit", "to_node": "electronic_connector", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "电子连接器用于扬声器单元的电路连接", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "spindle_bearing", "from_node": "spindle", "to_node": "bearing", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "轴承是电主轴的关键组件", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "non_metallic_mineral_product_new_material", "from_node": "non_metallic_mineral_product", "to_node": "new_material", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "非金属矿物制品属于新材料范畴", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "analytical_instrument_new_material", "from_node": "analytical_instrument", "to_node": "new_material", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "实验分析仪器用于新材料研发检测", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "photovoltaic_equipment_solar_cell", "from_node": "photovoltaic_equipment", "to_node": "solar_cell", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "光伏设备包含太阳能电池", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "building_decoration_construction_engineering", "from_node": "building_decoration", "to_node": "construction_engineering", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "建筑装饰是建筑工程的重要组成部分", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "intelligent_building_system_building_decoration", "from_node": "intelligent_building_system", "to_node": "building_decoration", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "智能建筑系统融入建筑装饰工程", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "fire_protection_engineering_building_decoration", "from_node": "fire_protection_engineering", "to_node": "building_decoration", "edge_namespace": "industrial_flow", "edge_type": "service_flow", "description": "消防工程是建筑装饰的配套工程", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "curtain_wall_building_decoration", "from_node": "curtain_wall", "to_node": "building_decoration", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "幕墙是建筑装饰的外围护结构", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "automotive_interior_exterior_trim_automotive_part", "from_node": "automotive_interior_exterior_trim", "to_node": "automotive_part", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "汽车内外饰件是汽车零部件的一类", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "automotive_body_metal_part_automotive_part", "from_node": "automotive_body_metal_part", "to_node": "automotive_part", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "车身金属件是汽车零部件的一类", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "automotive_lightweight_material_automotive_part", "from_node": "automotive_lightweight_material", "to_node": "automotive_part", "edge_namespace": "industrial_flow", "edge_type": "material_flow", "description": "车身轻量化材料用于汽车零部件制造", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "smart_chip_integrated_circuit", "from_node": "smart_chip", "to_node": "integrated_circuit", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "智能芯片是集成电路的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "special_integrated_circuit_integrated_circuit", "from_node": "special_integrated_circuit", "to_node": "integrated_circuit", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "特种集成电路是集成电路的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "memory_chip_integrated_circuit", "from_node": "memory_chip", "to_node": "integrated_circuit", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "存储器芯片是集成电路的一种", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "globe_valve_refrigeration_air_conditioning_equipment", "from_node": "globe_valve", "to_node": "refrigeration_air_conditioning_equipment", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "截止阀是制冷空调设备的控制组件", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "electronic_expansion_valve_refrigeration_air_conditioning_equipment", "from_node": "electronic_expansion_valve", "to_node": "refrigeration_air_conditioning_equipment", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "电子膨胀阀是制冷空调设备的节流组件", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "solenoid_valve_refrigeration_air_conditioning_equipment", "from_node": "solenoid_valve", "to_node": "refrigeration_air_conditioning_equipment", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "电磁阀是制冷空调设备的控制组件", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "railway_video_monitoring_railway_project", "from_node": "railway_video_monitoring", "to_node": "railway_project", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "铁路综合视频监控系统是铁路项目的子系统", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "railway_disaster_prevention_system_railway_project", "from_node": "railway_disaster_prevention_system", "to_node": "railway_project", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "铁路防灾安全监控系统是铁路项目的子系统", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
    {"edge_id": "railway_communication_system_railway_project", "from_node": "railway_communication_system", "to_node": "railway_project", "edge_namespace": "industrial_flow", "edge_type": "composition", "description": "铁路通信监控系统是铁路项目的子系统", "evidence": ev("产业知识图谱"), "confidence": "HIGH"},
]

BUSINESS = {
    "batch_id": "batch_118_business",
    "task_description": "Batch 118 business registration for 10 A-share companies",
    "companies_to_upsert": [
        {"company_id": "sz_002042", "name_zh": "华孚时尚", "name_en": "Huafu Fashion Co., Ltd.", "country": "CN", "province": "安徽", "city": "淮北市", "stock_codes": ["002042.SZ"], "description": "纯棉纱线、混纺纱线、纯棉坯布、混纺坯布等的生产和销售", "founded_year": 2000, "employee_count": 13772},
        {"company_id": "sz_002043", "name_zh": "兔宝宝", "name_en": "Deweller Rabbit Baby Decoration New Material Co., Ltd.", "country": "CN", "province": "浙江", "city": "湖州市", "stock_codes": ["002043.SZ"], "description": "中高档装饰贴面板、胶合板、单板的生产销售和原木加工", "founded_year": 2001, "employee_count": 3015},
        {"company_id": "sz_002044", "name_zh": "美年健康", "name_en": "Meinian Onehealth Healthcare Holdings Co., Ltd.", "country": "CN", "province": "浙江", "city": "绍兴市", "stock_codes": ["002044.SZ"], "description": "以健康体检为核心的专业体检和医疗服务", "founded_year": 1991, "employee_count": 38253},
        {"company_id": "sz_002045", "name_zh": "国光电器", "name_en": "Guoguang Electric Co., Ltd.", "country": "CN", "province": "广东", "city": "广州市", "stock_codes": ["002045.SZ"], "description": "扬声器单元、音响系统、电池和其他电子零配件的设计生产和销售", "founded_year": 1995, "employee_count": 9630},
        {"company_id": "sz_002046", "name_zh": "国机精工", "name_en": "Sinomach Precision Industry Group Co., Ltd.", "country": "CN", "province": "河南", "city": "洛阳市", "stock_codes": ["002046.SZ"], "description": "轴承、电主轴、轴承专用工艺装备和相关产品的研发生产销售", "founded_year": 2001, "employee_count": 2056},
        {"company_id": "sz_002047", "name_zh": "宝鹰股份", "name_en": "Shenzhen Baoying Construction Holding Group Co., Ltd.", "country": "CN", "province": "广东", "city": "深圳市", "stock_codes": ["002047.SZ"], "description": "综合建筑装饰工程业务", "founded_year": 1993, "employee_count": 209},
        {"company_id": "sz_002048", "name_zh": "宁波华翔", "name_en": "Ningbo Huaxiang Electronic Co., Ltd.", "country": "CN", "province": "浙江", "city": "宁波市", "stock_codes": ["002048.SZ"], "description": "汽车零部件的设计开发生产和销售", "founded_year": 1988, "employee_count": 21860},
        {"company_id": "sz_002049", "name_zh": "紫光国微", "name_en": "Unisoc Guoxin Microelectronics Co., Ltd.", "country": "CN", "province": "河北", "city": "唐山市", "stock_codes": ["002049.SZ"], "description": "集成电路芯片设计与销售", "founded_year": 2001, "employee_count": 2788},
        {"company_id": "sz_002050", "name_zh": "三花智控", "name_en": "Zhejiang Sanhua Intelligent Controls Co., Ltd.", "country": "CN", "province": "浙江", "city": "绍兴市", "stock_codes": ["002050.SZ"], "description": "截止阀、电子膨胀阀、电磁阀等制冷空调控制元器件", "founded_year": 1994, "employee_count": 19090},
        {"company_id": "sz_300150", "name_zh": "世纪瑞尔", "name_en": "Beijing Century Real Technology Co., Ltd.", "country": "CN", "province": "北京", "city": "北京市", "stock_codes": ["300150.SZ"], "description": "铁路行车安全监控系统及综合运维服务", "founded_year": 1999, "employee_count": 1026},
    ],
    "company_node_exposures_to_upsert": [
        {"exposure_id": "sz_002042_produce_cotton_yarn", "company_id": "sz_002042", "node_id": "cotton_yarn", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:纯棉纱线")},
        {"exposure_id": "sz_002042_produce_blended_yarn", "company_id": "sz_002042", "node_id": "blended_yarn", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:混纺纱线")},
        {"exposure_id": "sz_002042_produce_cotton_grey_cloth", "company_id": "sz_002042", "node_id": "cotton_grey_cloth", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:纯棉坯布")},
        {"exposure_id": "sz_002042_produce_blended_grey_cloth", "company_id": "sz_002042", "node_id": "blended_grey_cloth", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:混纺坯布")},
        {"exposure_id": "sz_002042_produce_textile_garment", "company_id": "sz_002042", "node_id": "textile_garment", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:纺织品")},
        {"exposure_id": "sz_002042_provide_service_technical_service", "company_id": "sz_002042", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:纺纱技术研究")},
        {"exposure_id": "sz_002043_produce_decorative_veneer", "company_id": "sz_002043", "node_id": "decorative_veneer", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:装饰贴面板")},
        {"exposure_id": "sz_002043_produce_plywood", "company_id": "sz_002043", "node_id": "plywood", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:胶合板")},
        {"exposure_id": "sz_002043_produce_wooden_floor", "company_id": "sz_002043", "node_id": "wooden_floor", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:地板制造")},
        {"exposure_id": "sz_002043_produce_furniture", "company_id": "sz_002043", "node_id": "furniture", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:家具制造")},
        {"exposure_id": "sz_002043_operate_wood_processing", "company_id": "sz_002043", "node_id": "wood_processing", "activity_type": "operate", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:木材加工")},
        {"exposure_id": "sz_002043_produce_coating", "company_id": "sz_002043", "node_id": "coating", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:涂料销售")},
        {"exposure_id": "sz_002044_provide_service_health_examination", "company_id": "sz_002044", "node_id": "health_examination", "activity_type": "provide_service", "weight": 0.40, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:健康体检")},
        {"exposure_id": "sz_002044_provide_service_health_management", "company_id": "sz_002044", "node_id": "health_management", "activity_type": "provide_service", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:健康管理")},
        {"exposure_id": "sz_002044_provide_service_medical_service", "company_id": "sz_002044", "node_id": "medical_service", "activity_type": "provide_service", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:医疗服务")},
        {"exposure_id": "sz_002045_produce_audio_system", "company_id": "sz_002045", "node_id": "audio_system", "activity_type": "produce", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:音响系统")},
        {"exposure_id": "sz_002045_produce_loudspeaker_unit", "company_id": "sz_002045", "node_id": "loudspeaker_unit", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:扬声器单元")},
        {"exposure_id": "sz_002045_produce_battery", "company_id": "sz_002045", "node_id": "battery", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:电池")},
        {"exposure_id": "sz_002045_produce_electronic_connector", "company_id": "sz_002045", "node_id": "electronic_connector", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:电子零配件")},
        {"exposure_id": "sz_002045_produce_electronic_component", "company_id": "sz_002045", "node_id": "electronic_component", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:电子零配件")},
        {"exposure_id": "sz_002046_produce_bearing", "company_id": "sz_002046", "node_id": "bearing", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:轴承")},
        {"exposure_id": "sz_002046_produce_spindle", "company_id": "sz_002046", "node_id": "spindle", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:电主轴")},
        {"exposure_id": "sz_002046_produce_non_metallic_mineral_product", "company_id": "sz_002046", "node_id": "non_metallic_mineral_product", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:非金属矿物制品")},
        {"exposure_id": "sz_002046_produce_non_ferrous_metal_alloy", "company_id": "sz_002046", "node_id": "non_ferrous_metal_alloy", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:有色金属合金")},
        {"exposure_id": "sz_002046_produce_analytical_instrument", "company_id": "sz_002046", "node_id": "analytical_instrument", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:实验分析仪器")},
        {"exposure_id": "sz_002046_produce_new_material", "company_id": "sz_002046", "node_id": "new_material", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:新材料技术研发")},
        {"exposure_id": "sz_002046_produce_photovoltaic_equipment", "company_id": "sz_002046", "node_id": "photovoltaic_equipment", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:光伏设备销售")},
        {"exposure_id": "sz_002047_provide_service_building_decoration", "company_id": "sz_002047", "node_id": "building_decoration", "activity_type": "provide_service", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:综合建筑装饰工程")},
        {"exposure_id": "sz_002047_provide_service_intelligent_building_system", "company_id": "sz_002047", "node_id": "intelligent_building_system", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:智能系统工程")},
        {"exposure_id": "sz_002047_provide_service_fire_protection_engineering", "company_id": "sz_002047", "node_id": "fire_protection_engineering", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:消防设施工程")},
        {"exposure_id": "sz_002047_produce_curtain_wall", "company_id": "sz_002047", "node_id": "curtain_wall", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:幕墙工程")},
        {"exposure_id": "sz_002047_provide_service_smart_city", "company_id": "sz_002047", "node_id": "smart_city", "activity_type": "provide_service", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:智慧城市")},
        {"exposure_id": "sz_002047_provide_service_construction_engineering", "company_id": "sz_002047", "node_id": "construction_engineering", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:建筑工程施工")},
        {"exposure_id": "sz_002048_produce_automotive_interior_exterior_trim", "company_id": "sz_002048", "node_id": "automotive_interior_exterior_trim", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:汽车内外饰件")},
        {"exposure_id": "sz_002048_produce_automotive_body_metal_part", "company_id": "sz_002048", "node_id": "automotive_body_metal_part", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:车身金属件")},
        {"exposure_id": "sz_002048_produce_automotive_lightweight_material", "company_id": "sz_002048", "node_id": "automotive_lightweight_material", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:车身轻量化材料")},
        {"exposure_id": "sz_002048_produce_automotive_part", "company_id": "sz_002048", "node_id": "automotive_part", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:汽车零部件")},
        {"exposure_id": "sz_002048_provide_service_technical_service", "company_id": "sz_002048", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术服务")},
        {"exposure_id": "sz_002048_provide_service_engineering_design_service", "company_id": "sz_002048", "node_id": "engineering_design_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:模具设计")},
        {"exposure_id": "sz_002049_produce_smart_chip", "company_id": "sz_002049", "node_id": "smart_chip", "activity_type": "produce", "weight": 0.30, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:智能芯片")},
        {"exposure_id": "sz_002049_produce_special_integrated_circuit", "company_id": "sz_002049", "node_id": "special_integrated_circuit", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:特种集成电路")},
        {"exposure_id": "sz_002049_produce_memory_chip", "company_id": "sz_002049", "node_id": "memory_chip", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:存储器芯片")},
        {"exposure_id": "sz_002049_produce_integrated_circuit", "company_id": "sz_002049", "node_id": "integrated_circuit", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:集成电路芯片设计")},
        {"exposure_id": "sz_002049_produce_electronic_component", "company_id": "sz_002049", "node_id": "electronic_component", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:电子元器件")},
        {"exposure_id": "sz_002050_produce_globe_valve", "company_id": "sz_002050", "node_id": "globe_valve", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:截止阀")},
        {"exposure_id": "sz_002050_produce_electronic_expansion_valve", "company_id": "sz_002050", "node_id": "electronic_expansion_valve", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:电子膨胀阀")},
        {"exposure_id": "sz_002050_produce_solenoid_valve", "company_id": "sz_002050", "node_id": "solenoid_valve", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:电磁阀")},
        {"exposure_id": "sz_002050_produce_refrigeration_air_conditioning_equipment", "company_id": "sz_002050", "node_id": "refrigeration_air_conditioning_equipment", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:制冷空调设备制造")},
        {"exposure_id": "sz_002050_produce_valve", "company_id": "sz_002050", "node_id": "valve", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:阀门制造")},
        {"exposure_id": "sz_002050_produce_pump", "company_id": "sz_002050", "node_id": "pump", "activity_type": "produce", "weight": 0.05, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:泵及真空设备制造")},
        {"exposure_id": "sz_300150_produce_railway_video_monitoring", "company_id": "sz_300150", "node_id": "railway_video_monitoring", "activity_type": "produce", "weight": 0.25, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:铁路综合视频监控系统")},
        {"exposure_id": "sz_300150_produce_railway_disaster_prevention_system", "company_id": "sz_300150", "node_id": "railway_disaster_prevention_system", "activity_type": "produce", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:铁路防灾安全监控系统")},
        {"exposure_id": "sz_300150_produce_railway_communication_system", "company_id": "sz_300150", "node_id": "railway_communication_system", "activity_type": "produce", "weight": 0.15, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主要产品:铁路通信监控系统")},
        {"exposure_id": "sz_300150_provide_service_railway_operation_maintenance_service", "company_id": "sz_300150", "node_id": "railway_operation_maintenance_service", "activity_type": "provide_service", "weight": 0.20, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("主营业务:铁路综合运维服务")},
        {"exposure_id": "sz_300150_provide_service_technical_service", "company_id": "sz_300150", "node_id": "technical_service", "activity_type": "provide_service", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:技术服务")},
        {"exposure_id": "sz_300150_produce_software", "company_id": "sz_300150", "node_id": "software_development_service", "activity_type": "produce", "weight": 0.10, "confidence": "HIGH", "status": "ACTIVE", "evidence": ev("经营范围:软件开发")},
    ],
    "industries_to_upsert": [],
    "industry_node_mappings_to_upsert": [],
}

def submit():
    batch = {"batch_id": "batch_118_nodes", "task_description": "Batch 118 industrial nodes and edges", "nodes_to_upsert": NODES, "edges_to_upsert": EDGES}
    path = os.path.join(BASE_DIR, "tmp_script", "batch_118_nodes.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(batch, f, ensure_ascii=False, indent=2)
    r1 = subprocess.run([PY, CLI_PATH, "submit", path], capture_output=True, text=True)
    print("[GRAPH]", r1.stdout[:500], r1.stderr[:500])

    path2 = os.path.join(BASE_DIR, "tmp_script", "batch_118_business.json")
    with open(path2, "w", encoding="utf-8") as f:
        json.dump(BUSINESS, f, ensure_ascii=False, indent=2)
    r2 = subprocess.run([PY, CLI_PATH, "business-batch", path2], capture_output=True, text=True)
    print("[BUSINESS]", r2.stdout[:500], r2.stderr[:500])

if __name__ == "__main__":
    submit()
