"""Tests for JSON file-based PROV statement storage layer."""

from __future__ import annotations

import json

import pytest

from app.models.prov_schema import ProvStatement, ProvRelation, ProvRole
from app.models.core import Confidence, Evidence
from app.services import prov_storage

pytestmark = pytest.mark.asyncio


@pytest.fixture(autouse=True)
def tmp_prov_dir(tmp_path, monkeypatch):
    prov_dir = tmp_path / "prov_statements"
    monkeypatch.setattr(prov_storage, "PROV_DIR", prov_dir)
    yield prov_dir


async def test_create_and_get_statement():
    data = ProvStatement(
        node_id="test_wafer",
        node_role=ProvRole.ENTITY,
        prov_relation=ProvRelation.WAS_GENERATED_BY,
        target_node_id="test_wafer_manufacturing",
        target_role=ProvRole.ACTIVITY,
        evidence=[
            Evidence(
                source_title="Test Source",
                quote="Wafer is generated by wafer manufacturing.",
            )
        ],
        confidence=Confidence.HIGH,
    )

    created = await prov_storage.create_statement(data)
    assert created.statement_id == "test_wafer__wasGeneratedBy__test_wafer_manufacturing"
    assert created.node_id == "test_wafer"

    fetched = await prov_storage.get_statement(created.statement_id)
    assert fetched is not None
    assert fetched.target_node_id == "test_wafer_manufacturing"
    assert fetched.prov_relation == ProvRelation.WAS_GENERATED_BY


async def test_list_statements_by_node():
    s1 = ProvStatement(
        node_id="test_silicon",
        prov_relation=ProvRelation.USED,
        target_node_id="test_wafer_manufacturing",
        target_role=ProvRole.ACTIVITY,
    )
    s2 = ProvStatement(
        node_id="test_silicon",
        prov_relation=ProvRelation.WAS_DERIVED_FROM,
        target_node_id="test_silicon_ore",
        target_role=ProvRole.ENTITY,
    )
    await prov_storage.create_statement(s1)
    await prov_storage.create_statement(s2)

    items, total = await prov_storage.list_statements_by_node("test_silicon")
    assert total == 2
    assert {i.prov_relation for i in items} == {ProvRelation.USED, ProvRelation.WAS_DERIVED_FROM}


async def test_update_and_delete_statement():
    data = ProvStatement(
        node_id="test_wafer",
        prov_relation=ProvRelation.WAS_GENERATED_BY,
        target_node_id="test_wafer_manufacturing",
        target_role=ProvRole.ACTIVITY,
        notes="initial note",
    )
    created = await prov_storage.create_statement(data)

    updated = await prov_storage.update_statement(
        created.statement_id,
        {"notes": "updated note", "is_inferred": True},
    )
    assert updated is not None
    assert updated.notes == "updated note"
    assert updated.is_inferred is True

    deleted = await prov_storage.delete_statement(created.statement_id)
    assert deleted is True
    assert await prov_storage.get_statement(created.statement_id) is None


async def test_duplicate_statement_raises():
    data = ProvStatement(
        node_id="test_wafer",
        prov_relation=ProvRelation.WAS_GENERATED_BY,
        target_node_id="test_wafer_manufacturing",
        target_role=ProvRole.ACTIVITY,
    )
    await prov_storage.create_statement(data)

    with pytest.raises(ValueError):
        await prov_storage.create_statement(data)


async def test_files_are_persisted_as_json(tmp_prov_dir):
    data = ProvStatement(
        node_id="test_persist",
        prov_relation=ProvRelation.USED,
        target_node_id="test_process",
        target_role=ProvRole.ACTIVITY,
    )
    await prov_storage.create_statement(data)

    file_path = tmp_prov_dir / "test_persist.prov.json"
    assert file_path.exists()
    raw = json.loads(file_path.read_text(encoding="utf-8"))
    assert isinstance(raw, list)
    assert raw[0]["node_id"] == "test_persist"
    assert raw[0]["prov_relation"] == "used"
